### ISSUE TITLE
Support common `org.jetbrains.compose.ui.tooling.preview.Preview` in IDEA and Android Studio

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#5078] opened 2024-07-08 12:55 UTC
State on 08-07-2024 (Compose 1.6.11):
- added commonMain `org.jetbrains.compose.ui.tooling.preview.Preview` (in `implementation(compose.components.uiToolingPreview)`)
- it is supported only in Fleet, IDEA/Android Studio support needs to be added separately
- there is currently multiple Preview's that confuses people. It is tracked in https://github.com/JetBrains/compose-multiplatform/issues/4869

**Comment by igordmn** [comment] 2024-07-08 12:57
Parent task: https://github.com/JetBrains/compose-multiplatform/issues/2045

**Comment by Him188** [comment] 2024-07-08 13:09
Is it possible to render Android previews from commonMain if android target is enabled? 
Desktop previews lack features such as device sizes, light/dark, interactive mode, layout inspector, animations, etc. Giving these limitations, I don't like and don't use desktop previews at all. I always open a separate editor tab and place all previews in androidMain. It could be very nice if a common @Preview annoatation can somehow trigger Android previews in Android Studio.

**Comment by igordmn** [comment] 2024-07-08 13:40
> Is it possible to render Android previews from commonMain if android target is enabled?

At the moment, it isn't possible officially. There can be workarounds, but I haven't checked them.

A current working official (but cumbersome) way is defining your android-only `@androidx.compose.ui.tooling.preview.Preview` previews in `androidMain` and call a common defined Composable in it.

**Comment by Andrew0000** [comment] 2024-07-08 13:55
How soon can we expect this feature to arrive? Is there any plan?
This would be really useful in terms of productivity and would make the transition from Jetpack Compose to CMP easier.

**Comment by Him188** [comment] 2024-07-08 14:15
> A current working official (but cumbersome) way is defining your android-only `@androidx.compose.ui.tooling.preview.Preview` previews in `androidMain` and call a common defined Composable in it.

Thanks, that's what I have been doing. The problem is it separates code and previews, making it hard for collaborators to find them. A separate IDE tab is also needed. Switching between tabs is frustrating. 

Common `@Preview` is the feature that I want most. However, whether I will use it in production is still questionable, due to the lack of features compared with Android previews. It's likely that I will continue writing previews in `androidMain`, but at least I might start using common `@Preview` for very small composables that do not need interactive mode or considering device sizes.

**Comment by brucemax** [comment] 2024-07-11 22:24
Just came here to see if anything changed after several month, unfortunately no. I just want to write UI and see preview right in the same file..

**Comment by hmy65** [comment] 2024-07-12 02:41
How could fleet support commonMain preivew? That's strange.

**Comment by gulabsagevadiya** [comment] 2024-07-13 13:11
> > Is it possible to render Android previews from commonMain if android target is enabled?
> 
> At the moment, it isn't possible officially. There can be workarounds, but I haven't checked them.
> 
> A current working official (but cumbersome) way is defining your android-only `@androidx.compose.ui.tooling.preview.Preview` previews in `androidMain` and call a common defined Composable in it.

yes i did the same but it is not showing preview like jetpack compose does in android. when i did like you said preview runs on emulator not showing in side by side

**Comment by igordmn** [comment] 2024-07-15 10:08
>  is not showing preview like jetpack compose does in android

You can check how it is done in https://kmp.jetbrains.com/:
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/1828826c-5e6b-4277-89d7-f3c8c373c5c9">

The important parts are in `composeApp/build.gradle.kts`:
```
androidMain.dependencies {
    ...
    implementation(compose.preview)
    ...
}
...
android {
    ...
    buildFeatures {
        compose = true
    }
    ...
}
```

**Comment by gulabsagevadiya** [comment] 2024-07-16 11:56
> > is not showing preview like jetpack compose does in android
> 
> You can check how it is done in https://kmp.jetbrains.com/: <img alt="image" width="1006" src="https://private-user-images.githubusercontent.com/5963351/348667996-1828826c-5e6b-4277-89d7-f3c8c373c5c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjYyMDQsIm5iZiI6MTcyMTEyNTkwNCwicGF0aCI6Ii81OTYzMzUxLzM0ODY2Nzk5Ni0xODI4ODI2Yy01ZTZiLTQyNzctODlkNy1mM2M4YzM3M2M1YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMTAzMTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQ1YTBkYWFkYTdmNGMyYTk2MmJlMzMxMWFjNmNmYzRjNTMyMGI2ZmQzMTI4ZTgwOTY2MjgwODU4ZTQ0ODY4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mLA-yUMPfHD-C2oVT6Itdv0uXyVnMJnCo0OJWS_oa2U">
> 
> The important parts are in `composeApp/build.gradle.kts`:
> 
> ```
> androidMain.dependencies {
>     ...
>     implementation(compose.preview)
>     ...
> }
> ...
> android {
>     ...
>     buildFeatures {
>         compose = true
>     }
>     ...
> }
> ```

yes this worked fine. can you help me little more as i am using common resource in kmp. when i use any drawable from common resource render gets fail

**Comment by igordmn** [comment] 2024-07-16 13:20
Maybe [this](https://github.com/JetBrains/compose-multiplatform/issues/4932) is what you encounter. Try the latest `dev` version

**Comment by Andrew0000** [comment] 2024-08-14 08:17
@igordmn sorry for asking again, but is there any time frame when we can expect Preview to work in commonMain in IDEA/AS?

For me this is a quite important feature that stops me from using CMP more.

**Comment by igordmn** [comment] 2024-08-14 10:04
> but is there any time frame when we can expect Preview to work in commonMain in IDEA/AS

We don't have public ETA

**Comment by okushnikov** [comment] 2024-08-23 13:41
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5078">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by storytellerF** [comment] 2024-08-24 15:44
Fleet compose preview only work for **fun App()**?

**Comment by adamglin0** [comment] 2024-08-24 16:56
> Fleet compose preview only work for **fun App()**?

It support all composable function

**Comment by ubarua123** [comment] 2024-09-15 06:26
This is unfair on Jetbrains part where they are trying to upsell Fleet so that all compose multiplatform devs switch to Fleet. So now not only do I need to learn multiplatform coding, I need to learn how to use Fleet (which is going to be a Paid tool like Intellij)

I am still stuck where it gives the "missing resource" error even with their Compose Multiplatform support plugin. If someone has a good solution please write it here.

**Closed** 2024-09-23 09:28 UTC
Labels: enhancement, ide, preview

**Comment by Endless-Lemniscate** [comment] 2024-11-13 21:34
> This is unfair on Jetbrains part where they are trying to upsell Fleet 
On top of that fleet laggy as hell, drains battery and loads cpu
