### ISSUE TITLE
iOS TextField in Column doesn't compiles

### ISSUE THREAD

**Issue by jyashi** [JetBrains/compose-multiplatform#3266] opened 2023-06-16 05:17 UTC
**Describe the bug**
I have an App.Kt file inside the `commonMain/kotlin/com/example/myapp` module which looks like : 

`@Composable
fun App() {
    Box(
        modifier = Modifier.fillMaxSize(),
        contentAlignment = androidx.compose.ui.Alignment.Center
    ) {
        Column {
            Text("Hello world from Compose...")
            Text("Column child 1")
        }
    }
}`

When building this i only get a `:shared:compileCommonMainKotlinMetadata` compile error but it still allows build and running of the app in IOS simulator so it is ok.

However, as soon as i add a `TextField` to the column like below :

`@Composable
fun App() {
    Box(
        modifier = Modifier.fillMaxSize(),
        contentAlignment = androidx.compose.ui.Alignment.Center
    ) {
        Column {
            Text("Hello world from Compose...")
            Text("Column child 1")
            TextField(
                singleLine = true,
                leadingIcon = {
                },
                value = " ",
                onValueChange = {

                },
                label = {  }
            )
        }
    }
}`

When i rebuild this suddenly i get compile error for `:shared:linkDebugFrameworkIosArm64` saying `e: Compilation failed: IrClassPublicSymbolImpl for com.example.alescakmmprototype/ComposableSingletons$AppKt|null[0] is already bound: CLASS OBJECT name:ComposableSingletons$AppKt modality:FINAL visibility:internal superTypes:[]` .

When this happens then my Xcode build fails and i cannot run app on the IOS simulator.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Ventura 13.4
- OS architecture (x86 or arm64): Mac M2
- IOS framework : Regular framework

**Expected behavior**
Rendering of Composable on IOS simulator

**Screenshots**

<img width="344" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/47436660/d7bec677-20ae-4102-8306-2bf147a03129">

In the case of `TextField` :
<img width="405" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/47436660/7079154b-48c9-4892-8303-48a714240949">

**Comment by dima-avdeev-jb** [comment] 2023-06-20 16:42
I will check this issue and will try to reproduce.

**Comment by ankitslice** [comment] 2023-07-30 18:04
happening for me also

**Comment by ankitslice** [comment] 2023-07-30 18:05
It is using because of lamda function , like button is using lamda ( onClick )  if removing that , it will not happen

**Comment by luangs7** [comment] 2023-09-11 01:47
> It is using because of lamda function , like button is using lamda ( onClick ) if removing that , it will not happen

can you please provide more information?

**Comment by dima-avdeev-jb** [comment] 2023-12-28 09:03
Can you please check with version of Compose 1.6.0-dev1350 ?

**Comment by mazunin-v-jb** [comment] 2024-06-07 15:33
Since there is no new answers for a long time, I'm closing that issue. Feel free to reopen if this behavior didn't fixed.

**Closed by mazunin-v-jb** 2024-06-07 15:33 UTC
Labels: bug, ios

**Comment by okushnikov** [comment] 2024-07-14 14:53
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3266">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment] 2024-07-14 14:54
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3266">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3266">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
