### ISSUE TITLE
Research performance issues on Desktop

### ISSUE THREAD

**Issue by mazunin-v-jb** [JetBrains/compose-multiplatform#3543] opened 2023-08-21 18:51 UTC
According to [this article](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1692607712891959) and performed tests with different versions of Compose, performance regression has been noticed after Compose 1.0 and Compose 1.2 (tested on Windows).
This is a potential point for further optimization.

**Comment by igordmn** [comment] 2023-08-21 20:04
Windows 11, Corretto 18, 10000 squares
Compose, Kotlin                  |FPS
---                         | ---
1.5.0, 1.9.0                        |69
1.5.0, 1.7.10                      |69
1.4.3, 1.7.10                      |68
1.3.1, 1.7.10                      |78
1.2.1, 1.7.10                      |78
1.1.1, 1.6.10                      |122
1.0.0, 1.5.31                      |122
0.4.0, 1.5.10                      |149

A reduced benchmark:
```kotlin
import androidx.compose.ui.awt.ComposeWindow     // for >= 1.0.0
// import androidx.compose.desktop.ComposeWindow // for 0.4.0
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.drawIntoCanvas
import java.awt.Dimension
import javax.swing.SwingUtilities
import kotlin.math.roundToInt

fun main() = SwingUtilities.invokeLater {
    System.setProperty("skiko.renderApi", "OPENGL")
    System.setProperty("skiko.vsync.enabled", "false")

    ComposeWindow().apply {
        size = Dimension(1280, 720)
        setContent {
            App()
        }
        isVisible = true
    }
}

val particlesCount = 10_000
val particles = Array(particlesCount) { RandomParticle() }

@Composable
fun App() {
    var time by remember { mutableStateOf(0L) }

    Canvas(Modifier.fillMaxSize()) {
        drawIntoCanvas {
            val fake = time // to cause redrawing (otherwise it caches)

            drawRect(Color.Red)
            (0 until particlesCount).forEach { id ->
                val particle = particles[id]
                drawRect(
                    color = Color.White,
                    Offset(size.width * particle.x, size.height * particle.y),
                    Size(10f, 10f)
                )
            }
        }
    }

    LaunchedEffect(Unit) {
        val fpsCounter = FPSCounter()
        while (true) {
            withFrameMillis { ms ->
                (0 until particlesCount).forEach { id ->
                    particles[id].updatePositionAndSpeed()
                }
                time = ms
                fpsCounter.tick()
            }
        }
    }
}

class RandomParticle(var x: Float = 0f, var y: Float = 0f) {
    fun updatePositionAndSpeed() {
        x = Math.random().toFloat()
        y = Math.random().toFloat()
    }
}

// a reduced copy from skiko
class FPSCounter(
    private val periodSeconds: Double = 2.0,
) {
    private val times = mutableListOf<Long>()
    private var lastLogTime = System.nanoTime()
    private var lastTime = System.nanoTime()
    var average = 0
        private set

    fun tick() {
        val time = System.nanoTime()
        val frameTime = time - lastTime
        lastTime = time

        times.add(frameTime)

        if ((time - lastLogTime) > periodSeconds.secondsToNanos() && times.isNotEmpty()) {
            average = (nanosPerSecond / times.average()).roundToInt()
            times.clear()
            lastLogTime = time
            println("FPS $average")
        }
    }

    private val nanosPerSecond = 1_000_000_000.0
    private fun Double.secondsToNanos(): Long = (this * nanosPerSecond).toLong()
}
```

**Comment by igordmn** [comment] 2023-08-21 20:34
The regression is in Skiko or in Skia, not in Compose itself. A pure Skiko benchmarks shows similar regressions:
```
// for 0.4.0
//import org.jetbrains.skija.Canvas
//import org.jetbrains.skija.Color
//import org.jetbrains.skija.Paint
//import org.jetbrains.skija.Rect

import org.jetbrains.skia.Canvas
import org.jetbrains.skia.Color
import org.jetbrains.skia.Paint
import org.jetbrains.skia.Rect
import org.jetbrains.skiko.SkikoView
import org.jetbrains.skiko.SkiaLayer
import java.awt.Dimension
import javax.swing.JFrame
import javax.swing.SwingUtilities
import kotlin.math.roundToInt

val redPaint = Paint().apply {
    color = Color.makeRGB(255, 0, 0)
}

val whitePaint = Paint().apply {
    color = Color.makeRGB(255, 255, 255)
}

fun main() = SwingUtilities.invokeLater {
    System.setProperty("skiko.renderApi", "OPENGL")
    System.setProperty("skiko.vsync.enabled", "false")

    JFrame().apply {
        size = Dimension(1280, 720)
        add(SkiaLayer().apply {
            size = Dimension(1280, 720)
// for 0.4.0
//            renderer = object : org.jetbrains.skiko.SkiaRenderer {
            skikoView = object : SkikoView {
                override fun onRender(canvas: Canvas, width: Int, height: Int, nanoTime: Long) {
                    fpsCounter.tick()
                    canvas.drawRect(Rect(0f, 0f, width.toFloat(), height.toFloat()), redPaint)
                    repeat(particlesCount) {
                        val x = Math.random().toFloat()
                        val y = Math.random().toFloat()
                        canvas.drawRect(
                            Rect.makeXYWH(width * x, height * y, 10f, 10f),
                            whitePaint
                        )
                    }
                    needRedraw()
                }
            }
        })
        isVisible = true
    }
}

val particlesCount = 10_000
val fpsCounter = FPSCounter()

// a reduced copy from skiko
class FPSCounter(
    private val periodSeconds: Double = 2.0,
) {
    private val times = mutableListOf<Long>()
    private var lastLogTime = System.nanoTime()
    private var lastTime = System.nanoTime()

    fun tick() {
        val time = System.nanoTime()
        val frameTime = time - lastTime
        lastTime = time

        times.add(frameTime)

        if ((time - lastLogTime) > periodSeconds.secondsToNanos() && times.isNotEmpty()) {
            val average = (nanosPerSecond / times.average()).roundToInt()
            times.clear()
            lastLogTime = time
            println("FPS $average")
        }
    }

    private val nanosPerSecond = 1_000_000_000.0
    private fun Double.secondsToNanos(): Long = (this * nanosPerSecond).toLong()
}
```

**Comment by MohamedRejeb** [comment] 2023-08-24 09:43
Does this mean that it could have some effects on other targets as well? iOS? If so, fixing this problem is going to boost performance for all targets

**Comment by igordmn** [comment] 2023-08-24 10:34
If it is not a Java/JNI overhead issue, then, yes, it should affect all platforms.

**Comment by elijah-semyonov** [comment] 2023-09-01 13:15
https://github.com/JetBrains/skiko/compare/master...es/regression-rollback
Regression was introduced by commit from which this branch starts, this commit shows FPS similar to Compose 1.1.1.

Regression is not present on macOS targets.

**Comment by MohamedRejeb** [comment] 2023-09-25 08:04
Hey, Any news about this issue?

**Comment by igordmn** [comment] 2023-09-25 08:30
We plan to update Skia, and if won't resolve the issue, we'll look further. It either a Skia regression, or a build configuration change.

**Comment by MohamedRejeb** [comment] 2023-09-28 10:24
Awesome, thanks for the great work! I'm working on a drawing app and users are encountering some latency issues, I hope that this will fix it.

**Comment by igordmn** [comment] 2023-10-05 18:55
Upgrading Skia from m110 to m116 doesn't help.

I checked new Skiko with [this PR](https://github.com/JetBrains/skiko/pull/808) - FPS is the same

**Comment by RyuuyaS** [comment] 2023-10-20 16:15
Is there any news regarding this problem

**Comment by RafaelAthosPrime** [comment] 2024-01-29 21:56
Any news about this problem? I'm verry worried because my customers of my desktop project have low-end specs and the FPS is about 10~15 that doesn't support OPENGL
I spend the last 2 years working on this project since the compose multiplatform was in 1.0 alpha

**Comment by MohamedRejeb** [comment] 2024-02-08 16:15
Any news about this problem?

**Comment by RafaelAthosPrime** [comment] 2024-03-01 03:53
Any news? Same problem with the version 1.6.0

**Comment by okushnikov** [comment] 2024-07-14 15:07
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3543">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:27 UTC
Labels: enhancement, performance, desktop, p:high
