### ISSUE TITLE
iOS app using compose cannot find the image resources

### ISSUE THREAD

**Issue by BitByAVampire** [JetBrains/compose-multiplatform#3800] opened 2023-10-10 21:32 UTC
**Describe the bug**
Getting this error when launching app in simulator `Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: img.xml`

**Affected platforms**
- iOS

**Versions**
- Kotlin version*:  latest
- Compose Multiplatform version*:  1.5.3
- OS version(s)* (required for Desktop and iOS issues): 13.6 for macos, ios 16.4 simulator
- OS architecture (x86 or arm64): arm64 (my mac is M1)
- JDK (for desktop issues): 

**To Reproduce**
I am building an xcframework using 
```
kotlinArtifacts {
    Native.XCFramework("SharedNetwork") {
        targets(iosX64, iosArm64, iosSimulatorArm64)
        setModules(

            project(":shared:data:network"),
            project(":shared:data:impl"),
            project(":shared:data:protocols"),
            project(":shared:data:storage"),
            project(":shared:feature:onboarding"),
            project(":shared:feature:more")
        )
        kotlinOptions {
            //settings used to silence the errors raised by compiler due to crashkios.
            // see: https://github.com/touchlab/CrashKiOS/issues/46
            freeCompilerArgs = listOf(
                "-linker-options",
                "-U _FIRCLSExceptionRecordNSException " +
                        "-U _OBJC_CLASS_\$_FIRStackFrame " +
                        "-U _OBJC_CLASS_\$_FIRExceptionModel " +
                        "-U _OBJC_CLASS_\$_FIRCrashlytics"
            )
        }
    }
}
```
there are images under data/onboarding/src/commonMain/resources. **edit:  the path is shared/**feature**/onboarding/src/commonMain/resources
I add the framework to my app as a pod (it's a manual pod integration where we build the xcframework and then add it as a cocoapod separately). When we build and then open the app (from Xcode) the app crashes with above error logged. 
**Expected behavior**
The image should be found and displayed in the compose UI. 

**Additional context**
After doing some digging I was wondering if the `MacOSResourceImpl` in `Resource.macos.kt` is the problem, because i see the code that looks for the image is 
```
val contentsAtPath: NSData? = NSFileManager.defaultManager().run {
            //todo in future bundle resources with app and use all sourceSets (skikoMain, nativeMain)
            contentsAtPath("$currentDirectoryPath/src/macosMain/resources/$path")
                ?: contentsAtPath("$currentDirectoryPath/src/commonMain/resources/$path")
        }

``` 
and the file path being searched is definitely not anywhere in the built xcode project..

**Comment by dima-avdeev-jb** [comment] 2023-10-16 05:30
Hello!
For now, resources library works only with images and binary files from commonMain/resources directory in project. Please take a look at our sample here: https://github.com/JetBrains/compose-multiplatform-template/tree/main/shared/src/commonMain/resources

Resources can't be added throw the Xcode project or another cocoapods module.

Can you please try to start project from our template and try resources: https://github.com/JetBrains/compose-multiplatform-template

If you still will have some problems with resources - better to create minimal reproducible sample and share in on GitHub.

**Comment by BitByAVampire** [comment] 2023-10-16 08:42
We are building an xcframework using the example build script above, and we have resources in shared/feature/onboarding/src/commonMain/resources. the resources seem to not exist in the final xcframework output, by the error thrown when running app in xcode.

**Comment by dima-avdeev-jb** [comment] 2023-10-16 18:56
Can you please try to reproduce the same with our template project?
https://github.com/JetBrains/compose-multiplatform-template

**Comment by BitByAVampire** [comment] 2023-10-18 17:22
Hi, I was not able to reproduce the issue with your project. the setup of project is different. in yours, the xcode project has the "compile Kotlin" build step, and your build script does not use the new kotlinArtifacts.  In ours we are generating the xcframework and adding it to the xcode project as a pod independently. 

Update: Actually the workaround for us is to add a folder called `compose-resources` in the folder of the xcframework to store all the compose images, then we updated the podspec to include the compose-resources folder.

**Comment by BassirouRabo** [comment] 2023-10-18 21:54
@dima-avdeev-jb i have been getting similar issue, it looks like `https://github.com/JetBrains/compose-multiplatform-template` work with regular framework, however the issue is when moving to *cocoapods*

**Comment by dima-avdeev-jb** [comment] 2023-10-23 20:39
@BassirouRabo For Cocoapods we have this sample project:
https://github.com/JetBrains/compose-multiplatform/tree/master/examples/cocoapods-ios-example

**Comment by dima-avdeev-jb** [comment] 2023-10-23 20:40
I closed this Issue, but if some new questions will be founded - fill free to reopen it and ask more.

**Closed by dima-avdeev-jb** 2023-10-23 20:40 UTC
Labels: wait for reply, question

**Comment by BassirouRabo** [comment] 2023-10-23 21:22
@dima-avdeev-jb i noticed my `shared.podspec` does not include `spec.resources = ['build/compose/ios/shared/compose-resources']`, how is this `podspec` being generated?

**Comment by dima-avdeev-jb** [comment] 2023-10-27 04:08
@BassirouRabo It is generate with this ` kotlin("native.cocoapods")` Gradle plugin https://github.com/JetBrains/compose-multiplatform/blob/master/examples/cocoapods-ios-example/shared/build.gradle.kts#L3

**Comment by dima-avdeev-jb** [comment] 2023-10-27 04:10
@BassirouRabo Since Compose `1.5.3` we don't need to set `spec.resources = ...` in CocoaPods. Resources will work without it.

**Comment by BassirouRabo** [comment] 2023-10-27 04:13
> @BassirouRabo Since Compose `1.5.3` we don't need to set `spec.resources = ...` in CocoaPods. Resources will work without it.

I think the issue is when mixing with the resource library `moko` or `libres`, enabling one of those pluging override the `compose resource` directory

**Comment by okushnikov** [comment] 2024-08-26 14:35
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3800">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by AliAzaz** [comment] 2024-09-17 17:23
I am still facing the issue while generating XCFramework through this command:
`./gradlew assembleSharedLibraryDebugXCFramework`

As my resources are located in commonMain/composeResources/files

and this is my gradle:

````
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinCocoapods)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.jetbrainsCompose)
    alias(libs.plugins.compose.compiler)
    id("maven-publish")
}

kotlin {
    //android
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }

    //iOS
    val iosArm64 = iosArm64()
    val iosX64 = iosX64()
    val iosSimulatorArm64 = iosSimulatorArm64()

    val xcFramework = XCFramework("SharedLibrary")
    configure(listOf(iosArm64, iosX64, iosSimulatorArm64)) {
        binaries {
            framework {
                isStatic = true
                version = 1.0
                baseName = "SharedLibrary"
                xcFramework.add(this)
            }
        }
    }

    //Windows
    /*mingwX64("windows") {
        binaries {
            sharedLib {
                baseName = "SharedLibrary"
            }
        }
    }*/

    sourceSets {
        commonMain.dependencies {
            api(compose.runtime)
            api(compose.components.resources)
            api("app.cash.zipline:zipline:1.17.0")
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }

        iosMain.dependencies {

        }

        androidMain.dependencies {

        }

        //Desktop
        /*val windowsMain by getting
        windowsMain.dependencies {

        }*/
    }
}

android {
    namespace = "com.aliazaz.testkmplibrary"
    compileSdk = 34
    defaultConfig {
        minSdk = 22

        aarMetadata {
            minCompileSdk = 22
            minSdk = 22
            targetSdk = 34
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    sourceSets["main"].resources.srcDirs("src/commonMain/composeResources")
    // Ensure that the dependencies are packaged into the .aar file
    packagingOptions {
        resources.excludes.add("META-INF/*")
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

compose.resources {
    publicResClass = true
    packageOfResClass = "com.aliazaz.testkmplibrary"
    generateResClass = auto
}

````

**Comment by Reedyuk** [comment] 2024-12-09 11:25
When performing the assembleXCFramework task, i assume the compose resources are not bundled in. Is there a particular step we can run that isnt the embededAndSignForXcode - as this requires a few variables to be passed in.
I assume we need to run assembleXCFramework + another task to embed the compose resources

**Comment by Reedyuk** [comment] 2024-12-09 11:33
btw - isStatic = true - you cant have a static library with resources in ios, this could also be the reason
