### ISSUE TITLE
Wrong lineHeight for Text for small values

### ISSUE THREAD

**Issue by SerVB** [JetBrains/compose-multiplatform#2149] opened 2022-06-30 09:13 UTC
Code:

```kotlin
@Composable
@Preview
fun App() {
    var size by remember { mutableStateOf(27) }

    MaterialTheme {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally
        ) {

            Slider(
                value = size.toFloat(),
                onValueChange = { new -> size = new.roundToInt() },
                valueRange = 10f..128f
            )

            Text("$size")

            Box(
                modifier = Modifier
                    .size(size.dp)
                    .clip(CircleShape)
                    .background(Color.Cyan),
                contentAlignment = Alignment.Center,
            ) {
                val (fontSize, lineHeight) = size * 0.4.sp to size.sp

                Text(
                    "AP",
                    color = Color.Red,
                    fontWeight = FontWeight.Normal,
                    fontSize = fontSize,
                    lineHeight = lineHeight,
                )
            }

        }
    }
}
```

Android studio preview and an Android app shows it correct:

![grafik](https://user-images.githubusercontent.com/20105593/176639172-3dbbe19c-744d-4bac-9cff-7c90b21d0196.png)

IDEA preview and Desktop app shows it incorrect:

![grafik](https://user-images.githubusercontent.com/20105593/176639418-ca302811-e8e7-49d0-8708-b9d114c6cd6c.png)

It's notable that for bigger values (`size > 65`), Desktop version seems correct:

![grafik](https://user-images.githubusercontent.com/20105593/176639537-0965ec35-327d-4840-a7ba-9c3f46af00fd.png)

**Comment by igordmn** [comment] 2022-06-30 19:18
It seems the issue is because on desktop we change the height of each line and align it in the center, and on Android we change the height of all lines except the last one, and align lines on top.

Compose 1.2.0-alpha01-dev731
```
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable
fun App() {
    Column {
        Row {
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp,)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp * 2)
        }
        Row {
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp,)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp * 2)
        }
    }
}
```
<img width="382" alt="image" src="https://user-images.githubusercontent.com/5963351/176759294-2a99277f-0402-4a2b-b9fa-dbe3bd63f13c.png">

**Comment by igordmn** [comment] 2022-06-30 19:38
On 1.1.1 it behaves more strange - on large sizes it doesn't change the line height (thus we have the behaviour represented on the video):
```
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable
fun App() {
    Column {
        Row {
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp,)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp, lineHeight = 10.sp)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp, lineHeight = 10.sp * 4)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp, lineHeight = 10.sp * 0.5f)
        }
        Row {
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp,)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp, lineHeight = 10.sp)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp, lineHeight = 10.sp * 4)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 10.sp, lineHeight = 10.sp * 0.5f)
        }
        Row {
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp,)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp * 4)
            Text("AP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp * 0.5f)
        }
        Row {
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp,)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp * 4)
            Text("AP\nAP", modifier = Modifier.border(0.5f.dp, Color.Black), fontSize = 27.sp, lineHeight = 27.sp * 0.5f)
        }
    }
}
```
<img width="209" alt="image" src="https://user-images.githubusercontent.com/5963351/176762856-587a4ec9-dd1c-4143-a12a-68dc0e5c5602.png">

**Comment by okushnikov** [comment] 2024-08-26 15:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2149">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:46 UTC
Labels: bug, text
