### ISSUE TITLE
iOS capitalizes first letter despite KeyboardCapitalization.None

### ISSUE THREAD

**Issue by jamesmbowler** [JetBrains/compose-multiplatform#3187] opened 2023-05-18 18:25 UTC
Here's my field
```
OutlinedTextField(
                value = email,
                onValueChange = { email = it },
                label = { Text("Email") },
                keyboardOptions = KeyboardOptions(
                    keyboardType = KeyboardType.Email,
                    imeAction = ImeAction.Next,
                    capitalization = KeyboardCapitalization.None
                ),
                modifier = Modifier.fillMaxWidth()
            )
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.2
- Compose Multiplatform version*: 1.4
- OS version(s)* (required for Desktop and iOS issues): 12.6.1
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 11

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. in a multiplatform app, create a text field, like this 
```
OutlinedTextField(
                value = email,
                onValueChange = { email = it },
                label = { Text("Email") },
                keyboardOptions = KeyboardOptions(
                    keyboardType = KeyboardType.Email,
                    imeAction = ImeAction.Next,
                    capitalization = KeyboardCapitalization.None
                ),
                modifier = Modifier.fillMaxWidth()
            )
```
2. Run the iosApp, and see that the first letter is capitalized, when typing into the input.

**Expected behavior**
I'd expect this option to apply in iOS: KeyboardCapitalization.None

**Screenshots**

**Additional context**

**Comment by alexzhirkevich** [comment] 2023-05-18 18:40
`keyboardOptions` and `keyboardActions` are not implemented for iOS

**Comment by jamesmbowler** [comment] 2023-05-18 21:32
OK, thanks for the quick response.

**Comment by AlexeyTsvetkov** [comment] 2023-05-23 02:17
Duplicate of #2735

**Closed by AlexeyTsvetkov** 2023-05-23 02:17 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:17
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3187">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
