### ISSUE TITLE
Inconsistence in material3 between Android vs Desktop (and iOS)

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3453] opened 2023-08-03 08:37 UTC
**Describe the bug**
There are inconsistence between platforms. 

**Affected platforms**
Select one of the platforms below:
- Desktop
- iOS

**Versions**
- Kotlin version*: 1.9.0 
- Compose Multiplatform version*: 1.4.3, 1.5.0-beta01
- OS version(s)* (required for Desktop and iOS issues): MacOS 13.4.1, iOS 16 (But it's doesn't matter)
- OS architecture (x86 or arm64): Arm64
- JDK (for desktop issues): 17

**To Reproduce**
Minimal reproducible sample: https://github.com/dima-avdeev-jb/ios-android-inconsistent

**Expected behavior**
Android and Desktop (and iOS) should looks the same

**Screenshots**
### Android
![image](https://github.com/JetBrains/compose-multiplatform/assets/99798741/1dca6e89-e956-4da9-a3c8-5fd949a28e68)

### Desktop and iOS
![image](https://github.com/JetBrains/compose-multiplatform/assets/99798741/ce47dc4d-8610-484c-bb0b-ae246c63cbfc)
![image](https://github.com/JetBrains/compose-multiplatform/assets/99798741/7aee7b3a-d81f-4584-94b6-c6ba65732923)

**Comment by alexzhirkevich** [comment] 2023-08-03 10:13
Probably related: https://github.com/JetBrains/compose-multiplatform/issues/2383

**Comment by alexzhirkevich** [comment] 2023-08-07 19:31
@igordmn @dima-avdeev-jb 

It's not related directly to m3. You can reproduce it with an m2 text if you set `lineHeight` to 24.sp (default m3 bodyLarge). m2 default text style just don't care about line height.

Look like there is a bug in skiko paragraph implementation.

Here is an example of weird behavior of skiko paragraph on desktop and android with Roboto font (m3 or m2 text, doesn't matter). Looks like android always trying to align text to the top, when line height is greater that text size. But skiko justifies it in a strange way: if `lineHeight`/`fontSize` < 2 it aligns to the top, otherwice to the bottom.

I guess the issue is somewhere on [this line](https://github.com/JetBrains/compose-multiplatform-core/blob/1ca81d97e90e743b69b437ebf4bcdad1503d2b26/compose/ui/ui-text/src/skikoMain/kotlin/androidx/compose/ui/text/platform/SkiaParagraph.skiko.kt#L533)

<table>
<tr>
<td>
</td>
<td>
textSize = 10.sp
<br>
lineHeight = 16.sp
</td>
<td>
textSize = 10.sp
<br>
lineHeight = 20.sp
</td>
<td>
textSize= 10.sp
<br>
lineHeight = 24.sp
</td>
</tr>
<tr>
<td>
Desktop
</td>
<td>
<img width="50" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/607cbadb-ddca-469c-bf79-2c9534e89fa6">
</td>
<td>
<img width="50" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/aa295ae5-7b08-4a46-b0a4-23ebc46d2ffb">
</td>
<td>
<img width="50" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/449ea388-e932-4d7f-86fa-fa18fdafd739">
</td>
</tr>
<tr>
<td>
Android
</td>
<td>
<img width="50" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/4579dbc1-47f5-4459-9b32-fd12c58f3975">
</td>
<td>
<img width="50" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/fdae28bc-2d6b-4633-a5d3-a62b829b80e4">
</td>
<td>
<img width="50" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/8a4b36f7-40ee-4acd-8274-95feced7decb">
</td>
</tr>
</table>

**Comment by MatkovIvan** [comment] 2023-10-19 07:42
Probably related: #1082

**Comment by MatkovIvan** [comment] 2023-11-09 11:50
> Worth to try Roboto (the default Android font) on Desktop/iOS. If it will look the same as in Android, then it is not a bug, but font-dependent behavior.

Yep, different font is one of the reasons. The second one is an assumption that 
```kt
modifier = Modifier.fillMaxSize()
textAlign = TextAlign.Center,
```
will align the text vertically, but it's not (and should not). The proper way to do this is to add `wrapContentHeight` modifier:
```kt
.wrapContentHeight(
    align = Alignment.CenterVertically, // Default value
    unbounded = true // Makes sense if the size less then text
),
```

The initial sample with this modifier:
<img width="328" alt="Screenshot 2023-11-09 at 12 48 05" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/3abe078c-502d-4fa3-a55f-da1e99735c67">


_On Android Jetpack Compose before 1.6.0, there was a need to disable extra padding via `includeFontPadding` flag for proper centering. Now it's false by default. But that's android-only known "feature"_

So, I'm closing this as not a bug. cc @dima-avdeev-jb 

> If line height is greater than font size, android trims first and last line

That's a different issue, it happens only with custom `lineHeight`. Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/897

> Looks like there the bug is in skiko paragraph implementation.

It's a bug, we just didn't support that parameter at all 😅

**Closed by MatkovIvan** 2023-11-09 11:50 UTC
Labels: bug, desktop, ios

**Comment by okushnikov** [comment] 2024-07-14 16:09
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3453">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
