### ISSUE TITLE
Endless re-layout of `TextField` with `singleLine = true` and intrinsic measurement

### ISSUE THREAD

**Issue by StepByStepler** [JetBrains/compose-multiplatform#4760] opened 2024-05-05 20:37 UTC
**Describe the bug**
I'm adding screenshot tests for my screens, and one of my screens was rendering infinitely. I've narrowed this problem down to this reproducer:
```kotlin
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.layout.height
import androidx.compose.material3.TextField
import androidx.compose.ui.Modifier
import androidx.compose.ui.test.ExperimentalTestApi
import androidx.compose.ui.test.runComposeUiTest
import org.junit.jupiter.api.Test

class MyTest {
    @OptIn(ExperimentalTestApi::class)
    @Test
    fun testTextField() = runComposeUiTest {
        setContent {
            Box(
                modifier = Modifier
                    .height(IntrinsicSize.Min),
            ) {
                TextField(
                    value = "something",
                    singleLine = true,
                    onValueChange = {},
                )
            }
        }
    }
}
```

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 2.0.0-RC2
- Compose Multiplatform version*: 1.6.10-rc01
- OS version(s)* (required for Desktop and iOS issues): macOS Sonoma 14.4.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): Eclipse Adoptium 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create fresh project with JUnit 5 test dependency
2. Add test code above
3. Launch this test
4. This test will stuck on something and never finish

**Expected behavior**
Test finishing almost instantly since it is very simple and has no assertions

**Screenshots**

**Additional context**

**Comment by m-sasha** [comment] 2024-05-07 08:58
This is a problem with real runs, not just tests. The measuring and layout gets into an infinite remeasure/relayout loop on every frame.

Reproduces in 1.6.x, but not in 1.5.12

**Comment by m-sasha** [comment] 2024-05-08 19:28
Reproducer:
```
fun main() = singleWindowApplication {
    val state = remember { mutableStateOf(1) }
    Layout(
        measurePolicy = { measurables, constraints ->
            val measurable = measurables.first()
            val placeable = measurable.measure(constraints)
            val prevValue = Snapshot.withoutReadObservation {
                state.value
            }
            state.value = prevValue+1
            layout(100, 100) {
                state.value  // Read the state value!
                placeable.placeRelative(0, 0)
            }
        },
        content = {
            Text("Hello")
        }
    )
}
```

**Comment by m-sasha** [comment] 2024-05-08 19:44
What happens here is:
1. The state is written in the measure phase, and `GlobalSnapshotManager` receives a write notification and schedules calling `Snapshot.sendApplyNotifications()`, but it's not yet called because the main thread is busy.
2. The layout phase happens, which reads the state, marking the scope as having read it.
3. When the rendering of the current frame (`BaseComposeScene.render()` ) completes, the GSM calls `Snapshot.sendApplyNotifications()`, the scope reports that it has read that state, so the scope is marked as invalid.
4. The next time `BaseComposeScene.render()` is called, the whole thing repeats from 1.

This appears to be a bug, because the state is read after it has been written to, so it should not mark the scope as invalid.

There are several differences in Android that "cover" for this, preventing the infinite relayout:
- Between the layout and drawing phases, Android's Choreographer flushes the tasks scheduled by the main dispatcher, which includes the GSM. This means that the scope is marked as invalid before the drawing phase.
- Android's drawing phase (`AndroidComposeView.dispatchDraw`) actually calls `measureAndLayout` again before drawing. This causes the layout scope to be executed again, and its invalidation state is cleared.

Additionally, in CMP, we don't mark nodes only for layout. Our `Owner.onRequestRelayout` implementation actually marks the node as needing to be measured. So even if we add `Snapshot.sendApplyNotifications()` and `doLayout()` between layout and draw, `doLayout()` will end up executing both measure and layout on the node, bring us back to square zero.

**Closed** 2024-05-13 14:38 UTC
Labels: bug, test, desktop

**Comment by okushnikov** [comment] 2024-08-26 13:40
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4760">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
