### ISSUE TITLE
Text issue on Material3 MaterialTheme

### ISSUE THREAD

**Issue by wtfisthatzzz** [JetBrains/compose-multiplatform#3267] opened 2023-06-16 16:14 UTC
**Describe the bug**
On IOS there is always spacing on top of the text, but on Android it's normal

**Affected platforms**
iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Just use the material3.MaterialTheme 

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/21653867/7b319a1e-0339-4f0b-9cf3-5158225ddaae)

**Comment by mahozad** [comment] 2023-06-16 16:50
This is also true in Desktop. I think this issue is a duplicate of #2383.
It affects every component that has text in it (Text, TextField, Button, RadioButton, etc.).

**Comment by dima-avdeev-jb** [comment] 2023-06-18 18:55
Thanks to @mahozad. Duplicate of this issue: https://github.com/JetBrains/compose-multiplatform/issues/2383

**Closed by dima-avdeev-jb** 2023-06-18 18:55 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:16
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3267">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
