### ISSUE TITLE
Border`s width mismatch when set it to 0.dp

### ISSUE THREAD

**Issue by wwalkingg** [JetBrains/compose-multiplatform#910] opened 2021-07-20 07:58 UTC
when set width to 0.dp
```koltin
Window {
        Box(Modifier.padding(10.dp)){
            Box(
                modifier = Modifier.size(200.dp,180.dp).background(Color.Red.copy(alpha = 0.2f))
                    .border(color = Color.Primary,width =0.dp)
            ){}
        }
    }
```
![Screenshot_20210720_155433](https://user-images.githubusercontent.com/42681996/126283506-61c30f6d-367a-4649-bc96-82c8e172137d.png)
show mismatch!
i can just set it to 0.001:
```kotlin
border(color = Color.Primary,width =0.001.dp)
```

![Screenshot_20210720_155433](https://user-images.githubusercontent.com/42681996/126283824-9d81c099-1e2f-4650-9808-d63bc97c64f5.png)

**Comment by akurasov** [comment] 2021-07-20 08:11
Hi! The issue is that border is drawn even when it's width is zero, or is it something else?

**Comment by WWALKINGG** [comment] 2021-07-20 08:14
> Hi! The issue is that border is drawn even when it's width is zero, or is it something else?
at least it should be invisible , i think

**Comment by akurasov** [comment] 2021-07-20 08:16
Do you know if it is the same in Jetpack Compose(on Android)?

**Comment by WWALKINGG** [comment] 2021-07-20 08:20
> Do you know if it is the same in Jetpack Compose(on Android)?

sorry,i just

> Do you know if it is the same in Jetpack Compose(on Android)?

sorry, I do not know. I just  develop desktop applications🤯

**Comment by akurasov** [comment] 2021-07-20 10:02
I tried it on Android and behavior is different. Probably we should align it in Compose MPP. 

@WWALKINGG, do you have any business task related to this issue, or it is just a finding you wanted to share?

**Comment by WWALKINGG** [comment] 2021-07-20 10:11
> I tried it on Android and behavior is different. Probably we should align it in Compose MPP.
> 
> @WWALKINGG, do you have any business task related to this issue, or it is just a finding you wanted to share?

its  a finding.i have achieved my goal with another way.

**Comment by akurasov** [comment] 2021-07-20 10:13
Thank you. I believe it's priority is not very high then(zero-size border seems to be not used very often). Anyway will look at it eventually.

**Comment by okushnikov** [comment] 2024-07-14 17:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5339">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 11:07 UTC
Labels: question, desktop
