### ISSUE TITLE
IncludeFontPadding not found

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#3281] opened 2023-06-21 13:26 UTC
**Describe the bug**
Hi
I want to set `includeFontPadding = false`
But that not found in `platformTextStyle`
What should i do?

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): all
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): 17

**Comment by kirill-grouchnikov** [comment] 2023-06-21 13:28
Are you missing the `g` letter in `includeFontPadding`?

If not, what is the full snippet of how it looks like in your code?

**Comment by Walingar** [comment] 2023-06-21 13:50
Hi @mahramane this API is an Android specific. 
Could you please describe your use case why do you need it for all platforms? Or is it only to write the common code?

**Comment by mahramane** [comment] 2023-06-21 14:00
@Walingar 
Hi Bro
Currently, I want to use it for Android and Windows.
The font I use has a space from the top that cannot be removed. and caused the text not to be placed in the middle.
I want to remove it.

**Comment by Walingar** [comment] 2023-06-21 14:04
@mahramane Do you have this issue only with Android or with Windows as well?

**Comment by mahramane** [comment] 2023-06-21 14:14
@Walingar 
I just tested in desktop and Android.
And I saw this problem only in the desktop.

**Comment by Walingar** [comment] 2023-06-21 14:21
Is this open sourced font? If so, I would be glad if you can provide a sample project with this case. You can start with the template [from here](https://github.com/JetBrains/compose-multiplatform-desktop-template#readme) and add this component for desktop only.

**Comment by m-sasha** [comment] 2023-06-21 15:13
This is a known issue: https://github.com/JetBrains/compose-multiplatform/issues/2477
I don't think it's likely we'll add support for it, since Android itself is moving away from it.

**Comment by m-sasha** [comment] 2023-06-21 15:15
Hmm, actually, looks like Google decided to keep it (and removed the deprecation). So we may need to support it after all.

https://developer.android.com/jetpack/androidx/releases/compose-ui#1.5.0-beta01

**Comment by Walingar** [comment] 2023-06-21 15:47
Ah, thank you @m-sasha I missed this one. So I'll close this one as duplicate then. @mahramane you can subscribe for the mentioned issue!

**Comment by Walingar** [comment] 2023-06-21 15:47
Duplicate of https://github.com/JetBrains/compose-multiplatform/issues/2477

**Closed as completed by Walingar** 2023-06-21 15:47 UTC
Labels: duplicate

**Comment by okushnikov** [comment] 2024-07-14 16:16
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3281">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
