### ISSUE TITLE
SelectionContainer shouldn't be focusable

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2947] opened 2023-03-31 06:58 UTC
Compose 1.3.1, Windows 11

1. Run this snippet:
```
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    MaterialTheme {
        Column {
            Button({}) {
                Text("Button")
            }

            SelectionContainer {
                Text("Text")
            }

            Button({}) {
                Text("Button")
            }
        }
    }
}
```
2. Try to move focus between buttons with Tab/Shift-Tab keys
3. See, that SelectionContainer is focusable:

https://user-images.githubusercontent.com/5963351/229046402-fda82f73-2c31-4c23-8c75-e8123c954f37.mp4

Expected:
It shouldn't be focusable, and the focus should switch only between buttons.

**Comment by elijah-semyonov** [comment] 2023-05-04 10:14
@igordmn 
It behaves in the same way Android does with attached keyboard. Isn't it by design?

**Comment by elijah-semyonov** [comment] 2023-05-04 10:25
@igordmn 
It behaves the same way Android does, is it a bug?

https://user-images.githubusercontent.com/4167681/236178386-3a9f30c7-8200-4f0d-a3d1-da57c5de4ce1.mp4

**Comment by okushnikov** [comment] 2024-08-26 14:43
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2947">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:26 UTC
Labels: bug, focus management
