### ISSUE TITLE
Text looks bad in Windows 10

### ISSUE THREAD

**Issue by adamsiembida** [JetBrains/compose-multiplatform#875] opened 2021-07-10 17:39 UTC
Text seems to look poorly rendered in Windows 10. I opened the Code Viewer example and just immediately thought the text looks _off_. Maybe it's not applying subpixel anti-aliasing, but I'm really not sure. The text looks too sharp and kinda jagged.

![image](https://user-images.githubusercontent.com/2823875/125171805-2786a400-e184-11eb-9cb8-70c3e7dcda0e.png)

And I don't think its only this example. Ever since I started testing Compose Desktop I thought the text just didn't look quite right.

**Comment by igordmn** [comment] 2021-07-10 18:00
Text in Compose for Desktop is rendered without subpixel anti-aliasing for now. The issue is known and blocked by [the issue in skia](https://bugs.chromium.org/p/skia/issues/detail?id=10833) ([another one](https://bugs.chromium.org/p/skia/issues/detail?id=10666&q=skparagraph%20skfont&can=1))

P.S.
1. Flutter has [a similar issue](https://github.com/flutter/flutter/issues/63043)

2. UWP applications (and Start Menu) don't use subpixel anti-aliaing too:
![image](https://user-images.githubusercontent.com/5963351/125171977-b82ea580-e1bf-11eb-8658-b368b22ff040.png)
There is [an issue in WinUI](https://github.com/microsoft/microsoft-ui-xaml/issues/768)

**Comment by adamsiembida** [comment] 2021-07-10 22:56
Thanks for that information, it's good that the cause is known! I feel like I'm always having this issue whenever a new multiplatform-framework targets windows. I remember similar issues when Electron was new, and Qt also has issues unless you manually mess with text rendering.

**Comment by igordmn** [comment] 2021-08-17 13:58
By the way, there is a way to draw a text with subpixel antialiasing, if we use Canvas directly:
```
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.drawscope.drawIntoCanvas
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.window.singleWindowApplication
import org.jetbrains.skija.Color
import org.jetbrains.skija.Font
import org.jetbrains.skija.FontEdging
import org.jetbrains.skija.Paint
import org.jetbrains.skija.TextLine
import org.jetbrains.skija.Typeface

val font = Font(Typeface.makeDefault()).apply {
    edging = FontEdging.SUBPIXEL_ANTI_ALIAS
    size = 24f
}

fun main() = singleWindowApplication {
    Canvas(Modifier.fillMaxSize()) {
        drawIntoCanvas {
            it.nativeCanvas.drawTextLine(
                TextLine.make("Text", font),
                0f,
                -font.metrics.ascent,
                Paint().apply {
                    color = Color.makeRGB(0, 0, 0)
                }
            )
        }
    }
}
```
![image](https://user-images.githubusercontent.com/5963351/129739365-35ec2bbb-8081-49b9-8190-b1227b7414b0.png)

**Comment by adamsiembida** [comment] 2022-09-03 15:57
Thanks, this is huge 🎉 It basically opens up Compose Desktop for use on Windows!

**Comment by igordmn** [comment] 2022-10-05 11:56
> [igordmn](https://github.com/igordmn) closed this as [completed](https://github.com/JetBrains/compose-jb/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/JetBrains/skia-pack/commit/05623f71f13aec9c860175fc8c42257b6f7676ce [on Sep 2](https://github.com/JetBrains/compose-jb/issues/875#event-7313864863)

It seems GitHub closed it somehow, even it is not yet merged.

It wasn't meant to be closed, so reopening, until we merge all functionality (it won't be in 1.2.0)

**Comment by okushnikov** [comment] 2024-07-14 17:06
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5359">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:42 UTC
Labels: bug, text, skia, windows, desktop
