### ISSUE TITLE
Dialog's content not occupying the whole screen

### ISSUE THREAD

**Issue by dhng22** [JetBrains/compose-multiplatform#4252] opened 2024-02-07 08:18 UTC
**Describe the bug**
I'm trying to make a full-screen dialog, but somehow it has some kind of platform padding at the bottom which make my dialog can not be full, even with **usePlatformDefaultWidth** set to false
**Affected platforms**
- Android
- iOS

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.4
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Create a dialog and make the content go fillMaxSize() to see

**Expected behavior**
The content inside the dialog should occupy the whole window

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/86188270/68ea31d4-f609-4787-8fd8-278f3e442e26)

**Comment by MatkovIvan** [comment] 2024-02-07 09:06
Use `DialogProperties.usePlatformInsets` for ignoring insets on iOS. For Android there is `decorFitsSystemWindows` option (if it doesn't work - please open an issue in Google's Jetpack Compose issue tracker)

Duplicate of #3741
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/833
Available since 1.5.10

**Closed by MatkovIvan** 2024-02-07 09:06 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 15:57
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4252">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
