### ISSUE TITLE
Unable to use debugger on iOS using compose-multiplatform-template

### ISSUE THREAD

**Issue by realityexpander** [JetBrains/compose-multiplatform#3761] opened 2023-10-03 01:44 UTC
**Describe the problem**
Explain the performance issue you're experiencing, including the following details:

Projects created with the following template are not able to be debugged on iOS from AS:
https://github.com/JetBrains/compose-multiplatform-template#setting-up-your-development-environment

- What specific issue did you encounter? (e.g. missing frames, high CPU usage, memory leaks)
Unable to start debug mode on iOS from Android Studio. It's greyed out. 
Other projects work fine.

- Have you noticed any patterns or specific circumstances under which the problem occurs?
Just with the template.

**Affected platforms**
Select one of the platforms below:
- iOS

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version: 1.9.10
agp.version=8.0.2
- Compose Multiplatform version: 1.5.2
- OS version(s) (required for Desktop and iOS issues): any iOS,  my dev machine is running Mac OS13.5.2 (22G91)
- OS architecture (x86 or arm64): any
- JDK (for desktop issues): 17.0.7
- Android Studio Hedgehog | 2023.1.1 Beta 6

**Sample code**
Just download a repo made by the template  and try to start debugger on iOS

**Reproduction steps**
Just download a repo made by the template  and try to start debugger on iOS

**Additional information**
![image](https://github.com/JetBrains/compose-multiplatform/assets/5157474/cd7dedda-d637-45ed-9ba3-7390ca159b23)

**Comment by pjBooms** [comment] 2023-10-03 15:52
Hum. Debugger works well on my site …

<img width="1520" alt="Screenshot 2023-10-03 at 6 49 58 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/2777612/6b5a2c2f-0be4-4495-bd30-9a216a8b3f72">

**Comment by pjBooms** [comment] 2023-10-03 15:53
What version of KMP plugin do you have?

**Comment by realityexpander** [comment] 2023-10-03 16:08
￼

**Comment by realityexpander** [comment] 2023-10-03 16:13
Yes, if I use the KMP wizard with an older version of AS (Giraffe), debugging works fine.

But I cant use iOS Compose with those older IDE's

**Comment by pjBooms** [comment] 2023-10-03 16:21
Debugger works with the Hedgehog beta on my site. So the most probably you have some configuration issue. 
So what version of KMP plugin do you have with Hedgehog?

**Comment by realityexpander** [comment] 2023-10-03 16:23
I assume you mean this plug-in… (name changes are confusing)

￼

**Comment by pjBooms** [comment] 2023-10-03 17:18
I can't see the attachment, only ￼ -- what is it?

**Comment by pjBooms** [comment] 2023-10-03 17:36
>Yes, if I use the KMP wizard with an older version of AS (Giraffe), debugging works fine.

And if you use KMM wizard with the Hedgehog beta? Does the debugger work?

**Comment by realityexpander** [comment] 2023-10-03 18:32
Cant see attachments? Ok...that makes things more difficult in 2023. (Lol)

I am using Kotlin Multiplatform Mobile plug-in version 0.6.1(231)-9 (I assume this the KMP plug-in you are referring to)

I tried using the KMP(KMM) project wizard.

Debugging is disabled for iOS.

Attempt to run in debug mode for Android:

Gets this error, and no breakpoint is triggered:

Cannot load class com.android.tools.compose.debug.ComposeFunctionBreakpointType ( error: class com.android.tools.compose.debug.ComposeFunctionBreakpointType cannot inherit from final class org.jetbrains.kotlin.idea.debugger.core.breakpoints.KotlinFunctionBreakpointType, classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Jetpack Compose, id=androidx.compose.plugins.idea, descriptorPath=plugin.xml, path=/Volumes/TRS-83/Applications/Android Studio Hedgehog | 2023.1.1 Beta 6.app/Contents/plugins/android-compose-ide-plugin, version=231.9392.1.2311.10844163, package=null, isBundled=true), packagePrefix=null, instanceId=130, state=active) )



My AS version:
Android Studio Hedgehog | 2023.1.1 Beta 6
Build #AI-231.9392.1.2311.10844163, built on September 21, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    analyze.exceptions.on.the.fly=true
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.tooltip.initialDelay=812
    ide.experimental.ui=true
    ide.browser.jcef.gpu.disable=true

Non-Bundled Plugins:
    com.c5inco.modifiers (1.0.14)
    com.github.copilot (1.3.0.3323)
    wu.seal.tool.jsontokotlin (3.7.4)
    org.jetbrains.kotlin (231-1.9.20-Beta2-release-363-AS8109.175)
    idea.plugin.protoeditor (231.9225.5)
    com.wakatime.intellij.plugin (14.2.2)
    com.github.airsaid.androidlocalize (3.0.0)
    DBN (3.4.1220.0)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-231)
    com.jetbrains.kmm (0.6.1(231)-9)
    com.squareup.sqldelight (2.0.0)
    com.developerphil.adbidea (1.6.11)
    org.jetbrains.compose.desktop.ide (1.5.2)
    by.overpass.svg-to-compose-intellij (0.12)
    mobi.hsz.idea.gitignore (4.5.1)
    com.abeade.plugin.figma.import (1.0.8)

**Comment by pjBooms** [comment] 2023-10-03 20:40
Closing the issue because it does not relate to Compose Multiplatform and we cannot reproduce it.

**Closed by pjBooms** 2023-10-03 20:40 UTC
Labels: android studio, IDE plugin

**Comment by realityexpander** [comment] 2023-10-03 22:36
OK, thanks for the confirmation and help!

**Comment by terrakok** [comment] 2023-10-04 08:57
KN debugger is experimental. You have to enable it explicitly
![image](https://github.com/JetBrains/compose-multiplatform/assets/3532155/47a471a5-bc20-4028-be70-7f79dfa55221)

**Comment by realityexpander** [comment] 2023-10-04 18:00
OK, that fixed it!

I didn’t see the notice to turn on that very hidden feature!

Thanks for the quick response.

Best,
Chris

**Comment by nacho4d** [comment] 2024-05-10 16:03
It looks like turning on/off above kotlin settings fixes the debug button.
I enabled experimental Multiplatform IDE features and it got fixed.

Thank you

**Comment by okushnikov** [comment] 2024-08-26 13:40
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3761">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
