### ISSUE TITLE
iOS BasicTextField keyboardType does not change

### ISSUE THREAD

**Issue by slartus** [JetBrains/compose-multiplatform#3885] opened 2023-10-31 05:52 UTC
**Describe the bug**

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.2, 1.5.3
- OS version(s)* (required for Desktop and iOS issues): 16-17

**To Reproduce**
```@Composable
fun App() {
    MaterialTheme {
        var keyboardOptions by remember { mutableStateOf(KeyboardOptions.Default) }
        Column(Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
            Row {
                Button(
                    onClick = {
                        keyboardOptions =
                            KeyboardOptions.Default.copy(keyboardType = KeyboardType.Phone)
                    }
                ) {
                    Text("Phone")
                }
                Button(
                    onClick = {
                        keyboardOptions =
                            KeyboardOptions.Default.copy(keyboardType = KeyboardType.Number)
                    }
                ) {
                    Text("Number")
                }
                Button(
                    onClick = {
                        keyboardOptions =
                            KeyboardOptions.Default.copy(keyboardType = KeyboardType.Email)
                    }
                ) {
                    Text("Email")
                }
            }
            val focusRequester = remember { FocusRequester() }
            BasicTextField(
                modifier = Modifier.fillMaxWidth().focusRequester(focusRequester)
                    .background(color = Color.LightGray),
                value = "",
                onValueChange = {},
                singleLine = true,
                keyboardOptions = keyboardOptions,
            )

            LaunchedEffect(Unit) {
                focusRequester.requestFocus()
            }
        }
    }
}```

**Comment by eymar** [comment] 2023-10-31 10:12
Reproduced on iOS with 1.5.10-rc02 too.
Android works fine: it changes the keyboard layout when the new keyboard type selected. iOS changes the keyboard type only after a character was typed in the TextField.

**Comment by eymar** [comment] 2023-10-31 10:29
Investigation: I can't debug properly right now, but maybe the cause is somewhere here - https://github.com/JetBrains/compose-multiplatform-core/blob/8845d3031785beb2ee69486190272158ae05e6a9/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/CoreTextField.kt#L560
new `imeOptions` value is expected to trigger the DisposableEffect to restart.

**Comment by okushnikov** [comment] 2024-08-26 13:38
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3885">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:38 UTC
Labels: bug, text, ios, reproduced
