### ISSUE TITLE
Function 'getKoin' can not be called: No function found for symbol

### ISSUE THREAD

**Issue by HahhVwgwg** [JetBrains/compose-multiplatform#4361] opened 2024-02-24 11:05 UTC
**Bug**
I cannot build a web version, after upgrading to 1.6.0-rc03. 

**Affected platforms**
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 1.9.22
- Koin dependency*: 3.5.0 (happens with latest version also 3.5.3)
- Compose Multiplatform version*: 1.6.0-rc03
- OS architecture (x86 or arm64): arm64

**To Reproduce**
1. Run the project with "koin" dependency and upgrade to  1.6.0-rc03

Uncaught runtime errors:

ERROR
Function 'getKoin' can not be called: No function found for symbol 
`
'org.koin.compose/getKoin|getKoin(androidx.compose.runtime.Composer?;kotlin.Int){}[0]'
IrLinkageError: Function 'getKoin' can not be called: No function found for symbol 'org.koin.compose/getKoin|getKoin(androidx.compose.runtime.Composer?;kotlin.Int){}[0]'
    at throwLinkageError (webpack-internal:///./kotlin/kotlin-kotlin-stdlib.js:7106:11)
    at protoOf.Content_a1ofyo_k$ (webpack-internal:///./kotlin/DNAPaymentsKMP-composeApp.js:57127:7)
    at ComposableSingletons$SlideTransitionKt$lambda_1$lambda_40c7b8 (webpack-internal:///./kotlin/DNAPaymentsKMP-composeApp.js:120641:8)
    at protoOf.invoke_gk4tfu_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:38375:92)
    at Object.eval [as _v] (webpack-internal:///./kotlin/DNAPaymentsKMP-composeApp.js:120633:25)
    at eval (webpack-internal:///./kotlin/DNAPaymentsKMP-composeApp.js:120490:18)
    at protoOf.invoke_z8di7s_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:38347:92)
    at eval (webpack-internal:///./kotlin/DNAPaymentsKMP-composeApp.js:120506:25)
    at CompositionLocalProvider_0 (webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime.js:7526:5)
    at protoOf.SaveableStateProvider_3h7wny_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-compose-runtime-runtime-saveable.js:598:5)`

**Comment by dima-avdeev-jb** [comment] 2024-02-25 08:17
`org.koin.compose/getKoin` it is not a Compose package and function.
Look's like it is compiler related Issue.
Are this bug happends only in JS and Wasm?

@HahhVwgwg 
Can you please create a minimal reproducible sample project of this bug on GitHub?

**Comment by HLCaptain** [comment] 2024-02-25 19:01
I would recommend you to upgrade Koin to version [3.6.0-wasm-alpha2](https://mvnrepository.com/artifact/io.insert-koin/koin-bom/3.6.0-wasm-alpha2). It should support Wasm and JS target better. It works for me using Compose Multiplatform `1.6.0-rc03`. Project: [new commit with updated dependencies will be here](https://github.com/HLCaptain/butler/tree/5-remove-gitlive-firebase-sdk-implementation-to-make-project-multiplatform/client).

**Comment by dima-avdeev-jb** [comment] 2024-02-28 15:10
@HahhVwgwg
I will close this Issue because it is not related to Compose Multiplatform. Please ask Koin developers for help.
But fill free to reopen it if you will have additional questions.

**Closed by dima-avdeev-jb** 2024-02-28 15:10 UTC
Labels: bug, wait for reply

**Comment by okushnikov** [comment] 2024-08-26 13:46
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4361">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
