### ISSUE TITLE
ComposeUIViewController not released at all

### ISSUE THREAD

**Issue by Alex009** [JetBrains/compose-multiplatform#3201] opened 2023-05-23 16:08 UTC
**Describe the bug**
I embed `ComposeUIViewController` to native iOS navigation. When i navigate back current `ComposeUIViewController` should release memory, but it's not. 

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.10 , 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4 (simulator)
- OS architecture (x86 or arm64): tested on arm64

**To Reproduce**
1. clone https://github.com/Alex009/compose-ui-vc-leak
2. run app
3. navigate back to root (press back at top left corner)
4. check memory - it's not released
5. run `Simulate memory warning` on simulator - you see in logs that many `ComposeUIViewController` got this warning

**Expected behavior**
`ComposeUIViewController` should release memory when it's not used by app. 

**Screenshots**
<img width="1512" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5010169/0e005bc2-fc9c-4ae0-ac51-772908fd613b">

**Additional context**

**Comment by alexzhirkevich** [comment] 2023-05-24 13:00
Had the same problem. I thought that was my fault of leaked reference somewhere :)

**Comment by warnyul** [comment] 2023-05-29 22:01
I have a workaround for this. I just set the `ComposeUIViewController.view` to an empty UIView.

**Comment by warnyul** [comment] 2023-05-29 23:27
But it not solved my original memory leaks. Somewhy lot of IOSurface stuck in the memory:

<img width="1112" alt="Screenshot 2023-05-29 at 23 45 35" src="https://github.com/JetBrains/compose-multiplatform/assets/1662183/36af0624-cbed-470c-af6c-783cd72ea975">

Do you experience the same?

**Comment by elijah-semyonov** [comment] 2023-06-05 07:15
The problem is pinned down and is related to GC. In this particular case it's resolved via using new Kotlin language feature to manually release native API reference counted objects when their lifetime is critical for correct usage of API (CAMetalDrawable is living for too long and holds IOSurface memory). The latest possible moment the fix arrives is release associated with Kotlin 1.9.0.

**Comment by elijah-semyonov** [comment] 2023-07-26 08:27
I found more sources of this leak caused by interaction of GC and ARC-managed memory, to be resolved later

**Comment by elijah-semyonov** [comment] 2023-08-08 07:49
The leak of ComposeWindow itself (but not all associated resources) is fixed in [this PR](https://github.com/JetBrains/compose-multiplatform-core/pull/728)

**Closed** 2023-08-08 10:16 UTC
Labels: bug, ios, reproduced

**Comment by okushnikov** [comment] 2024-08-26 14:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3201">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
