### ISSUE TITLE
LWJGL Integration

### ISSUE THREAD

**Issue by smallshen** [JetBrains/compose-multiplatform#652] opened 2021-05-09 01:40 UTC
Since it uses skia, it is possible to use jetpack compose in LWJGL, it would help build ui in lwjgl application.
Such as UI in Minecraft Mods

https://github.com/semoro/MCCompose
https://github.com/smallshen/JetpackComposeMinecraft

Those two are able to use but not perfect, not with new version, can't load on windows and etc.

It would be good to have official support with LWJGL integration.

**Comment by olonho** [comment] 2021-05-11 08:59
Contributions are welcome in this direction.

**Comment by igordmn** [comment] 2021-11-02 09:49
Check [the example](https://github.com/JetBrains/compose-jb/tree/master/experimental/lwjgl-integration). 80-90% of features work.

Officially we still don't support LWJGL.

**Comment by smallshen** [comment] 2021-11-05 08:57
Thanks for the work, already make Compose working in Minecraft, waiting to get rid of awt events

**Comment by smallshen** [comment] 2022-01-22 22:58
An issue with cursor position when trying to implement more things with OpenGL.
https://github.com/JetBrains/compose-jb/issues/652

**Comment by smallshen** [comment] 2022-01-23 06:51
The cursor on the text field is not working.

**Comment by akurasov** [comment] 2022-01-24 11:41
Maybe you could share a bit more info on your solution, so others could use is too?

**Comment by jsixface** [comment] 2022-06-08 18:50
Question: I see the LWJGL integration example uses OpenGL . Is it possible to use OpenGL ES to render instead of OpenGL? I saw Skia support rendering to OpenGL ES through ANGLE. If it is possible what steps would that take?

**Comment by hakanai** [comment] 2022-09-30 02:24
Here's a [more cursed example](https://github.com/ephemeral-laboratories/ComposeVR) based somewhat on the LWJGL example which shows what you have to go through to render to an offscreen buffer. I got to the point where it renders, but handling input looks like it will be way too hard without putting a lot of time into research.

The other use case I have for this sort of integration is pretty much the exact opposite - there's an application I want to write where the main UI is all Compose, but then I want a preview which is a separate OpenGL context. Maybe I can fake it by copying the texture to an image and displaying the image, but the less copies I can get away with, the better.

**Comment by daocaoren123** [comment] 2022-10-09 17:23
> 这是一个基于 LWJGL 示例的[更受诅咒的示例，它显示了渲染到屏幕外缓冲区所必须经历的事情。](https://github.com/ephemeral-laboratories/ComposeVR)我已经到了渲染的地步，但是如果不花大量时间进行研究，处理输入看起来太难了。
> 
> 我对这种集成的另一个用例几乎完全相反——我想编写一个应用程序，其中主 UI 都是 Compose，但是我想要一个预览，它是一个单独的 OpenGL 上下文。也许我可以通过将纹理复制到图像并显示图像来伪造它，但是我可以逃脱的副本越少越好。

**Comment by daocaoren123** [comment] 2022-10-09 17:35
The problem is probably the same with the desktop application I'm currently experimenting with, where I'm unable to combine the compose ui and opengl render data together

**Comment by smallshen** [comment] 2022-10-20 07:46
@jsixface @hakanai rendering render compose inside Minecraft(which is lwjgl) is possible
https://www.youtube.com/watch?v=DOSsVuRlzOI

But compose performance is not good enough for games when you have a complex UI. It's probably enough for small screens or a to-do list. 

1. Current desktop ComposeSence will re-run the layout after every key-mouse input event, (the older version doesn't have it) which blocks the thread.
2. State management (updating a state from another thread or concurrently) is limited to one thread.
3. no async layout. layout phase is blocking the rendering. In my example,  with Minecraft. the UI content is changing all the time. which needs re-render every frame. Plus problems in 1 and 2. It's actually blocking the main thread(Redner thread) a lot. 


# Some not so accurate benchmark

Minecraft 1.19.2 (Fabric, Sodium, Iris, Faithful resource pack, playing on hypixel skywars)

UI is something like in this video https://www.youtube.com/watch?v=UMNsio6ah0I (with chat hud rewrite in compose)

the blur effect is also written in compose and skia

No Skia, no compose: 100-150 fps

Skia only, no compose: 100-130 fps

No Skia, compose only(states, effects): 45-90 fps

Full Compose: 35-80 fps



Multiple factors made compose not really ideal for games. If noria is open source or public, I would consider using noria in the game, based on the performance of the fleet.

**Comment by hakanai** [comment] 2022-10-20 23:42
In my case, the comparison would probably have to be between a full app running in a normal window and then being injected in as an overlay using XSOverlay or similar, vs. an app running compose and throwing the texture directly at the overlay API.

Both run at about the same speed as far as I can tell from inside VR.

Throwing the texture directly at the overlay API should use less CPU resources overall, though, because in the case of the window, the framework still has to do a framebuffer swap to display the new content, but then some other application has to grab that window and then inject _that_ as a texture into the overlay.

Only issue is, getting input to work for the overlay is way too hard. :(

**Comment by okushnikov** [comment] 2024-08-26 15:46
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6047">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:22 UTC
Labels: enhancement, discussion
