### ISSUE TITLE
UIKitView is displayed on top of all other components

### ISSUE THREAD

**Issue by artsmvch** [JetBrains/compose-multiplatform#3848] opened 2023-10-22 21:18 UTC
**Describe the bug**
`UIKitView` is displayed on top of all other components

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.10-rc01
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4
- OS architecture (x86 or arm64): x86

**To Reproduce**
[Here](https://gist.github.com/artsmvch/1f8eeb80c4b4f8b23bff0fee0d75f963) is a `Compose` screen for iOS.
The screen is a stack of two boxes with video players inside them. Video players are implemented via `UIKitView`.
But the video player from the bottom box is displayed on top of all other components (See attached screenshot).

**Expected behavior**
The first video is not visible at all, because it is placed under the second video and the blue background.

**Screenshots**

<img width="417" alt="Screenshot 2023-10-22 at 23 16 09" src="https://github.com/JetBrains/compose-multiplatform/assets/61359788/ed420ef7-21e1-4850-a009-fe47d40d5295">

**Additional context**
If I remove the top video, the bottom video will not be visible (correct behaviour).

**Comment by KevinnZou** [comment] 2023-10-30 02:04
@dima-avdeev-jb I think this [issue](https://github.com/KevinnZou/compose-webview-multiplatform/issues/34) is also caused by this bug

**Comment by shuaihuzhou** [comment] 2024-01-20 04:37
It also happed to me, has it been solved?

**Comment by dima-avdeev-jb** [comment] 2024-01-29 10:37
Maybe this issue is related with https://github.com/JetBrains/compose-multiplatform-core/pull/965

**Comment by dima-avdeev-jb** [comment] 2024-01-29 10:39
@artsmvch Can you please wait version `1.6.0-beta02` and test it again

**Comment by dima-avdeev-jb** [comment] 2024-02-27 06:05
@artsmvch Can you please check it on version 1.6.0-rc03 ?

**Comment by artsmvch** [comment] 2024-02-28 16:56
@dima-avdeev-jb it works well not, thanks!

**Comment by MatkovIvan** [comment] 2024-02-28 17:03
Great. The current state will work if it's displayed at the same time. https://github.com/JetBrains/compose-multiplatform-core/pull/1145 - will solve the situation in a more generic way. Closing as the original issue is already resolved

**Closed by MatkovIvan** 2024-02-28 17:03 UTC
Labels: bug, ios, reproduced, uikit interop

**Comment by okushnikov** [comment] 2024-07-14 15:08
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3848">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
