### ISSUE TITLE
Pressing backspace in text field should delete entire emoji, even when its a compound emoji

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#3759] opened 2023-10-02 19:19 UTC
**Describe the bug**

Certain characters, like flags or family emojis, are compound symbols made up of multiple unicode characters. For example:
<img width="670" alt="Screenshot 2023-10-02 at 21 16 54" src="https://github.com/JetBrains/compose-multiplatform/assets/2178959/2466677a-a68c-4940-821d-cbd6aa54bc30">

<img width="640" alt="Screenshot 2023-10-02 at 21 17 27" src="https://github.com/JetBrains/compose-multiplatform/assets/2178959/9d30f855-4ccd-4e0f-9891-a9a5a062a528">

These are expected to be deleted with a single "backspace" press. However, in Compose Multiplatform, they are handled as their individual joined pieces:

https://github.com/JetBrains/compose-multiplatform/assets/2178959/582c3510-b8d8-4fdd-b7c3-9512ebcd6c95

**Affected platforms**
Select one of the platforms below:
- iOS (did not test on Desktop)

**Versions**
Compose 1.5.2

**To Reproduce**
Type 👩‍👩‍👧‍👧 into a text field and press backspace. Watch the individual family members disappear.

**Expected behavior**
The whole emoji should be deleted

**Comment by MatkovIvan** [comment] 2023-10-02 19:41
Duplicate of #3104, should be fixed in the last beta

**Closed by MatkovIvan** 2023-10-02 19:41 UTC
Labels: bug, ios, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:11
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3759">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
