### ISSUE TITLE
[desktop] SystemTray Enhancement

### ISSUE THREAD

**Issue by xinkunZ** [JetBrains/compose-multiplatform#3684] opened 2023-09-15 06:28 UTC
compose desktop use awt SystemTray, it has many broken behavior：
1. not support CJK font on windows #1936
2. not support hidpi on windows
3. SystemTray use awt `PopupMenu`, It has not been maintained for a long time, maybe use `JPopupMenu` instead or some compose way used in Toolbox [like this](https://stackoverflow.com/questions/74297092/styling-compose-for-desktop-tray-composable) 
    * plz let me know how toolbox implement the system tray in this picture

**Comment by MatkovIvan** [comment] 2023-09-15 10:52
Thank you for opening this issue and detailing the problems you're experiencing with SystemTray when using Compose Desktop. Here's some information to address your concerns:

1. Regarding the issue of Chinese characters generating garbled code in the system tray (#1936), we acknowledge that this is an existing problem, so please follow the mentioned issue. 

2. As for the concern on HiDPI support on Windows, could you please follow bug issue template and provide more details for us to better understand the problem? Kindly describe the current situation, what was expected, the environment where you noticed this issue, and the version of Compose Desktop you're using. 

3. The issue is already discussed in #289. According to the discussions there, Toolbox uses a system API to position an undecorated compose window. This is a similar strategy we could consider for solving the present matter. 

Thank you for your patience and your valuable contributions to the community.

**Comment by okushnikov** [comment] 2024-08-26 14:36
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3684">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:23 UTC
Labels: enhancement, wait for reply, tray, desktop
