### ISSUE TITLE
Window resizing causes artifacts on Windows

### ISSUE THREAD

**Issue by kobutri** [JetBrains/compose-multiplatform#164] opened 2020-12-02 23:22 UTC
I know from discussions around other frameworks that properly handling window resizing is a notoriously hard issue, but I hope it is something that will get addressed fairly soon.

**Comment by GGorAA** [comment] 2020-12-07 09:31
And not only on Windows. I think it is an issue on every platform.
For example, the  `BottomSheet` is not disappearing when you hide it: it is just outside of the window. And when you resize it, you can see the bottom sheet trying to hide :D

**Comment by hakanai** [comment] 2021-01-08 21:55
The example Code Viewer application being resized, for example:

![image](https://user-images.githubusercontent.com/43236/104068093-734da480-5258-11eb-9491-f4e242b37afc.png)

**Comment by Rsedaikin** [comment] 2021-01-12 09:22
@hakanai could you please give your PC specifications? I cannot reproduce this bug. On Windows, when you resize a window, you can usually get black areas on the right and bottom of the window.

**Comment by hakanai** [comment] 2021-01-15 01:51
OS: Windows 10 Home 10.0.19041 Build 19041
Graphics card: NVIDIA GeForce GTX 1080 Ti  (ROG-STRIX-GTX1080TI-O11G-GAMING)
Graphics driver: 27.21.14.5671

And although I get this issue, I don't get it _every_ time I launch the demo app. Sometimes it does pad the space with black. The most reliable way to get it to happen so far has been to click around on the tree on the left until the demo app hangs, and then resize the window.

**Comment by FranckRJ** [comment] 2021-02-26 20:43
> On Windows, when you resize a window, you can usually get black areas on the right and bottom of the window.

@Rsedaikin Will this be fixed ?

**Comment by CeH9** [comment] 2021-03-17 12:06
Discussed same  here(ru) https://t.me/compose_mpp/1437 
I think realtime resizing should be exposed as optional parameter rather than forced for all apps. Intellij idea(swing) for example have same behavior, while chrome hasn't.

**Comment by olonho** [comment] 2021-03-25 07:47
Could you please retry with latest versions of Compose?

**Comment by jimgoog** [comment] 2021-03-25 16:43
The latest build number can be found here: https://github.com/JetBrains/compose-jb/tags

When responding with the test results, please mention which version you used, for the sake of posterity

**Comment by kobutri** [comment] 2021-03-25 16:54
@jimgoog I just tested 0.4.0-build176 and the problem persists.

**Comment by okushnikov** [comment] 2024-07-14 17:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5572">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 11:11 UTC
Labels: ui glitch, desktop
