### ISSUE TITLE
[Wasm] Variable fonts are displayed as �����

### ISSUE THREAD

**Issue by Nek-12** [JetBrains/compose-multiplatform#4635] opened 2024-04-16 20:58 UTC
**Describe the bug**

Variable fonts seem to not be supported on compose/wasmJs

Platform:
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*:  1.9.23
- Compose Multiplatform version*:  1.6.2
- OS architecture (x86 or arm64): Arm 64
- Device (model or simulator for iOS issues): Chrome Version 124.0.6367.49 (Official Build) beta (arm64)  
- JDK (for desktop issues): 21

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
Use a variable-width font, such as [Comfortaa](https://fonts.google.com/specimen/Comfortaa) 

**Expected behavior**
Font is displayed 

**Screenshots**

![Untitled 2](https://github.com/JetBrains/compose-multiplatform/assets/46318640/aeb53cf9-f961-41a2-926b-ddd1a56959cd)

**Comment by terrakok** [comment] 2024-04-17 12:51
duplicates https://github.com/JetBrains/compose-multiplatform/issues/3051

**Comment by Nek-12** [comment] 2024-04-17 17:57
How is this a duplicate if the issue is that variable fonts are not supported (not emoji, not non-english characters and not font styles)?

**Comment by terrakok** [comment] 2024-04-18 07:22
The issue is the same.

**Comment by okushnikov** [comment] 2024-08-26 13:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4635">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:49 UTC
Labels: bug, text, web
