### ISSUE TITLE
How to get the location of the tray icon

### ISSUE THREAD

**Issue by guiyanakuang** [JetBrains/compose-multiplatform#3965] opened 2023-11-23 02:32 UTC
Like the toolbox, I want to click on the tray icon to display my main interface, but I'm not finding any way to position the icon so that my interface stays below it? Is there an api for this?
<img width="601" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/4069905/3f55f01f-bb13-4ab7-831d-2cb60433659b">

**Comment by MatkovIvan** [comment] 2023-11-23 09:52
Duplicate of #289

**Closed by MatkovIvan** 2023-11-23 09:52 UTC
Labels: enhancement, submitted

**Comment by MatkovIvan** [comment] 2023-11-23 09:54
> Is there an api for this?

Not in Compose, but you can use system API for that

**Comment by okushnikov** [comment] 2024-07-14 16:09
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3965">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by enciyo** [comment] 2024-09-04 16:36
I found a workaround like below. At least one click is needed to get Windows location of the TrayIcon

    import androidx.compose.runtime.compositionLocalOf
    import androidx.compose.ui.unit.dp
    import androidx.compose.ui.window.WindowPosition
    import java.awt.SystemTray
    import java.awt.TrayIcon
    import java.awt.event.MouseEvent
    import java.awt.event.MouseListener
    import java.beans.PropertyChangeEvent
    import java.beans.PropertyChangeListener
    
    
    val LocalTrayIconWindowPosition = compositionLocalOf { TrayIconWindowPosition() }
    
    class TrayIconWindowPosition : PropertyChangeListener, MouseListenerWrapper {
    
        @Volatile
        var currentLocation: WindowPosition = WindowPosition(0.dp, 0.dp)
        private val propertyName = "trayIcons"
    
        init {
            if (SystemTray.getSystemTray().trayIcons.isEmpty())
                SystemTray.getSystemTray().addPropertyChangeListener(propertyName, this)
        }
    
    
        override fun propertyChange(evt: PropertyChangeEvent?) {
            getLastTray().addMouseListener(this)
        }
    
        override fun mousePressed(e: MouseEvent) {
            synchronized(this) {
                currentLocation = WindowPosition(e.x.dp, e.y.dp)
            }
            getLastTray().removeMouseListener(this)
        }
    
    
        private fun getLastTray(): TrayIcon {
            return SystemTray.getSystemTray().trayIcons.last()
        }
    
    }
    
    private interface MouseListenerWrapper : MouseListener {
        override fun mouseClicked(e: MouseEvent?) = Unit
        override fun mousePressed(e: MouseEvent) = Unit
        override fun mouseReleased(e: MouseEvent?) = Unit
        override fun mouseEntered(e: MouseEvent?) = Unit
        override fun mouseExited(e: MouseEvent?) = Unit
    
    }
