### ISSUE TITLE
Keyboard issues

### ISSUE THREAD

**Issue by artsmvch** [JetBrains/compose-multiplatform#3485] opened 2023-08-11 22:34 UTC
**Describe the bug**
After migrating to 1.5.0-beta02, new keyboard issues appeared in iOS:
- [x] The layout is not smoothly panned when the keyboard appears.
- [x] Extra space between the keyboard and the text field.
- [x] Buttons moved to the top by the keyboard do not respond to clicks the first time.

**Affected platforms**
- iOS

**To Reproduce**
The code snippet is [here](https://gist.github.com/alexeiartsimovich/9375671c81e11c5d2a6350854e747d38) - it's a simple chat screen with a text field and a button.
1. Click on the text field - you'll see that the keyboard appears and the layout is not panned smoothly. You'll also see a blank space between the keyboard and the text field.
2. Type something in the text field.
3. Click the Send button.
4. See that the Send button doesn't respond the first time.

**Expected behavior**
1. When the keyboard appears, the layout is panned smoothly.
2. No extra space between the keyboard and the text field.
3. No issues with clicking buttons that are moved up by the keyboard.

**Video with Issue**

https://github.com/JetBrains/compose-multiplatform/assets/99798741/7d28aaaa-e21e-4f0a-8a61-6d2414254c16

**Video with NO Issue**

https://github.com/JetBrains/compose-multiplatform/assets/99798741/f6cb00f0-0a20-4652-ab0d-8bd11f687922

**Additional context**
The issues appeared after migrating from version 1.4.3 to version 1.5.0-beta02

**Comment by elijah-semyonov** [comment] 2023-08-14 08:06
Thanks for reporting the issue, we'll be looking into it.

**Comment by dima-avdeev-jb** [comment] 2023-08-17 06:51
@alexeiartsimovich I can't reproduce bug with extra white space.
Can you please create a minimal reproducible sample on GitHub?

**Comment by dima-avdeev-jb** [comment] 2023-08-17 07:39
@alexeiartsimovich I reproduce it! So, the reason of extra white space is safe area.
You can use `ComposeView().ignoresSafeArea(.all)` in SwiftUI to workaround this problem

**Comment by alexeiartsimovich** [comment] 2023-08-25 06:26
Thanks guys, it works well now!

**Comment by mazunin-v-jb** [comment] 2024-06-07 16:09
Looks like everything here is done, consider closing it. Feel free to reopen if any case.

**Closed by mazunin-v-jb** 2024-06-07 16:09 UTC
Labels: bug, ios, regression, reproduced

**Comment by okushnikov** [comment] 2024-08-26 13:38
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3485">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
