### ISSUE TITLE
LayoutDirection is not applied to Dialog on iOS

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#4504] opened 2024-03-18 05:33 UTC
**Describe the bug**
I have a composable wrapped with a composition local updating the `LayoutDirection` to `RTL` and I have a dialog inside that composable. On Android it works fine, and the dialog is `RTL`, but on iOS the dialog is `LTR`

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): iOS 16.6.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 13 mini

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add a composable with a `LayoutDirection.RTL`
2. Add a dialog inside that composable
3. Open the dialog on a simulator or a device
4. You will notice that the dialog `LayoutDirection` is `LTR`

**Expected behavior**
The dialog `LayoutDirection` should be the same as the parent composable, which is `RTL` in this case.

**Additional context**
It's happening on the simulator as well, iPhone 14 Pro iOS 16.4, so I think it's not related to a particular device.
I'm not sure if this issue is happening for other composition locals, but it shouldn't.

Thanks!

**Comment by MatkovIvan** [comment] 2024-03-25 12:52
It was a problem in 1.6.0-beta(s), but fixed in the release. I suspect that it's because some of your dependencies still resolves Compose to beta version.

I rechecked this and I don't see the problem in the release. Please make sure that your project uses the latest Compose or provide reproducible sample.

Closing for now

**Closed by MatkovIvan** 2024-03-25 12:52 UTC
Labels: bug, ios

**Comment by okushnikov** [comment] 2024-08-26 13:44
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4504">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
