### ISSUE TITLE
Snapping `SnapFlingBehavior` not working on desktop and web, works on Android

### ISSUE THREAD

**Issue by alexstyl** [JetBrains/compose-multiplatform#3602] opened 2023-09-01 09:25 UTC
**Describe the bug**
The below code is expected to produce a snapping effect according to the  [androidx docs](https://developer.android.com/reference/kotlin/androidx/compose/foundation/gestures/snapping/SnapFlingBehavior). It works on Android. On Desktop and Canvas based Web it is as if the behavior is not applied:

```kotlin
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.snapping.rememberSnapFlingBehavior
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.Text

val state = rememberLazyListState()

LazyRow(
    modifier = Modifier.fillMaxSize(),
    verticalAlignment = Alignment.CenterVertically,
    state = state,
    flingBehavior = rememberSnapFlingBehavior(lazyListState = state)
) {
    items(200) {
        Box(
            modifier = Modifier
                .height(400.dp)
                .width(200.dp)
                .padding(8.dp)
                .background(Color.Gray),
            contentAlignment = Alignment.Center
        ) {
            Text(it.toString(), fontSize = 32.sp)
        }
    }
}
```

**Affected platforms**
Select one of the platforms below:
- Desktop
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*:  `1.9.20-dev-8763`
- Compose Multiplatform version*: `1.5.0`
- OS version(s)* (required for Desktop and iOS issues): Mac OS 13.4.1 (c) (22F770820d)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): openjdk 19 2022-09-20

**Comment by m-sasha** [comment] 2023-09-02 08:19
Thanks for the report. This is a duplicate of https://github.com/JetBrains/compose-multiplatform/issues/3454

**Closed by m-sasha** 2023-09-02 08:19 UTC
Labels: bug, duplicate

**Comment by okushnikov** [comment] 2024-08-26 14:38
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3602">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
