### ISSUE TITLE
Run/Debug Configurations Report an Error ：“Please specify Xcode project location” and Execution target Can't find IOS Simulator.

### ISSUE THREAD

**Issue by JingZaia** [JetBrains/compose-multiplatform#3636] opened 2023-09-07 04:19 UTC
my  system is macos 14
after xcode update 15 deta,android studio ios It doesn't work.
Run/Debug Configurations Report an Error ：“Please specify Xcode project location” and Execution target Can't find IOS Simulator.
![image](https://github.com/JetBrains/compose-multiplatform/assets/96556562/4f744879-9a03-495c-b1b3-1790d4760e4c)
In the terminal input kdoctor can detects [✓]xocde

**Comment by igordmn** [comment] 2023-09-12 20:26
Will a clean git clone of https://github.com/JetBrains/compose-multiplatform-template help?

Also, please:
- select the execution target (it should be selected)
- tell which versions of Android Studio, Kotlin Plugin and KMM plugin do you have
- try to File - Invalidate caches
- check if it works with [non-Compose sample](https://github.com/Kotlin/kmm-basic-sample). If it doesn't, please create an issue in https://youtrack.jetbrains.com/issues/KT.

I tried on macos 13 + xcode 15 beta, and I didn't reproduce the issue.

**Comment by igordmn** [comment] 2023-09-20 14:30
Closing, as we are not able to reproduce the issue.

If it still reproduces, please provide steps/projects how to reproduce it. Also, most probably it is a Kotlin Plugin for Android Studio issue - the https://youtrack.jetbrains.com/issues/KT tracker is more suitable for this.

**Closed by igordmn** 2023-09-20 14:30 UTC
Labels: bug, wait for reply, ide

**Comment by okushnikov** [comment] 2024-08-26 13:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3636">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
