### ISSUE TITLE
[mac] Cmd+C/V/X shortcuts for non-English locales

### ISSUE THREAD

**Issue by avently** [JetBrains/compose-multiplatform#3497] opened 2023-08-15 17:26 UTC
Clipboard keyboard shortcuts like `Cmd+X` don't work on macos with Russian locale (when instead of `x` is `ч`, ), for example. However, they work good with English locale. 

**MacOS** Ventura 13.4.1
**JVM: Coretto 20.0.2.9.1** also reproduced on Oracle Open JDK 20
Version: 1.4.3
Version: 1.5.0-rc01

On **Linux** and Coretto 20.0.2 it works fine!

Reproducer: https://github.com/mazunin-v-jb/compose-mp-issue-3497

**Comment by mazunin-v-jb** [comment] 2023-08-15 18:02
Hello! Thanks for the issue.
I've checked the ImageViewer example on desktop (macOS Ventura 13.4) with "Russian - PC" locale, tried cmd + С/V/X in photo description textfield, and it works fine. 
Could you provide minimal reproducer of that behavior where it's not possible to use keyboard shortcuts with Russian locale?

**Comment by avently** [comment] 2023-08-16 09:51
Checked your link, but with Compose 1.4.0 (because 1.4.3 doesn't work on my mac in virtual machine) and Kotlin 1.8.0. Keybindings with Russian - PC don't work too. I will check on real mac with Compose 1.4.3 and will write the result. 
In my case I have macOs Monterey with version 12.6.1

**Comment by avently** [comment] 2023-08-16 15:18
Still doesn't work. Same example but with Compose 1.4.3 on real mac (aarch64), Ventura 13.4.1
Corretto JDK in both cases -17.0.7 (virtual mac) and 20.0.2.9.1 (aarch64)

```bash
git clone https://github.com/JetBrains/compose-multiplatform -b master --depth 1 compose
cd compose/examples/imageviewer
./gradlew run
```

**Comment by mazunin-v-jb** [comment] 2023-08-16 18:48
Thank you for providing information, I or someone else from our team will return soon with further information and/or questions.

**Comment by mazunin-v-jb** [comment] 2023-08-17 13:35
Thanks for waiting. For now it looks like that is a rare bug because keyboard shortcuts should work fine at any locale.
Could you please try to run [my reproducer](https://github.com/mazunin-v-jb/compose-mp-issue-3497) and let me know how it works?

In addition, could you please try to run this reproducer on **another** mac, if it's possible? We will require that info for understanding the problem.

**Comment by avently** [comment] 2023-08-17 16:04
- VM mac corretto -> doesn't work
- VM mac openjdk@17 from Homebrew -> works
- m1 mac corretto -> doesn't work
- intel mac openjdk@11 from Homebrew -> works.

So, looks like the problem is with JDK distribution. But OpenJDK is problematic in other aspect at least via brew (while packaging it links to different libs which fails to run on user's computer because of linking issues, see https://github.com/JetBrains/compose-multiplatform/issues/3107) while Corretto works good in this aspect. 

You probably can't do anything with this issue, right? If you can't, what distribution you can recommend that expected to be the most mature (without problems I mentioned at least)?

**Comment by dima-avdeev-jb** [comment] 2023-08-18 11:38
<img width="1029" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/2d40f848-069a-4329-9acd-1f4507f99e56">

Thanks, checked on Correto 20.0.2....  it reproduced

**Comment by mazunin-v-jb** [comment] 2023-08-18 11:40
@avently, for now I recommend you to switch to the Coretto 17 (or another distributor, but 17), It should work fine.

**Comment by dima-avdeev-jb** [comment] 2023-08-18 12:40
Checked on Linux and Coretto 20.0.2 - works fine!

**Comment by dima-avdeev-jb** [comment] 2023-08-22 13:23
Checked also on Oracle Open JDK - same Issue

**Comment by igordmn** [comment] 2023-08-22 13:37
Windows - also works fine

**Comment by igordmn** [comment] 2023-08-22 13:59
```
import java.awt.Dimension
import java.awt.event.KeyEvent
import java.awt.event.KeyListener
import javax.swing.JFrame
import javax.swing.SwingUtilities

fun main()  {
    SwingUtilities.invokeLater {
        val frame = JFrame()
        frame.addKeyListener(object : KeyListener {
            override fun keyTyped(p0: KeyEvent?) {

            }

            override fun keyPressed(p0: KeyEvent) {
                println(" " + p0.modifiersEx + " " + p0.keyCode + " " + p0.keyLocation)
            }

            override fun keyReleased(p0: KeyEvent?) {
            }
        })
        frame.size = Dimension(200, 200)
        frame.isVisible = true
    }
}
```
JDK 20 russian, keyCode = 16778305
JDK 17 russian, JDK 17/20 english, keyCode = 67

**Comment by okushnikov** [comment] 2024-08-26 14:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3497">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:16 UTC
Labels: bug, macos, desktop, p:high, reproduced
