### ISSUE TITLE
Video is not showing on desktop when use "interop" between compose

### ISSUE THREAD

**Issue by paulocoutinhox** [JetBrains/compose-multiplatform#4389] opened 2024-02-29 02:40 UTC
**Describe the bug**

Video is not showing on desktop when use "interop" between compose.

![image](https://github.com/JetBrains/compose-multiplatform/assets/395096/06d2351a-07b5-4e93-b6b8-0bd4fb2ff234)

It works on macOS only if i use `System.setProperty("compose.interop.blending", "true")`.

<img width="800" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/395096/459d194b-b70b-4b96-9684-1eafc7a54a47">

On Windows, if i remove `System.setProperty("compose.interop.blending", "true")` the video appear, but the compose text element not:

![image (1)](https://github.com/JetBrains/compose-multiplatform/assets/395096/16c952f9-1cf1-47b3-bccc-5b686be7cc59)

**Affected platforms**
Select one of the platforms below:
- Desktop

**To Reproduce**

```
git clone https://github.com/paulocoutinhox/jdataxow.git
cd jdataxow
./gradlew run
```

**Expected behavior**

It needs show the text element in front of the video.

**Comment by MatkovIvan** [comment] 2024-02-29 07:37
It's a known limitation and out of Compose control. With `compose.interop.blending` flag we have to rely on the system's blending behaviour of two native views. In the case of Windows - it does NOT alpha blend two views that rendered directly on GPU/DirectX, the top one just replaces the previous. You may reproduce it even with two copies of Compose itself.

This is one of the reasons why it's under the flag now.

There is a workaround for this - you need to render your component (video) off-screen (to texture first) and draw it via Swing graphics. It has some performance drop, but allows achieving the expected result.
It's a general mechanism, I don't know how/if you can achieve this via that video player library.

Documented it here:
https://github.com/JetBrains/compose-multiplatform-core/blob/d562a39a6d89da6aabbd4cef7e7a4c6a1b558625/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/ComposeFeatureFlags.desktop.kt#L67-L71

I'll make sure that this will be added to more visible place. Closing as a known limitation

**Closed by MatkovIvan** 2024-02-29 07:37 UTC
Labels: bug, submitted

**Comment by paulocoutinhox** [comment] 2024-03-01 01:31
Hi,

I made it work here:
https://github.com/caprica/vlcj/issues/1218

Full code (custom adapter):

```
package com.dataxow

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.material.TextField
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPosition
import androidx.compose.ui.window.WindowState
import androidx.compose.ui.window.application
import org.jetbrains.skia.Bitmap
import org.jetbrains.skia.ColorAlphaType
import org.jetbrains.skia.ImageInfo
import uk.co.caprica.vlcj.factory.MediaPlayerFactory
import uk.co.caprica.vlcj.player.base.MediaPlayer
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer
import uk.co.caprica.vlcj.player.embedded.videosurface.CallbackVideoSurface
import uk.co.caprica.vlcj.player.embedded.videosurface.VideoSurfaceAdapters
import uk.co.caprica.vlcj.player.embedded.videosurface.callback.BufferFormat
import uk.co.caprica.vlcj.player.embedded.videosurface.callback.BufferFormatCallback
import uk.co.caprica.vlcj.player.embedded.videosurface.callback.RenderCallback
import uk.co.caprica.vlcj.player.embedded.videosurface.callback.format.RV32BufferFormat
import java.awt.FileDialog
import java.awt.Frame
import java.io.File
import java.nio.ByteBuffer
import org.jetbrains.skia.Image as SkiaImage

val adapter = RenderCallbackAdapter()
val videoSurface = CallbackVideoSurface(adapter, adapter, true, VideoSurfaceAdapters.getVideoSurfaceAdapter())
val mediaPlayerFactory = MediaPlayerFactory()
val mediaPlayer: EmbeddedMediaPlayer = mediaPlayerFactory.mediaPlayers().newEmbeddedMediaPlayer()

fun main() = application {
    var text by remember { mutableStateOf("Your text here") }
    var imagePath by remember { mutableStateOf<String?>(null) }
    var videoPath by remember { mutableStateOf<String?>(null) }
    var secondWindowOpen by remember { mutableStateOf(false) }

    mediaPlayer.controls().repeat = true

    // Main window
    Window(onCloseRequest = ::exitApplication, title = "Control Window") {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                TextField(
                    value = text,
                    onValueChange = { text = it },
                    label = { Text("Text to display") }
                )
                Button(onClick = { secondWindowOpen = true }) {
                    Text("Update Text")
                }
            }
            Button(onClick = {
                val file = selectFile("Select Image", "image/*")
                imagePath = file?.absolutePath
                videoPath = null // Reset video path to stop video if playing
                secondWindowOpen = true
            }) {
                Text("Select Image")
            }
            Button(onClick = {
                val file = selectFile("Select Video", "video/*")
                videoPath = file?.absolutePath
                imagePath = null // Reset image path to remove image if displayed
                secondWindowOpen = true
            }) {
                Text("Select Video")
            }
        }
    }

    // Second window logic
    if (secondWindowOpen) {
        Window(
            onCloseRequest = { secondWindowOpen = false },
            title = "Display Window",
            state = WindowState(width = 800.dp, height = 600.dp, position = WindowPosition.Aligned(Alignment.Center))
        ) {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                imagePath?.let {
                    Image(
                        bitmap = SkiaImage.makeFromEncoded(File(it).readBytes()).toComposeImageBitmap(),
                        contentDescription = null,
                        modifier = Modifier.fillMaxSize(),
                        contentScale = ContentScale.Crop
                    )
                }
                if (videoPath != null) {
                    mediaPlayer.videoSurface().set(videoSurface)
                    mediaPlayer.media().play(videoPath)

                    videoPlayerImpl(
                        adapter,
                        Modifier.fillMaxSize()
                            .aspectRatio(16f / 9f, matchHeightConstraintsFirst = true)
                            .align(Alignment.Center)
                    )
                }
                Text(
                    text = text,
                    style = TextStyle(
                        color = Color.White,
                        fontSize = 60.sp,
                        fontWeight = FontWeight.Bold,
                        background = Color.Transparent,
                        textAlign = TextAlign.Center,
                    ),
                    modifier = Modifier.align(Alignment.Center)
                )
                Text(
                    text = text,
                    style = TextStyle(
                        color = Color.Black,
                        fontSize = 60.sp,
                        fontWeight = FontWeight.Bold,
                        background = Color.Transparent,
                        textAlign = TextAlign.Center,
                        drawStyle = Stroke(
                            miter = 10f,
                            width = 5f,
                            join = StrokeJoin.Round,

                            )
                    ),
                    modifier = Modifier.align(Alignment.Center)
                )
            }
        }
    }
}

@Composable
fun videoPlayerImpl(
    adapter: RenderCallbackAdapter,
    modifier: Modifier,
) {
    Box(modifier = modifier) {
        videoFrame(adapter.imageBitmap)
    }
}

@Composable
fun videoFrame(imageBitmap: ImageBitmap?) {
    imageBitmap?.let {
        Image(
            bitmap = it,
            contentDescription = "Video Frame",
            modifier = Modifier.fillMaxSize()
        )
    }
}


class RenderCallbackAdapter : BufferFormatCallback, RenderCallback {
    var imageBitmap by mutableStateOf<ImageBitmap?>(null)
        private set

    override fun getBufferFormat(sourceWidth: Int, sourceHeight: Int): BufferFormat {
        return RV32BufferFormat(sourceWidth, sourceHeight)
    }

    override fun allocatedBuffers(buffers: Array<out ByteBuffer>) {
        // this is managed by vlcj
    }

    override fun display(mediaPlayer: MediaPlayer?, nativeBuffers: Array<ByteBuffer>, bufferFormat: BufferFormat) {
        val fixedImage = false

        if (fixedImage) {
            val testImage = File("/Users/paulo/Downloads/pexels.webp")
            val bitmap = SkiaImage.makeFromEncoded(testImage.readBytes())
            imageBitmap = bitmap.toComposeImageBitmap()
        } else {
            val buffer = nativeBuffers[0]
            buffer.rewind()

            val size = bufferFormat.width * bufferFormat.height * 4

            if (buffer.isDirect) {
                val byteArray = ByteArray(size)
                buffer.get(byteArray)
                updateImageBitmap(byteArray, bufferFormat.width, bufferFormat.height)
            } else {
                updateImageBitmap(buffer.array(), bufferFormat.width, bufferFormat.height)
            }
        }
    }

    private fun updateImageBitmap(pixelData: ByteArray, width: Int, height: Int) {
        val bitmap = Bitmap().apply {
            allocPixels(ImageInfo.makeS32(width, height, ColorAlphaType.PREMUL))
            installPixels(imageInfo, pixelData, (width * 4))
        }

        imageBitmap = bitmap.asComposeImageBitmap()
    }
}

fun selectFile(title: String, fileType: String): File? {
    val fileDialog = FileDialog(Frame(), title, FileDialog.LOAD)
    fileDialog.isVisible = true
    return fileDialog.files.firstOrNull()
}
```

If need a test project:

https://github.com/paulocoutinhox/jdataxow

Thanks.

**Comment by okushnikov** [comment] 2024-07-14 15:07
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4389">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by jonolds** [comment] 2024-11-19 08:23
@paulocoutinhox This totally works for my use case. Thank you so much!
