### ISSUE TITLE
Merge material3 1.2

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#4124] opened 2024-01-15 07:08 UTC
![image](https://github.com/JetBrains/compose-multiplatform/assets/14316223/90cbe32f-50af-4966-92d6-0666b0e455e6)

As you can see in this image. A lot of code should be shipped in Compose Multiplatform 1.6.0, but it is still missing.

On the left is the original Androidx repository with version 1.2.0-beta02 of Material 3 checked out.

https://developer.android.com/jetpack/androidx/releases/compose-material3#1.2.0-beta02
https://android.googlesource.com/platform/frameworks/support/+/7a45f0bc9e0a73744b3780a6f92e1b570de58bba

**Comment by MatkovIvan** [comment] 2024-01-15 10:15
Don't worry, we're aware of this diff and working on it.

1.6 merge - https://github.com/JetBrains/compose-multiplatform-core/pull/980
material 1.2 in our queue as well.

Duplicate of #4052

**Comment by MatkovIvan** [comment] 2024-01-15 10:16
Hm, that issue doesn't formally mention material3 1.2, so let's keep it open then

**Comment by MatkovIvan** [comment] 2024-01-25 08:17
> Is there a plan to make it to 1.6 release?

yes

**Comment by Omico** [comment] 2024-01-30 08:20
I created a new issue to describe my thoughts on the version management of the Compose Multiplatform. https://github.com/JetBrains/compose-multiplatform/issues/4201

**Comment by MatkovIvan** [comment] 2024-02-03 19:30
Merged in https://github.com/JetBrains/compose-multiplatform-core/pull/1044

**Closed by MatkovIvan** 2024-02-03 19:30 UTC
Labels: enhancement, material3

**Comment by okushnikov** [comment] 2024-07-14 15:58
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4124">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
