### ISSUE TITLE
compose multiplatform does not support kotlin version 1.8.21 

### ISSUE THREAD

**Issue by anuj72** [JetBrains/compose-multiplatform#3277] opened 2023-06-19 16:19 UTC
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- All
- Desktop

compose multiplatform does not support kotlin version 1.8.21

**Comment by MatkovIvan** [comment] 2023-06-20 09:24
Duplicate of #3214

**Closed by MatkovIvan** 2023-06-20 09:24 UTC
Labels: duplicate

**Comment by okushnikov** [comment] 2024-07-14 16:16
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3277">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
