### ISSUE TITLE
Cannot find declaration of: remember { ... } 

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-multiplatform#142] opened 2020-11-25 14:27 UTC
![obraz](https://user-images.githubusercontent.com/34739613/100240166-87507780-2f32-11eb-9160-b99625c9e66e.png)

Workaround: 
add to imports
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue

**Comment by igordmn** [comment] 2020-11-26 08:20
Did you try to sync the project with Gradle?

![image](https://user-images.githubusercontent.com/5963351/100324992-04cec300-2fd9-11eb-8a41-971c1ee1a933.png)

Also can you provide archive with the project and tell what version of IDEA/Kotlin plugin are you using?

**Comment by atoktoto** [comment] 2020-11-26 09:13
I've tried to:
- sync as instructed
- upgraded to latest compose (0.1.0-build119)
- invalidate & restart

The project:
https://github.com/atoktoto/compose-experiment

Intellj version:
```
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Subscription is active until December 7, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: documentation.show.toolbar=true
Non-Bundled Plugins: org.antlr.intellij.plugin, org.jetbrains.plugins.hocon, org.jetbrains.plugins.vue, io.ktor.intellij.plugin, com.intellij.lang.jsgraphql
```

**Comment by igordmn** [comment] 2020-11-26 09:26
Thanks! Reproduced the issue

**Comment by Dominaezzz** [comment] 2020-11-26 09:33
The same thing happens in Android studio and iirc it's intentional since it's an intrinsic.

**Comment by atoktoto** [comment] 2020-11-26 09:46
The thing is, it makes it hard to understand what is going on without prior experience in Android dev. I finally found the documentation:
https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary#remember
https://developer.android.com/jetpack/compose/state

It also has a kotlin implementation in source code:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:compose/runtime/runtime/src/commonMain/kotlin/androidx/compose/runtime/Remember.kt?q=remember&ss=androidx%2Fplatform%2Fframeworks%2Fsupport:compose%2Fruntime%2Fruntime%2F

**Comment by Vadim-Kapustin** [comment] 2020-11-27 08:51
I have the same error. Some more information:

![remember-bug](https://user-images.githubusercontent.com/75115677/100428254-bedf3100-30a4-11eb-8617-b24020bccc65.png)

and

![remember-bug2](https://user-images.githubusercontent.com/75115677/100429057-db2f9d80-30a5-11eb-90ba-1ee99db3e285.png)

Treated with replacement
`import androidx.compose.runtime.remember`
to
`import androidx.compose.runtime.*`

IDEA version:

```
IntelliJ IDEA 2020.3 RC (Community Edition)
Build #IC-203.5981.114, built on November 26, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.18-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 977M
Cores: 2
Non-Bundled Plugins: com.atlassian.bitbucket.references, no.tornado.tornadofx.idea
Current Desktop: KDE
```
(and earlier versions)

Compose v. 0.2.0-build131 and earlier

Construction val a = remember { .... } works fine...

**Comment by igordmn** [comment] 2020-11-27 09:35
Error "has no method" happened because there are no these imports in the file:
```
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
```
getValue/setValue are [kotlin delegates](https://kotlinlang.org/docs/reference/delegated-properties.html) needed for "var test by" expression.

IDEA doesn't offer to import them if we wrap `mutableStateOf` in `remember`, so will have to write them manually.

**Comment by jimgoog** [comment] 2020-12-12 16:53
https://youtrack.jetbrains.com/issue/KT-39199

**Comment by akurasov** [comment] 2021-12-10 13:52
New Kotlin ticket - https://youtrack.jetbrains.com/issue/KTIJ-20402

**Comment by okushnikov** [comment] 2024-07-14 17:27
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5591">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:57 UTC
Labels: bug, ide, kotlin
