### ISSUE TITLE
Navigation for compose multiplatform

### ISSUE THREAD

**Issue by dhng22** [JetBrains/compose-multiplatform#3638] opened 2023-09-07 09:45 UTC
Jetpack compose navigation is a really powerful library, which has NavHost, NavController, etc.. Is there any plan for these to become available? Since there's currently no way to navigate in compose multiplatform but with external library

**Comment by MatkovIvan** [comment] 2023-09-07 10:42
Thank you for your feature request. This isn't a part of Compose itself, but we understand its significance in the ecosystem. 

Currently, we are working closely with Google to investigate this matter and determine its feasibility. The task complexity is amplified by the substantial dependency on Android-specific references. 

At this moment, we cannot promise anything or provide any ETA. For organization, I’m closing this as a duplicate of #85. Please follow that thread for future updates.

**Closed by MatkovIvan** 2023-09-07 10:42 UTC
Labels: enhancement, submitted

**Comment by okushnikov** [comment] 2024-08-26 14:38
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3638">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
