### ISSUE TITLE
Cannot add task 'checkNotarizationStatus' as a task with that name already exists

### ISSUE THREAD

**Issue by russellbanks** [JetBrains/compose-multiplatform#2233] opened 2022-08-06 15:44 UTC
Running `./gradlew packagePkg` on macOS results in a `DuplicateTaskException: Cannot add task 'checkNotarizationStatus' as a task with that name already exists.`. I ran this on GitHub actions using `macos-latest`.

I can provide the full stacktrace if necessary.

**Comment by AlexeyTsvetkov** [comment] 2022-10-23 02:51
@russellbanks do you define a task with such name yourself? if not, what tasks do you use in a subproject, where the issue happens?

**Comment by MoreOwO** [comment] 2023-05-19 16:43
Having this issue on Compose Multiplatform 1.3.1 with Kotlin 1.8.10. Any workaround ?

**Comment by AlexeyTsvetkov** [comment] 2023-05-19 22:33
@MoreOwO what Gradle plugins are you using? What exactly is the error message in your case?

**Comment by MoreOwO** [comment] 2023-05-20 09:44
I have Kotlin Multiplatform 1.8.20 with compose 1.4.0. The error is `> Cannot add task 'checkNotarizationStatus' as a task with that name already exists.` when I try to reload Gradle project in IntelliJ

**Comment by AlexeyTsvetkov** [comment] 2023-05-21 11:50
@MoreOwO are there other plugins are you using?

**Comment by MoreOwO** [comment] 2023-05-22 16:06
No, no other plugins

Le dim. 21 mai 2023 à 13:50, Alexey Tsvetkov ***@***.***> a
écrit :

**Comment by russellbanks** [comment] 2023-05-22 16:31
@AlexeyTsvetkov This is my project that it occurs in: [russellbanks/HashHash](https://github.com/russellbanks/HashHash)

**Comment by liokso** [comment] 2023-09-12 01:48
Try to remove TargetFormat.Dmg. It works for me.

**Comment by dzirbel** [comment] 2023-10-11 21:11
I also ran into this when adding both `TargetFormat.Dmg` and `TargetFormat.Pkg`, but not with only one of the two. https://github.com/dzirbel/compose-playground/tree/macFormat provides a minimal reproducer (it seems to happen to any project that simply targets both formats, even when building with `packageReleaseDistributionForCurrentOS` on non-macOS).

**Comment by okushnikov** [comment] 2024-07-14 16:11
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2233">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:10 UTC
Labels: native distribution
