### ISSUE TITLE
Layout flickers when resizing the window (regression)

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#4744] opened 2024-05-01 08:47 UTC
**Describe the bug**
When changing window width on desktop, the content of the window repeatedly shrinks or expands while the resizing is in progress.

This problem did not exist in compose multiplatform 1.5.10.

**Affected platforms**
- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 21

**To Reproduce**
Run the below app and resize the window with mouse.
```kotlin
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        Box(Modifier.width(400.dp).height(50.dp).background(Color.Red))
    }
}
```

**Additional context**
This also happens even when window is not resizable. when programmatically changing window size, the content breaks for a moment:

https://github.com/JetBrains/compose-multiplatform/assets/29678011/e7f90b27-bcf6-4996-a5dc-e3ff33f7913b

**Comment by elijah-semyonov** [comment] 2024-05-10 08:06
Can't reproduce it on macOS.
@mahozad was `macOS` wrongly added to the affected platforms list, or you indeed have this behavior on `macOS` machine?

**Comment by elijah-semyonov** [comment] 2024-05-10 08:08
@MatkovIvan I don't think I touched `windows` related rendering since 1.5.10. Can you bisect the regression point on a Windows machine?

**Comment by babramovitch** [comment] 2024-05-10 08:51
I'm also having problems with window resizing on windows.  I'm not sure if this is the same problem, but it might be?  If it's different I can make another issue.

The hardcoded 200 width moves around as I resize the window, on windows.  On a Mac, the 200 width remains in place as the rest of the window expands and shrinks.

This is on 1.6.2

```
Window(
    onCloseRequest = ::exitApplication,
    state = WindowState(width = 800.dp, height = 1000.dp),
) {
    Box(modifier = Modifier.fillMaxSize().background(Color.Red)) {
        Box(modifier = Modifier.width(200.dp).fillMaxHeight().background(Color.Blue))
    }
}

```
Please forgive this horrible video quality...

https://github.com/JetBrains/compose-multiplatform/assets/3608443/039e8b22-28ff-4fe9-a5d0-03d49f4bba7c

**Comment by mahozad** [comment] 2024-05-10 17:17
I should say that CMP 1.6.0 also did not have this problem.

**Comment by mahozad** [comment] 2024-05-10 17:25
> Can't reproduce it on macOS...

@elijah-semyonov

Sorry. I only tested Windows. The macOS and Linux were remnants of issue template.

**Comment by MatkovIvan** [comment] 2024-05-14 14:24
Explanation here - https://github.com/JetBrains/compose-multiplatform/issues/4521#issuecomment-2014834922

Closing as duplicate of #4521

**Closed by MatkovIvan** 2024-05-14 14:24 UTC
Labels: bug, rendering, windows, skiko, directx, desktop, regression, reproduced

**Comment by okushnikov** [comment] 2024-08-26 13:40
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4744">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
