### ISSUE TITLE
Compillation fails on Desktop/JVM when building with Proguard and JDK21

### ISSUE THREAD

**Issue by mikedawson** [JetBrains/compose-multiplatform#4216] opened 2024-02-01 08:43 UTC
**Describe the bug**
Compillation fails on Desktop/JVM when building with Proguard and JDK21. As per the [version requirements docs](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html?utm_campaign=kmp&utm_medium=docs&utm_source=github#limitations-of-compose-multiplatform-releases) "Only JDK 17 or later is supported for packaging native distributions". 

The compose/desktop plugin is using Proguard 7.2.2 ( adding classpath "com.guardsquare:proguard-gradle:7.4.2" to the buildscript on Gradle does not change this).  As per [Proguard's release notes](https://www.guardsquare.com/manual/releasenotes), JDK21 support was added in Proguard 7.4

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.21 
- Compose Multiplatform version*:  1.5.11 
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 23.10 
- OS architecture (x86 or arm64): x86 (64bit)
- JDK (for desktop issues): OpenJDK21  (java -version output: openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-Ubuntu-223.10)
OpenJDK 64-Bit Server VM (build 21.0.1+12-Ubuntu-223.10, mixed mode, sharing))

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a new compose desktop application (e.g. using wizard)
2. Set JAVA_HOME / JDK to JDK 21
3. Attempt to build release jars e.g. module-name:proguardReleaseJArs

**Expected behavior**
Should build jars, and proguard should shrink / obfuscate as per settings

**Screenshots**
```
java.io.IOException: Can't read [/usr/lib/jvm/java-21-openjdk-amd64/jmods/jdk.jdi.jmod(;;;;;;;!**.jar;!module-info.class)] (Can't process class [com/sun/jdi/AbsentInformationException.class] (Unsupported version number [65.0] (maximum 62.65535, Java 18)))
```

**Comment by MatkovIvan** [comment] 2024-02-01 09:29
Duplicate of #3818

**Closed** 2024-02-01 09:29 UTC
Labels: bug, duplicate, desktop

**Comment by mikedawson** [comment] 2024-02-01 09:31
Yes, this is a duplicate. Not sure how I missed it looking through issues whilst trying to resolve.

**Comment by MatkovIvan** [comment] 2024-02-01 09:32
@mikedawson there is [a posted solution](https://github.com/JetBrains/compose-multiplatform/issues/3818#issuecomment-1795163561) there:
```
compose.desktop {
  buildTypes.release.proguard {
    version.set("7.4.0")
  }
}
```

**Comment by okushnikov** [comment] 2024-08-26 13:48
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4216">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
