### ISSUE TITLE
Navigate From Screen A to Screen B and dismiss back to Screen A when click back button

### ISSUE THREAD

**Issue by hafiz013** [JetBrains/compose-multiplatform#4181] opened 2024-01-26 08:44 UTC
Hi, I would like to have this feature by default in which it support navigation screen in compose multi platform which consist of ios, android and wasmJs as fast as possible. Thank you.

**Comment by elijah-semyonov** [comment] 2024-01-26 09:44
Duplicate of https://github.com/JetBrains/compose-multiplatform/issues/85

**Closed by elijah-semyonov** 2024-01-26 09:44 UTC
Labels: duplicate, enhancement

**Comment by okushnikov** [comment] 2024-08-26 13:49
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4181">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
