### ISSUE TITLE
OnClick.skiko will make Android target failed to build

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#4468] opened 2024-03-11 13:10 UTC
Compose Multiplatform version 1.6.0

I accidentally used `androidx.compose.foundation.onClick` in my project. It works properly if I run Android or Desktop target separately.

But this will failed to build if I run `gradle build`. Then I noticed that https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/foundation/foundation/src/skikoMain/kotlin/androidx/compose/foundation/OnClick.skiko.kt may not be used in Android target.

```
e: file:///home/runner/_work/xxx/xxx/xxx/core/feature/notes/src/commonMain/kotlin/me/omico/xxx/feature/notes/NotesUi.kt:16:36 Unresolved reference: onClick
e: file:///home/runner/_work/xxx/xxx/xxx/core/feature/notes/src/commonMain/kotlin/me/omico/xxx/feature/notes/NotesUi.kt:124:20 Type mismatch: inferred type is Unit but Modifier was expected
e: file:///home/runner/_work/xxx/xxx/xxx/core/feature/notes/src/commonMain/kotlin/me/omico/xxx/feature/notes/NotesUi.kt:127:18 Unresolved reference: onClick
e: file:///home/runner/_work/xxx/xxx/xxx/core/feature/notes/src/commonMain/kotlin/me/omico/xxx/feature/notes/NotesUi.kt:16:36 Unresolved reference: onClick
e: file:///home/runner/_work/xxx/xxx/xxx/core/feature/notes/src/commonMain/kotlin/me/omico/xxx/feature/notes/NotesUi.kt:124:20 Type mismatch: inferred type is Unit but Modifier was expected
e: file:///home/runner/_work/xxx/xxx/xxx/core/feature/notes/src/commonMain/kotlin/me/omico/xxx/feature/notes/NotesUi.kt:127:18 Unresolved reference: onClick
> Task :xxx-core-feature-notes:compileDebugKotlinAndroid FAILED
> Task :xxx-core-feature-notes:compileReleaseKotlinAndroid FAILED
```

```
// This will cause the above error
@OptIn(ExperimentalFoundationApi::class)
@Composable
fun Card() {
    Card(
        modifier = Modifier.onClick { },
        content = { }
    )
}

// This is the correct way btw.
@Composable
fun Card2() {
    Card(
        onClick = { },
        content = { }
    )
}
```

**Comment by eymar** [comment] 2024-03-11 13:49
Right, `.onClick` is not available for Android target.
Unfortunately, IDE shows it in autocompletion in common code (destkop+android). We're investigating this probelm.

**Comment by MatkovIvan** [comment] 2024-03-11 22:45
Duplicate of #3503

**Closed by MatkovIvan** 2024-03-11 22:45 UTC
Labels: bug, external bug

**Comment by okushnikov** [comment] 2024-08-26 13:46
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4468">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
