### ISSUE TITLE
Ime actions don't work on Ios after showing dialog/bottom sheet

### ISSUE THREAD

**Issue by vlad1710** [JetBrains/compose-multiplatform#4291] opened 2024-02-13 13:25 UTC
**Describe the bug**
Ime actions don't work on Ios after showing dialog/bottom sheet

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: tested on 1.6.0-beta02 and 1.6.0-dev1419
- OS version(s)* (required for Desktop and iOS issues): ios 17.2

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. set an ime action to keyboard options (for example "Done") in text field
2. tap on text field and press "Done" - it works
3. open and dismiss dialog or modal bottom sheet
4. tap on text field and press "Done" - it doesn't work anymore

**Expected behavior**
ime action works after showing dialog/bottom sheet

**Comment by dima-avdeev-jb** [comment] 2024-02-13 15:06
Hello! Thanks for this Issue.
Can you please provide a minimal reproducible sample on GitHub?

**Comment by vlad1710** [comment] 2024-02-14 08:50
https://github.com/vlad1710/IssueReport

**Comment by dima-avdeev-jb** [comment] 2024-02-15 10:18
I tried to reproduce in my repo, but it works as expected:
https://github.com/dima-avdeev-jb/issue-4291-reproducer/tree/master

@vlad1710 Can you please check my sample as well?

**Comment by dima-avdeev-jb** [comment] 2024-02-15 11:07
Thanks! We reproduced the problem. The problem is with keyboard disappearing, correct?

**Comment by vlad1710** [comment] 2024-02-16 09:46
Yes, keyboard doesn't disappear. 
But also i'm not sure if ime actions work how they should. I can't handle modifier's onKeyEvent lambda, there are no events inside it. This bug could be on my side, but it definitely worked in my another app. Please check it if you can. Thanks.

**Comment by dima-avdeev-jb** [comment] 2024-02-17 14:09
@vlad1710 about onKeyEvent lambda:
Can you please provide another one reproducible sample with this behavior ?

**Comment by vlad1710** [comment] 2024-02-18 09:05
I've updated the sample.

**Comment by dima-avdeev-jb** [comment] 2024-02-19 10:39
@vlad1710  - thanks, I reproduced this issue with `onKeyEvent`. Also it was reproduced on previous versions.
Created a separate bug about this behavior: https://github.com/JetBrains/compose-multiplatform/issues/4331

**Comment by dima-avdeev-jb** [comment] 2024-02-19 13:24
Should be fixed in 1.6.0-rc03

**Closed by dima-avdeev-jb** 2024-02-19 13:24 UTC
Labels: bug, ios

**Comment by okushnikov** [comment] 2024-07-14 15:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4291">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
