### ISSUE TITLE
CfW: The aspect ratio of CanvasBasedWindow is incorrect on certain devices and browsers.

### ISSUE THREAD

**Issue by matsudamper** [JetBrains/compose-multiplatform#3754] opened 2023-09-30 17:57 UTC
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*:  1.9.20-Beta2
- Compose Multiplatform version*:  1.5.10-beta02
- OS version(s)* (required for Desktop and iOS issues):   -
- OS architecture (x86 or arm64):  -
- JDK (for desktop issues):  -

**To Reproduce**
The aspect ratio is wrong when viewed on certain devices and browsers. Please see screenshots.

**Expected behavior**
The aspect ratio is displayed correctly

**Screenshots**
Galazy Z Fold 3(Closed mode)
<table>
<tr>
<td>Chrome</td>
<td>Opera</td>
<td>FireFox</td>
<td>Edge</td>
</tr>
<tr>
<td><img width="300" src="https://github.com/JetBrains/compose-multiplatform/assets/9250063/3e70740f-0b62-4c1b-bf42-3268425260b2" /></td>
<td><img width="300" src="https://github.com/JetBrains/compose-multiplatform/assets/9250063/e892f4df-a3e4-409c-a15b-88167bdba9c4" /></td>
<td><img width="300" src="https://github.com/JetBrains/compose-multiplatform/assets/9250063/d08fb1cf-764e-4903-8cd4-b26fb2e80f37" /></td>
<td><img width="300" src="https://github.com/JetBrains/compose-multiplatform/assets/9250063/6553d6d0-3cbb-4111-a91f-9beb85e9daa9" /></td>
</tr>
</table>

Desktop
<img width="500" src="https://github.com/JetBrains/compose-multiplatform/assets/9250063/240d5ec7-5286-4418-aee1-1351740694ad" />

**Additional context**
<details>
<summary>Compose Code</summary>

```
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.CanvasBasedWindow
import org.jetbrains.skiko.wasm.onWasmReady

@OptIn(ExperimentalComposeUiApi::class)
fun main(@Suppress("UNUSED_PARAMETER") args: Array<String>) {
    onWasmReady {
        CanvasBasedWindow(
            title = "",
        ) {
            Text("Hello, world!")
            Box(
                modifier = Modifier.fillMaxSize(),
                contentAlignment = Alignment.Center,
            ) {
                Box(
                    modifier = Modifier
                        .background(Color.Red)
                        .padding(24.dp)
                        .size(100.dp),
                ) {
                    Text("Hello, world!")
                }
            }
        }
    }
}
```

</details>

**Comment by eymar** [comment] 2023-10-02 08:15
@matsudamper Thank you for trying it in many browsers. As I see from the screenshots the issue is only in Chrome mobile.
We'll plan the fix for this.

**Comment by okushnikov** [comment] 2024-07-14 16:11
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3754">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:12 UTC
Labels: bug, web, reproduced
