### ISSUE TITLE
LazyColumn displays repeated images out of their order

### ISSUE THREAD

**Issue by mal7othify** [JetBrains/compose-multiplatform#3189] opened 2023-05-18 19:43 UTC
**Describe the bug**
When using LazyColumn to display images, they will be displayed but on scrolling they change to display repeated images and out of their original order in the list.
Full code in this [repository](https://github.com/mal7othify/art-gallery-all)

**Affected platforms**
Select one of the platforms below:
- Desktop
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4, MacOS Ventura 13.3.1
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17.0.6

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to this [repository](https://github.com/mal7othify/art-gallery-all)
2. Click run the code for iOS and desktop
3. Scroll down quickly to the bottom, then, back to top
4. You will see images out of their order and duplicated.
5. Match this abnormal behavior with the normal behavior on the Android app.

**Expected behavior**
I expect the images to be stable and displayed once based on their correct order defined in the list.

**Comment by AlexeyTsvetkov** [comment] 2023-05-23 03:54
Reproduced. 

A simplified example for desktop with just solid colors can be found [here](https://github.com/AlexeyTsvetkov/lazy-column-image).
When I scroll the example, `violet.jpeg` and `black.jpeg` show red and orange colors correspondingly. 

<img width="912" alt="Screenshot 2023-05-23 at 05 47 31" src="https://github.com/JetBrains/compose-multiplatform/assets/654232/2b81f661-0ad4-489a-bd56-2fd613a0140e">

If I resize the window, the correct colors are shown. 

<img width="957" alt="Screenshot 2023-05-23 at 05 47 40" src="https://github.com/JetBrains/compose-multiplatform/assets/654232/b036e9f6-0804-43d2-b670-06d4aa001b3b">

But now if I scroll up, `red.jpeg` and `orange.jpeg` are shown as violet and orange colors.

<img width="957" alt="Screenshot 2023-05-23 at 05 51 30" src="https://github.com/JetBrains/compose-multiplatform/assets/654232/afed5c0d-91dd-49ad-9683-f5ad83cef4bd">

**Comment by m-sasha** [comment] 2023-05-23 07:59
Note that you can, for now, work around this issue by wrapping your `ImageView` call with `key`, e.g.:
```
        items(Items) { item ->
            key(item){
                ImageView(item)
            }
        }
```

**Comment by m-sasha** [comment] 2023-05-23 19:01
This is a bug we inherited from upstream and it's already been fixed, but we haven't merged the fix yet. It should come in the next Compose release.

The problem is in `LayoutNode.onReuse()`:
```
    override fun onReuse() {
        interopViewFactoryHolder?.onReuse()
        if (deactivated) {
            deactivated = false
            // we don't need to reset state as it was done when deactivated
        } else {
            resetModifierState()
        }
        // resetModifierState detaches all nodes, so we need to re-attach them upon reuse.
        nodes.attach()  // <-- This line was removed and after we merged from upstream, returned
    }
```

**Comment by okushnikov** [comment] 2024-07-14 16:17
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3189">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:24 UTC
Labels: bug, desktop, ios, reproduced
