### ISSUE TITLE
Using LazyListScope as parameter to other function should be possible on iOS

### ISSUE THREAD

**Issue by MikolajKakol** [JetBrains/compose-multiplatform#3087] opened 2023-04-22 19:47 UTC
**Describe the bug**
Given code should compile
```
fun foo(
    content: LazyListScope.() -> Unit
) {
}
```
It fails with error:
```
error: There are still 3 unbound symbols after generation of IR module <shared>:
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: androidx.compose.foundation.lazy/LazyListScope.item|-2398404341226065315[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: androidx.compose.foundation.lazy/LazyListScope.items|8564101490881923997[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: androidx.compose.foundation.lazy/LazyListScope.stickyHeader|431226128286809998[0]
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): 16.2
- OS architecture (x86 or arm64): x86

**Comment by eymar** [comment] 2023-04-24 09:07
Reproduced. Adding a bit more context:

Same function with `@Composable` annotation does work:

```kotlin
@Composable
fun foo(
    content: LazyListScope.() -> Unit
) {
}
```
Or this works too:
```kotlin
fun foo(
    content: @Composable LazyListScope.() -> Unit
) {
}
```


@MikolajKakol Thank you for submitting the bug. I just want to confirm that your intention was indeed to not have `@Composable` anntation neither on the foo function nor the content lambda? 
Regardless, the issue is valid and it should compile.

**Comment by MikolajKakol** [comment] 2023-04-24 09:31
Yes, it is intended. We use it to separate the code that goes into LazyColumn. Errors, I provided here and before are from migrating a large Android project with around 200 screens in compose.

**Comment by MikolajKakol** [comment] 2023-04-26 14:12
An interesting workaround is to add an empty composable like this:
```
fun foo(
    content: LazyListScope.() -> Unit
    t: @Composable () -> Unit = {},
) {
}
```

**Comment by eymar** [comment] 2023-04-26 14:25
Thanks for extra input. It's helpful

**Comment by eymar** [comment] 2023-05-22 09:23
The workaround is to add @HiddenFromObjC annotation:

```kotlin
@OptIn(ExperimentalObjCRefinement::class)
@HiddenFromObjC
fun foo(
    content: LazyListScope.() -> Unit
) {
}
```

A proper fix is in progress.

**Comment by eymar** [comment] 2023-05-22 09:24
I close this issue if you don't mind. I'm sure it's a duplicate of https://github.com/JetBrains/compose-multiplatform/issues/3086 because they have the same workaround.

**Closed by eymar** 2023-05-22 09:24 UTC
Labels: bug, compiler, reproduced

**Comment by okushnikov** [comment] 2024-08-26 14:43
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3087">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
