### ISSUE TITLE
MaterialTheme.colorScheme not persisted for some components in iOS

### ISSUE THREAD

**Issue by pcorreia89** [JetBrains/compose-multiplatform#4336] opened 2024-02-21 07:30 UTC
**Describe the bug**
Components (AlertDialog, OutlinedButton, etc.) with different colors between Android and iOS version but with the same MaterialTheme.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.22 
- Compose Multiplatform version*: 1.6.0-beta02 
- OS version(s)* (required for Desktop and iOS issues): Simulator iPhone 15 | iOS 17.2

**Expected behavior**
Components (AlertDialog, OutlinedButton, etc.) in iOS with the same colors as the Android since they are being called from a MaterialTheme with a pre-defined colorScheme.

**Screenshots**
<img width="850" alt="Screenshot 2024-02-21 at 3 42 33 pm" src="https://github.com/JetBrains/compose-multiplatform/assets/124446615/5e3b2383-5f83-477a-88d2-62a48e4734f3">

![Screenshot 2024-02-21 at 11 40 18 am](https://github.com/JetBrains/compose-multiplatform/assets/124446615/54dbcb84-3c94-435e-867c-866b627d0244)

**Comment by pcorreia89** [comment] 2024-02-21 07:44
It might be related to this issue here: https://github.com/JetBrains/compose-multiplatform/issues/4281

But I wasn't sure.

**Comment by MatkovIvan** [comment] 2024-02-21 08:42
Duplicate of #4281, fixed in 1.6.0-rc02

**Closed by MatkovIvan** 2024-02-21 08:42 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-08-26 13:47
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4336">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
