### ISSUE TITLE
LazyColumn: Scrolling sometimes snaps back

### ISSUE THREAD

**Issue by sawil314** [JetBrains/compose-multiplatform#3959] opened 2023-11-21 08:16 UTC
**Describe the bug**
In a LazyColumn, under some circumstances if you try to scroll up slowly, it keeps snapping back.

**Affected platforms**
Select one of the platforms below:
- Probably All
- reproduced for Desktop and Android

**Versions**
- Kotlin version: 1.9.20, 1.9.0
- Compose Multiplatform version: 1.5.10, 1.5.1
- OS version(s): Reproduced on: Windows 11, Android Api28, Android Api33

**To Reproduce**
I am not sure under what conditions it occurs, therefor there is no minimal example but I uploaded on code where it occurs:
(https://github.com/sawil314/ScrollingBugComposeMultiplatform/tree/main)
1. Clone Project and start for Desktop or  in landscape Mode for Android Virtual Device: Nexus 9 Api33
2. Scroll down and than scroll up slowly.

**Expected behavior**
It should be possible to scroll up.

**Screenshots**
For Desktop:
https://github.com/JetBrains/compose-multiplatform/assets/79279490/8ad39fba-bef5-431d-99d7-c20e68d326ab

**Additional context**
Probably connected to:
(https://github.com/JetBrains/compose-multiplatform/issues/800)
(https://issuetracker.google.com/issues/179593134)

Without the Textfields and their measuring it doesn't occur.

**Comment by elijah-semyonov** [comment] 2023-11-21 10:39
Since the issue is present on Android, it means that Jetpack Compose itself is an origin of it. Could you please write create a report [here](https://issuetracker.google.com/components/612128) and link it in this thread?

**Comment by sawil314** [comment] 2023-11-21 13:43
Issue created here:
(https://issuetracker.google.com/issues/312227062)

**Comment by okushnikov** [comment] 2024-07-14 16:09
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3959">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:06 UTC
Labels: bug, desktop, android
