### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented: UITextGranularityParagraph iterator

### ISSUE THREAD

**Issue by brendanw** [JetBrains/compose-multiplatform#3978] opened 2023-11-26 06:51 UTC
**Describe the bug**
I had a user run into this same crash two times consecutively. I tried to reproduce on a simulated version of their device but was unable to. I suspect the issue is reproducible on the actual physical device + OS combo of the user.

Given the stacktrace, it looks like there is an unimplemented function in compose or compose multiplatform.

```

kotlin.NotImplementedError: An operation is not implemented: UITextGranularityParagraph iterator

0  BaseBetaiOS +0x2ee9b8      kfun:androidx.compose.ui.platform.toTextIterator#internal (UIKitTextInputService.uikit.kt)
1  BaseBetaiOS +0x2ed0a0      kfun:androidx.compose.ui.platform.UIKitTextInputService.object-1.isPositionAtBoundary#internal (UIKitTextInputService.uikit.kt:414:39)
2  BaseBetaiOS +0x316a98      kfun:androidx.compose.ui.platform.IOSSkikoInput#isPositionAtBoundary(kotlin.Int;platform.UIKit.UITextGranularity;kotlin.Long){}kotlin.Boolean-trampoline (IOSSkikoInput.kt:140:5)
3  BaseBetaiOS +0xb5be18      _6f72672e6a6574627261696e732e636f6d706f73652e75693a75692f6f70742f6275696c644167656e742f776f726b2f356234626566333562333562396631322f636f6d706f73652f75692f75692f7372632f75696b69744d61696e2f6b6f746c696e2f616e64726f6964782f636f6d706f73652f75692f77696e646f772f536b696b6f5549566965772e6b74_kncfun168
4  UIKitCore +0xb92868        +[UIDictationUtilities selectionStartInfoWithBlock:]
5  UIKitCore +0xb7c338        -[UIDictationController dictationConnection:receivedInterpretation:languageModel:secureInput:]
6  UIKitCore +0xb65474        -[UIDictationConnection dictationConnection:didRecognizeTokens:languageModel:]
7  AssistantServices +0x97a94 -[AFDictationConnection _delegateDidRecognizeSpeechTokens:nluResult:languageModel:delegate:]
8  AssistantServices +0x654c  ___53-[AFDictationConnection _dispatchCallbackGroupBlock:]_block_invoke_2
9  libdispatch.dylib +0x26a4  __dispatch_call_block_and_release
10 libdispatch.dylib +0x42fc  __dispatch_client_callout
11 libdispatch.dylib +0x12994 __dispatch_main_queue_drain
12 libdispatch.dylib +0x125ac __dispatch_main_queue_callback_4CF
13 CoreFoundation +0x379b8    ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
14 CoreFoundation +0x346c4    ___CFRunLoopRun
15 CoreFoundation +0x33e14    _CFRunLoopRunSpecific
16 GraphicsServices +0x35e8   _GSEventRunModal
17 UIKitCore +0x22f2f8        -[UIApplication _run]
18 UIKitCore +0x22e934        _UIApplicationMain
19 BaseBetaiOS +0x1beac       main (AppDelegate.swift:15:7)
20 dyld +0x5d40               start
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10

**To Reproduce**
I did a search of the compose-multiplatform codebase for `UITextGranularityParagraph` and found no results. I don't have an understanding of how compose-multiplatform is built on top of compose. I was hoping I could find a stray `TODO` near `UITextGranularityParagraph` usage.

I was unable to reproduce using a simulator to mirror the user's device. I also tried setting device locale to `en_au` as well, but could not reproduce. Many other users are making it through this simple screen without issue. The screen the user is on when the app crashes is very simple

Code is below:

```kotlin
@Composable
fun NameScreen(
   backNavigate: () -> Unit,
   nextScreen: () -> Unit,
   model: CreateAccountModel,
   analytics: Analytics = AppDependencies.analytics
) {
   LaunchedEffect(Unit) {
      analytics.trackEvent(AE.SIGNUP_NAME_SCREEN_VIEWED)
   }

   OnboardingWrap(
      backNavigate = backNavigate,
      nextScreen = nextScreen,
      model = model
   ) {
      Column(
         modifier = Modifier.padding(start = 20.dp, end = 20.dp, top = 100.dp)
      ) {
         Text(
            text = "What's your name?",
            color = Color.White,
            fontSize = 30.sp,
         )

         Spacer(modifier = Modifier.height(70.dp))

         TextField(
            label = { Text("First name") },
            value = model.firstName.value,
            modifier = Modifier.fillMaxWidth(),
            onValueChange = { model.firstName.value = it },
            colors = authTextFieldColors()
         )

         Spacer(modifier = Modifier.height(40.dp))

         TextField(
            label = { Text("Last name") },
            value = model.lastName.value,
            modifier = Modifier.fillMaxWidth(),
            onValueChange = { model.lastName.value = it },
            colors = authTextFieldColors()
         )

         Spacer(modifier = Modifier.height(40.dp))

         val focusManager = LocalFocusManager.current

         AuthButton(
            text = "NEXT",
            isLoading = model.isLoading.value,
            action = {
               focusManager.clearFocus(force = true)
               model.onNameNextTapped()
            }
         )
      }
   }
}

@Composable
fun authTextFieldColors(): TextFieldColors {
   return TextFieldDefaults.textFieldColors(
      textColor = Color.White,
      focusedLabelColor = Color.White,
      unfocusedLabelColor = Color.White,
      focusedIndicatorColor = Color.White,
      cursorColor = Color.White
   )
}
```

**Expected behavior**
App should not crash for a simple use of `TextField` on an iOS device.

**Additional context**
apple device: iPhone SE (3rd generation) (iPhone14,6)
os version: 17.0.3
locale: en_au

**Comment by dima-avdeev-jb** [comment] 2023-12-23 15:03
@brendanw Can you please provide a minimal reproducible sample. Because in your code sample there are some Entities I can't compile:
OnboardingWrap, CreateAccountModel, Analytics, etc.

**Comment by brendanw** [comment] 2023-12-30 16:27
hey @dima-avdeev-jb I am not able to reproduce the issue, I was more so sharing the code for context. 

```
kotlin.NotImplementedError: An operation is not implemented: UITextGranularityParagraph iterator
```

This is the error. It seems somehow my code is leading to a codepath getting executed that I assume you guys don't believe should be possible. I was hoping it'd be possible to infer the root cause just by inspecting the code.

Or worst case just implemented the unimplemented.

If not, no worries, I only saw this crash happen once and it has not happened since.

**Comment by okushnikov** [comment] 2024-07-14 14:53
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3978">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment] 2024-07-14 14:54
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3978">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3978">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:38 UTC
Labels: bug, ios
