### ISSUE TITLE
Unable to Run Generated App on an M1 Mac

### ISSUE THREAD

**Issue by kevinrjones** [JetBrains/compose-multiplatform#2961] opened 2023-04-03 10:26 UTC
If I try and run the generated application on an M1 Mac it fails to start. If I run the app from the console I see this exception

Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /Applications/Game Of Life.app/Contents/app/libskiko-macos-arm64.dylib

**Affected platforms**
- Desktop (M1 Mac)

**Versions**
- Kotlin version: 1.8: 
- Compose Multiplatform version: 1.3.1: 
- OS version(s)* Ventura 13.2.1: 
- OS architecture arm64: 
- JDK 17.1 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
Generate a Compose Desktop app from within IntelliJ Idea, Choose 'single platform'
From the Gradle tab click on 'packageDmg'
After the dmg has been built copy the app from the dmg to the Applications directory
Run the app (it fails to start on my machine)
From a terminal run /Applications/[AppName.app]/Contents/MacOS/[AppName]

**Expected behavior**
The app should run

**Screenshots**
This is the full exception I'm getting

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /Applications/Game Of Life.app/Contents/app/libskiko-macos-arm64.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.jetbrains.skiko.Library.loadLibraryOrCopy(Library.kt:20)
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:85)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
	at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:110)
	at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
	at MainKt.main(Main.kt:33)
	at MainKt.main(Main.kt)
Failed to launch JVM
```

**Additional context**
I've tried this with multiple projects on two M1 machines and I get the same issue every time. 

If I look at the contents of the .app the dylib is in the place where the error says it's not (ie it is in /Applications/Game Of Life.app/Contents/app/ and does have the right name). 

If I run the app from the IDE it creates a ~/.skiko direcrtory and copys a version of the dylib into that directory. If I take that copy of the dylib and copy it into the .app/Contents/app directory then I can run the app from the Applications directory (make sense?) So it looks like the wrong dylib is being copied into the .app file when it's created

**Comment by kevinrjones** [comment] 2023-04-03 11:51
I've since update my JDK to v20 and the build now works. The previous SDK was 17.0.3 (from Temurin) if that helps

**Comment by AlexeyTsvetkov** [comment] 2023-04-03 15:07
Duplicate of #2867
Another possible workaround is to add entitlements as described in #2887

**Closed by AlexeyTsvetkov** 2023-04-03 15:07 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:19
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2961">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
