### ISSUE TITLE
Cannot override SelectionContainer cursor

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#3872] opened 2023-10-28 03:21 UTC
**Describe the bug**

It is expectated that a child property will override a parent property. This applied with cursors, and usually works as expected. However, with a `Text` inside `SelectionContainer` it does not work.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.20-RC2
- Compose Multiplatform version*: 1.5.10-rc02
- OS version(s)* (required for Desktop and iOS issues): macOS 14.0
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 20

**To Reproduce**

```kotlin
    fun main() {
        application {
            Window(visible = true, onCloseRequest = {
                exitApplication()
            }) {
                Column {

                    Text("Text not in selection container. Meets expectation of default cursor.")

                    SelectionContainer {
                        Text("Text in selection container. Meets expectation of text input cursor.")
                    }

                    Text(
                        "Text not in selection container, with hand cursor modifier. Meets expectation of hand cursor.", modifier = Modifier.pointerHoverIcon(
                            PointerIcon.Hand
                        )
                    )

                    SelectionContainer {
                        Text(
                            "Text in selection container, with hand cursor. Does NOT meet expectation. Because the Text is the child of SelectionContainer, we expect the cursor of the child to override the parent. Therefore, we expect a hand cursor here. However, we get a text input cursor.", modifier = Modifier.pointerHoverIcon(
                                PointerIcon.Hand
                            )
                        )
                    }
                }
            }
        }
    }
```

**Expected behavior**
The Text cursor should override the selection container cursor.

**Additional context**

This is a minimal reproducible example representing an issue from a more complex scenario. In the more complex scenario, we want clickable "links" inside of selectable text. So most of the text should have the text input cursor, but specific ranges should have a hand cursor. The machinery is already in place that makes the cursor conditional on the characterOffset closest to the mouse pointer. We can get the cursor to only be a hand when the user is hovering over the link, and not a hand for the rest of the text. However, this only works when not in a SelectionContainer because inside a SelectionContainer the cursor is a text input cursor always, no matter what.

**Comment by dima-avdeev-jb** [comment] 2023-10-29 05:39
Thanks for Issue!
Add project on GitHub with your code snippet. https://github.com/dima-avdeev-jb/issue-3872-selection-container
Also we need to check how it will works on Android.

**Comment by eymar** [comment] 2023-10-30 12:32
Reproduced on android (JC 1.5.4) too. So it affects all platforms.

**Comment by eymar** [comment] 2023-11-06 15:17
@mgroth0 Could you please submit this issue to Jetpack Compose? - https://issuetracker.google.com/issues/new?component=612128&template=1253476 (since it affects Android, and it should be fixed in the commonMain code)

**Comment by Grantapher** [comment] 2024-02-13 19:14
The above issue is now resolved on Jetpack Compose's side, fixed in https://android-review.googlesource.com/2954163.

**Closed as completed** 2024-02-16 05:58 UTC
Labels: bug, upstream (AOSP), selection

**Comment by okushnikov** [comment] 2024-07-14 15:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3872">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
