### ISSUE TITLE
Linux run from IDEA gutter, Cannot find libskiko-linux-x64.so.sha256

### ISSUE THREAD

**Issue by 456634** [JetBrains/compose-multiplatform#3717] opened 2023-09-20 18:15 UTC
**Describe the bug**

Trying to run on Linux with IDEA 2023.2 gutter icon:

![image](https://github.com/JetBrains/compose-multiplatform/assets/99798741/33745710-486b-4abc-8fe8-04f5390d3886)

```
/usr/lib/jvm/java-17-openjdk/bin/java...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at androidx.compose.ui.awt.WindowComposeBridge.<init>(WindowComposeBridge.desktop.kt:40)
	at androidx.compose.ui.awt.ComposeWindowDelegate.<init>(ComposeWindowDelegate.desktop.kt:53)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:62)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:60)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:179)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:173)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:405)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:402)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:74)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:73)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1041)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-linux-x64.so.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:105)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.awt.kt:32)
	... 32 more
```

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.1
- OS version(s)* (required for Desktop and iOS issues): Arch Linux
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): openJDK17

**To Reproduce**
Upgrade runing Project with Kotlin 1.8.0 to 1.9.10

**Additional context**
```
build.gradle.kts (:desktop)
....

kotlin {
    jvm {
        jvmToolchain(17)
        withJava()
    }
    sourceSets {
        val jvmMain by getting {
            dependencies {
                implementation(project(":common"))
                implementation(compose.desktop.currentOs)
            }
        }
        val jvmTest by getting
    }
}

compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "demo"
            packageVersion = "1.0.0"
        }
    }
}
```

**Comment by dima-avdeev-jb** [comment] 2023-09-23 19:37
I can't reproduce your problem.
Can you please try to reproduce on my repository https://github.com/dima-avdeev-jb/issue-3717-desktop-linux

**Comment by 456634** [comment] 2023-09-23 22:39
Hello Dima,

thanks for looking at it. I tested your project and had the same behaviour.



But in the meantime I also became aware of https://github.com/JetBrains/compose-multiplatform/issues/3123, which seems very similar to me.



When I run MainKt as Kotlin via Intellij(CE2023.2), I have this problem. 

Not with gradle `:desktop:run.`



However, it is not clear to me why this happens from 1.8.0 to 1.9.20.

**Comment by dima-avdeev-jb** [comment] 2023-09-24 00:55
@456634 

What JVM version and vendor do you have in Gradle settings of this project?

<img width="963" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/9aa2082f-7313-48f4-a78b-9242891052bf">

**Comment by 456634** [comment] 2023-09-24 08:29
Hello Dima,
corresponds exactly to your screenshot, with the difference that I use Project SDK for Gradle Jvm(17.0.8).

**Comment by dima-avdeev-jb** [comment] 2023-09-25 08:22
@456634 
Can you please delete gradle and maven cahces:
`rm -rf ~/.gradle`
`rm -rf ~/.m2`

**Comment by 456634** [comment] 2023-09-25 10:40
@dima-avdeev-jb 
Deleted gradle an maven caches. Same behaviour.

With Gradle configuration works.
With Kotlin configuration the skiko error comes. 

In both projects (yours, mine).

**Comment by dima-avdeev-jb** [comment] 2023-09-25 16:17
Do I correctly understand, what you are trying to run from the gutter icon near the `fun main` ?

<img width="259" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/48aa77ca-d3e5-4060-a457-b92a13d9d486">

**Comment by 456634** [comment] 2023-09-25 16:37
> Do I correctly understand, what you are trying to run from the gutter icon near the `fun main` ?
> 
> <img alt="image" width="259" src="https://user-images.githubusercontent.com/99798741/270407935-48aa77ca-d3e5-4060-a457-b92a13d9d486.png">

Yes, that's what I'm talking about. Is that wrong? I honestly never thought about it, since there were no problems with it until 1.9.x. Sorry if I wasted your time and was not clear in https://github.com/JetBrains/compose-multiplatform/issues/3717#issuecomment-1732424625

**Comment by dima-avdeev-jb** [comment] 2023-09-25 17:24
I was trying to do so with Linux Manjaro - and it was succesfully runs on IDEA 2023.2

**Comment by changhexuefei** [comment] 2023-09-26 06:14
Thank you for your suggestion. I will try to use a multi-window program to achieve the above requirements.

**Comment by orelvis15** [comment] 2023-10-03 17:29
I am having the same problem on MAC Intel.

```
kotlin.version=1.9.10 || 1.9.0
compose.version=1.5.2
```

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at androidx.compose.ui.awt.WindowComposeBridge.<init>(WindowComposeBridge.desktop.kt:40)
	at androidx.compose.ui.awt.ComposeWindowDelegate.<init>(ComposeWindowDelegate.desktop.kt:53)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:62)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:60)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:179)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:173)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:405)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:402)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:74)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:73)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1041)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-macos-x64.dylib.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:105)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.awt.kt:32)
	... 32 more
```


But it does work in these versions

```
kotlin.version=1.8.0
compose.version=1.5.2
```

**Comment by lexasok** [comment] 2023-10-14 13:54
Hello, Same issue on Ubuntu 22.04.3 LTS

Exception in thread "main" java.lang.ExceptionInInitializerError
	at androidx.compose.ui.awt.WindowComposeBridge.<init>(WindowComposeBridge.desktop.kt:40)
	at androidx.compose.ui.awt.ComposeWindowDelegate.<init>(ComposeWindowDelegate.desktop.kt:53)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:62)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:60)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:179)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:173)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:405)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:402)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:74)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:73)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1041)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-linux-x64.so.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:105)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.awt.kt:32)
	... 32 more

**Comment by lexasok** [comment] 2023-10-14 13:55
Hello, Same issue on Ubuntu 22.04 LTS (New project by Full Stack Compose Multiplatform pluggin)

**Comment by adamglin0** [comment] 2024-07-02 03:21
Same in Macos， This issue does not occur frequently.

**Comment by okushnikov** [comment] 2024-07-14 14:51
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3717">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:28 UTC
Labels: bug, linux, desktop
