### ISSUE TITLE
Windows 7 : DLL Error

### ISSUE THREAD

**Issue by theapache64** [JetBrains/compose-multiplatform#468] opened 2021-03-06 15:12 UTC
After installing the exported `msi` file, when launching the program, below errors are showing.

![image](https://user-images.githubusercontent.com/9678279/110211355-42869600-7ebc-11eb-8896-1aa3a399bf59.png)

**After pressing OK**

![image](https://user-images.githubusercontent.com/9678279/110211363-4b776780-7ebc-11eb-82fb-e608aae1ba5e.png)

**OS:**: Windows 7

**Comment by olonho** [comment] 2021-03-06 15:58
Will installation of MSVC redistributable help?

**Comment by theapache64** [comment] 2021-03-06 21:10
I didn't try that, but after installing JDK `(openjdk-15)`, the error is gone.

**Comment by jimgoog** [comment] 2021-03-08 16:24
You installed openjdk-15 before doing the build?  Or on the machine which you ran the app?  Or are those the same machine?

Hopefully installing the jdk on the target machine where you run the app is not necessary.

I think we might have added a rule against building with JDk-14 in https://github.com/JetBrains/compose-jb/commit/ecbf3485381b39be66aaa299ff17a1851a97089b

**Comment by theapache64** [comment] 2021-03-08 16:33
> You installed `openjdk-15` before you ran the app? 

No. It was a fresh Windows 7 VM (No JDK at all)

**Comment by jimgoog** [comment] 2021-03-08 16:34
So shall we close this bug since it should no longer occur now that we require JDK 15?  Or did I miss something?

**Comment by olonho** [comment] 2021-03-15 06:05
Would be cool to test if installing Visual C++ redistributable (https://aka.ms/vs/16/release/vc_redist.x64.exe) is enough. If this is the case - then it's likely OpenJDK issue.

**Comment by JunkFood02** [comment] 2023-06-08 02:24
The same issue can still be reproduced on Windows 7. The first error is exactly the one about `api-ms-win-crt-runtime-l1-1-0.dll`, then followed by the error of `jni.dll`. Install `openjdk-17` on the target device fixes this problem.

**Comment by RafaelUSA7** [comment] 2023-07-26 04:40
> The same issue can still be reproduced on Windows 7. The first error is exactly the one about `api-ms-win-crt-runtime-l1-1-0.dll`, then followed by the error of `jni.dll`. Install `openjdk-17` on the target device fixes this problem.

I fixed this issue installing the update KB2999226 avaliable at the link below (I'm using openjdk-20 to generate the installer):
https://www.microsoft.com/en-US/download/confirmation.aspx?id=49093

**Comment by okushnikov** [comment] 2024-08-26 15:46
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6045">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:19 UTC
Labels: native distribution

**Comment by chethann** [comment] 2024-11-28 07:28
I had the same issue on windows 7.
Fixed after installing open jdk [https://aka.ms/download-jdk/microsoft-jdk-17.0.13-windows-x64.msi](https://aka.ms/download-jdk/microsoft-jdk-17.0.13-windows-x64.msi)
