### ISSUE TITLE
LazyListState.animateScrollToItem Not scrolling correctly to the specified index

### ISSUE THREAD

**Issue by ltttttttttttt** [JetBrains/compose-multiplatform#4148] opened 2024-01-20 11:37 UTC
**Describe the bug**
LazyListState.animateScrollToItem Not scrolling correctly to the specified index

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): macOS 13.0.1 (22A400)
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. run iosApp in https://github.com/ltttttttttttt/ComposeViews
2. Click on 'ValueSelector功能'
3. Dragging the Value selector control at the top and dragging it down to the bottom of the screen will trigger scrolling to the corresponding index, but there is no animation
4. Code in https://github.com/ltttttttttttt/ComposeViews/blob/main/ComposeViews/src/commonMain/kotlin/com/lt/compose_views/value_selector/ValueSelector.kt   line:133

**Expected behavior**
I hope to scroll to the corresponding index like Android

**Screenshots**
<img width="292" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/23447567/747c0843-c3e2-4bb9-b5be-288977b59f61">

**Comment by elijah-semyonov** [comment] 2024-01-23 12:28
I didn't manage to compile it. Can you provide a minimal snippet reproducing the problem?

**Comment by mazunin-v-jb** [comment] 2024-02-04 23:01
Hello, @ltttttttttttt!
Unfortunately, your project contains a significant amount of user-specific code and details. We can't accept that as reproducer because we can't be sure that the issue is on our side.

Could you please provide a stripped down version of your code that demonstrates the issue?

**Comment by okushnikov** [comment] 2024-07-14 15:58
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4148">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:00 UTC
Labels: bug, wait for reply
