### ISSUE TITLE
BasicTextField loses focus when we change `modifier`

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2431] opened 2022-10-26 16:46 UTC
Compose 1.2.0

```
import androidx.compose.foundation.border
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsFocusedAsState
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    val interactionSource = remember { MutableInteractionSource() }
    val isFocused by interactionSource.collectIsFocusedAsState()

    BasicTextField(
        value = "value",
        modifier = if (isFocused) Modifier.border(2.dp, Color.Blue) else Modifier,
        onValueChange = { },
        interactionSource = interactionSource
    )
}
```

1. Click on the text field
2. See that the text field receives the focus, but on the next frame it is lost.

Workaround - wrap `BasicTextField` into `Box` and apply modifier to it

**Comment by m-sasha** [comment] 2023-01-30 11:46
This seems to be a problem not with the textfield, but with `Modifier.border`. The problem reproduces with a `Button`, but does not reproduce if you change `Modifier.border` to `Modifier.background`.

**Comment by okushnikov** [comment] 2024-08-26 14:47
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2431">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:34 UTC
Labels: bug, text
