### ISSUE TITLE
Issues with `Keyboard` and `TextField` on iOS.

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#3621] opened 2023-09-05 04:47 UTC
**Describe the bug**
Here are three issues about `Keyboard` And `TextField`:

- https://github.com/JetBrains/compose-multiplatform/issues/4016
- [x] When a `TextField` is included in a scrollable `Column`, if `TextField` is long enough, `TopAppBar` will exceed the edge of the screen. 
- [x] No `TextField` on the screen, but the `Keyboard` is open.
- [x] Crash when using Chinese input method on 1.5.10-beta02, caused by [SkikoUIView.kt#L513](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/SkikoUIView.kt#L513)

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0
- OS version(s)* (required for Desktop and iOS issues): all
- OS architecture (x86 or arm64): all

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

https://github.com/robxyy/keyboard-issues

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/9105106/1c2642be-dd92-4e9c-a3f9-8ef0c6a3427c

**Comment by m-sasha** [comment] 2023-09-06 12:46
@robxyy I wasn't able to reproduce "No TextField on the screen, but the Keyboard is open." What exactly is happening at the end of the video? Or maybe there's a shorter reproduction for it?

**Comment by robxyy** [comment] 2023-09-06 13:14
> @robxyy I wasn't able to reproduce "No TextField on the screen, but the Keyboard is open." What exactly is happening at the end of the video? Or maybe there's a shorter reproduction for it?

Yes, at the end of the video, when I leave `Screen2` , clicking the current screen or other button will automatically open the keyboard, probably related to focus.

**Comment by m-sasha** [comment] 2023-09-06 13:25
> Yes, at the end of the video, when I leave Screen2 , clicking the current screen or other button will automatically open the keyboard, probably related to focus.

Doesn't seem to reproduce for me.

**Comment by robxyy** [comment] 2023-09-06 13:48
> > Yes, at the end of the video, when I leave Screen2 , clicking the current screen or other button will automatically open the keyboard, probably related to focus.
> 
> Doesn't seem to reproduce for me.

Thanks, I found a way to reproduce, when I use the Chinese input method in `Screen2` and leave the input in an unfinished state, then click the `Screen1` or `goTo Screen3` button to automatically open the keyboard.

**Comment by TheMelody** [comment] 2023-09-11 06:45
**Replace**: `Modifier.fillMaxWidth().defaultMinSize(minHeight = 200.dp)` 

`Modifier.fillMaxWidth().requiredHeightIn((maxHeight = 200.dp)` 

**or** 
`Modifier.fillMaxSize()`

**Comment by jxdom** [comment] 2023-09-21 03:40
I also have the same problem, I am using TabRow, when Screen1 textfield uses Chinese input method, after clicking screen2, the input method will always be displayed and cannot be hidden. It should be noted that if the English input method is used in screen1, this bug will not be repeated, it seems that this bug only exists when using the Chinese input method

**Comment by jQrgen** [comment] 2023-09-25 17:00
Same issue here:


https://github.com/JetBrains/compose-multiplatform/assets/3964957/1bbdd1e1-264d-478c-bd03-0218cf7c88ec

**Comment by robxyy** [comment] 2023-10-09 01:42
Update: Crash when using `Chinese input method` on `1.5.10-beta02`, caused by [SkikoUIView.kt#L513](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/SkikoUIView.kt#L513)

**Comment by mazunin-v-jb** [comment] 2023-10-25 19:13
@robxyy 
I don't quite understand first issue here:`Extra space between Keyboard and TextField`
Could you please provide more detailed description of reproducing this?
Or just link me to messages here in case if it is already here and I missed them.
By the linked video I assume that it is a part of second problem, not a separate one.

**Comment by robxyy** [comment] 2023-10-26 03:41
@mazunin-v-jb 
Yes, it looks like part of the second problem. In this screenshot, there is a blank space between `Keyboard` and `Column`,  refer: #3485. If you don't mind my asking, could you let me know in which version you plan to fix these issues?
<img width="294" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/9105106/2bfd6ee8-2663-4798-8a85-e3a6d231f00d">

**Comment by mazunin-v-jb** [comment] 2023-10-26 09:27
@robxyy thank you for provided example.
We're planning to take it into work in the nearest future but for now I can't say anything specific about version where it is planned to be fixed.

**Comment by robxyy** [comment] 2024-01-06 14:26
Update: `v1.6.0-dev1357` has fixed the problem of automatically opening the keyboard.

**Comment by gandrewstone** [comment] 2024-03-15 14:27
Note for the whitespace above soft keyboard problem, the workaround mentioned in https://github.com/JetBrains/compose-multiplatform/issues/3485#issuecomment-1681791377 works for me in compose 1.6.0:
```
ComposeContentView().ignoresSafeArea(.keyboard,.all)
```

**Comment by oblakr24** [comment] 2024-05-30 16:28
Any updates here? This still does not work on 1.6.10.
I tried `.ignoresSafeArea(.keyboard,.all)`.
My content is a Scaffold with 

```
   bottomBar = {
            
                TextField(value = "", onValueChange = { a ->
                   // TODO
                })
        }

```

The footer scrolls to be on top of the keyboard, but so does the entire content, including the `topBar` in the scaffold (which should be pinned at the top).

**Comment by bevcastillo** [comment] 2024-07-01 10:18
Hi @oblakr24 I wonder if you have found a solution on the `topBar` issue with Scaffold?

**Comment by bevcastillo** [comment] 2024-07-01 10:51
I'm still having keyboard issues here same with @oblakr24. Any updates?

**Comment by oblakr24** [comment] 2024-07-01 11:02
@bevcastillo in my case, `.imePadding()` on the footer (the part which is supposed to be pinned atop the keyboard) did the trick. My `ContentView` in SwiftUI has ` .ignoresSafeArea(.keyboard)`.

That said, the keyboard opening/closing is still choppy, compared to native iOS apps.

**Comment by okushnikov** [comment] 2024-08-26 13:33
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3621">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:20 UTC
Labels: bug, ios, reproduced
