### ISSUE TITLE
First click inside BasicAlertDialog accompanied by jump of rise component

### ISSUE THREAD

**Issue by ExNDY** [JetBrains/compose-multiplatform#4950] opened 2024-06-10 05:10 UTC
**Describe the bug**
Clickable content inside Dialog/BasicAlertDialog on iOS platform accompanied by jump of resize component.

**Affected platforms**
- iOS

**Versions**
- Compose Multiplatform version: 1.6.10, 1.6.11
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): iOS 17.4
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): Device, Simulator

**To Reproduce**
1. Run this code snippet:
   ```kt
   BasicAlertDialog(
                modifier = Modifier.fillMaxWidth(),
                onDismissRequest = {  },
            ) {
                Button(
                    onClick = {}
                ){
                    Text("sametext")
                }
            }
   ```
2. Click on button
3. See jump on first click any elements

**Expected behavior**
Click without "jumps" like on Android platform

**Video**

https://github.com/JetBrains/compose-multiplatform/assets/22731300/caefbc96-3edc-4103-b304-e7f932c8de39

**Comment by MatkovIvan** [comment] 2024-06-10 07:09
Duplicate of #4924

**Closed by MatkovIvan** 2024-06-10 07:09 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 14:54
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4950">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4950">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
