### ISSUE TITLE
Texts are not displayed on specific windows device

### ISSUE THREAD

**Issue by sdercolin** [JetBrains/compose-multiplatform#3247] opened 2023-06-07 12:32 UTC
**Describe the bug**
All texts are not displayed on a specific device.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): amd64
- JDK (for desktop issues): 17

**To Reproduce**

Tested with the Hello World project template created by IDEA.

```
@Composable
@Preview
fun App() {
    var text by remember { mutableStateOf("Hello, World!") }

    MaterialTheme {
        Button(onClick = {
            text = "Hello, Desktop!"
        }) {
            Text(text)
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

**Expected behavior**

![image](https://github.com/JetBrains/compose-multiplatform/assets/7665216/7c8148c0-c0ec-4bea-b315-48a6e9d4b333)

**Screenshots**

![image](https://github.com/JetBrains/compose-multiplatform/assets/7665216/9c072882-2cbb-4d8f-aaad-9161f6302002)

**Additional context**

- I thought it was related to locale (es_VE) but after switching to English it still happens
- The texts in dialog title and the menu are displayed properly

**Comment by m-sasha** [comment] 2023-06-07 14:18
Does this show the text?

```
fun main() = singleWindowApplication(
    state = WindowState(
        size = DpSize(400.dp, 800.dp)
    )
) {
    Text("Hello")
}
```

**Comment by sdercolin** [comment] 2023-06-07 18:00
Tried. The text is still not displayed.

**Comment by m-sasha** [comment] 2023-06-07 18:03
We're going to need something more to go on, since it's obviously a unique case. Can you think of any reason (other than the locale) that particular PC won't render compose text?

**Comment by sdercolin** [comment] 2023-06-07 20:04
I think it looks like similar to #214, but it's already solved 🤔 
Not sure if related but this device is AMD CPU, which is somehow rare..

**Comment by m-sasha** [comment] 2023-06-07 20:40
Maybe it's a regression, or maybe that PC has even less memory in its graphics card.
Can you try with either `SKIKO_RENDER_API=SOFTWARE` (environment variable) or `skiko.renderApi=SOFTWARE` (Java system property)?

**Comment by sdercolin** [comment] 2023-06-08 10:43
It's working after setting `SKIKO_RENDER_API=SOFTWARE`!

Is it possible to fix the problem?

**Comment by m-sasha** [comment] 2023-06-08 11:45
What's the graphics card on that PC?

**Comment by sdercolin** [comment] 2023-06-08 12:24
Provided by the user
`integrated graphic ati radeon 4200 hd`

**Comment by m-sasha** [comment] 2023-06-08 12:36
That GPU doesn't support even DirectX 11. But we should fallback gracefully to OpenGL or software renderer.

Can you try `SKIKO_RENDER_API=OPENGL`?

**Comment by sdercolin** [comment] 2023-06-12 05:46
Sorry for the delay.
`OPENGL` does not work either.

**Comment by m-sasha** [comment] 2023-06-15 12:09
Perhaps our fallback mechanism is broken or doesn't always detect an unsupported render API.

**Comment by m-sasha** [comment] 2023-06-20 14:01
The GPU specs:
https://www.techpowerup.com/gpu-specs/radeon-hd-4200-igp.c775

**Comment by okushnikov** [comment] 2024-08-26 14:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3247">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:22 UTC
Labels: bug
