### ISSUE TITLE
UI Preview does not work inside Android Studio

### ISSUE THREAD

**Issue by DreamerChaserHAH** [JetBrains/compose-multiplatform#4984] opened 2024-06-17 04:18 UTC
**Describe the bug**
UI Preview does not work inside Android Studio after adding a PainterResource inside commonMain/composeResources/drawable despite the project is being built successfully

**Affected platforms**
- Android Studio on Mac

**Versions**
- Compose Multiplatform Mobile Version : 0.8.2(233)-8
- OS : Mac OS 14.5
- JDK : 21

**To Reproduce**
1. Add a image or icon into a component
For e.g,
```kt
Icon(painterResource(Res.drawable.baseline_info_24), null)
```
2. Load Preview by going to AndroidMain's MainActivity

**Expected behavior**
Preview displaying normally

**Screenshots**
It should display like this inside preview (this is IOS Simulator)
<img width="340" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/109950820/709594e8-5e82-4099-bbef-b3a312402aa1">
But it is displaying like this inside Android Studio Preview
<img width="237" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/109950820/5294b08f-fe18-4381-b369-910f1642001f">

**Additional context**
None

**Comment by MatkovIvan** [comment] 2024-06-17 09:41
Duplicate of #4932 (and #4476)

**Closed by MatkovIvan** 2024-06-17 09:41 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-08-26 13:37
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4984">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
