### ISSUE TITLE
"compose-resources" path of UIKitResourceImpl on iOS

### ISSUE THREAD

**Issue by SongOnWater** [JetBrains/compose-multiplatform#3637] opened 2023-09-07 09:06 UTC
**Describe the bug**
Why there is a intermedia path "compose-resources" of UIKitResourceImpl , that makes files should be placed under it then to be read.  I think the file path should be consistency of multiple platforms. 

**Affected platforms**
Select one of the platforms below:
- iOS

**Comment by igordmn** [comment] 2023-09-07 17:20
`compose-resources` folder is implementation details, and it doesn't supposed to be accessed via uikit resource api. It is designed in a way that it should be accessed only via Compose resource API (`org.jetbrains.compose.resources.resource`).

What is your use case?

**Comment by SongOnWater** [comment] 2023-09-10 06:45
@igordmn The iOS sample project of components/resources/iosApp reports error "org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: dir/vector.xml". I think that intermedia path "compose-resources" is the root cause.

**Comment by pjBooms** [comment] 2023-09-11 08:56
@SongOnWater If you use  `implementation(compose.components.resources)` ("org.jetbrains.compose.components:components-resources") of the same version as Compose Multiplatform Gradle plugin then it should not be a root cause, because the resource library of 1.5 version prepends all resource paths with "compose-resources" itself.

**Comment by igordmn** [comment] 2023-09-11 12:25
As @pjBooms mentioned, you need to use `implementation(compose.components.resources)`. Also, see the template, it [uses org.jetbrains.compose.resources.painterResource](https://github.com/JetBrains/compose-multiplatform-template/blob/220ee7687167611d71af0590f62459ac8d384db9/shared/src/commonMain/kotlin/App.kt#L33) to load a resource from `shared/src/commonMain/resources`.

If the issue is still present, please provide a project where it is reproducible.

**Comment by igordmn** [comment] 2023-09-11 12:50
As you mentioned `MissingResourceException` and `UIKitResourceImpl`, you already use the resource library, but it seems it is an older version (maybe it comes from some library).

To use a valid version, you should add [it explicitly](https://github.com/JetBrains/compose-multiplatform-template/blob/220ee7687167611d71af0590f62459ac8d384db9/shared/build.gradle.kts#L30)

**Comment by SongOnWater** [comment] 2023-09-11 12:58
Yes I use the library by "implementation(compose.components.resources)"  and  the version is as below 

val kotlinVersion = "1.9.10"
 kotlin("multiplatform").version(kotlinVersion).apply(false)
  id("org.jetbrains.compose").version("1.5.1").apply(false)
  
  To bypass  this issue , I add a middle path "compose-resources"  under my resources root path for iOS

**Comment by igordmn** [comment] 2023-09-11 13:08
Is it possible to provide a project with the issue? Adding the path shouldn't be necessary.

**Comment by igordmn** [comment] 2023-09-18 12:20
Closing, as we didn't reproduce it.

If you have a reproducer, please, attach it here, we will look at it and reopen the issue.

**Closed by igordmn** 2023-09-18 12:20 UTC
Labels: bug, wait for reply, resources

**Comment by okushnikov** [comment] 2024-08-26 14:37
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3637">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
