### ISSUE TITLE
Order of accessibility nodes is wrong

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#4795] opened 2024-05-10 09:16 UTC
1.6.10-rc01

https://github.com/Kotlin/KMP-App-Template/tree/426bead7f26ba27ba1facfbfd1d5c0f7628a437a

<img width="1133" alt="Screenshot 2024-05-10 at 11 14 28" src="https://github.com/JetBrains/compose-multiplatform/assets/2178959/73893cd4-28bd-4e2f-ae6e-768cb9ad131e">

**Comment by elijah-semyonov** [comment] 2024-05-10 09:43
Hm, what's the situation on Android? This is a single Element, so based on mismatch of visible text and Accessibility label I assume the data there was merged. The merging of semantics in the subtree is done in the order described [here](https://github.com/JetBrains/compose-multiplatform-core/blob/f9b90c58dfb166be398917f1e43326f6566e50ff/compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/semantics/SemanticsNode.kt#L241-L274).

We either have a runtime bug that somehow causes this order to be different from order in which underlying nodes are _apparently_ emitted in code, or it's a Google-side bug/(feature?).

A workaround for now would be to use `Modifier.clearAndSetSemantics` and explicitly provide the string to be visible by a11y services.

**Comment by tylerwilson** [comment] 2024-05-23 15:06
I have a similar if not the same issue in my app: it will read starting from the second element, go to the end, and then go back and read the first element. I was using a Column, then switched to a LazyColumn, but same result.

Hope the cause can be found and fixed. Thank you.

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4795">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:27 UTC
Labels: bug, accessibility, ios
