### ISSUE TITLE
Different behavior of flow subscriptions when screen is in background (Android vs iOS)

### ISSUE THREAD

**Issue by gradha** [JetBrains/compose-multiplatform#3889] opened 2023-11-01 15:45 UTC
**Describe the bug**
After implementing a few activities/view controllers I noticed certain parts of my logic were being run when I wasn't expecting. On Android, using a stateflow's `.collectAsState()` will keep the flow _subscribed_, and if the user touches the home button to exit the app, the flow keeps working. On iOS using the same code produces a flow that pauses whenever users exit the app pressing the home button.

In order to test this, I've built [the following example pull request against the ios android compose template](https://github.com/gradha/compose-multiplatform-ios-android-template/pull/1/files?diff=unified&w=0) as the minimum example I could think of. The main part of this PR is creating first a pseudo viewmodel that can be used on both platforms:

```kotlin
class PseudoViewModel {

    val _state = MutableStateFlow(1)
    val state = _state.asStateFlow()

    private var mJob: Job? = null

    init {
        _state.monitorSubscriptionCountIn(GlobalScope,
            onStartBeingObserved = {
                mJob = GlobalScope.launch {
                    println("Beginning to observe")
                    while (true) {
                        delay(2_000L)
                        _state.update { it + 1 }
                        println("Updated ticker to ${_state.value}")
                    }
                }

            },
            onStopBeingObserved = {
                mJob?.cancel()
                println("Finished observing")
            })
    }
}
```

This pseudo viewmodel exposes a `state` `StateFlow` that will increase it's value like a ticker as long as somebody is _watching_ the value.

The monitoring subscription helper is [based on the subscriptionCount documentation](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-shared-flow/subscription-count.html):

```kotlin
fun <T> MutableStateFlow<T>.monitorSubscriptionCountIn(
    scope: CoroutineScope,
    onStartBeingObserved: () -> Unit,
    onStopBeingObserved: () -> Unit,
) {
    subscriptionCount
        .map { count -> count > 0 } // map count into active/inactive flag
        .distinctUntilChanged() // only react to true<->false changes
        .drop(1) // ignore the initial state
        .onEach { isActive -> // configure an action
            if (isActive) onStartBeingObserved() else onStopBeingObserved()
        }
        .launchIn(scope) // launch it
}
```

With these changes in place, the template's `App` composable is modified with the following lines to monitor the value of the ticker and display it on screen:

```kotlin
        val state = vm.state.collectAsState()
…
            Text("Counter ${state.value}")
```

**Affected platforms**
Select one of the platforms below:
- iOS
- Android

**Versions**
- Kotlin version: 1.9.20
- Compose Multiplatform version: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): iOS 15 simulator
- OS architecture (x86 or arm64): arm64

**To Reproduce**

With the changes mentioned above, which can be ([obtained here](https://github.com/gradha/compose-multiplatform-ios-android-template/pull/1/files?diff=unified&w=0)):

1. Run the android app on a simulator and wait until the ticker is seen on screen.
2. Click on the home button of the simulator and watch the android studio log output.
3. The ticker count keeps going on.

For the other platform:

1. Run the iOS app on a simulator and wait until the ticker is seen on screen.
2. Click on the home button of the simulator and watch the log output.
3. The ticker count freezes, it returns to count only when the app is opened again.

**Expected behavior**

Either both platforms keep the flow active when the app is in the background, or both platforms keep the flow inactive when the app is in the background.

**Additional context**

I discovered this discrepancy when I was looking for [implementations of collectAsStateWithLifecycle for iOS](https://slack-chats.kotlinlang.org/t/13222387/hey-guys-any-way-to-use-collectasstatewithlifecycle-on-compo). Funnily enough, for my particular use case I could implement the expect-actual pattern proposed in that slack chat, since then my android code would stop the flow, and iOS does this already.

But I'm raising this here because I'd like to know what the _correct_ behavior is. Would prefer if a future update didn't break my viewmodel logic.

**Comment by eymar** [comment] 2023-11-06 10:06
It's indeed related to https://github.com/JetBrains/compose-multiplatform/issues/3890, the cause is the same - different lifecycle in Compose for iOS that for Android.


> Click on the home button of the simulator and watch the android studio log output.
    The ticker count keeps going on.
   
Eventually Android might kill the Activity, the flow collection will stop anyway. The moment it happens can't be determined, therefore it's better to assume that the flow collection will stop too. 
___

https://developer.android.com/jetpack/compose/state#use-other-types-of-state-in-jetpack-compose
> Use collectAsState for platform-agnostic code instead of collectAsStateWithLifecycle, which is Android-only.

I'm not sure that collectAsState behaviour can be 100% aligned for all platforms even after we manage to improve the Lifecycle issues. It's likely that  `collectAsState` behaviour will change on iOS then, but it doesn't mean it's going to be consistent with Android. 
I guess something like `collectAsStateWithLifecycle` will be needed for iOS too.

**Comment by okushnikov** [comment] 2024-08-26 14:35
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3889">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:08 UTC
Labels: bug, ios
