### ISSUE TITLE
Not filled spaceline on right side in Window with wrap content on Linux

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-multiplatform#2706] opened 2023-02-06 14:56 UTC
Compose version: 1.3.0
Kotlin version: 1.8.0
OS: 6.1.9-1-MANJARO
GUI: Gnome with XORG
![image](https://user-images.githubusercontent.com/63443274/217004118-6c506e80-3544-465c-ba90-f13e88c6ec83.png)

**Comment by eymar** [comment] 2023-02-06 15:36
What's is the code of `Keyboard`?

I'm wondering how this code would behave for you:

```kotlin
fun main() = application {
    val windowState = rememberWindowState(size = DpSize.Unspecified)
    Window(onCloseRequest = ::exitApplication,
        state = windowState
    ) {
        Surface {
            Surface {
                Column {
                    Box(modifier = Modifier.background(Color.DarkGray).size(300.dp)) {
                        Text("BOX", modifier = Modifier.align(Alignment.Center))
                    }
                }
            }
        }
    }
}
```

**Comment by GazimSoliev** [comment] 2023-02-06 22:52
Keyboard is buttons of calculator

I added your code and got it:
![image](https://user-images.githubusercontent.com/63443274/217105372-3e3e7c5e-6b8b-4e8d-9521-51bd3e1b2318.png)

I added resizeble and got correctly result:

**Comment by terrakok** [comment] 2024-04-18 09:37
Is it valid yet? I couldn't reproduce it

**Comment by okushnikov** [comment] 2024-07-14 15:05
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2706">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:49 UTC
Labels: desktop
