### ISSUE TITLE
Tray menus not working on Fedora

### ISSUE THREAD

**Issue by elect86** [JetBrains/compose-multiplatform#4614] opened 2024-04-14 16:58 UTC
**Describe the bug**
[easnx](https://github.com/elect86/easnx) isn't working properly under Fedora 39, KDE 5.115.0, Qt 5.15.12 with Wayland, according to one user

**Affected platforms**
- Desktop (Linux)

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues):  39
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): java-17-openjdk

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. clone the project
2. `./gradlew run`
3. wait for the icon tray to appear and try to call the menu with the right button

**Expected behavior**
The menus shall open

**Screenshots**
Unfortunately I cant screenshot because it's outside the screenshottable area

**Additional context**
I'm willing to implement whatever trick/workaround you may have in mind

**Comment by elect86** [comment] 2024-04-16 12:21
Sure, https://github.com/elect86/easnx

Right click on the tray icon shall open a menu

**Comment by m-sasha** [comment] 2024-04-18 10:04
1. We'd rather not clone 3rd-party projects to reproduce bugs. It's a security hazard.
2. Often, while trying to create a reproducer you discover why the problem was occurring, and sometimes it's not a bug in Compose.

**Comment by okushnikov** [comment] 2024-08-26 13:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4614">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:49 UTC
Labels: bug, linux, window management
