### ISSUE TITLE
Cursor is not visble in JS `TextField`

### ISSUE THREAD

**Issue by sproctor** [JetBrains/compose-multiplatform#4072] opened 2023-12-26 18:20 UTC
**Describe the bug**
Cursor doesn't display in `TextField` in JS. Same code works fine on desktop and Android.

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 22.04
- OS architecture (x86 or arm64): amd64
- Browser: Firefox 121.0 and Chrome 120.0

**To Reproduce**
https://github.com/sproctor/CrewPicker/

- Launch the app: `./gradlew :web:jsBrowserDevelopmentRun`
- Click on the text field
- Notice that there is no cursor

**Expected behavior**
I expect the cursor to show when the `TextField` is focused.

**Comment by dima-avdeev-jb** [comment] 2023-12-27 06:28
I think it should be fixed in newest dev version.
can you please try to use Compose 1.6.0-dev1350

**Comment by eymar** [comment] 2024-01-02 15:01
It's a duplicate of https://github.com/JetBrains/compose-multiplatform/issues/3120

The fix was implemented in skiko. As I see skiko version was not updated yet in Compose Multiplatform, therefore the fix is not yet available in the dev builds.

**Comment by eymar** [comment] 2024-04-24 10:58
Closing as fixed in https://github.com/JetBrains/skiko/pull/846

**Closed by eymar** 2024-04-24 10:58 UTC
Labels: bug, wait for reply, web

**Comment by okushnikov** [comment] 2024-08-26 13:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4072">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
