### ISSUE TITLE
graphicsLayer render resolution slower towards bottom of screen

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#4998] opened 2024-06-19 18:14 UTC
**Describe the bug**

When using `graphicsLayer` (or `clip`, which uses `graphicsLayer`) the shape is rendered with a lower resolution as it moves down the screen. In other words, if you have a column of the same shape drawn the same way from the top to the bottom of the screen, the shape is rendered perfectly smooth at the top of the screen and very pixelated at the bottom.

**Affected platforms**
Desktop (macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11
- Kotlin version:  2.0.0-RC1
- OS version(s) (required for Desktop and iOS issues): MacOS 14.5
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues):  20

**To Reproduce**

```kotlin
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.GenericShape
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

fun main() {
    val triangle =
        GenericShape { size, _ ->
            moveTo(
                x = 0f,
                y = 0f
            )
            lineTo(
                x = size.width,
                y = size.height / 2
            )
            lineTo(
                x = 0f,
                y = size.height
            )
            close()
        }
    application {
        Window(onCloseRequest = ::exitApplication) {
            Row {
                Column {
                    repeat(100) {
                        Box(
                            modifier =
                                Modifier
                                    .clip(triangle)
                                    .background(Color.Black)
                                    .size(25.dp)
                        )
                    }
                }
            }
        }
    }
}
```

**Expected behavior**

Resolution should not change relative to the y value within a single screen.

**Screenshots**

This image was taken on a vertical 4k monitor. The code is above, in the reproduction section.
<img width="1437" alt="Screenshot 2024-06-19 at 2 09 10 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/12831489/b5c68de5-9a15-40e6-9159-cb90d40ff974">

**Comment by MatkovIvan** [comment] 2024-08-15 08:36
The cause of the issue is not clear, it requires more detailed investigation.

For the moving to YT - it's kind of in progress (script issues + delays because of vacations), all the issues will be moved

**Comment by okushnikov** [comment] 2024-08-26 13:24
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4998">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:26 UTC
Labels: bug, rendering, skiko
