### ISSUE TITLE
Nested IntrinsicSize Layout not react on changes of inner Text / TextButton childs

### ISSUE THREAD

**Issue by fyam1997** [JetBrains/compose-multiplatform#881] opened 2021-07-13 08:29 UTC
compose desktop version: 0.5.0-build235

Here is an example to reproduce the issue
``` kotlin
fun main() = Window {
    expandable("1") {
        expandable("2") {
            Text("end")
        }
        expandable("3") {
            Text("end")
        }
    }
}

@Composable
private fun expandable(
    name: String,
    content: @Composable () -> Unit
) {
    var expanded: Boolean by remember { mutableStateOf(false) }
    Column {
        TextButton(
            onClick = { expanded = !expanded },
            content = { Text("${if (expanded) "-" else "+"}$name") }
        )
        if (expanded)
            Row(Modifier.height(IntrinsicSize.Min).onSizeChanged {
                println("$name-[$it]")
            }) {
                Box(Modifier.padding(horizontal = 8.dp).fillMaxHeight().width(2.dp).background(Color.Gray))
                Column { content() }
            }
    }
}

```
<img width="83" alt="Screenshot 2021-07-13 at 4 10 30 PM" src="https://user-images.githubusercontent.com/43132422/125415965-734c923a-a283-45e2-9f4a-31dc0d6b90c8.png">

when the expandable view with "3"(bottom one) is clicked, the content "end" won't be shown. But when I do something to recompose the screen, like resize the window, contents then shown correctly.
I haved tried to log the size change of the layout with IntrinsicSize, the bottom expandable have 0-height when first expanded, and have normal size after manually resize.

This Issue seems only happen to `Text / TextButton`, if replace the `Text / TextButton` with a `Button`, the content will be shown correctly without manually refresh the screen.
This behaviour is the same in android

**Comment by akurasov** [comment] 2021-07-14 09:48
Played with it a bit. 
If height is set explicitly for the top-level expandable, the issue doesn't exist. Looks like top expandable doesn't change it's height when Text is added to the inner expandable

For height log:
when top level is expanded:
1-[164 x 144]

when inner level is expanded:
3-[83 x 0]
top-level is not resized. 

after window resize that forces recomposition (both rows resized)
3-[83 x 28]
1-[164 x 172]

**Comment by akurasov** [comment] 2021-07-19 13:50
2check on Android

**Comment by JoeSteven** [comment] 2021-12-17 12:10
Facing the same issue here, Unexpected behavior when click IconButton:
```kotlin
    val expanded = remember { mutableStateOf(false) }
    Row(modifier = Modifier.height(IntrinsicSize.Min)) {
        Column(modifier = Modifier.fillMaxHeight(), horizontalAlignment = Alignment.CenterHorizontally) {
            Text("Hello")
            Box(modifier = Modifier.weight(1f).width(1.dp).background(color = Color.Black))
        }
        Spacer(modifier = Modifier.width(10.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text("Header")
            IconButton(onClick = {
                expanded.value = !expanded.value
            }) {
                Icon(
                    painter = painterResource(res = MR.files.ic_expand_more),
                    contentDescription = null,
                    modifier = Modifier.width(24.dp).height(24.dp)
                )
            }
            Button(onClick = {
                expanded.value = !expanded.value
            }) {
                Text("Expand")
            }
            if (expanded.value) {
                Text("expanded text")
            }
            Text("Footer")
        }
    }
```
![gWFkGj8Dn0](https://user-images.githubusercontent.com/16322233/146534840-99dab01e-5cab-4a5c-87ce-96b29cc15ba3.gif)

And I found a another problem ,  footer won't be shown if there is a Icon placed in Column with unspecified size:

```Kotlin
    Row(modifier = Modifier.height(IntrinsicSize.Min)) {
        Column(modifier = Modifier.fillMaxHeight(), horizontalAlignment = Alignment.CenterHorizontally) {
            Text("Hello")
            Box(modifier = Modifier.weight(1f).width(1.dp).background(color = Color.Black))
        }
        Spacer(modifier = Modifier.width(10.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text("Header")
            Icon(
                painter = painterResource(res = MR.files.ic_expand_more),
                contentDescription = null,
                tint = MaterialTheme.colors.primary,
            )
            Text("Footer")
        }
    }
```
![51639739167_ pic](https://user-images.githubusercontent.com/16322233/146541725-a271ffca-13cc-47cb-8a68-6d432d12d8e2.jpg)

Footer will display as expected if `Modifier.size(24.dp)` is set to Icon, I'm not sure if this is  a bug or  I have to specify the size of the icon

![61639742505_ pic](https://user-images.githubusercontent.com/16322233/146541980-91eb4329-cf75-47eb-8484-a2d1975c1684.jpg)

**Comment by okushnikov** [comment] 2024-07-14 17:03
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5356">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:39 UTC
Labels: bug, desktop
