### ISSUE TITLE
Reduce ios app size.

### ISSUE THREAD

**Issue by begali** [JetBrains/compose-multiplatform#4855] opened 2024-05-23 06:30 UTC
I created KMP + compose multiplatform (android and ios) using [this](https://kmp.jetbrains.com/) site and run for ios simulator from android studio. The app size for ios simulator are: debug version 40.5mb and release version 50.8mb. By the way I selected debug and release versions from android studio by editing device configurations and din't add any libraries. If I create KMP project without CM, then app size for ios is 1.7mb. How can we reduce app size for compose multipatform. What is the skia/skiko library size bundled with ios framework?

**Comment by hellomr3** [comment] 2024-05-23 09:53
face same probleam! my release ios app is 13mb+

**Comment by brewin** [comment] 2024-05-23 16:45
There's an `optimized` property that reduces the app size. I don't know exactly what it does though and I've never found any documentation for it. I'm not sure if it's safe to use.
```Kotlin
kotlin {
    iosArm64 {
        binaries{
            framework { 
                optimized = true
            }
        }
    }
}
```
or
```Kotlin
kotlin {
    cocoapods {
        framework {
            optimized = true
        }
    }
}
```

**Comment by Thomas-Vos** [comment] 2024-05-25 20:02
Release builds are already optimized so no need for that option

**Comment by Thomas-Vos** [comment] 2024-05-25 20:04
iOS apps being about 10x as large as Android apps is quite normal. Just take a look at other (popular) iOS apps on the App Store. Personally I do not see current app sizes as an issue at all.

**Comment by MatkovIvan** [comment] 2024-05-27 10:51
It seems as a duplicate of #3632

**Closed by MatkovIvan** 2024-05-27 10:51 UTC
Labels: enhancement, ios

**Comment by okushnikov** [comment] 2024-08-26 13:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4855">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
