### ISSUE TITLE
Desktop app for Mac crash when running packaged app 

### ISSUE THREAD

**Issue by imptah** [JetBrains/compose-multiplatform#904] opened 2021-07-19 12:18 UTC
I made Compose Desktop application, but it keeps immediately closing after startup of the App inside dmg.
`runDistributable` - successfully run the App.

I've tried to run it from Terminal:
` ./MyApp.app/Contents/MacOS/MyApp` and it shows error: 
`"Error opening "/PathToApp/MyApp.app/Contents/Contents/app/MyApp.cfg" file: No such file or directory"` - I was surprised by the duplication of Contents directory.

When I moved `MyApp.app/Contents/MacOS/MyApp` to `MyApp.app/Contents/MyApp` and run it from Terminal - it successfully started.

I am using:
* compose 0.4.0
* kotlin 1.5.10
* java 15.0.2

**Comment by AlexeyTsvetkov** [comment] 2021-07-19 14:04
@imptah can you share a sample reproducible project?

**Comment by akurasov** [comment] 2021-07-23 05:20
[ComposeBug.zip](https://github.com/JetBrains/compose-jb/files/6866699/ComposeBug.zip)
Here is reproducer from https://github.com/JetBrains/compose-jb/issues/928 (looks like the same issue)

**Comment by imptah** [comment] 2021-07-29 00:17
> @imptah can you share a sample reproducible project?

Sorry for the long reply. I have figured out the issue. It was related to the creation of the new files inside the packaged App. After switching off logging and making the database work in memory, the App successfully started. 

Here is the sample that reproduces it. It's just a template App with the creation of a File in `fun main()`. If you run packaged App in .dmg, it will close immediately. If you do `runDistributable`, it will create the file and run the App.

Maybe it is somehow related to the permissions inside the MacOS ecosystem? Do you have any ideas on how it can be fixed?

[Uploading NewFileError.zip…]()

**Comment by imptah** [comment] 2021-08-15 11:08
Reproduced with v1.0.0-alpha3 as well

**Comment by anikrajc** [comment] 2023-03-05 18:54
Issue still exists with 1.3.0. Mostly related to Mac Permissions

**Comment by Kevin-Case** [comment] 2023-04-18 09:45
As @anikrajc mentioned. The issue still exists.

I'm using SqlDelight with KMM project. The packaged app fails when start the application from generated *.app file (packageDMG). But if I start the app from Contents/MacOs/ it works. If I configure SqlDelight to use IN_MEMORY it works fine. It seems an issue with write permissions of the starting process.

**Comment by okushnikov** [comment] 2024-07-14 16:18
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5341">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:27 UTC
Labels: native distribution
