### ISSUE TITLE
[Desktop] Scrolling stops working when movableContentOf switches

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#2696] opened 2023-02-04 13:31 UTC
Compose: `1.3.0`
Kotlin: `1.8.0`

Scrollable content inside `movableContentOf` stops scrolling when `movableContentOf` switches. E.g. `Column(Modifier.verticalScroll(...))` can not be scrolled using mouse wheel or by dragging the scrollbar. `LazyColumn` scrolls fine via mouse wheel, but still doesn't scroll via scrollbar.

The reproducer below demonstrates the issue. Both sides are scrollable at the beginning, but scrolling stops working when the button is pressed.

Reproducer:

```kotlin
@Composable
fun Foo() {
    val child1: @Composable (Modifier) -> Unit = remember { movableContentOf { modifier -> MyScrollable(modifier) } }
    val child2: @Composable (Modifier) -> Unit = remember { movableContentOf { modifier -> MyScrollable(modifier) } }
    var isHorizontal by remember { mutableStateOf(true) }

    Column(modifier = Modifier.fillMaxSize()) {
        val modifier = Modifier.fillMaxWidth().weight(1F)
        if (isHorizontal) {
            Row(modifier = modifier) {
                child1(Modifier.weight(1F))
                Divider(modifier = Modifier.fillMaxHeight().width(1.dp))
                child2(Modifier.weight(1F))
            }
        } else {
            Column(modifier = modifier) {
                child1(Modifier.weight(1F))
                Divider(modifier = Modifier.fillMaxWidth().height(1.dp))
                child2(Modifier.weight(1F))
            }
        }

        Button(onClick = { isHorizontal = !isHorizontal }) {
            Text("Switch")
        }
    }
}

@Composable
fun MyScrollable(modifier: Modifier = Modifier) {
    Box(modifier = modifier) {
        val state = rememberScrollState(0)

        // LazyColumn is also affected
        Column(modifier = Modifier.fillMaxSize().verticalScroll(state)) {
            (0..100).forEach { x ->
                Text(text = "Item #$x", modifier = Modifier.padding(16.dp))
            }
        }

        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
            adapter = rememberScrollbarAdapter(
                scrollState = state,
            )
        )
    }
}
```

**Comment by yangwulang** [comment] 2023-02-04 14:46
It's not just the scroll bar that has problems. I found that the split panel is invalid

**Comment by yangwulang** [comment] 2023-02-04 14:50
I use the replaceCurrent method of StackNavigation

**Comment by arkivanov** [comment] 2023-02-04 17:36
It appears that `LayoutModifier` and `MeasurePolicy` (if used inside `movableContentOf`) stop being triggered on captured state change, once `movableContentOf` switches first time. This is reproducible on desktop but not on Android.

```kotlin
@Composable
fun Sample(modifier: Modifier) {
    var offsetY by remember { mutableStateOf(0) }

    LaunchedEffect(Unit) {
        while (isActive) {
            delay(100L)
            offsetY += 10
        }
    }

    Layout(
        modifier = modifier,
        content = { Text("Text") }
    ) { measurables, constraints ->
        println("1") // This is not printed after movableContentOf switches

        val placeables = measurables.map { it.measure(constraints) }

        layout(constraints.maxWidth, constraints.maxHeight) {
            println("2") // This is not printed after movableContentOf switches
            placeables.forEach {
                it.placeRelative(x = 0, y = 0)
            }
        }
    }
}
```

**Comment by arkivanov** [comment] 2023-02-04 17:51
The only workaround I could find is to downgrade Compose to either `1.2.2` or `1.3.0-alpha01-dev831`. The issue is reproducible on desktop since `1.3.0-alpha01-dev849`, and is not reproducible on Android.

**Comment by eymar** [comment] 2023-02-06 14:22
reproduced: it was indeed introduced in a commit with rebasing on the upstream 1.3 tree.

**Comment by felixdivo** [comment] 2023-02-18 16:16
Is there any progress on this/Is it scheduled for the next milestone? It currently blocks my application from moving to compose-jb `1.3.0` / Kotlin `1.8.0`.

**Comment by ScottPierce** [comment] 2023-02-20 02:27
My team is seeing this as well. We've done most of the work to upgrade to 1.3.0/1.8.0 and now we're blocked by this, and our code is forced to sit.

I'm surprised such a glaring UI issue for Desktop was reported, and reproduced 2 weeks ago, and there isn't a fix out for it yet.

**Comment by arkivanov** [comment] 2023-02-20 18:26
As a workaround, it should be possible to use older version of Compose (1.2.2 or 1.3.0-alpha01-dev831) and update Kotlin to 1.8.0. See the [docs](https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#using-the-latest-kotlin-version).

**Comment by eymar** [comment] 2023-02-21 17:34
Forcing compose runtime version to 1.2.2 should be enough to workaround (at least if a project is not targeting k/js, k/native).

Something like:

```kotlin
project.configurations.all {
            val conf = it
            conf.resolutionStrategy.eachDependency {
                if (it.requested.module.group == "org.jetbrains.compose.runtime") {
                    it.useVersion("1.2.2")
                }
            }
```

**Comment by arkivanov** [comment] 2023-02-25 10:07
Seems like fixed in version `1.3.1-rc01`. Thank you!

**Comment by felixdivo** [comment] 2023-03-13 10:08
Since [1.3.1](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.3.1) is out now, I guess this can be closed?

**Comment by eymar** [comment] 2023-04-24 14:00
Fixed. Closing

**Closed by eymar** 2023-04-24 14:00 UTC
Labels: desktop, p:critical, wait for build, regression, reproduced

**Comment by okushnikov** [comment] 2024-07-14 16:18
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2696">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
