### ISSUE TITLE
Forced to add compose runtime to jvmMain when using compose + ktor

### ISSUE THREAD

**Issue by tom-pratt** [JetBrains/compose-multiplatform#1568] opened 2021-12-09 20:41 UTC
The `compileKotlinJvm` task fails with: 

`androidx.compose.compiler.plugins.kotlin.IncompatibleComposeRuntimeVersionException: The Compose Compiler requires the Compose Runtime to be on the class path, but none could be found. The compose compiler plugin you are using (version 1.1.0-beta01) expects a minimum runtime version of 1.0.0.`

Unless I add `implementation(compose.runtime)` to `jvmMain.dependencies`

But this feels weird since I'm only using compose for the js target.

**Comment by akurasov** [comment] 2021-12-10 10:16
Could you share you project? It looks like you also have jvm target in your mpp module.

**Comment by tom-pratt** [comment] 2021-12-13 11:05
[web.zip](https://github.com/JetBrains/compose-jb/files/7703209/web.zip)

Theres a comment above the line including compose.runtime in jvm. If you comment out that line then the errors occurs.

**Comment by akurasov** [comment] 2021-12-14 10:24
The issue is that you have single module project and this module contains both server and Js code. You use Compose plugin in this module, so it is used for all sourceSets. Compose plugin forces usage of Compose Compiler plugin, that checks compose runtime presence. So your build scripts uses Compose for server side. 

I would suggest to separate Server and JS code into separate modules.

**Comment by tom-pratt** [comment] 2021-12-16 18:35
Ok that makes sense. Although that is the project structure provided in the official sample project for frontend/backend kotlin! Are there any examples using separate modules that you can link to? I suppose you need a third library module to share the reusable parts between front and backend.

https://play.kotlinlang.org/hands-on/Full%20Stack%20Web%20App%20with%20Kotlin%20Multiplatform

**Comment by akurasov** [comment] 2021-12-20 15:55
@Artrosis have you split the code into two modules?

**Comment by Artrosis** [comment] 2021-12-21 08:11
@akurasov No, I added "implementation(compose.runtime)". I have little experience to do this on my own. I have a Spring project that depends on the build artifacts of a Compose for web project. I would like to have an example application with different Spring and compose for web modules.

**Comment by akurasov** [comment] 2021-12-21 11:48
>I would like to have an example application with different Spring and compose for web modules.

There is no such at the moment, but probably we should create one.

**Comment by markusressel** [comment] 2023-01-22 20:51
Hey there, I am facing the same issue. Any plan on creating a multi-module project example like mentioned above?
Is there maybe an existing project on GitHub I can check out?

**Comment by a-blekot** [comment] 2023-01-26 10:27
I'm also struggling to make it work. I've managed to split demo project into three modules common, server (ktor) and web: [https://github.com/a-blekot/jvm-js-fullstack](https://github.com/a-blekot/jvm-js-fullstack)  (main branch)

But applications run independently on different ports

server: localhost:8080   (:server:run)
web: localhost:8081   (:web:jsBrowserDevelopmentRun)

And I can't register task in the server module to copy webpack output from :web to :server. **:web:jsBrowserDevelopmentWebpack**
Please help))

**Comment by dima-avdeev-jb** [comment] 2023-01-26 15:26
@a-blekot 
Hello!
Your project page is not available (https://github.com/a-blekot/jvm-js-fullstack)
Can you open your repository or make reproducible sample without security sensitive code?

**Comment by a-blekot** [comment] 2023-01-26 16:14
@dima-avdeev-jb 
Oh, sorry, I didn't notice that it is private.
I will update it tomorrow morning cause I'm writing from mobile now)

**Comment by a-blekot** [comment] 2023-01-26 16:14
@dima-avdeev-jb 
Oh, sorry, I didn't notice that it is private.
> I will update it tomorrow morning cause I'm writing from mobile now)

**Comment by a-blekot** [comment] 2023-01-26 20:10
@dima-avdeev-jb
done, now it's public
[https://github.com/a-blekot/jvm-js-fullstack](https://github.com/a-blekot/jvm-js-fullstack)

**Comment by dima-avdeev-jb** [comment] 2023-01-26 22:22
@a-blekot Done in this PR:
https://github.com/a-blekot/jvm-js-fullstack/pull/1

**Comment by a-blekot** [comment] 2023-01-27 15:22
@dima-avdeev-jb 
Thank you!! It works perfectly now 🥳

**Comment by dima-avdeev-jb** [comment] 2024-01-24 18:01
@mgroth0 You can create a new Issue for your suggestion as a **enhancment**

**Comment by okushnikov** [comment] 2024-08-26 15:43
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6019">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:22 UTC
Labels: documentation, wait for reply, question, desktop
