### ISSUE TITLE
[IOS] Error after upgrading to Compose Multiplatform 1.6.0: Missing org.jetbrains.skiko:skiko-cinterop-uikit dependency

### ISSUE THREAD

**Issue by dan15d** [JetBrains/compose-multiplatform#4430] opened 2024-03-05 09:13 UTC
Hello,

After updating my project to Compose Multiplatform version 1.6.0, I encountered the following compilation error:

Could not find "org.jetbrains.skiko:skiko-cinterop-uikit" in [/Users/---/Documents/git/---, /Users/---/.konan/klib, /Users/---/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/common, /Users/---/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/platform/ios_simulator_arm64].

This issue is preventing me from compiling my project for iOS after the update (in 1.5.22 its okay). Is there a known solution to this problem, or are there any additional steps required to properly include this dependency?

I don`t have any reference to skiko in my code.

**Comment by igordmn** [comment] 2024-03-07 21:56
Could you provide a project where you have this?

It may be caused by some dependency that depends on an old Compose.

**Comment by okushnikov** [comment] 2024-07-14 15:07
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4430">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:20 UTC
Labels: bug, wait for reply
