### ISSUE TITLE
Focus the first item at the start

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4917] opened 2024-06-03 09:26 UTC
When we:
- start a window, a dialog or popup, focus the first.
- call `focusManager.clearFocus`
we should focus the first focusable node, otherwise remove the focus completely (the root node focusState = Inactive). In Compose 1.6.10 we always focus the root node on non-Android platforms.

A relevant change in Jetpack Compose was in https://android-review.googlesource.com/c/platform/frameworks/support/+/2813125

**Comment by m-sasha** [comment] 2024-06-03 09:31
Welcome change, but it is a breaking one...

**Comment by igordmn** [comment] 2024-06-03 09:31
>Welcome change, but it is a breaking one...

This happened in Jetpack Compose 1.7 as well with TextField

**Comment by igordmn** [comment] 2024-06-03 12:53
After https://github.com/JetBrains/compose-multiplatform-core/pull/1352, it already works for `ComposePanel`

**Comment by m-sasha** [comment] 2024-06-03 13:27
Right, but there one could think of it as making `ComposePanel` behave as a proper Swing widget, where initial selection is the norm.

**Comment by igordmn** [comment] 2024-06-07 08:58
> This happened in Jetpack Compose 1.7 with TextField as well

Seems like it happens only when we use physical keyboard. Probably it wasn't intentional

**Comment by iamcalledrob** [comment] 2024-06-17 10:04
+1 on this, just ran into this and was about to report as a bug.

Discovered when `onPreviewKeyEvent` wasn't initially working within my window.

**Comment by iamcalledrob** [comment] 2024-07-04 14:58
I'd like to bump to the priority of this.

It appears, in my testing, that it's *impossible* to receive keyboard events reliably in Compose Desktop, because if `FocusManager.clearFocus` is ever called, no further key events will ever be received by any composable.

I might be missing something, but if true, this is a huge issue. I just want `Esc` to close my window, but can't implement it reliably if `clearFocus` is called anywhere in my codebase.

**Comment by igordmn** [comment] 2024-07-04 15:28
Your issue is solvable using https://github.com/JetBrains/compose-multiplatform/issues/4764#issue-2280501620 (answered in [Slack](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1720105859457259?thread_ts=1720104779.195739&cid=C01D6HTPATV))

This enhancement won't solve it, as if there is no focusable elements, there will be no focus.

**Comment by iamcalledrob** [comment] 2024-07-14 09:10
Agreed.

The challenge with hooking in to this at the Window level is implementing hotkeys adds tight coupling between window code and the screen-level code, which I try and keep separate.

It's also arguably an unexpected behaviour, which means it'll be a source of bugs. I know it was for me.

This is mentioned in the second bullet point in #4764, but just echoing here to give it a +1

**Comment by okushnikov** [comment] 2024-08-23 13:41
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4917">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:33 UTC
Labels: enhancement, p:high, focus management
