### ISSUE TITLE
support touchpad horizontal scroll event

### ISSUE THREAD

**Issue by mbunderline76** [JetBrains/compose-multiplatform#2956] opened 2023-04-02 22:35 UTC
Hi, I really need to can detect horizontal scroll event.
`.onPointerEvent(PointerEventType.Scroll)`  just detects verticall scrolls!

**Comment by AlexeyTsvetkov** [comment] 2023-04-03 14:45
I could not reproduce the issue with the following snippet with Compose for Desktop 1.3.0:
```
@file:OptIn(ExperimentalComposeUiApi::class)

import androidx.compose.material.MaterialTheme
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.foundation.HorizontalScrollbar
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.onPointerEvent
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
@Preview
fun App() {
    var text by remember { mutableStateOf("") }
    var eventNum by remember { mutableStateOf(0) }

    MaterialTheme {
        Column {
            Row {
                Text(text)
            }
            LazyRow(Modifier.onPointerEvent(PointerEventType.Scroll) {
                eventNum++
                text = "Horizontal scroll $eventNum"
            }) {
                items(100) { Text("Item #$it ") }
            }
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

@mbunderline76 could you provide more details?
What version of Compose do you use?
Which target platform is affected?
What is the OS?
If possible, please provide an example snippet.

**Comment by mbunderline76** [comment] 2023-04-03 18:56
@AlexeyTsvetkov 
Hi and thank you for your reply.
Im developing a custom component from scratch and i cant use LazyRow.
What i need is to detect touchpad events.
And turns out i can produce that behaviour with Shift + vertical scroll but that's a bad experience for my product

**Comment by AlexeyTsvetkov** [comment] 2023-04-03 19:25
@mbunderline76 how exactly do you use `onPointerEvent` data? I just tried it on a normal `Row` and a `Surface`, and scroll is still registers

**Comment by mbunderline76** [comment] 2023-04-03 19:30
@AlexeyTsvetkov 
Please read this question

https://stackoverflow.com/questions/75772483/compose-desktop-cant-detect-horizontal-scrolling/75800018#75800018

**Comment by AlexeyTsvetkov** [comment] 2023-04-03 20:35
I still can't reproduce the issue.
In my case horizontal scroll events work on `Surface` just fine without `Shift`.
Here is the code I'm using:
```
import androidx.compose.material.MaterialTheme
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawWithContent
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.onPointerEvent
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
@Composable
@Preview
fun App() {
    var eventNum by remember { mutableStateOf(0) }
    var xDelta by remember { mutableStateOf(0f) }
    var yDelta by remember { mutableStateOf(0f) }

    MaterialTheme {
        Column(Modifier.padding(5.dp)) {
            Text("Number of scroll events: $eventNum")
            Text("x scroll offset: $xDelta")
            Text("y scroll offset: $yDelta")

            Row {
                val size = 300.dp
                val surfaceModifierBase = Modifier.size(size).border(1.dp, Color.Black)
                Surface(surfaceModifierBase.onPointerEvent(PointerEventType.Scroll) {
                    val scrollDelta = it.changes.fold(Offset.Zero) { acc, c -> acc + c.scrollDelta }
                    val halfSizePx = size.toPx() / 2
                    xDelta = (xDelta + scrollDelta.x).coerceIn(-halfSizePx, halfSizePx)
                    yDelta = (yDelta + scrollDelta.y).coerceIn(-halfSizePx, halfSizePx)
                    eventNum++
                }) {
                    Box {
                        Text("Scroll here", modifier = Modifier.align(Alignment.Center))
                    }
                }

                Spacer(Modifier.size(10.dp))

                Surface(surfaceModifierBase.drawWithContent {
                    val maxSizePx = size.toPx()
                    val centerOffsetPx = maxSizePx / 2
                    val xOffset = (centerOffsetPx + xDelta)
                    val yOffset = centerOffsetPx + yDelta

                    drawLine(Color.DarkGray, start = Offset(xOffset, 0f), end = Offset(xOffset, maxSizePx), strokeWidth = 4f)
                    drawLine(Color.DarkGray, start = Offset(0f, yOffset), end = Offset(maxSizePx, yOffset), strokeWidth = 4f)
                    drawCircle(Color.Red, center = Offset(xOffset, yOffset), radius = 5f)
                }) {
                    Box {
                        Text("Scroll here", modifier = Modifier.align(Alignment.Center))
                    }
                }
            }

        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

Can you try it on your system?
Here's how it looks on my machine (I'm scrolling using touchpad without shift):
https://user-images.githubusercontent.com/654232/229620869-9bebe62a-2dac-41b6-9005-f0a5218e82d8.mov

**Comment by mbunderline76** [comment] 2023-04-03 21:46
here is the result of your code on my machine
horizontal scroll worked but while i pressed shift.

[Screencast from 04-04-2023 01:13:32 AM.webm](https://user-images.githubusercontent.com/95180357/229634321-48f90852-6ffc-4e71-a01a-a48ee14ad413.webm)

**Comment by AlexeyTsvetkov** [comment] 2023-04-04 02:40
Duplicate of #2528

**Comment by AlexeyTsvetkov** [comment] 2023-04-04 02:42
@mbunderline76 I'm closing this issue as a duplicate of #2528

**Closed by AlexeyTsvetkov** 2023-04-04 02:42 UTC
Labels: enhancement, wait for reply

**Comment by okushnikov** [comment] 2024-08-26 14:44
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2956">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
