### ISSUE TITLE
iOS: Font should default to SF Pro

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#3173] opened 2023-05-16 12:40 UTC
https://developer.apple.com/design/human-interface-guidelines/typography#Using-system-fonts

**Comment by MatkovIvan** [comment] 2023-05-16 15:41
Duplicate of #2874

**Comment by MatkovIvan** [comment] 2023-05-16 15:46
It should be fixed in last dev build, please re-open if something still goes wrong here

**Closed by MatkovIvan** 2023-05-16 15:46 UTC
Labels: enhancement, ios, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:17
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3173">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
