### ISSUE TITLE
LocalInspectionMode.current cannot get true in preview mode

### ISSUE THREAD

**Issue by ancircle0** [JetBrains/compose-multiplatform#2852] opened 2023-03-09 08:21 UTC
**Describe the bug**
LocalInspectionMode.current in preview mode is not true ,but return true in jetpack compose preview mode.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.7.10
- Compose Multiplatform version*: 1.2.0
- OS version(s)* (required for Desktop and iOS issues):  Windows Professional edition
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues):
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
No repeat step is required

**Expected behavior**
LocalInspectionMode.current can return true in preview mode

**Screenshots**
![R(OG1M$JI%M100KXBS9RL}I](https://user-images.githubusercontent.com/10388557/223962410-d496d7e8-200b-40bf-87c8-97bb6dff2360.png)

**Additional context**
Nothing

**Comment by m-sasha** [comment] 2023-03-09 20:28
Thanks, we'll take a look at it.

**Comment by alexfacciorusso** [comment] 2023-11-02 18:52
Is this going to be picked up?

**Comment by alexfacciorusso** [comment] 2023-11-03 12:27
I am looking at the compose-multiplatform code to check if there is anything that can be done from within the repo, but the clues bring to [androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-tooling/src/desktopMain/kotlin/androidx/compose/desktop/ui/tooling/preview/runtime/NonInteractivePreviewFacade.kt;l=46?q=androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade) which uses a `TestComposeWindow` to render the composable and expose it as a window.

Now, a quick fix in that code would be from 

            window.setContent @Composable {
                // We need to delay the reflection instantiation of the class until we are in the
                // composable to ensure all the right initialization has happened and the Composable
                // class loads correctly.
                androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(
                    className,
                    methodName,
                    currentComposer
                )
            }

to something like

            window.setContent @Composable {
                // We need to delay the reflection instantiation of the class until we are in the
                // composable to ensure all the right initialization has happened and the Composable
                // class loads correctly.
                CompositionLocalProvider(LocalInspectionMode provides true) {
                  androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(
                      className,
                      methodName,
                      currentComposer
                  )
               )
            }

It may be a simplification (or maybe there is something else simpler that can be done) but yeah, it seems the issue is, as many times is, enclosed within the `androidx` monorepo.

This is quite an annoying bug as previews are not only not configurable for desktop, but within previews we cannot even know the view is indeed a preview and do something for that. 

Furthermore, there seems to be yet another bug (at least on Windows) where if the system is in dark mode, the preview composable will be rendered in dark mode, but **with a white background**. I will file a separate one for this after I confirm it with further tests from my side.

**Comment by chrisjenx** [comment] 2024-05-30 17:29
Just ran into this too. Probably an issue with the Preview plugin not treating jetbrains.preview the same.

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2852">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:40 UTC
Labels: bug
