### ISSUE TITLE
DatePicker is not rendering properly when inside a container with horizontal padding

### ISSUE THREAD

**Issue by RodrigoFerreira001** [JetBrains/compose-multiplatform#3554] opened 2023-08-23 04:12 UTC
**Describe the bug**
When a DatePicker is rendered inside a container, like a column, and this container has horizontal padding, the days are overlapping and it seems that the space of the composable it's not calculated properly.

**Affected platforms**
Select one of the platforms below:
- iOS
- Android

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta02
- OS version(s)* (required for Desktop and iOS issues): iOS 16.04, Android 13
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
 - Call the DatePicker composable inside a container with horizontal padding (24.dp for example)

**Expected behavior**
The DatePicker be rendered properly, without overlapping days

**Screenshots**
![AndroidScreenshot](https://github.com/JetBrains/compose-multiplatform/assets/6041505/168f6b4d-2bfc-4e65-9706-cefa4ac7c595)

![Simulator Screenshot - iPhone 14 - 2023-08-23 at 01 10 54](https://github.com/JetBrains/compose-multiplatform/assets/6041505/61382c93-84e1-4112-bd9a-701b3b68b7c4)

![AndroidLayoutBounds](https://github.com/JetBrains/compose-multiplatform/assets/6041505/bf40e752-b65c-47dc-b016-978be96712b6)

**Comment by Walingar** [comment] 2023-08-23 14:05
Hello @RodrigoFerreira001 thank you for such informative bug request! Since the issue is reproducible in Android as well, could you please file and issue in [Android bug tracker](https://source.android.com/docs/setup/contribute/report-bugs), and post the link here.
Thank you!

**Comment by okushnikov** [comment] 2024-07-14 16:13
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3554">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:16 UTC
Labels: bug, upstream (AOSP), android, reproduced
