### ISSUE TITLE
How do I add shadows to a window when its undecorated attribute was set to true? 

### ISSUE THREAD

**Issue by Adiudiu** [JetBrains/compose-multiplatform#3295] opened 2023-06-28 08:18 UTC

**Comment by TanotiCoder** [comment] 2023-06-29 19:08
add a simple text in the middle of a box that fillMaxSize

**Comment by Adiudiu** [comment] 2023-06-30 04:54
> add a simple text in the middle of a box that fillMaxSize

**Comment by AlexeyTsvetkov** [comment] 2023-07-03 19:50
@Adiudiu please provide more context:
* What is the expected result?
* What is the actual result?
* Your environment: kotlin version, compose version, jdk version, operating system name and its version?
* Add relevant screenshots & reproduction sample if possible.

**Comment by Raphael-N** [comment] 2023-08-07 21:36
Maybe I can add some more details since I'm facing the same issue. 

**Expected Result**
My use case is that I would like to build a Spotlight/[Alfred](https://www.alfredapp.com/)/[Raycast](https://www.raycast.com/) style input window. These are all undecorated but have an (OS made) DropShadow on MacOS. This behaviour would be the expected result.

**Actual Result**
I can build an undecorated window with transparent background that behaves in a similar way but it doesn't have a shadow which is a bit unusual on MacOS.

<img width="661" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/23119195/e159eef6-4c84-4846-981e-c2e34cdadf91">

**Environment**
I am working on Kotlin 1.9.0, compose version 1.4.3, jdk version 17.0.3.1, MacOS Ventura 13.5
 
**Additional Info**
It is actually not trivial to produce this behaviour with AppKit on MacOS. It can be achieved by leaving decorations on but then making the titlebar transparent, making the space of the titlebar space usable by the app and hiding the close, minimize and maximize buttons. With that, it looks something like this:

<img width="661" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/23119195/c8873fb0-63a8-4c2f-8d7f-57a26d02ee5d">

It would be great to have some more access to the detailed window behaviour in each operating system but I am not sure how and if this is achievable.

**Comment by mahozad** [comment] 2023-08-19 09:04
@Raphael-N I provided a solution for native shadows and animations for Windows:
- https://github.com/JetBrains/compose-multiplatform/issues/3388#issuecomment-1672732504

Maybe it will be handy for you as well.

**Comment by okushnikov** [comment] 2024-07-14 14:47
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3295">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:29 UTC
Labels: wait for reply, question, window management, undecorated window
