### ISSUE TITLE
Can I used algorithm triple des in compose mutilplatform ?

### ISSUE THREAD

**Issue by thanhhoai162963** [JetBrains/compose-multiplatform#4470] opened 2024-03-12 04:30 UTC
I try convert triple des from swift code to kotlin mutilplaform but result outputData?.base64EncodedStringWithOptions(options = 0uL = "SpE3b1aZ7MM=") wrong. 

In module iosMain:

`@Suppress("CAST_NEVER_SUCCEEDS")
fun String.nsdata(): NSData? {
    return (this as NSString).dataUsingEncoding(NSUTF8StringEncoding)
}

fun String.toUTF8String(): String {
    val bytes = this.toByteArray(Charsets.UTF_8)
    return bytes.decodeToString()
}

@OptIn(ExperimentalEncodingApi::class)
actual fun tripleDesEncryptString(input: String, keyRd: String): String? {
    val inputData = input.toUTF8String().nsdata()
    val keyData = keyRd.nsdata()
    val outLength = cValue<ULongVarOf<size_t>>()
    val outputData = NSMutableData.dataWithLength(inputData?.length?.plus(kCCBlockSize3DES) ?: 0uL)
    val outLength1 = cValue<size_tVar>()

    memScoped {
        val result = CCCrypt(
            op = kCCEncrypt,
            alg = kCCAlgorithm3DES,
            options = (kCCOptionPKCS7Padding or kCCOptionECBMode),
            key = keyData?.bytes,
            keyLength = keyData?.length ?: 0uL,
            iv = null,
            dataIn = inputData?.bytes,
            dataInLength = inputData?.length ?: 0uL,
            dataOut = outputData?.mutableBytes,
            dataOutAvailable = outputData?.length ?: 0uL,
            dataOutMoved = outLength1.ptr
        )

        if (result != kCCSuccess) {
            return null
        }
        outputData?.setLength(outLength1.size.toULong())
    }
    return outputData?.base64EncodedStringWithOptions(options = 0uL)
}
`
Has anyone ever come across this problem? Hoping for your help

**Comment by eymar** [comment] 2024-03-13 09:50
Unless I miss something, the problem is not really related to Compose Multiplatform. 
You likely need to carefully go through your code and check what parts get "translated" from swift to kotlin not properly.

For example I see:
```
@Suppress("CAST_NEVER_SUCCEEDS")
fun String.nsdata(): NSData? {
return (this as NSString).dataUsingEncoding(NSUTF8StringEncoding)
}
```
If you aim to have a multiplatform solution, then you can't use platform specific types. In this case it's NSData. 
Kotlin's ByteArray can be an alternative, I think.

If it's not common code, then casting String to NSString, afaik, is incorrect. IDE highlighted that issue, but you suppressed it for some reason - `@Suppress("CAST_NEVER_SUCCEEDS")`

**Comment by eymar** [comment] 2024-03-13 09:52
Closing this as unrelated to Compose Multiplatform.

**Closed by eymar** 2024-03-13 09:52 UTC
Labels: question

**Comment by okushnikov** [comment] 2024-08-26 13:45
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4470">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
