### ISSUE TITLE
Use HTML tag in Compose for web / Kotlin Wasm

### ISSUE THREAD

**Issue by sz21106677** [JetBrains/compose-multiplatform#3172] opened 2023-05-16 07:29 UTC
Is there any existing method to insert HTML native tags in Compose?

**Comment by alexzhirkevich** [comment] 2023-05-16 11:41
You probably can add html with absolute position and set their

**Comment by eymar** [comment] 2023-05-17 12:04
There is no such API out of a box for now.

**Comment by sc941737** [comment] 2023-09-08 01:02
> You probably can add html with absolute position next to the compose render canvas and set its position from compose wasm code

I've been doing this, works for me for now.

**Comment by usert-4** [comment] 2023-12-19 21:34
@sc941737  is this Compose kotlin/js or wasm ? it seem js, is there a way to render html in Compose web/wasm ?
mainly for example using js library as there is only kotlin multiplatform library that we can use on web, or wasm or other ?

**Comment by okushnikov** [comment] 2024-07-14 16:08
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3172">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:04 UTC
Labels: enhancement, to be considered, web

**Comment by Jacko760** [comment] 2024-10-24 17:21
Code Overview:

JS Main (main.kt):

fun main() {
    onWasmReady {
        CanvasBasedWindow("Compose Multiplatform") {
            App()
        }
    }
}

JS Main (platform.js.kt):

class JSPlatform: Platform {
    override val name: String = "compose web using Kotlin/JS"
}

actual fun getPlatform(): Platform = JSPlatform()

@Composable
actual fun PlatformSpecificContent() {
    val platform = getPlatform().name
    if (platform == "compose web using Kotlin/JS") {
        Row {
            IconButton(onClick = { /* Handle Home click */ }) {
                Icon(imageVector = Icons.Filled.Home, contentDescription = "Home", modifier = Modifier.size(24.dp))
            }
            IconButton(onClick = { /* Handle Favorite click */ }) {
                Icon(imageVector = Icons.Filled.Favorite, contentDescription = "Favorite", modifier = Modifier.size(24.dp))
            }
            IconButton(onClick = { /* Handle Settings click */ }) {
                Icon(imageVector = Icons.Filled.Settings, contentDescription = "Settings", modifier = Modifier.size(24.dp))
            }
        }
        Iframe(attrs = {
            // Set iframe attributes here
            attr("src", "index1.html")
            attr("width", "600")
            attr("height", "400")
            attr("style", "border: none;")
        })
    } else {
        Text("Greeting does not match.")
    }
}

Common Main (App.kt):


package com.telo.robotics.common

import androidx.compose.runtime.Composable
import androidx.compose.ui.window.ApplicationScope

expect fun getPlatform(): Platform

@Composable
expect fun PlatformSpecificContent()

// Main entry point for your app
@Composable
fun App() {
    ApplicationScope {
        // Render platform-specific content
        PlatformSpecificContent()
    }
}



Resources/assets 
index.html:

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>KmpApp2</title>
    <script src="skiko.js"></script>
    <link type="text/css" rel="stylesheet" href="styles.css">
</head>

<body>
    <div>
        <canvas id="ComposeTarget" width="600" height="800"></canvas>
    </div>
    <script src="composeApp.js"></script>
</body>

</html>

Expected Behavior:

The iframe should be rendered beside the row of Icon Buttons in jsMain. The HTML content from index1.html should appear in the iframe.

Actual Behavior:

Only the row of Compose Icon Buttons is visible, and the iframe does not render at all. It seems to be an issue specific to the jsMain platform, while other platforms like Android (with WebView) and Desktop render fine.

System Information:

	•	Xcode Version: e.g., 14.2
	•	macOS Version: e.g., macOS Monterey 12.4
	•	Kotlin Multiplatform Plugin Version: Latest
	•	Compose Multiplatform Version: Latest

Library Used:

implementation("org.jetbrains.compose.html:internal-html-core-runtime-js:1.7.0")

**Comment by Skaldebane** [comment] 2024-10-24 20:04
Hey @Jacko760, found you here as I was looking into this 😅 

That approach isn't gonna work, because you're mixing two fundamentally incompatible things (even if both use the Compose Runtime, neither is aware of each other's rendering).

Look at @sc941737's approach, that looks a lot more promising, though you'll have to handle absolute positioning etc... yourself, and it'll be overlaid on top of the canvas, so it's not without drawbacks.
