### ISSUE TITLE
Hotkeys when typing Korean in a TextField in macOs on Desktop Issue

### ISSUE THREAD

**Issue by eshc123** [JetBrains/compose-multiplatform#4621] opened 2024-04-16 00:46 UTC
**Describe the bug**
I am developing a Desktop Application, but unlike Windows, when I enter Korean language in TextField on macOs, if I use shortcut keys such as Select All (command + a) and Copy (command + c), they are not applied at once, but I have to press them twice. 
(* English, numbers, etc. can be done at once.)

**Affected platforms**

- Desktop (macOS)

**Versions**
- Kotlin version*:  1.9.0
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): macOS Sonoma 14.4.1
- JDK (for desktop issues): 17

**Screenshots**

![2024-04-169 23 48-ezgif com-video-to-gif-converter](https://github.com/JetBrains/compose-multiplatform/assets/50227341/0e9bfd4c-3517-467c-baf3-35ffd24b727b)
When viewing the gif, in English, the text is not underlined.
In Korean, the first time you press the shortcut(command + a) after the underline appears, the shortcut is not applied and the underline disappears.
If you press the shortcut(command + a) again, it will be applied.

**Comment by MatkovIvan** [comment] 2024-04-18 08:02
Seems like duplicate of #3497

**Comment by eshc123** [comment] 2024-04-19 03:36
I thought it was a JDK version issue, so I tried changing the version, but unfortunately, the same issue occurred. The difference with issue #3497 is that in my case, the [Cmd+C/V/X shortcut] works fine if I type it multiple times. However, it is quite inconvenient that I have to type the shortcut twice for it to work.

**Comment by m-sasha** [comment] 2024-08-21 08:56
This is unrelated to #3497 but is a bug in Java/Swing. The exact same behavior reproduces with a `JTextField`.

**Comment by m-sasha** [comment] 2024-08-21 09:36
It seems AWT is just not sending us the KEY_DOWN event corresponding to cmd-a when "composing" the last character. Below is the log of events when pressing, for example g, h, cmd-a
```
java.awt.event.InputMethodEvent[INPUT_METHOD_TEXT_CHANGED, "" + "ㅎ", 0 characters committed, caret: TextHitInfo[0T], visible position: TextHitInfo[-1T]] on canvas0
java.awt.event.KeyEvent[KEY_RELEASED,keyCode=71,keyText=G,keyChar='ㅎ',keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0,extendedKeyCode=0x0] on canvas0
java.awt.event.InputMethodEvent[INPUT_METHOD_TEXT_CHANGED, "" + "호", 0 characters committed, caret: TextHitInfo[0T], visible position: TextHitInfo[-1T]] on canvas0
java.awt.event.KeyEvent[KEY_RELEASED,keyCode=72,keyText=H,keyChar='ㅗ',keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0,extendedKeyCode=0x0] on canvas0
java.awt.event.KeyEvent[KEY_PRESSED,keyCode=157,keyText=⌘,keyChar=Undefined keyChar,modifiers=⌘,extModifiers=⌘,keyLocation=KEY_LOCATION_LEFT,rawCode=0,primaryLevelUnicode=0,scancode=0,extendedKeyCode=0x9d] on canvas0
java.awt.event.InputMethodEvent[INPUT_METHOD_TEXT_CHANGED, "" + "호", 0 characters committed, caret: TextHitInfo[0T], visible position: TextHitInfo[-1T]] on canvas0
java.awt.event.InputMethodEvent[INPUT_METHOD_TEXT_CHANGED, "호" + "", 1 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]] on canvas0
java.awt.event.KeyEvent[KEY_RELEASED,keyCode=65,keyText=A,keyChar='a',modifiers=⌘,extModifiers=⌘,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0,extendedKeyCode=0x41] on canvas0
java.awt.event.KeyEvent[KEY_RELEASED,keyCode=157,keyText=⌘,keyChar=Undefined keyChar,keyLocation=KEY_LOCATION_LEFT,rawCode=0,primaryLevelUnicode=0,scancode=0,extendedKeyCode=0x9d] on canvas0
```

**Comment by okushnikov** [comment] 2024-08-26 13:24
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4621">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:26 UTC
Labels: bug
