### ISSUE TITLE
Cannot delete previous distribution on Windows

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#4302] opened 2024-02-15 00:01 UTC
Run `createDistributable` or `createReleaseDistributable` first.

Then, make some changes to the code.

Run `createDistributable` or `createReleaseDistributable` again.

```
Unable to delete directory 'G:\Git\Omico\xxx\xxx\desktop\build\compose\binaries\main-release\app'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - G:\Git\Omico\xxx\xxx\desktop\build\compose\binaries\main-release\app\xxx-desktop\xxx-desktop.exe
  - G:\Git\Omico\xxx\xxx\desktop\build\compose\binaries\main-release\app\xxx-desktop
```

I can delete it manually in IDEA, but a `Clear Read-Only Status` dialog will pop up before the operation proceeds.

I only face this in Windows.

**Comment by Schahen** [comment] 2024-02-15 14:29
Thank you for report, Omico, can you clarify which version of compose-multiplatform you are using in the project that causes this problem?

**Comment by Omico** [comment] 2024-02-15 14:44
@Schahen I'm facing the same thing in `1.6.0-rc01`, `1.6.0-beta02`, `1.5.12`, and `1.5.11`; not sure about the other versions.

**Comment by Schahen** [comment] 2024-02-15 15:14
Thanks @Omico that's enough for further investigation

**Comment by badmannersteam** [comment] 2024-03-16 13:34
This issue is not related to the Compose, but we have 2 problems here:
1. `jpackage` generates `exe` with readonly flag on Windows.
    - There is an old issue (https://bugs.openjdk.org/browse/JDK-8261845), it was fixed in 2021 and the fix is still presented in openjdk master branch, but the generated file is readonly with the last openjdk 17/19/21.
    Don't know why, looks like another regression.
3. Gradle can't delete readonly file.
    - This issue (https://github.com/gradle/gradle/issues/26912, https://github.com/gradle/gradle/issues/26539) was introduced in Gradle 8.4 and was fixed in 8.7.

So for now to fix repeatable builds we can downgrade Gradle to 8.3 or upgrade it to 8.7-rc-1.

**Comment by Omico** [comment] 2024-03-16 19:24
Hi @badmannersteam, thanks for your info. 

I realize that the latest Temurin 17 on Winget is only 17.0.9.9. When I checked the source code, I found that the patch you mentioned has been included. Then, I upgraded to the latest 17.10.7 from the official website, which can still be reproduced.

And yes, after I upgraded to 8.7-rc-1, the issue is gone.

Thanks again!

**Comment by okushnikov** [comment] 2024-07-14 15:07
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4302">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:53 UTC
Labels: bug, gradle, windows
