### ISSUE TITLE
`PullRefreshIndicator` in `LazyColumn` on Desktop

### ISSUE THREAD

**Issue by imknown** [JetBrains/compose-multiplatform#4708] opened 2024-04-26 12:29 UTC
Already checked:
- https://stackoverflow.com/questions/70774033/compose-for-desktop-lazyrow-lazycolumn-not-scrolling-with-mouse-click
- https://github.com/JetBrains/compose-multiplatform/issues/1555

Just want to use [`androidx.compose.material.pullrefresh`][pullrefresh] on Desktop and Browser.  
But I cannot pull down the `LazyColumn` on Desktop.
This Composable works on Android & iOS. 

[pullrefresh]: https://developer.android.com/reference/kotlin/androidx/compose/material/pullrefresh/package-summary#top-level-functions

**Comment by MatkovIvan** [comment] 2024-04-26 13:18
Duplicate of #4436

> it will not trigger this logic because it [explicitly waits dragging](https://github.com/JetBrains/compose-multiplatform-core/blob/v1.6.0/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/pulltorefresh/PullToRefresh.kt#L333-L334), but `scrollable` modifier [disables](https://github.com/JetBrains/compose-multiplatform-core/blob/v1.6.0/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt#L657) dragging for mouse.

**Closed by MatkovIvan** 2024-04-26 13:18 UTC
Labels: enhancement, submitted

**Comment by okushnikov** [comment] 2024-08-26 13:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4708">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
