### ISSUE TITLE
Align Text overflow behaviour with Android or add new option

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3950] opened 2023-11-19 14:09 UTC
When `overflow = TextOverflow.Ellipsis` is set to a `Text` composable,

https://developer.android.com/jetpack/compose/text/configure-layout
According to this webpage, the string is truncated by characters in Android. For example, a string "abcde fghijklm" could be truncated to "abcde fghij...".

In Compose Desktop, the string is truncated by words. In the previous example, if the final character cannot be shown, the string is always truncated to "abcde...".

In my opinion, both use cases exist. It would be best if this is a configurable option, and align the default behaviour to that of Android.

**Comment by MatkovIvan** [comment] 2023-11-20 13:09
Duplicate of #1888

SInce you deleted our issue template, so I just assume that you're using not the latest dev version where it's already fixed.

**Closed by MatkovIvan** 2023-11-20 13:09 UTC
Labels: enhancement, text

**Comment by okushnikov** [comment] 2024-08-26 14:34
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3950">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
