### ISSUE TITLE
[Web][Wasm] ComposeViewport introduced overscroll stretching animation

### ISSUE THREAD

**Issue by egorikftp** [JetBrains/compose-multiplatform#4672] opened 2024-04-22 16:35 UTC
**Describe the bug**
I'm trying to migrate from **CanvasBasedWindow** to **ComposeViewport** we observe stretch animation (like overscroll on Android)

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version: 2.0.0-RC1 
- Compose Multiplatform version: 1.6.10-beta01 

**To Reproduce**
1. Replace _CanvasBasedWindow_ with _ComposeViewport_
2. Replace `<canvas id="youID"></canvas>` with `<div id="youID"></div>`
3. Observe stretching effect during vertical scroll

**Expected behavior**
No animation

**Screenshots**
CanvasBasedWindow

https://github.com/JetBrains/compose-multiplatform/assets/16294951/e89a4aef-5fa0-45fa-ad17-c4a7881e59a3

**ComposeViewport**

https://github.com/JetBrains/compose-multiplatform/assets/16294951/de2b8afe-93cd-4b78-926f-8b8695400e92

**Additional context**
Can be easily reproduced in this branch
https://github.com/ComposeGears/Tiamat/tree/feature/wasm

and this git patch
[overscroll.patch](https://github.com/JetBrains/compose-multiplatform/files/15065930/overscroll.patch)

**Comment by Nek-12** [comment] 2024-04-29 17:18
Actually, I would argue an overscroll animation is the expected behavior :)

**Comment by PMARZV** [comment] 2024-04-29 17:35
@Nek-12 ive never seen a web with the ios-like overscroll shown in the video

**Comment by Nek-12** [comment] 2024-04-29 18:35
I always wanted web apps to have this feature. There are extensions that do this, there are websites that have this on purpose, there are apps that promise the same things. I'm fact, i think it should be configurable

**Comment by nevrozza** [comment] 2024-06-18 17:36
it works for me: (from https://github.com/nevrozza/PansionApp/blob/main/composeApp/src/wasmJsMain/resources/styles.css)
``
#composeApp {
    width: 100%;
    height: 100%;
}


html, body {
    background-color: #2b2d30;
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    display: flex;
    overflow: hidden;
    justify-content: center;
    align-items: center;
}
``

**Comment by okushnikov** [comment] 2024-07-14 14:52
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4672">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:36 UTC
Labels: bug, web
