### ISSUE TITLE
No way to create a UIKitView with transparent background

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3154] opened 2023-05-11 13:57 UTC
**Describe the bug**

I want to place UIKIt view with transparent background on top of my Compose content, but [this](https://github.com/JetBrains/compose-multiplatform-core/blob/feaab5420821266f10982a0b36d41b22d89bc3bf/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/interop/UIKitView.uikit.kt#L109) line cuts underlying Compose content and exposes the white root view

**Versions**
- Compose Multiplatform version*: 1.4.0

**Comment by igordmn** [comment] 2023-05-11 17:56
This is a limitation of the current implementation. We will look in the future, if is is possible to fully support transparency.

I add `enhancement`, and keep `bug` until we add a check into code:
```
require(background != Color.Transparent) {
  "Transparent background isn't supported at the moment. Follow https://github.com/JetBrains/compose-multiplatform/issues/3154"
}
```

**Comment by alexzhirkevich** [comment] 2023-05-11 19:46
Hope you find a way some day!
>require(!background.isSpecified || background.isSpecified && background.alpha == 1.0)

P.S. 2nd `background.isSpecified` check is redundant. It is always true after 1st check 😅

**Comment by alexeiartsimovich** [comment] 2023-07-14 21:51
Is there a workaround for this? 
This is really a blocking issue as I cannot use UIKitView with UIImageView to display `png` icons.

**Comment by alexzhirkevich** [comment] 2023-07-15 10:54
@alexeiartsimovich Are you sure you need to use a uiimageview for that? What about compose image/icon?

**Comment by alexeiartsimovich** [comment] 2023-07-15 10:57
I need to display a local `png` icon on iOS. Can compose image/icon do this? I didn't find an example

**Comment by alexzhirkevich** [comment] 2023-07-15 11:01
Like from resources or from file system? There are many libraries for common resources. Official one is used in [template](https://github.com/JetBrains/compose-multiplatform-ios-android-template). You can also display image from file system by decoding byte array to skia image

**Comment by alexzhirkevich** [comment] 2023-07-15 11:05
Also if you want to display [iOS system icons](https://developer.apple.com/sf-symbols/) in compose you can use [this trick](https://github.com/alexzhirkevich/compose-look-and-feel/blob/master/lookandfeel/src/iosMain/kotlin/com/github/alexzhirkevich/lookandfeel/util/UIImage.ios.kt)

**Comment by alexeiartsimovich** [comment] 2023-07-15 11:15
Wow I didn't know we can draw vectors on iOS. Thanks!

**Comment by alexzhirkevich** [comment] 2023-07-15 11:19
This can be any image (png, jpeg). Not only xml

**Comment by rustamsmax** [comment] 2023-11-07 13:30
@JamshedAlamQaderi Here's a temporary [workaround](https://gist.github.com/rustamsmax/50394673840190c1df7ccc09e9f8ec1f)

**Comment by JamshedAlamQaderi** [comment] 2023-11-07 15:01
@rustamsmax thanks for the workaround. I'm gonna try it

**Comment by LaatonWalaBhoot** [comment] 2023-11-07 19:52
@rustamsmax 
Doing this UiKitView still adds a flicker to the view before setting the background color
The flicker is still white.
This is how I am doing it. 

```
var animation by remember { mutableStateOf<CompatibleAnimation?>(null) }

    LaunchedEffect(Unit) {
        animation = CompatibleAnimation(
            name = animationRes.fileName,
            subdirectory = null,
            animationRes.bundle
        )
    }

    when (val value = animation) {
        null -> {}
        else -> {
            UIKitView(
                modifier = modifier,
                factory = {
                    UIView().apply {
                        backgroundColor = UIColor.clearColor
                        opaque = true
                        setClipsToBounds(true)
                    }
                },
                background = MaterialTheme.colorScheme.surface,
                update = {
                    val view = CompatibleAnimationView()
                    view.translatesAutoresizingMaskIntoConstraints = false
                    it.addSubview(view)

                    NSLayoutConstraint.activateConstraints(
                        listOf(
                            view.widthAnchor.constraintEqualToAnchor(it.widthAnchor),
                            view.heightAnchor.constraintEqualToAnchor(it.heightAnchor)
                        )
                    )

                    view.setAnimationSpeed(speed.toDouble())
                    view.setCompatibleAnimation(value)
                    view.setLoopAnimationCount(if (isInfinite) -1.0 else 1.0)
                    view.setContentMode(UIViewContentMode.UIViewContentModeScaleAspectFit)
                    view.playWithCompletion { completed ->
                        if (completed) onComplete?.invoke()
                    }
                }
            )
        }
    }

```

**Comment by JamshedAlamQaderi** [comment] 2023-11-11 11:39
Hi @rustamsmax , it's not working.

**Comment by elijah-semyonov** [comment] 2023-11-15 11:10
@LaatonWalaBhoot 

I couldn't replicate reported behavior using the snippet below. Could you please make a minimal reproducible one which I can investigate?

```kotlin
val UIKitRenderSync = Screen.Example("UIKitRenderSync") {
    var text by remember { mutableStateOf("Type something") }
    var showUIViews by remember { mutableStateOf(true) }
    LazyColumn(Modifier.fillMaxSize().background(Color.Red)) {
        item {
            Button(onClick = {
                showUIViews = !showUIViews
            }) {
                Text("Click")
            }
        }
        items(100) { index ->
            when (index % 4) {
                0 -> Text("material.Text $index", Modifier.fillMaxSize().height(40.dp))
                1 -> {
                    if (showUIViews) {
                        UIKitView(
                            factory = {
                                val label = UILabel(frame = CGRectZero.readValue())
                                label.text = "UILabel $index"
                                label.textColor = UIColor.blackColor
                                label.backgroundColor = UIColor.clearColor
                                label
                            },
                            background = Color.Green,
                            modifier = Modifier.fillMaxWidth().height(40.dp)
                        )
                    }
                }
                2 -> TextField(text, onValueChange = { text = it }, Modifier.fillMaxWidth())
                else -> {
                    if (showUIViews) {
                        ComposeUITextField(text, onValueChange = { text = it }, Modifier.fillMaxWidth().height(40.dp))
                    }
                }
            }
        }
    }
}

/**
 * Compose wrapper for native UITextField.
 * @param value the input text to be shown in the text field.
 * @param onValueChange the callback that is triggered when the input service updates the text. An
 * updated text comes as a parameter of the callback
 * @param modifier a [Modifier] for this text field. Size should be specified in modifier.
 */
@Composable
private fun ComposeUITextField(value: String, onValueChange: (String) -> Unit, modifier: Modifier) {
    val latestOnValueChanged by rememberUpdatedState(onValueChange)

    UIKitView(
        factory = {
            val textField = object : UITextField(CGRectMake(0.0, 0.0, 0.0, 0.0)) {
                @ObjCAction
                fun editingChanged() {
                    latestOnValueChanged(text ?: "")
                }
            }
            textField.addTarget(
                target = textField,
                action = NSSelectorFromString(textField::editingChanged.name),
                forControlEvents = UIControlEventEditingChanged
            )
            textField
        },
        modifier = modifier,
        update = { textField ->
            textField.text = value
        }
    )
}
```

https://github.com/JetBrains/compose-multiplatform/assets/4167681/05153560-5866-4d92-957c-db4347c4e7ec

**Comment by JamshedAlamQaderi** [comment] 2023-11-15 11:47
@elijah-semyonov could you change the background color to `Color.Transparent` and check if the `LazyColumn` background color `Red` is visible or not?

**Comment by elijah-semyonov** [comment] 2023-11-15 12:58
It won't be visible, because currently interop views are drawn _behind_ the compose view through the transparent holes.

**Comment by JamshedAlamQaderi** [comment] 2023-11-15 13:45
@elijah-semyonov isn't it possible to stack it to top off all compose views by anyway?

**Comment by elijah-semyonov** [comment] 2023-11-15 13:51
In absolute terms - yes, it is possible and we will probably do it that way in the future. It will require adapting all modifiers that affect masking (like round corners) for native views as well.

**Comment by BoykoDmytro** [comment] 2023-11-20 17:01
@elijah-semyonov Hi, do u have approximate date or release when it can be on release? Thx

**Comment by ismai117** [comment] 2024-03-16 02:31
I've tried different ways to make the background transparent, but it keeps showing a white background. Is there a way I can sort this out?

```Kotlin
@Composable
fun LottieAnimation(
    modifier: Modifier,
    composition: Any?,
    progress: () -> Float,
    backgroundColor: Color,
) {
    when (composition as? CompatibleAnimationView) {
        null -> {}
        else -> {
            UIKitView(
                factory = {
                    UIView().apply {
                        this.backgroundColor = UIColor.clearColor
                        this.opaque = false
                        this.setClipsToBounds(true)
                    }
                },
                modifier = modifier,
                update = { view ->
                    view.backgroundColor = UIColor.clearColor
                    composition.translatesAutoresizingMaskIntoConstraints = false
                    view.addSubview(composition)
                    NSLayoutConstraint.activateConstraints(
                        listOf(
                            composition.widthAnchor.constraintEqualToAnchor(view.widthAnchor),
                            composition.heightAnchor.constraintEqualToAnchor(view.heightAnchor)
                        )
                    )
                },
                background = Color.Transparent
            )
        }
    }

}
```

**Comment by ismai117** [comment] 2024-03-26 21:31
Hi @elijah-semyonov @dima-avdeev-jb is there any workarounds for a transparent background on Uikitview?

**Comment by LaatonWalaBhoot** [comment] 2024-04-09 08:43
@elijah-semyonov 
Is there any particular reason why this issue will not worked on for the next release?
Supporting dark mode is impossible with this because of white blinking which seemingly presents as a UI glitch
Especially when using animations

**Comment by LaatonWalaBhoot** [comment] 2024-04-09 12:14
@elijah-semyonov this is available with what version of CMP?

**Comment by JamshedAlamQaderi** [comment] 2024-05-30 14:26
It's been so long. but still facing this issue. Please somehow help me. Background shows white if backgroundColor set to transparent

```kotlin
    UIKitView(
      factory = {
          UIView().apply {
              backgroundColor = UIColor.clearColor
              opaque = false
              clipsToBounds = true
          }
      },
      update = {
          it.backgroundColor = UIColor.clearColor
          it.opaque = false
          it.clipsToBounds = true
      },
      modifier = Modifier.size(250.dp).border(1.dp, Color.Transparent).padding(50.dp),
  )
```

**Comment by JamshedAlamQaderi** [comment] 2024-05-30 15:30
@LaatonWalaBhoot thank you for the workaround. I'm gonna give it a try with your example.

**Comment by JamshedAlamQaderi** [comment] 2024-05-30 18:36
Hi @LaatonWalaBhoot , could you tell me what is the package of `CompatibleAnimationView()`?

**Comment by ismai117** [comment] 2024-05-30 19:11
@LaatonWalaBhoot  I tried your solution but it doesn't work for me?

**Comment by JamshedAlamQaderi** [comment] 2024-06-01 13:18
@LaatonWalaBhoot neither work for me too

**Comment by vickyleu** [comment] 2024-06-17 12:11
i found a solutions
```kotlin
fun UIView.parent(count:Int):UIView?{
    if(count<=0)return null
    var c = count-1
    var v:UIView? = this.superview
    while ((c-- >0 && v!=null)){
        v =v.superview
    }
    return v
}


update = { view ->
      val parent = view.parent(4) ?: return@UIKitView
      parent.backgroundColor = UIColor.clearColor
}
```
view.parent(4) is ComposeContainer UIController root view, normally is black systemBackgroundColor

```Objective-C
Printing description of $13:
<ComposeContainer: 0x1087ec740>
Printing description of $14:
<UIView_IgnoreSafeArea: 0x1087ea340; frame = (0 0; 390 844); clipsToBounds = YES; opaque = NO; autoresize = W+H; backgroundColor = <UIDynamicSystemColor: 0x3012faf80; name = systemBackgroundColor>; layer = <CALayer: 0x30079ae40>>
```

so you just need change UIView_IgnoreSafeArea backgroundColor

**Comment by ismai117** [comment] 2024-06-17 13:05
@vickyleu can you show the full UIKitView code please

**Comment by vickyleu** [comment] 2024-06-17 13:12
> @vickyleu can you show the full UIKitView code please

```

fun UIView.parent(count:Int):UIView?{
    if(count<=0)return null
    var c = count-1
    var v:UIView? = this.superview
    while ((c-- >0 && v!=null)){
        v =v.superview
    }
    return v
}

fun UIView.removeControllerColor(scope: CoroutineScope){
    if(tag.toInt()!=10086){
        opaque = true
        backgroundColor = UIColor.clearColor
        findViewController()?. apply controller@ {
            scope.launch {
                var notStop=true
                while (notStop){
                    withContext(uoocDispatchers.io){
                        delay(100)
                        withContext(uoocDispatchers.main){
                            if(this@controller.isViewLoaded()){
                                notStop=false
                                this@controller.view.opaque = true
                                this@controller.view.backgroundColor = UIColor.clearColor
                                this@controller.view.setTag(10086)
                            }
                        }
                    }
                }
            }
        }
    }
}

UIKitView(
      factory = {
                    webview
      },
      interactive = true,
      background = Color.Transparent,
      modifier = Modifier.fillMaxWidth().height(height),
      update = { view ->
           val parent = view.parent(4) ?: return@UIKitView
           parent.removeControllerColor(coroutineScope)
      })
```

**Comment by ismai117** [comment] 2024-06-17 14:25
It still shows a white background, am I missing something? 

```Kotlin 
@OptIn(ExperimentalForeignApi::class)
@Composable
fun TestAnimation(
    modifier: Modifier,
) {
    val scope = rememberCoroutineScope()
    when (composition as? CompatibleAnimationView) {
        null -> {}
        else -> {
            UIKitView(
                modifier = modifier,
                factory = {
                    val view = UIView()
                    view
                },
                background = Color.Transparent,
                update = { view ->
                    val parent = view.parent(4)
                    parent?.removeControllerColor(scope)
                }
            )
        }
    }
}


fun UIView.parent(count:Int):UIView?{
    if(count<=0)return null
    var c = count-1
    var v:UIView? = this.superview
    while ((c-- >0 && v!=null)){
        v =v.superview
    }
    return v
}
fun UIView.findViewController(): UIViewController? {
    var nextResponder: UIResponder? = this
    while (nextResponder != null) {
        if (nextResponder is UIViewController) {
            return nextResponder
        }
        nextResponder = nextResponder.nextResponder
    }
    return null
}
fun UIView.removeControllerColor(scope: CoroutineScope) {
    if (tag.toInt() != 10086) {
        opaque = true
        backgroundColor = UIColor.clearColor
        findViewController()?.apply controller@{
            scope.launch {
                var notStop = true
                while (notStop) {
                    withContext(Dispatchers.IO) {
                        delay(100)
                        withContext(Dispatchers.Main) {
                            if (this@controller.isViewLoaded()) {
                                notStop = false
                                this@controller.view.opaque = true
                                this@controller.view.backgroundColor = UIColor.clearColor
                                this@controller.view.setTag(10086)
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by vickyleu** [comment] 2024-06-17 14:58
> It still shows a white background, am I missing something? 
> 
> 
> 
> ```Kotlin 
> 
> @OptIn(ExperimentalForeignApi::class)
> 
> @Composable
> 
> fun TestAnimation(
> 
>     modifier: Modifier,
> 
> ) {
> 
>     val scope = rememberCoroutineScope()
> 
>     when (composition as? CompatibleAnimationView) {
> 
>         null -> {}
> 
>         else -> {
> 
>             UIKitView(
> 
>                 modifier = modifier,
> 
>                 factory = {
> 
>                     val view = UIView()
> 
>                     view
> 
>                 },
> 
>                 background = Color.Transparent,
> 
>                 update = { view ->
> 
>                     val parent = view.parent(4)
> 
>                     parent?.removeControllerColor(scope)
> 
>                 }
> 
>             )
> 
>         }
> 
>     }
> 
> }
> 
> 
> 
> 
> 
> fun UIView.parent(count:Int):UIView?{
> 
>     if(count<=0)return null
> 
>     var c = count-1
> 
>     var v:UIView? = this.superview
> 
>     while ((c-- >0 && v!=null)){
> 
>         v =v.superview
> 
>     }
> 
>     return v
> 
> }
> 
> fun UIView.findViewController(): UIViewController? {
> 
>     var nextResponder: UIResponder? = this
> 
>     while (nextResponder != null) {
> 
>         if (nextResponder is UIViewController) {
> 
>             return nextResponder
> 
>         }
> 
>         nextResponder = nextResponder.nextResponder
> 
>     }
> 
>     return null
> 
> }
> 
> fun UIView.removeControllerColor(scope: CoroutineScope) {
> 
>     if (tag.toInt() != 10086) {
> 
>         opaque = true
> 
>         backgroundColor = UIColor.clearColor
> 
>         findViewController()?.apply controller@{
> 
>             scope.launch {
> 
>                 var notStop = true
> 
>                 while (notStop) {
> 
>                     withContext(Dispatchers.IO) {
> 
>                         delay(100)
> 
>                         withContext(Dispatchers.Main) {
> 
>                             if (this@controller.isViewLoaded()) {
> 
>                                 notStop = false
> 
>                                 this@controller.view.opaque = true
> 
>                                 this@controller.view.backgroundColor = UIColor.clearColor
> 
>                                 this@controller.view.setTag(10086)
> 
>                             }
> 
>                         }
> 
>                     }
> 
>                 }
> 
>             }
> 
>         }
> 
>     }
> 
> }
> 
> ```

your UIView background not set

**Comment by ismai117** [comment] 2024-06-17 16:17
![Screenshot 2024-06-17 at 17 17 22](https://github.com/JetBrains/compose-multiplatform/assets/88812838/657b4969-2509-4e18-a8f5-8199cc1e42d1)


```Kotlin
@OptIn(ExperimentalComposeApi::class)
fun MainViewController() = ComposeUIViewController() {
    val modifier: Modifier = Modifier
   Box(
       modifier = modifier.fillMaxSize().background(Color.Red),
       contentAlignment = Alignment.Center
   ){
       Box(
           modifier = modifier
               .size(200.dp)
       ){
           TestAnimation(
               modifier = modifier
           )
       }
   }
}


@OptIn(ExperimentalForeignApi::class)

@Composable

fun TestAnimation(
    modifier: Modifier,
    ) {

    val scope = rememberCoroutineScope()

    UIKitView(

        modifier = modifier.fillMaxSize(),

        factory = {
            
            UIView().apply { 
                backgroundColor = UIColor.clearColor
                opaque = false
            }
            
        },

        background = Color.Transparent,

        update = { view ->

            val parent = view.parent(4)

            parent?.removeControllerColor(scope)

        }

    )

}





fun UIView.parent(count:Int):UIView?{

    if(count<=0)return null

    var c = count-1

    var v:UIView? = this.superview

    while ((c-- >0 && v!=null)){

        v =v.superview

    }

    return v

}

fun UIView.findViewController(): UIViewController? {

    var nextResponder: UIResponder? = this

    while (nextResponder != null) {

        if (nextResponder is UIViewController) {

            return nextResponder

        }

        nextResponder = nextResponder.nextResponder

    }

    return null

}

fun UIView.removeControllerColor(scope: CoroutineScope) {

    if (tag.toInt() != 10086) {

        opaque = true

        backgroundColor = UIColor.clearColor

        findViewController()?.apply controller@{

            scope.launch {

                var notStop = true

                while (notStop) {

                    withContext(Dispatchers.IO) {

                        delay(100)

                        withContext(Dispatchers.Main) {

                            if (this@controller.isViewLoaded()) {

                                notStop = false

                                this@controller.view.opaque = true

                                this@controller.view.backgroundColor = UIColor.clearColor

                                this@controller.view.setTag(10086)

                            }

                        }

                    }

                }

            }

        }

    }

}
```

**Comment by vickyleu** [comment] 2024-06-17 18:34
@ismai117 
maybe the factory method of UIKitView is recreat, now add Observer for CMPInteropWrappingView's backgroundColor

![WX20240618-022750@2x](https://github.com/JetBrains/compose-multiplatform/assets/19390292/b06bd617-98cd-4ee1-bf15-988eca527600)


```kotlin
update = { view ->
                        val parent = view.parent(4) ?: return@UIKitView
                        view.removeInteropWrappingViewColor(coroutineScope)
                        parent.removeControllerColor(coroutineScope)
}
```

```kotlin
/**
 * UIKitView factory maybe reattach to window,Observe backgroundColor change
 */
class InteropWrappingViewWatching(val view:UIView) : NSObject(), ObserverProtocol {
    override fun observeValueForKeyPath(
        keyPath: String?,
        ofObject: Any?,
        change: Map<Any?, *>?,
        context: COpaquePointer?
    ) {
        if(keyPath=="backgroundColor"){
            if(view.backgroundColor!=UIColor.clearColor){
                view.opaque = true
                view.backgroundColor = UIColor.clearColor
                view.setTag(10088)
                view.removeObserver(this,"backgroundColor")
            }
        }
    }
}

fun UIView.removeInteropWrappingViewColor(scope: CoroutineScope){
    if(tag.toInt()!=10087 && tag.toInt()!=10088){
        opaque = true
        backgroundColor = UIColor.clearColor
        val parent = superview?:return
        val obs= InteropWrappingViewWatching(parent)
        findViewController()?. apply controller@ {
            scope.launch {
                var notStop=true
                while (notStop){
                    withContext(uoocDispatchers.io){
                        delay(100)
                        withContext(uoocDispatchers.main){
                            if(this@controller.isViewLoaded()){
                                notStop=false
                                parent.apply {
                                    opaque = true
                                    backgroundColor = UIColor.clearColor
                                    setTag(10087)
                                    addObserver(obs, forKeyPath = "backgroundColor", options = NSKeyValueObservingOptionNew, context = null)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

observer.def
```def
language = Objective-C
---
#import <Foundation/Foundation.h>

@protocol Observer
@required
- (void)observeValueForKeyPath:(NSString *)keyPath
    ofObject:(id)object
    change:(NSDictionary<NSKeyValueChangeKey, id> *)change
    context:(void *)context;
@end;
```


```kotlin
targets.withType<KotlinNativeTarget> {
        val path = projectDir.resolve("src/nativeInterop/cinterop/observer")
        binaries.all {
            linkerOpts("-F $path")
            linkerOpts("-ObjC")
        }
        compilations.getByName("main") {
            cinterops.create("observer") {
                compilerOpts("-F $path")
            }
        }
    }
```

**Comment by ismai117** [comment] 2024-06-19 23:07
I've made all the layout transparent even the iPhone system colour, its not going to work 
![Screenshot 2024-06-20 at 00 03 42](https://github.com/JetBrains/compose-multiplatform/assets/88812838/99c46219-0fdb-4a9f-8de9-1e197a54c789)

**Comment by MatkovIvan** [comment] 2024-06-20 07:07
> [elijah-semyonov](https://github.com/elijah-semyonov) commented [on Nov 15, 2023](https://github.com/JetBrains/compose-multiplatform/issues/3154#issuecomment-1812493661)
It won't be visible, because currently interop views are drawn _behind_ the compose view through the transparent holes.

And currently there are no plans to change that

**Comment by vickyleu** [comment] 2024-06-22 16:14
> I've made all the layout transparent, including the system background color, and it still doesnt work. background color will be black if there is no color set.
> 
> ![Screenshot 2024-06-20 at 00 03 42](https://private-user-images.githubusercontent.com/88812838/341220264-99c46219-0fdb-4a9f-8de9-1e197a54c789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzI1ODMsIm5iZiI6MTcxOTA3MjI4MywicGF0aCI6Ii84ODgxMjgzOC8zNDEyMjAyNjQtOTljNDYyMTktMGZkYi00YTlmLThkZTktMWUxOTdhNTRjNzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYTY4OGMxOTcyYTU1NDA2ZDE5YTk0OTM2NjUxMTg4NGJiYjliZmJiODAzOGFmMzM0OWNiNTkwNjZlYzkzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vmKnUczY0fSrRr0O4TXJBMOfk6cxqOdeUagDjOtHKz8)

@ismai117 hi ismai,i found CompatibleAnimationView's subview is black,so you should also change CompatibleAnimationView's subview backgroundColor

```kotlin
update = { view ->
                    view.removeInteropWrappingViewColor(coroutineScope)
                    view.parent(4)?.removeControllerColor(coroutineScope)
                    view.apply { //CompatibleAnimationView's subview is black
                        subviews.forEach {
                            (it as UIView).backgroundColor= UIColor.clearColor
                        }
                    }
                    val parent = view.parent(3)
                    parent?.apply {
                        (subviews as List<UIView>).apply {
                            val collection = this
                            collection.find { it is androidx.compose.ui.window.InteractionUIView }?.apply {
                               val interactionInParentIndex = collection.indexOf(this)
                                  if(interactionInParentIndex!=0){
                                    parent.sendSubviewToBack(this)//move compose content to back
                                    this.subviews.forEach {
                                        val rendering=this as? androidx.compose.ui.window.RenderingUIView
                                        rendering?.apply {

                                        }
                                    }
                                }
                           }
                        }
                    }
                }
```
and @MatkovIvan no need drawn behind, InteractionUIView can be send to back

We only need to move androidx.compose.ui.window.InteractionUIView to the bottom layer, digging a hole is completely unnecessary.
According to my understanding, InteractionUIView should only have once layer in UIWindow , right? Since the dialog is an independent UIWindow, there's no need to dig a hole to display InteropWrappingView. Simply move any InteractionUIView that is not at the bottom layer to the bottom.

**Comment by vickyleu** [comment] 2024-06-22 18:11
😭I've just thought about another issue. If I need to overlay something above a UIKit view inside a Box, it seems like a problem. It appears to have no solution, leading to being torn between different priorities. Alternatively, like in Android, extract a texture and place the real view onto a second display (all controllers at the bottom, with one controller for buffering textures).

**Comment by ErickSorto** [comment] 2024-07-03 17:43
I am having the same issue here..

**Comment by okushnikov** [comment] 2024-07-14 14:50
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3154">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:33 UTC
Labels: enhancement, rendering, ios
