### ISSUE TITLE
Tootlip doesn't disappear when we move mouse outside of the window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1546] opened 2021-12-04 15:44 UTC
Compose 1.0.0, Windows 11

https://user-images.githubusercontent.com/5963351/144715614-f0b1d630-0d20-45f5-a4e4-8e84686020c9.mp4

```
import androidx.compose.foundation.TooltipArea
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        Box(Modifier.fillMaxSize(), contentAlignment = Alignment.BottomEnd) {
            TooltipArea(
                tooltip = {
                    Text("Button", modifier = Modifier.background(Color.LightGray).padding(8.dp))
                }
            ) {
                Button(onClick = {}) {
                    Text("Button")
                }
            }
        }
    }
}
```

**Comment by felixdivo** [comment] 2021-12-09 08:41
As a side note: I did have problems with tooltips not disappearing within scrollable containers when outside of the visible range back in/around version `1.0.0-rc4`, but they are not fixed in the stable release! Thank you! 😄

**Comment by felixdivo** [comment] 2022-01-24 08:19
> but they are now fixed in the stable release!

That is apparently not the case, it's just that the problem was tricky for me to reproduce. Moving the cursor out of the window apparently is still problematic in `1.0.1` and also in `1.1.0-alpha1-dev550`.

**Comment by felixdivo** [comment] 2023-01-08 14:54
It is still a problem in 1.2.2 and very annoying since there does not appear to be a reasonable workaround.

**Comment by okushnikov** [comment] 2024-08-26 15:49
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6074">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:36 UTC
Labels: bug, window management, desktop
