### ISSUE TITLE
[jvm] HorizontalPager can't have snap scroll

### ISSUE THREAD

**Issue by codlab** [JetBrains/compose-multiplatform#3849] opened 2023-10-22 23:20 UTC
edit : changed the title to be more explicit about the issue which makes more sense on desktops

**Describe the bug**
Scrolling using the trackpad won't pan on entire page : stopping mid "scroll" will keep the pages in a weird state where it doesn't magnet to the new "currentPage"

edit : removing this part : _Using the HorizontalPager on jvm artifact will have this weird behaviour that no drag interaction can change pages. On Mac for instance, only either switching pages programmatically or scrolling on the trackpad will work. Shouldn't a mouse drag be working just like on mobile platforms ?_

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.10-beta02
- OS version(s)* (required for Desktop and iOS issues): MacOS
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): JDK shipped with Android Studio Hedgehog | 2023.1.1 Beta 5

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a project which will have a screen with a HorizontalPager holding few dummy pages
2. run
3. Scroll horizontally the pager using the mouse or trackpads
4. the pages won't snap scroll and just stop animating in between pages

**Expected behavior**
When scrolling using the trackpad, it should land to "full" currentPage instead of just be in a weird interstate
edit : removed _It should be possible to scroll just on the other mobile platforms._ 

**Additional context**
I took a quick snippet from another issue just to check if it wasn't my implementation which was introducing such issues and could reproduce the issue right away

```
    val state = rememberPagerState(
        pageCount = { 3 }
    )

    ...
    HorizontalPager(
        modifier = Modifier.fillMaxSize(),
        state = state,
    ) { index ->
        when (index) {
            0 -> Box(modifier = Modifier.fillMaxSize().background(Color.Red))
            1 -> Box(modifier = Modifier.fillMaxSize().background(Color.Black))
            2 -> Box(modifier = Modifier.fillMaxSize().background(Color.Yellow))
        }
    }
```

**Comment by jbruchanov** [comment] 2023-10-23 13:45
+1on windows, 
scrolling works only via 
- vertical wheel 
- horizontal shift + mouse wheel

but it can't be simply dragged by mouse click + drag...
also it seems to be working simply as scrollable container, there is no "snap scrolling effect"

**Comment by codlab** [comment] 2023-10-23 14:00
> scrolling works only via

Fair enough, it can be easily circumvented even tho the nowadays use cases all revolve around inverted behaviour where everything now matches touchscreens :p (interestingly, it reminds me I didn't check using a laptop with touchscreens)

> also it seems to be working simply as scrollable container, there is no "snap scrolling effect"

this is problematic as the whole purpose of a "pager" is to actually introduce said snap scroll. Otherwise, this is simply a lazy horizontal list

**Comment by alexzhirkevich** [comment] 2023-10-23 14:24
Now it's a duplicate of #3447

**Comment by codlab** [comment] 2023-10-23 15:07
Awesome, I'll update this one then. Almost finished to work onto something which may be (hopefully) cleaner than using a LaunchedEffect

**Comment by dima-avdeev-jb** [comment] 2023-10-27 04:06
Thanks to @alexzhirkevich 
It is duplicate of Issue https://github.com/JetBrains/compose-multiplatform/issues/3447

**Closed by dima-avdeev-jb** 2023-10-27 04:06 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:10
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3849">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
