### ISSUE TITLE
Popup covered by SwingPanel

### ISSUE THREAD

**Issue by ionull** [JetBrains/compose-multiplatform#3823] opened 2023-10-14 10:15 UTC
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.5.0
- OS version(s)* (required for Desktop and iOS issues): macOS Sonoma 14.0 Ubuntu 22.04 Windows 10
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): zulu-javafx-17.40.19

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a popup that will pop outside its parent
2. Create a SwingPanel that will be pop over by the popup created on step 1

**Expected behavior**
Popup overlay anything else

**Screenshots**
<img width="912" alt="Screenshot 2023-10-14 at 18 09 29" src="https://github.com/JetBrains/compose-multiplatform/assets/242295/3b7f7efb-b9ba-4327-941d-b7fd1d714e26">
<img width="912" alt="Screenshot 2023-10-14 at 18 09 52" src="https://github.com/JetBrains/compose-multiplatform/assets/242295/7c5dbb2d-24da-430f-8e76-4b31fc34e85d">

**Comment by MatkovIvan** [comment] 2023-10-14 11:54
Duplicate of #2926

**Closed by MatkovIvan** 2023-10-14 11:54 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:09
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3823">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
