### ISSUE TITLE
iOS pod implementation throws selector error

### ISSUE THREAD

**Issue by LaatonWalaBhoot** [JetBrains/compose-multiplatform#3836] opened 2023-10-18 12:32 UTC
**Describe the bug**
GoogleSignIn ios pod fails with selector implementation

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.1

**To Reproduce**
`
@OptIn(ExperimentalForeignApi::class)
@Composable
actual fun OnboardingView(
    modifier: Modifier
) {

    val controller = UIApplication.sharedApplication.keyWindow?.rootViewController

    Box(Modifier.fillMaxSize()) {
        UIKitView(
            modifier = Modifier.fillMaxSize(),
            factory = {
                UIView()
            },
            update = {
                val config = GIDConfiguration(clientID = BuildKonfig.GOOGLE_WEB_CLIENT_ID)
                controller?.let {
                    GIDSignIn.sharedInstance().setConfiguration(config)
                    GIDSignIn.sharedInstance.signInWithPresentingViewController(controller) { result, error ->

                    }
                }
            }
        )
    }

}
`

**Expected behavior**
ViewController should handle the delegated sign-in flow

**Additional context**
Android implementation is working correctly. iOS implementation consistently throws 
`'NSInvalidArgumentException', reason: '-[GIDSignIn setConfiguration:]: unrecognized selector sent to instance 0x600000d0a6a0'`

**Comment by MatkovIvan** [comment] 2023-10-18 13:38
Please check if you included `GoogleSignIn` correctly into your project. `unrecognized selector sent` usually means that a library is missing and the application cannot load it at runtime.

This problem does not seem related to Compose, closing

**Closed by MatkovIvan** 2023-10-18 13:38 UTC
Labels: bug, submitted

**Comment by LaatonWalaBhoot** [comment] 2023-10-18 13:53
Apologies. This is my gradle spec with GoogleSignIn

`
@OptIn(org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi::class)
kotlin {
    targetHierarchy.default()
    jvmToolchain(11)
    android()
    ios()
    iosSimulatorArm64()

    cocoapods {
        summary = "Some description for the Shared Module"
        homepage = "Link to the Shared Module homepage"
        version = "1.0"
        ios.deploymentTarget = "14.1"
        podfile = project.file("../iosApp/Podfile")
        framework {
            baseName = "shared"
            isStatic = true
        }

        pod("Amplitude", "8.17.1")
        pod("FirebaseMessaging")
        pod("FirebaseAuth")
        pod("Reachability")
        pod("GoogleSignIn")
        pod("lottie-ios") {
            version = "4.3.3"
            moduleName = "Lottie"
        }
    }
`

**Comment by MatkovIvan** [comment] 2023-10-19 07:52
Could you please provide more details on why you believe the issue is related to Compose but not `GoogleSignIn`?

**Comment by LaatonWalaBhoot** [comment] 2023-10-19 07:56
when used as a swift package dependency in native code GoogleSignIn works absolutely fine.
But kotlin cocoa pods seem to be having this issue
Have double-checked my imports.
Like you said the lib seems like its missing method signature perhaps because of interop issue

**Comment by terrakok** [comment] 2023-10-19 09:05
Since is is not the Compose issue, could you file a new issue in [Kotlin Cocoapods tracker](https://youtrack.jetbrains.com/newIssue?project=KT&c=Subsystems+Tools.+Gradle.+Cocoapods) (with a small reproducer)?

**Comment by LaatonWalaBhoot** [comment] 2023-10-19 09:07
Sure. Thanks

**Comment by okushnikov** [comment] 2024-07-14 14:47
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3836">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
