### ISSUE TITLE
SwingPanel is always on the top

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#3739] opened 2023-09-28 06:21 UTC
**Describe the bug**
If I use android Views or iOS UIKit interop with Compose the z index is respected and I can have a composable on top of a UIKit View for example but for desktop it's not the case, swing components are always on the top.
```
Box {
    SwingInterop()
    Text("Demo text") // this text should be visible on top of swing
}
```

https://github.com/MohamedRejeb/Calf/blob/8dd27303afba2f76503089567ad65ffe94e5a051/calf-ui/src/desktopMain/kotlin/com/mohamedrejeb/calf/ui/web/WebView.desktop.kt#L120

https://github.com/MohamedRejeb/Calf/blob/8dd27303afba2f76503089567ad65ffe94e5a051/sample/common/src/commonMain/kotlin/com.mohamedrejeb.calf.sample/ui/WebViewScreen.kt#L47

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.20-Beta
- Compose Multiplatform version*: 1.5.10-beta01
- OS version(s)* (required for Desktop and iOS issues): macOs
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a Box composable
2. Add SwingPanel
3. Add any other composable under the SwingPanel
4. The composable is not going to be visible 

**Expected behavior**
The composable should be on top of the SwingPanel

**Additional context**
In my case I'm using JavaFX WebView, I'm not sure if it's a common problem or related to using JavaFX

**Comment by MatkovIvan** [comment] 2023-09-28 06:25
It looks like duplicate of #2926

**Closed** 2023-09-29 10:37 UTC
Labels: bug, duplicate

**Comment by okushnikov** [comment] 2024-07-14 16:09
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3739">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
