### ISSUE TITLE
Support Compose.material on JS target

### ISSUE THREAD

**Issue by MEJIOMAH17** [JetBrains/compose-multiplatform#1369] opened 2021-11-07 17:04 UTC
Currently I can't use compose.foundation and compose.material on JS target. Do you have any plans for adoption ui components from android compose to js target?

**Comment by arkivanov** [comment] 2021-11-07 17:58
Partially duplicate of https://github.com/JetBrains/compose-jb/issues/1257

**Comment by MEJIOMAH17** [comment] 2021-11-22 09:57
@akurasov  no, I won't. Rename it

**Comment by Schahen** [comment] 2024-04-12 08:59
we lucky to find ourselves in situation when material is supported in both wasm and js )

**Closed by Schahen** 2024-04-12 08:59 UTC
Labels: enhancement, web

**Comment by okushnikov** [comment] 2024-08-26 15:41
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6007">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
