### ISSUE TITLE
[Windows] Selection & Key Press Trigger IllegalStateException in OutlinedTextField on Desktop

### ISSUE THREAD

**Issue by pisfer** [JetBrains/compose-multiplatform#3880] opened 2023-10-29 20:51 UTC
**Describe the bug**
I get an error on Desktop when using OutlinedTexfField. When I select a text and try to use space key (or any other key to clear the text) while holding a selection I get following error:
`Suppressed: java.lang.IllegalStateException: OffsetMapping.transformedToOriginal returned invalid mapping: 15 -> 15 is not in range of original text [0, 13]`
It seems to come from `VisualTransformation` but I do not use any custom implementation of it, so it is most likely an internal problem.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): windows 11
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 19

**To Reproduce**
Launch the following code and start to enter some text. Then select (and hold the selection) just a part of it and hit the space key once the text that was selected is changed to a space and then (mouse button is still pressed) you move the selection to another side, you get the error.
Here is a code:
```
val text = remember { mutableStateOf(TextFieldValue("0123456789")) }
OutlinedTextField(
    text.value,
    { textFieldValue ->
        text.value = textFieldValue
    },
    Modifier
        .height(200.dp),
    label = { Text("Some text") }
)
```

**Expected behavior**
No errors.

Full stack trace:
```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:37)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:42)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:28)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:231)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:91)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: java.lang.IllegalStateException: OffsetMapping.transformedToOriginal returned invalid mapping: 13 -> 13 is not in range of original text [0, 9]
		at androidx.compose.foundation.text.ValidatingOffsetMapping.transformedToOriginal(ValidatingOffsetMapping.kt:69)
		at androidx.compose.foundation.text.selection.TextFieldSelectionManager.updateSelection(TextFieldSelectionManager.kt:776)
		at androidx.compose.foundation.text.selection.TextFieldSelectionManager.access$updateSelection(TextFieldSelectionManager.kt:64)
		at androidx.compose.foundation.text.selection.TextFieldSelectionManager$mouseSelectionObserver$1.onDrag-3MmeM6k(TextFieldSelectionManager.kt:329)
		at androidx.compose.foundation.text.selection.TextSelectionMouseDetectorKt$mouseSelectionDetector$2$2.invoke(TextSelectionMouseDetector.kt:105)
		at androidx.compose.foundation.text.selection.TextSelectionMouseDetectorKt$mouseSelectionDetector$2$2.invoke(TextSelectionMouseDetector.kt:104)
		at androidx.compose.foundation.gestures.DragGestureDetectorKt.drag-jO51t88(DragGestureDetector.kt:115)
		at androidx.compose.foundation.gestures.DragGestureDetectorKt$drag$1.invokeSuspend(DragGestureDetector.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
		at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
		at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
		at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:672)
		at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:549)
		at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:571)
		at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:292)
		at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
		at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
		at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:156)
		at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:93)
		at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:97)
		at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:362)
		at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:355)
		at androidx.compose.ui.ComposeScene.processMove(ComposeScene.skiko.kt:686)
		at androidx.compose.ui.ComposeScene.processPointerInput(ComposeScene.skiko.kt:612)
		at androidx.compose.ui.ComposeScene.access$processPointerInput(ComposeScene.skiko.kt:68)
		at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:245)
		at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:245)
		at androidx.compose.ui.SyntheticEventSender.sendInternal(SyntheticEventSender.kt:157)
		at androidx.compose.ui.SyntheticEventSender.send(SyntheticEventSender.kt:64)
		at androidx.compose.ui.ComposeScene.sendPointerEvent-WlEVilQ(ComposeScene.skiko.kt:581)
		at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU(ComposeScene.skiko.kt:523)
		at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU$default(ComposeScene.skiko.kt:506)
		at androidx.compose.ui.awt.ComposeBridge_desktopKt.onMouseEvent(ComposeBridge.desktop.kt:405)
		at androidx.compose.ui.awt.ComposeBridge_desktopKt.access$onMouseEvent(ComposeBridge.desktop.kt:1)
		at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:245)
		at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:238)
		at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:126)
		at androidx.compose.ui.awt.ComposeBridge.onMouseEvent(ComposeBridge.desktop.kt:238)
		at androidx.compose.ui.awt.ComposeBridge.access$onMouseEvent(ComposeBridge.desktop.kt:59)
		at androidx.compose.ui.awt.ComposeBridge$attachComposeToComponent$4.mouseDragged(ComposeBridge.desktop.kt:224)
		at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6668)
		at java.desktop/java.awt.Component.processEvent(Component.java:6389)
		at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
		at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
		at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
		at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
		... 6 more
Caused by: java.lang.NoClassDefFoundError: android/os/Build$VERSION
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:38)
	... 29 more
Caused by: java.lang.ClassNotFoundException: android.os.Build$VERSION
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 31 more
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: OffsetMapping.transformedToOriginal returned invalid mapping: 13 -> 13 is not in range of original text [0, 9]
	at androidx.compose.foundation.text.ValidatingOffsetMapping.transformedToOriginal(ValidatingOffsetMapping.kt:69)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager.updateSelection(TextFieldSelectionManager.kt:776)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager.access$updateSelection(TextFieldSelectionManager.kt:64)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManager$mouseSelectionObserver$1.onDrag-3MmeM6k(TextFieldSelectionManager.kt:329)
	at androidx.compose.foundation.text.selection.TextSelectionMouseDetectorKt$mouseSelectionDetector$2$2.invoke(TextSelectionMouseDetector.kt:105)
	at androidx.compose.foundation.text.selection.TextSelectionMouseDetectorKt$mouseSelectionDetector$2$2.invoke(TextSelectionMouseDetector.kt:104)
	at androidx.compose.foundation.gestures.DragGestureDetectorKt.drag-jO51t88(DragGestureDetector.kt:115)
	at androidx.compose.foundation.gestures.DragGestureDetectorKt$drag$1.invokeSuspend(DragGestureDetector.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:672)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:549)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:571)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:292)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:156)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:93)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:97)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:362)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:355)
	at androidx.compose.ui.ComposeScene.processMove(ComposeScene.skiko.kt:686)
	at androidx.compose.ui.ComposeScene.processPointerInput(ComposeScene.skiko.kt:612)
	at androidx.compose.ui.ComposeScene.access$processPointerInput(ComposeScene.skiko.kt:68)
	at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:245)
	at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:245)
	at androidx.compose.ui.SyntheticEventSender.sendInternal(SyntheticEventSender.kt:157)
	at androidx.compose.ui.SyntheticEventSender.send(SyntheticEventSender.kt:64)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-WlEVilQ(ComposeScene.skiko.kt:581)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU(ComposeScene.skiko.kt:523)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU$default(ComposeScene.skiko.kt:506)
	at androidx.compose.ui.awt.ComposeBridge_desktopKt.onMouseEvent(ComposeBridge.desktop.kt:405)
	at androidx.compose.ui.awt.ComposeBridge_desktopKt.access$onMouseEvent(ComposeBridge.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:245)
	at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:238)
	at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:126)
	at androidx.compose.ui.awt.ComposeBridge.onMouseEvent(ComposeBridge.desktop.kt:238)
	at androidx.compose.ui.awt.ComposeBridge.access$onMouseEvent(ComposeBridge.desktop.kt:59)
	at androidx.compose.ui.awt.ComposeBridge$attachComposeToComponent$4.mouseDragged(ComposeBridge.desktop.kt:224)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6668)
	at java.desktop/java.awt.Component.processEvent(Component.java:6389)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@5cececc, androidx.compose.runtime.BroadcastFrameClock@46a20a23, StandaloneCoroutine{Cancelling}@164cbfc6, FlushCoroutineDispatcher@7c7f7638]
```

**Comment by eymar** [comment] 2023-10-30 12:57
Hi @pisfer , I tried to reproduce according to your report, but it didn't crash for me.
I recorded a video of my actions or I miss something. Does it match your steps?
Could you please record a video with correct reproducing steps if my one is wrong?


https://github.com/JetBrains/compose-multiplatform/assets/7372778/25c8ec32-6a25-4db4-a02f-2cf9c2847265

**Comment by pisfer** [comment] 2023-10-30 13:39
Yeah, I just noticed that it happens specifically when you select the last part of the text. I attached a video. Thanks for the help!

https://github.com/JetBrains/compose-multiplatform/assets/26014147/e992dd21-a478-4c2d-9529-9ec263233b06

**Comment by eymar** [comment] 2023-10-30 13:40
Thanks! Reproduced now

**Comment by gutnikvk** [comment] 2024-02-27 13:53
Any hope of this being fixed? Running into this problem in a production app.

**Comment by m-sasha** [comment] 2024-02-27 17:04
> It looks like you release the mouse button after typing,

You can see that I'm not by the circle around the cursor. Can you try this with Compose 1.6.0-rc03?

**Comment by gutnikvk** [comment] 2024-02-27 17:12
I see what you meant by the latest release now. Yes, the issue seems to be resolved in 1.6.0-rc03. Do you know, by any chance, when it's going to become a full release?

**Comment by m-sasha** [comment] 2024-02-27 17:14
It's planned for tomorrow.

**Closed** 2024-02-27 17:15 UTC
Labels: bug, text, reproduced

**Comment by okushnikov** [comment] 2024-07-14 15:54
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3880">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
