### ISSUE TITLE
Unbound public symbol IrSimpleFunctionPublicSymbolImp error in iOS build

### ISSUE THREAD

**Issue by sunildhiman90** [JetBrains/compose-multiplatform#3175] opened 2023-05-17 04:47 UTC
**Describe the bug**
After adding voyager library in compose multiplatform project, getting this error in ios build:

```error: There are still 6 unbound symbols after generation of IR module <shared>:
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: cafe.adriel.voyager.navigator.tab/Tab.icon.<get-icon>|-5764684600227404327[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: cafe.adriel.voyager.navigator.tab/Tab.options.<get-options>|7766868889533212780[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: cafe.adriel.voyager.navigator.tab/Tab.title.<get-title>|371973571756195065[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: androidx.compose.foundation.lazy/LazyListScope.item|-2398404341226065315[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: androidx.compose.foundation.lazy/LazyListScope.items|8564101490881923997[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: androidx.compose.foundation.lazy/LazyListScope.stickyHeader|431226128286809998[0]

This could happen if there are two libraries, where one library was compiled against the different version of the other library than the one currently used in the project. Please check that the project configuration is correct and has consistent versions of dependencies.
error: Compilation finished with errors
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- voyager: 1.0.0-rc06

**To Reproduce**
Steps and/or the code snippet to reproduce the behaviour:
1. I have created a reproducer for this issue, please checkout this fork: 
https://github.com/sunildhiman90/compose-multiplatform-template-with-navigation
and choose the branch **with-voyager-navigation**
2. Try to build for iosApp.
3. It should reproduce this bug

**Comment by TheMrDOC111** [comment] 2023-05-19 16:54
I have same problem

**Comment by eymar** [comment] 2023-05-22 13:47
There is a workaround:
The idea is to not use `cocoapods` in shared module, but create an extra module `iosEntryPoint` with `cocoapods` but without Compose. `iosEntryPoint` should only provide a ViewController:

```
fun AppController() = MainViewController()
```
And then later in can be used in ContentView.swif:
```
func makeUIViewController(context: Context) -> UIViewController {
        Main_iosKt.AppController()
    }
```

Created a patch which can be applied to the reproducer you provided: https://gist.github.com/eymar/c488eeed7df85d2024fa33090d1a66ca

**Comment by sunildhiman90** [comment] 2023-05-26 15:56
> @sunildhiman90 
> Hi, you use `internal class` instead of `class` for `Tab`.  
> It helped me.

Hi@adtarassov, Thanx, yes that will also fix this issue, But it may arise in other libraries as well. Then we will have to make similar changes in other libraries as well.  So thats why as of now i did workaround mentioned here: https://github.com/JetBrains/compose-multiplatform/issues/3175#issuecomment-1557252486

Because i wanted a central common fix/workaround for this. So If we do this workaround, Then we will not have to worry about this issue anymore in other libraries until its fix available in compose.

**Comment by sunildhiman90** [comment] 2023-05-28 08:38
Hi @eymar, Actually after using that approach of separate iosEntryPoint module: https://github.com/JetBrains/compose-multiplatform/issues/3175#issuecomment-1557252486, now i am facing this issue in ios app:

`org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: add_post_icon.png`

Resources are missing i think now. do we have any workaround for that? May be its not able to copy resources for ios. But they are working fine in all other platforms.

**Comment by paringer** [comment] 2023-08-09 17:43
Hi, I have same problem, with voyager navigation, final **data class TabOptions**, used inside interface Tab, **is not exported**, it is either: does not open, final class, which was wrapped somehow unsuccessfully, or does not have generated getters and setters, or getters and setters are not exported, or interfaces can not have val fields after being exported, I have no idea, what wrong with compiler. It helped to use internal but I can not use object construction for tabs

**Comment by babramovitch** [comment] 2023-08-10 23:36
Setting it to internal gets it compiling for me as well

**Comment by JoelKanyi** [comment] 2023-08-29 04:57
Adding the `internal` keyword on my Tabs worked:
```
internal object HomeTab : Tab {
```

**Comment by shriharsha-srb** [comment] 2023-08-29 20:48
+1

**Comment by fajarazay** [comment] 2023-08-30 09:44
worked like a charm 👍

**Comment by fajarazay** [comment] 2023-08-30 09:44
> Adding the `internal` keyword on my Tabs worked:
> 
> ```
> internal object HomeTab : Tab {
> ```


worked like a charm 👍

**Comment by kochchy** [comment] 2024-03-12 20:05
cant have tab internal because it is in another module, any other solution?

**Comment by eymar** [comment] 2024-03-13 06:32
Please try to use voyager 1.1.0-alpha03 and Compose Multiplatform 1.6.0

The issue was fixed in the compiler plugin a while ago, but the libraries should also be recompiled and I see that latest alpha of Voyager depends on CM 1.6.0-rc02 - so it should work IMO 

This way no "add internal" workarounds should be necessary

**Comment by eymar** [comment] 2024-03-13 06:33
I'm closing this issue as fixed.

**Closed by eymar** 2024-03-13 06:33 UTC
Labels: bug, compiler, reproduced

**Comment by okushnikov** [comment] 2024-07-14 15:07
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3175">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
