### ISSUE TITLE
Quickly dragging the window causes @Composable to stretch

### ISSUE THREAD

**Issue by whitescent** [JetBrains/compose-multiplatform#4980] opened 2024-06-16 16:26 UTC
Platforms tested: 
- Windows 11 23H2 22631.3737 x64 (running with problems)
- macOS 15 (running fine)
- JDK: 17 (Jetbrains runtime)
- Gradle: 8.7

Dependent version:
- compose = "1.6.8"
- kotlin = "2.0.0"
- compose-plugin = "1.6.10"

https://github.com/JetBrains/compose-multiplatform/assets/31311826/9adbb87f-1b04-4c28-8801-118ae59942e2

https://github.com/JetBrains/compose-multiplatform/assets/31311826/aa087113-3028-4fee-9e0f-a1659fae9195

Not sure if this is a duplicate issue, if it is, feel free to close this issue

**Comment by MatkovIvan** [comment] 2024-06-17 07:47
Duplicate of #4521

Should be improved/fixed by https://github.com/JetBrains/skiko/pull/923

**Closed by MatkovIvan** 2024-06-17 07:47 UTC
Labels: bug, windows, directx

**Comment by okushnikov** [comment] 2024-08-26 13:37
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4980">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
