### ISSUE TITLE
Scan NFC tag for IOS 

### ISSUE THREAD

**Issue by joemockdao** [JetBrains/compose-multiplatform#3773] opened 2023-10-04 16:14 UTC
**Describe the bug**
I have this error, "tagReaderSession(session: NFCTagReaderSession, didDetectTags: List<*>) gives the error “Delegate does not implement -tagReaderSession:didDetectTags: method” .
The very strange thing is that the tagReaderSessionDidBecomeActive func is correctly called instead
Could this be a recognized bug?
I read that with swift the delegate implementation code is this “tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag]) ” but in kotlin it is different “tagReaderSession(session: NFCTagReaderSession, didDetectTags: List<*>)”

Below my code
Thank you for help

 actual class NfcReader private actual constructor() : BaseNfcImplementation() {
    private var session: NFCTagReaderSession? = null
    private var tag: NFCISO7816TagProtocol? = null
    actual constructor(readingInterface: NfcReading, androidContext: Any?) : this() {
        this.readingInterface = readingInterface
    }

    override fun connect(iosMessage: String, actionDone: () -> Unit) {
        session = NFCTagReaderSession(NFCPollingISO14443, NfcReaderIos { ok, mTag ->
            if (ok) {
                tag = mTag
                actionDone.invoke()
            } else
                readingInterface.error("no connection to nfc tag..")
        }, null)
        session?.alertMessage = iosMessage
        session?.beginSession()
    }

    @OptIn(ExperimentalForeignApi::class)
    @Suppress("CAST_NEVER_SUCCEEDS")//for cast in objective c objects but obviously right!!
    override val readCie: ReadCie
        get() = ReadCie(object : OnTransmit {
            override fun addSha1ByteArray(a5NoHash: ByteArray): ByteArray {
                val digest = UByteArray(CC_SHA256_DIGEST_LENGTH)
                a5NoHash.usePinned { inputPinned ->
                    digest.usePinned { digestPinned ->
                        CC_SHA256(inputPinned.addressOf(0), a5NoHash.size.convert(), digestPinned.addressOf(0))
                    }
                }
                return digest.toByteArray()
            }

            override fun convertNis(rawNis: ByteArray) = NSString.create(contentsOfFile = rawNis.decodeToString(), NSUTF8StringEncoding, null) as String
            override fun error(why: String) {
                disconnect()
                readingInterface.error(why)
            }

            override fun sendCommand(apdu: ByteArray, message: String): ApduResponse {
                readingInterface.onTransmit(message)
                var response: ApduResponse? = null
                tag?.sendCommandAPDU(
                    NFCISO7816APDU(
                        NSData.create(contentsOfFile = apdu.decodeToString())!!
                    )
                ) { data, _, _, nsError ->
                    response = if (nsError != null) {
                        val (filteredByteArray, temp) = (data as ByteArray).transmitLogic()
                        ApduResponse(filteredByteArray, temp)
                    } else
                        ApduResponse(byteArrayOf(), byteArrayOf())
                }
                while (response == null) {
                    //wait
                }
                return response!!
            }
        }, readingInterface)

    override fun disconnect() {
        session?.invalidateSession()
    }

    actual fun nfcReaderAvailable() = NFCTagReaderSession.readingAvailable
    class NfcReaderIos(
        private val itsOk: (ok: Boolean, tag: NFCISO7816TagProtocol?) -> Unit
    ) : NSObject(), NFCTagReaderSessionDelegateProtocol {
        override fun tagReaderSessionDidBecomeActive(session: NFCTagReaderSession) {
            Log.i("NFC TAG", "ACTIVE")
        }

        override fun tagReaderSession(session: NFCTagReaderSession, didDetectTags: List<*>) {
            Log.i("NFC TAG", "didDetectTags:$didDetectTags")
            val tag = didDetectTags.firstOrNull() as? NFCISO7816TagProtocol
            if (tag == null)
                itsOk.invoke(false, null)
            else {
                session.connectToTag(tag) {
                    itsOk.invoke(it != null, tag)
                }
            }
        }

        override fun tagReaderSession(session: NFCTagReaderSession, didInvalidateWithError: NSError) {
            Log.e("IOS ERROR", didInvalidateWithError.code.toString())
        }
    }
}

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): IOS 16-17
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
Open the app, scan the NFC tag for my Identity card

**Expected behavior**
Recognize NFC my identity card

**Screenshots**

![IMG_2415](https://github.com/JetBrains/compose-multiplatform/assets/8806969/81a7e5e9-99b5-4112-ae24-d42db65dcd1a)

**Comment by carlodek** [comment] 2023-10-05 07:20
Hi, I got same problem. Swift code should look like this:
```swift
 nonisolated func tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag]) {
        guard let tag = tags.first, case .iso7816(let mifare) = tag else {
            session.alertMessage = "Not found."
            return
        }
    }
```
Maybe the problem is on generic object passed to List?
Error shown in xcode is:
45[NFCTagReaderSession didDetectTags:connectedTagIndex:]:159 Delegate does not implement -tagReaderSession:didDetectTags: method

**Comment by pjBooms** [comment] 2023-10-06 15:33
It seems to be general Kotlin/Native ObjC interop issue. Can you file the same here: https://youtrack.jetbrains.com/issues/KT ?

**Comment by joemockdao** [comment] 2023-10-09 14:22
> It seems to be general Kotlin/Native ObjC interop issue. Can you file the same here: https://youtrack.jetbrains.com/issues/KT ?

yes, my problem is the same as reported in the YouTrack link, unfortunately this problem seems to still be present.
Thank you for help

**Comment by pjBooms** [comment] 2023-10-09 14:32
>my problem is the same as reported in the YouTrack link

What issue are you mentioing?

**Comment by joemockdao** [comment] 2023-10-09 14:34
> > my problem is the same as reported in the YouTrack link
> 
> What issue are you mentioning?

This is link https://youtrack.jetbrains.com/issue/KT-54114/Kotlin-Multiplatform-iOS-Native-CoreNFC-Delegate-does-not-implement-tagReaderSessiondidDetectTags-method

**Comment by pjBooms** [comment] 2023-10-09 15:07
THank you. If you provide more information to them you may re-open the issue. As I guess they need reproducible example to look more closely the issue. Closing this issue because it does not related to CMP directly

**Closed by pjBooms** 2023-10-09 15:07 UTC
Labels: bug, ios, native

**Comment by diarmuidmcg** [comment] 2024-05-11 15:48
Not ideal, but this solution worked for me:

```    @Suppress("CONFLICTING_OVERLOADS")
    override fun readerSession(session: NFCNDEFReaderSession, didDetectNDEFs: List<*>) {
    }

    @Suppress("CONFLICTING_OVERLOADS")
    override fun readerSession(session: NFCNDEFReaderSession, didDetectTags: List<*>) {```
    
    Then i was able to cast the lists as expected:
    ```
     val firstTag = didDetectTags.firstOrNull()

        if (firstTag != null) {
            val tag: NFCNDEFTagProtocol = firstTag as NFCNDEFTagProtocol```

**Comment by okushnikov** [comment] 2024-08-26 13:40
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3773">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
