### ISSUE TITLE
Different behavior between iOS and Android when clicking on item inside scrollable container

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3132] opened 2023-05-07 07:24 UTC
```Kotlin
Column(
    Modifier
        .fillMaxSize()
        .verticalScroll(rememberScrollState()),
    horizontalAlignment = Alignment.CenterHorizontally,
    verticalArrangement = Arrangement.spacedBy(10.dp)
) {
    repeat(10) {
        Button(
        modifier = Modifier.size(200.dp, 400.dp),
        onClick = {}
        ) {
            Text("Hello, World!")
        }
    }
}
```

### iOS

https://user-images.githubusercontent.com/57913130/236113943-8fd5c430-ea67-4a88-b81e-2431c38dd395.mp4

Desktop now has behavior like in iOS. Maybe it's good for the Desktop.

### Android
https://user-images.githubusercontent.com/57913130/236114121-779c7474-8f03-43fc-936c-ca8d73e2f202.webm

Sample project with Desktop + iOS + Android: https://github.com/dima-avdeev-jb/different-scroll-behavior-on-item-click
Slack discussion: https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1683118890415769
Original sample project: https://github.com/AlexYudenkov/compose-multiplatform-compose-android-example

**Comment by m-sasha** [comment] 2023-05-07 08:47
As discussed, the reason for this is that `Modifier.clickable` makes the item focused when clicked, which in turn activates the "bringIntoView" scroll mechanism.

**Comment by pjBooms** [comment] 2023-05-08 11:36
The root cause of the issue is the following PR: https://github.com/JetBrains/compose-multiplatform-core/pull/257
Now focus management is different on Android and other platforms causing this different behavior.

We need to find a way to configure focus management, say introduce some configuration that will or won't transfer focus automatically for clickable widgets. 

**Workaround for the issue:**  

Use `focusProperties { canFocus = false }` modifier for a clickable widget inside scrollable container  to return to Android behavior.

**Comment by SebastianAigner** [comment] 2023-07-27 20:55
This issue (and workaround) were also mentioned on https://exyte.com/blog/jetpack-compose-multiplatform.

**Comment by okushnikov** [comment] 2024-07-14 16:15
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3132">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:19 UTC
Labels: bug, ios, reproduced
