### ISSUE TITLE
After update to 1.6.0-rc02 `compileCommonMainKotlinMetadata` fails with "Unresolved reference: launch" on `CoroutineScope#launch`

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#4326] opened 2024-02-17 15:19 UTC
**Describe the bug**

I'm not sure if this is actually a bug or not. My module with Compose code doesn't have direct dependency on `kotlinx-coroutines`, as the dependency has been used to be exposed as `api` from Compose. As I have been able to use coroutines without adding the dependency explicitly. But after updating Compose from `1.6.0-alpha01` to `1.6.0-rc02`, `kotlinx.coroutines` imports are unresolved and `compileCommonMainKotlinMetadata` task fails. Though, tasks like `jvmJar`, `assembleDebug`, `jsJar`, etc. - all work fine.

**Affected platforms**

Select one of the platforms below:

- Common

**Versions**
- Kotlin version*: 1.9.21, 1.9.22
- Compose Multiplatform version*: 1.6.0-rc02
- OS version(s)* (required for Desktop and iOS issues): macOS 13.5.2 (22G91)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): jbr-17

**To Reproduce**

Don't add `kotlinx-coroutines` dependency to a module with Compose.

Code: 

```kotlin
import kotlinx.coroutines.launch
```

Run: `./gradlew compileCommonMainKotlinMetadata`

Error:

```
> Task :extensions-compose:compileCommonMainKotlinMetadata FAILED
e: file:///....... Unresolved reference: coroutines
```

I'm also not able to use `rememberCoroutineScope`, the error is:

```
> Task :extensions-compose:compileCommonMainKotlinMetadata FAILED
e: file:///........ Cannot access class 'kotlinx.coroutines.CoroutineScope'. Check your module classpath for missing or conflicting dependencies
```

**Expected behavior**

I think it should work work fine without adding `kotlinx-coroutines` explicitly, but I might be wrong.

**Comment by arkivanov** [comment] 2024-02-17 15:33
Also, adding `kotlinx-coroutines` as `api` to one module only solves the compilation in that particular module, other dependent modules still do not compile and also require adding `kotlinx-coroutines` to them.

**Comment by eymar** [comment] 2024-02-19 07:06
Do you have wasmJs target? What if you try to disable it? Do you have a link to such project?

**Comment by alexzhirkevich** [comment] 2024-02-19 07:45
Same happened after upgrading coroutines to `1.8.0` in other modules. Coroutines dependencies became unresolved in modules with compos and without coroutines declared explicitly. wasmJs enabled. With coroutines `1.8.0-RC2` everything works well.

**Comment by eymar** [comment] 2024-02-19 08:24
@alexzhirkevich is your project available on GitHub? Could you please share the link and the branch?

**Comment by alexzhirkevich** [comment] 2024-02-19 08:34
It's not, but i'll try to create a smal reproducer. I guess if you'll update coroutines to 1.8.0, everything should be fine

**Comment by arkivanov** [comment] 2024-02-19 09:46
Yes I have wasmJs targey. You can try this branch in Decompose: https://github.com/arkivanov/Decompose/tree/v3.0

If you remove coroutines deps [here](https://github.com/arkivanov/Decompose/blob/3a3466057ea7dda2e1a305f704818bc1b635b193/extensions-compose/build.gradle.kts#L53) and [here](https://github.com/arkivanov/Decompose/blob/3a3466057ea7dda2e1a305f704818bc1b635b193/sample/shared/compose/build.gradle.kts#L68), then it should start failing again.

**Comment by eymar** [comment] 2024-02-19 11:38
Thanks! Reproduced it in Decompose. But having troubles to reproduce it is a separate simple project.
___

I thought it's somehow caused by web targets. But if I remove only an android target and keep the rest enabled, then it works. Or if I keep only android and jvm targets then it works too, but breaks if I add any web or native target. So android + native/web doesnt' work.


removing `implementation(deps.jetbrains.kotlinx.kotlinxCoroutinesSwing)` helps too. 
It's surprising to me, since it's added only in the test source set, which shouldn't be involved in commonMainMedatada compilation (afaiu). 


Continue investigation...

**Comment by eymar** [comment] 2024-02-19 16:02
@alexzhirkevich Does adding `implementation(deps.jetbrains.kotlinx.kotlinxCoroutinesCore)` explicitly (either to commonMain or androidMain) help in your case too?

**Comment by alexzhirkevich** [comment] 2024-02-19 16:36
Yep

**Comment by alexzhirkevich** [comment] 2024-02-19 16:57
@eymar One more reproducer if needed 
```
git clone https://github.com/alexzhirkevich/compose-4326 & cd compose-4326 & ./gradlew core:compileCommonMainKotlinMetadata
```

There are 2 dependencies in commonTest including coroutines.test. If you remove them or change coroutines from 1.8.0 to 1.8.0-RC2  in toml everything works fine wtf :D.

**Comment by eymar** [comment] 2024-02-19 18:58
Thanks everyone for reproducers!
The issue is reported to kotlin - https://youtrack.jetbrains.com/issue/KT-65954

In compose multiplatform 1.6.0 we won't update coroutines versions. Because it's already rc2 and updating a dependency is not desirable. We'll do that in 1.6.1.

For 1.6.0 and if such an issue arises, we'll advise to use the workaround with adding an explicit dependency to `coroutines-core` in commoMain.

**Comment by antohaby** [comment] 2024-02-20 07:31
Thank you very much for reporting this. It discovers an awful flaw in our dependency resolution mechanism. We are targeting a fix for this in 1.9.23

**Comment by arkivanov** [comment] 2024-08-06 23:02
Seems working with Kotlin 2.0.10. Thanks!

**Comment by okushnikov** [comment] 2024-08-26 13:24
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4326">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:27 UTC
Labels: bug, external bug, regression
