### ISSUE TITLE
Skottie animations don't redraw properly on Kotlin/Native (iOS and web)

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3149] opened 2023-05-10 19:54 UTC
**Describe the bug**
Animation is stuck on the 1st frame. Reading state reference inside `drawIntoCanvas` block solves the issue. 

May be it is a bug cause it works normally on desktop.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

--- 
Btw, can it be used in common code with android target by any chance? I added skia dependency and binaries to androidMain, but getting compile error on [this](https://github.com/JetBrains/compose-multiplatform-core/blob/4d767f3e28fe6fc61b776db133fcef6de4dace90/compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/LottieAnimation.kt#L60) line:

`
e: file:///.../compose-multiplatform-ios-android-template/shared/src/commonMain/kotlin/App.kt:55:26 Type mismatch: inferred type is NativeCanvas /* = android.graphics.Canvas */ but org.jetbrains.skia.Canvas was expected
`

**Comment by MatkovIvan** [comment] 2023-05-10 20:45
> animations don't redraw properly on iOS

That's why it was added 😅 (see description in https://github.com/JetBrains/compose-multiplatform-core/pull/560)

We're using that `mpp` app to try the things without publishing any packages (it depends on project sources). Please use this folder as a source of official examples: https://github.com/JetBrains/compose-multiplatform/tree/master/examples

> can it be used in common code with android target by any chance?

Please wait proper support or use `expect`/`actual`. Also please note that skiko/skia is implementation details and any references to it cannot be considered as stable API.

> I added skia dependency and binaries to androidMain

Compose on android doesn't use "our" skia/skiko, I don't think mixing this is a good idea and doubt that it will work.

**Comment by alexzhirkevich** [comment] 2023-05-10 20:52
Oh, i see. Thanks for demo and help :)

**Comment by MatkovIvan** [comment] 2023-05-11 09:12
Thanks to @eymar, we found the root cause of this problem. It's related to K/Native compose compiler plugin, so it's not only about iOS, but web target is affected too.
The problem here is about incorrect detection "stability" of external types. External types here stands for classes from libraries that compiled without compose compiler plugin. Also, there might be more cases with types declared in module-dependencies at the moment. In this case using `Animation` type doesn't trigger re-drawing the canvas. That's why adding _any_ mutable state into `drawIntoCanvas` scope resolves the issue.

I'm reopening this issue to track this problem publicly.

**Comment by ivfr89** [comment] 2023-05-11 11:40
> **Describe the bug** I tried [new example with lottie animation](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/LottieAnimation.kt) from @MatkovIvan on iOS. Animation is stuck on the 1st frame. Reading `time` reference inside `drawIntoCanvas` block solves the issue.
> 
> May be it is a bug cause it works normally on desktop.
> 
> **Affected platforms** Select one of the platforms below:
> 
> * iOS
> 
> **Versions**
> 
> * Kotlin version*: 1.8.20
> * Compose Multiplatform version*: 1.4.0
> 
> Btw, can it be used in common code with android target by any chance? I added skia dependency and binaries to androidMain, but getting compile error on [this](https://github.com/JetBrains/compose-multiplatform-core/blob/4d767f3e28fe6fc61b776db133fcef6de4dace90/compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/LottieAnimation.kt#L60) line:
> 
> `e: file:///.../compose-multiplatform-ios-android-template/shared/src/commonMain/kotlin/App.kt:55:26 Type mismatch: inferred type is NativeCanvas /* = android.graphics.Canvas */ but org.jetbrains.skia.Canvas was expected`

Same thing happens to me

**Comment by ivfr89** [comment] 2023-06-28 08:05
I was able to achieve this in iOS using this approach. Of couse is a solution that could be improve but it works for me

`@Composable
fun LottieAnimation(
    modifier: Modifier,
    animationRoute: String,
    restart: Boolean,
    loading: @Composable () -> Unit = {},
) {
    var animation by remember { mutableStateOf<Animation?>(null) }

    LaunchedEffect(Unit) {
        animation = Animation.makeFromData(Data.makeFromBytes(animationRoute.readByteArray()))
    }

    when (val value = animation) {
        null -> loading()
        else -> SkiaAnimation(
            modifier = modifier,
            animation = value,
            restart = restart
        )
    }
}

@Composable
private fun SkiaAnimation(
    modifier: Modifier,
    animation: Animation,
    restart: Boolean,
) {
    var elapsedSeconds: Float by remember { mutableStateOf(DefaultElapsedSeconds) }
    var lastTimeInMillis: Long by remember { mutableStateOf(DefaultLastTimeInMillis) }
    val invalidationController = remember { InvalidationController() }


    Surface(
        modifier = modifier
            .drawAnimationOnCanvas(
                animation = animation,
                time = elapsedSeconds,
                invalidationController = invalidationController
            )
    ) {}


    LaunchedEffect(Unit) {
        while (this.coroutineContext[Job]?.isActive == true) {
            withFrameMillis { absoluteMillis ->
                if (lastTimeInMillis > DefaultLastTimeInMillis) {
                    val deltaMillis =
                        (absoluteMillis - lastTimeInMillis)
                    elapsedSeconds += deltaMillis / MillisecondsInOneSecond
                }
                lastTimeInMillis = absoluteMillis
            }

            if (elapsedSeconds >= animation.duration) {
                elapsedSeconds %= animation.duration
            }
        }
    }
}

private fun Modifier.drawAnimationOnCanvas(
    animation: Animation,
    time: Float,
    invalidationController: InvalidationController
): Modifier = this then drawWithContent {
    drawIntoCanvas { canvas ->
        animation.seekFrameTime(time, invalidationController)
        animation.render(
            canvas = canvas.nativeCanvas,
            dst = Rect.makeWH(size.width, size.height),
        )
    }
}

private const val MillisecondsInOneSecond = 1000F
private const val DefaultElapsedSeconds = 0f
private const val DefaultLastTimeInMillis = 0L`

and readByteArray could be something like this, for the iOS part:

```
actual fun ResourceName.readByteArray(): ByteArray {
    val filePath = NSBundle.mainBundle.pathForResource(name = this, ofType = null)
        ?: throw Exception("No resource found at path: $this")
    val url = NSURL.fileURLWithPath(filePath)
    val data = NSData.dataWithContentsOfURL(url) as NSData
    return data.bytes!!.readBytes(data.length.toInt())
```

**Comment by MatkovIvan** [comment] 2023-06-28 08:15
@alexzhirkevich please note that workaround for code that we have [in our reproduction](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/LottieAnimation.kt) was mentioned in the first message here:

> Reading time reference inside drawIntoCanvas block solves the issue.

We are keeping this issue open to track problem with "stability" types in compiler plugin

**Comment by alexzhirkevich** [comment] 2023-06-28 12:29
@MatkovIvan Yep, I undestood that from the 1st time. Not sure why u tag me 😅 (prev comment was not from me)

**Comment by MatkovIvan** [comment] 2023-06-28 15:14
Ooops, yeah it was supposed to tag @ivfr89, sorry

**Comment by Deorigami** [comment] 2023-10-17 22:07
hey @MatkovIvan .. i the code from official sample .. but it seems doesn'e work with lottie that based on animation base64 image .. any workaround for this .. ?

**Comment by MatkovIvan** [comment] 2023-10-18 07:14
>  official sample

As mentioned above, "mpp" is our internal project for testing, **it's not an official sample**.

> doesn'e work with lottie that based on animation base64 image

Currently this format is only supported by an underlying skiko library, not Compose Multiplatform itself. Skiko just wraps Google's skia - https://skia.org/docs/user/modules/skottie/
If the issue that you are experiencing is related to skia, it's better to report it as a bug on skia's issue tracker.

Anyway, if it's not an issue about lack of recomposition on iOS/Web - it's better to file a separate issue with a clear description and steps to reproduce.

**Comment by MatkovIvan** [comment] 2024-01-19 14:19
Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/1002

**Closed by MatkovIvan** 2024-01-19 14:19 UTC
Labels: bug, compiler

**Comment by okushnikov** [comment] 2024-07-14 16:05
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3149">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
