### ISSUE TITLE
TextField cursor animation uses a lot of CPU

### ISSUE THREAD

**Issue by zoff99** [JetBrains/compose-multiplatform#4225] opened 2024-02-03 11:25 UTC
**Describe the bug**
i have a text input in my app, when i click on it to focus and enter text, cpu usage goes to 100%
as soon as i click somewhere else to shift focus, cpu goes back to normal again

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*:  1.9.22
- Compose Multiplatform version*: 1.5.11, 1.5.12
- OS version(s)* (required for Desktop and iOS issues): ubuntu 22.04
- OS architecture (x86 or arm64): x86 64bit
- JDK (for desktop issues): 17, 21

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
set focus on the textfield and not use 100% cpu

**Comment by zoff99** [comment] 2024-02-03 11:27
to reproduce:
```
git clone https://github.com/zoff99/trifa_material
cd trifa_material
git checkout cpu_burn
./gradlew run
```

the click inside the green textfield to focus it, and you see the blinking cursor.
what cpu usage with htop

**Comment by m-sasha** [comment] 2024-02-03 11:29
Could you provide a minimal reproducer?

**Comment by zoff99** [comment] 2024-02-03 11:33
whats the problem with this one?

**Comment by m-sasha** [comment] 2024-02-03 11:43
A small/minimal reproducer demonstrates the bug.

A project
1. Requires us to check out the code, potentially running malicious code in the gradle build file, or the code itself. 
2. If the code isn't minimal - requires to look through it to find the issue.
3. Often the issue turns out to be user error. Reducing the reproducer to a minimal one lowers the chance of that.
4. Having the code in the ticket makes it easier to discuss and for 3rd parties to look at. Your project could be gone a year from now, and someone looking at this ticket then wouldn't be able to understand the issue.

**Comment by zoff99** [comment] 2024-02-03 11:58
i will remove as much as i can. but as you say its probably a combination of things.

**Comment by m-sasha** [comment] 2024-02-03 12:31
Can you post the code here then?

**Comment by zoff99** [comment] 2024-02-03 12:31
https://github.com/zoff99/trifa_material/blob/cpu_burn/src/main/kotlin/Main.kt

**Comment by zoff99** [comment] 2024-02-03 12:39
you will still need some project and gradle files to run it.

**Comment by zoff99** [comment] 2024-02-03 12:39
@file:OptIn(ExperimentalComposeUiApi::class, ExperimentalFoundationApi::class)

import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.material.MaterialTheme
import androidx.compose.material.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import com.zoffcc.applications.trifa_material.trifa_material.BuildConfig
import kotlinx.coroutines.DelicateCoroutinesApi


@OptIn(DelicateCoroutinesApi::class, ExperimentalFoundationApi::class)
@Composable
@Preview
fun App()
{
    MaterialTheme {
        Column(modifier = Modifier.fillMaxSize()) {
            Row(modifier = Modifier.fillMaxWidth().height(100.dp)
                .background(Color.Green)) {
                SendMessage() { text -> //
                }
            }
        }
    }
}

@OptIn(ExperimentalFoundationApi::class)
@Composable
fun SendMessage(sendMessage: (String) -> Unit)
{
    var inputText by remember { mutableStateOf("") }
    // var show_emoji_popup by remember { mutableStateOf(false) }
    TextField(
        modifier = Modifier.fillMaxWidth(),
        value = inputText,
        onValueChange = {
        }
    )
}

fun main() = application(exitProcessOnExit = true) {
    MainAppStart()
}

@OptIn(ExperimentalComposeUiApi::class)
@Composable
private fun MainAppStart()
{
    val appIcon = painterResource("icon-linux.png")
    // ----------- main app screen -----------
    // ----------- main app screen -----------
    // ----------- main app screen -----------
    Window(
        onCloseRequest = { }, title = "TRIfA - " + BuildConfig.APP_VERSION,
        icon = appIcon,
        focusable = true,
    ) {
        App()
    }
}

**Comment by zoff99** [comment] 2024-02-14 08:31
any progress on the fix? is there an issue or PR to watch?

**Comment by m-sasha** [comment] 2024-02-14 10:23
There will be a fix, but not in 1.6.0. I'll post an update here.

**Comment by zoff99** [comment] 2024-02-21 08:51
> There will be a fix, but not in 1.6.0. I'll post an update here.

after it is merged, how can i get it in my app?

**Comment by m-sasha** [comment] 2024-02-21 09:41
> after it is merged, how can i get it in my app?

We have regular dev releases.

**Comment by zoff99** [comment] 2024-02-21 10:20
yes but those seem to miss descriptions and i don't get an answer why that is.
![compose_1512](https://github.com/JetBrains/compose-multiplatform/assets/6833516/7e0c6c2d-9e92-4c75-b585-c36d0bf4786b)
![compose_160_rc02](https://github.com/JetBrains/compose-multiplatform/assets/6833516/968fd7d2-febc-4f36-bbae-2faaf924de69)

**Comment by m-sasha** [comment] 2024-02-21 10:20
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/1113

**Closed by m-sasha** 2024-02-21 10:20 UTC
Labels: performance

**Comment by okushnikov** [comment] 2024-08-26 13:47
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4225">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
