### ISSUE TITLE
Jetbrain compose navigation with argument failed in IOS

### ISSUE THREAD

**Issue by fjr619** [JetBrains/compose-multiplatform#4657] opened 2024-04-19 08:25 UTC
**Describe the bug**
When tried to using jetbrain compose navigation (2.8.0-alpha01) with arguments (either optional parameter or not) it will make iOS app crash. It will not crash in Android with same code

**Affected platforms**
- iOS

**Versions**
- Kotlin version*:  1.9.22
- Compose Multiplatform version*: 1.6.2
- iOS Simulator 17.2
- org.jetbrains.androidx.navigation:navigation-compose:2.8.0-alpha01

```
Uncaught Kotlin exception: kotlin.IllegalArgumentException: Navigation destination that matches route TaskScreen?taskId=123 cannot be found in the navigation graph ComposeNavGraph startDestination={Destination route=HomeScreen}

```

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. create navhost and 2 composeable like list and detail, with argument to detail like DetailScreen/{id}.

**Expected behavior**
Can navigate to next screen with argument

**Comment by MatkovIvan** [comment] 2024-04-19 08:34
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/1277 and https://github.com/JetBrains/compose-multiplatform-core/pull/1289. It will be available in the next release


Duplicate of #4633

**Closed by MatkovIvan** 2024-04-19 08:34 UTC
Labels: bug, submitted

**Comment by ibenabdallah** [comment] 2024-04-21 11:02
Hello @MatkovIvan, What is the new version that contains this fix?

**Comment by MatkovIvan** [comment] 2024-04-21 11:23
@ibenabdallah `dev1593` (`2.8.0-dev1593` for navigation/lifecycle and `1.6.10-dev1593` for compose) is already available and I'll publish `2.8.0-alpha02` during next week

**Comment by ibenabdallah** [comment] 2024-04-21 16:51
@MatkovIvan Thank you for your answer, when I put the version that tells me, I get this following error, when I launched for iOS : 
_**Uncaught Kotlin exception: kotlin.IllegalStateException: NavHost requires a ViewModelStoreOwner to be provided via LocalViewModelStoreOwner**_

**Comment by MatkovIvan** [comment] 2024-04-21 18:07
Please update Compose to this dev version too. At this development stage it's better to keep them in sync.

For the particular issue: I'll revert fallback logic to avoid such requirement

**Comment by okushnikov** [comment] 2024-07-14 15:04
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4657">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
