### ISSUE TITLE
Desktop: Updating composable lambda from compose scope throw CompletionHandlerException

### ISSUE THREAD

**Issue by G0xilla** [JetBrains/compose-multiplatform#3715] opened 2023-09-20 15:24 UTC
**Describe the bug**
When I update composable lambda from compose scope I get **CompletionHandlerException**

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.1
- OS version(s)* (required for Desktop and iOS issues): Linux 6.1.53
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): OpenJDK 18.0.2

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```kotlin
fun main() {
    val content = MutableStateFlow<(@Composable () -> Unit)?>(null)

    fun updateContent() {
        // Simulate some time to update content
        Thread.sleep(1000)
        content.value = {
            Box(
                contentAlignment = Alignment.Center,
                modifier = Modifier.fillMaxSize()
            ) {
                Text("Second Screen")
            }
        }
    }

    // init content
    content.value = {
        val scope = rememberCoroutineScope()

        Box(
            contentAlignment = Alignment.Center,
            modifier = Modifier.fillMaxSize()
        ) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text("First Screen")
                Button(
                    onClick = {
                        scope.launch { updateContent() }
                    }
                ) {
                    Text("Update Content")
                }
            }
        }
    }

    application {
        Window(onCloseRequest = ::exitApplication) {
            val contentState = content.collectAsState()
            contentState.value!!.invoke()
        }
    }
}
```

To reproduce behavior click **Upadate Content** several times in a row. 

**Expected behavior**
Normally open Second Screen without exception.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/62667055/a9c6ebb4-140f-48ea-8cbf-57b797b0168f

**Comment by dima-avdeev-jb** [comment] 2023-09-23 08:37
Also reproduces on MacOS: https://github.com/dima-avdeev-jb/issue-3715-exception-desktop

**Comment by eymar** [comment] 2023-09-26 09:49
`rememberCoroutineScope` is tied to the particular point of composition. 
> Return a CoroutineScope bound to this point in the composition using the optional CoroutineContext provided by getContext. getContext will only be called once and the same CoroutineScope instance will be returned across recompositions.
This scope will be cancelled when this call leaves the composition.

> This scope will be cancelled 
it can't be cancelled in your case because you use blocking Thread.sleep():

Running `updateContent` in `scope.launch { updateContent() }` still blocks the UI because `rememberCoroutineScope` will by default use the dispatcher of Recomposer.applier.

if you want to run a heavy task in onClick callback, you can use a different dispatcher:
```
val scope = rememberCoroutineScope {
            Dispatchers.IO // just an example
        }
```        

or if you want to have a simple delay:
- make `updateContent` a suspend fun
- replace Thread.sleep(...) with delay(...)

```kotlin     

suspend fun updateContent() {
        // Simulate some time to update content
       delay(1000)
}
```

making any of these changes makes your code snippet work.

**Comment by Gorry077** [comment] 2023-09-27 16:36
Yes, I should not do heavy task in Recomposer.applier, but if i do it should not end up with Exception. If you run same project on android, only UI will block and exception will not throw.  [Here](https://github.com/Gorry077/issue-compose-multi-3715-android) is a example project for android. This issue can be duplicate of [other issue](https://github.com/JetBrains/compose-multiplatform/issues/3399).

**Comment by eymar** [comment] 2023-09-27 16:38
@Gorry077 thank you!

**Comment by okushnikov** [comment] 2024-07-14 16:11
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3715">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:12 UTC
Labels: bug, wait for reply, desktop, reproduced
