### ISSUE TITLE
FR: `@Preview` should work from Common Layer

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#1603] opened 2021-12-15 20:59 UTC
I realize having `@Preview` work is odd in the common layer, but perhaps there can be a new Annotation provided. Something like `@JvmPreview` or something to specify which platfrom it should run the preview for. Not being able to get Previews in the common layer, makes the common layer significantly more annoying to work with.

**Comment by brucemax** [comment] 2024-02-12 02:27
Absolutely agree!
I started my project but missing this feature makes development much slower! 😞
With new wizard template with "composeApp" folder I haven't "Code/Splite/Design" buttons at all in Android Studio! 😡

Preview feature is very important, but all template projects just ignore it.
Please pay more attention  for preview in shared (composeApp/commonMain) files. 
This will be a really big argument for using your solution (kotlin and compose multiplatform) for cross-platform development!
🫡

**Comment by bartekpacia** [comment] 2024-05-30 00:59
this looks like a duplicate of #2045

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5122">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:40 UTC
Labels: enhancement, preview
