### ISSUE TITLE
No Sources in Multiplatform

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-multiplatform#4213] opened 2024-01-31 07:50 UTC
**Describe the bug**
No Sources in Multiplatform, IDE can'r find them

**Affected platforms**
Select one of the platforms below:
- All

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Arch Linux
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
Look sources

**Expected behavior**
See sources

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/63443274/d22bf4c0-3d7e-4228-800c-ad58d87451a6)
![image](https://github.com/JetBrains/compose-multiplatform/assets/63443274/596c961b-b1f9-4c24-87a4-13ee7fa6b977)

**Comment by mazunin-v-jb** [comment] 2024-01-31 11:50
Hello!
I can't reproduce that. Could you please provide information about reproducing the issue, step by step?

**Comment by daoenpan** [comment] 2024-02-03 19:05
I have the same problem after apply org.jetbrains.compose plugin in shared project. Add a dependency e.g. implementation(compose.material3) to commonMain. Then open MyApplicationTheme.kt in androidApp, from there open MaterialTheme composable on line 49 with Command+Click. That will reproduce this bug.

Here is the demo project https://github.com/daoenpan/kmp-bugreport

**Comment by ktkahkon** [comment] 2024-03-10 11:52
I'm facing the same issue. I created a project through the Kotlin Multiplatform Wizard web page. When I add, for example,

```
@Composable
fun Foobar() {
    Text("Foo")
}
```

to a file under androidMain and click go to definition on the Text function, it will show the sources of Text composable. But if I add Foobar under commonMain and go to definition of Text from there, I get IntelliJ API Decompiler stub source generated from a class file.

Is it possible to access the sources from commonMain somehow?

**Comment by MindWing-net** [comment] 2024-03-14 07:41
I get the source on Android Studio Iguana | 2023.2.1

**Comment by GazimSoliev** [comment] 2024-03-25 20:35
> Hello! I can't reproduce that. Could you please provide information about reproducing the issue, step by step?

Now it's working in commonMain, but it doesn't work for specific target for example desktopMain (aka jvmMain)

**Comment by okushnikov** [comment] 2024-08-26 13:44
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4213">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:21 UTC
Labels: bug, wait for reply
