### ISSUE TITLE
🐞 onKeyEvent not working as expected

### ISSUE THREAD

**Issue by theapache64** [JetBrains/compose-multiplatform#570] opened 2021-04-08 15:50 UTC
If i add `fillMaxSize`  before `onKeyEvent`, the `onKeyEvent` is not getting called.

![image](https://user-images.githubusercontent.com/9678279/114057306-13df4f00-98b0-11eb-8fd9-0c88b7f231f0.png)

**Comment by olonho** [comment] 2021-04-09 11:40
Interesting problem, do you have full reproducer?

**Comment by prepor** [comment] 2021-04-09 12:11
I'm pretty sure it's upstream Compose a problem, we need to check it on Android

**Comment by timo-drick** [comment] 2021-04-25 23:50
It would be nice to have a onKeyEvent on App level. Which is independent from focus. Because in Android legacy view system as well as in compose it is a pain to get focus working. It is near to impossible to reliable catch key events.

**Comment by crjacinro** [comment] 2021-06-14 00:12
I have the same problem. How to workaround this issue? I am thinking it has something to do with focus. Is there a tutorial or example somewhere that clearly describes how to use onKeyEvent? I just launched a window and want to handle arrow events but its not even fired.

**Comment by kirill-grouchnikov** [comment] 2021-06-14 12:01
App-level key events can be handled with `LocalWindow.current.keyboard.onKeyEvent` block starting with `0.5.0` builds. See example at https://github.com/kirill-grouchnikov/aurora/blob/icicle/demo/src/desktopMain/kotlin/org/pushingpixels/aurora/demo/AuroraScrollDemo.kt#L192

**Comment by crjacinro** [comment] 2021-06-14 14:01
> App-level key events can be handled with `LocalWindow.current.keyboard.onKeyEvent` block starting with `0.5.0` builds. See example at https://github.com/kirill-grouchnikov/aurora/blob/icicle/demo/src/desktopMain/kotlin/org/pushingpixels/aurora/demo/AuroraScrollDemo.kt#L192

This worked. Thanks!

**Comment by okushnikov** [comment] 2024-07-14 17:40
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5438">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 11:09 UTC
Labels: bug, input, desktop
