### ISSUE TITLE
Cannot locate tasks that match ':desktopApp:compileJava' as task 'compileJava' not found in project ':desktopApp'.

### ISSUE THREAD

**Issue by mironoff2007** [JetBrains/compose-multiplatform#3662] opened 2023-09-11 21:40 UTC
https://github.com/JetBrains/compose-multiplatform-template/

Android Studio Iguana | 2023.2.1 Canary 3
Build #AI-232.9559.62.2321.10773421, built on September 7, 2023
Runtime version: 17.0.8+0--10699129 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.squareup.sqldelight (2.0.0)
    org.jetbrains.compose.desktop.ide (1.5.1)

Cannot locate tasks that match ':desktopApp:compileJava' as task 'compileJava' not found in project ':desktopApp'.

* Try:
> Run gradle tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 843ms

**Comment by mironoff2007** [comment] 2023-09-11 21:47
Same result in Giraffe
Android target builds fine
![image](https://github.com/JetBrains/compose-multiplatform/assets/18057056/2baa519f-6887-491d-995d-a2ef55675db6)
 Desktop not
![image](https://github.com/JetBrains/compose-multiplatform/assets/18057056/bb9185a4-9c70-44f1-acb0-535cd0054339)

**Comment by mironoff2007** [comment] 2023-09-12 05:40
Steps to reproduce.
1) Pull template.
2) Add new branch.
3) Add new module, link it. (any common module)
4) Try to build. See build error.
5) Checkout main
6) Clean project
7) You can't build desktop target

**Comment by MatkovIvan** [comment] 2023-09-12 08:12
Hi @mironoff2007,

I've been trying to replicate the problem that you're facing, but without success. The `compileJava` task seems to be not required for this project, as there's no Java code included. Therefore, it is quite unclear what exactly is triggering it.

With regards to reproduction steps, both 4 and 7 seem to operate well on my end. It would be highly beneficial if you could share with us the entire project, inclusive of all the modifications you've made to our template. This would greatly aid in the identification of the issue.

**Comment by mironoff2007** [comment] 2023-09-12 10:40
I've deleted fork and pull template again. I had same error. 
But I realised that I use different run method.
Is this method wrong?
It worked before in my pet projects, but it is broken in pet project in same way.

![image](https://github.com/JetBrains/compose-multiplatform/assets/18057056/590d17c0-b8eb-4b33-8680-519b006dbca7)

In pet projects I'm using jvm { withJava() } instead of just jvm() in build.kts. With this desktop target builds, but I causes runtime no class found exceptions for dependencies outside of desktope module

**Comment by MatkovIvan** [comment] 2023-09-12 12:02
Indeed, I've reproduced that - this method doesn't quite function as expected when attempted via Android Studio, although it works seamlessly in IntelliJ IDEA. This method is perfectly valid and should ideally perform without a hitch, but it seems to be some sort of an issue specific to the Android Studio IDE. 

At present, I would recommend using the "desktopApp" run configuration - simply utilize the run button located on the top bar. 

I'm going to close this issue as it appears to be more related to Android Studio rather than a problem inherent to Compose Multiplatform. I would suggest that you bring this to the attention of Google's Android Studio IDE via their issue tracker. They should be able to provide further assistance in this regard.

**Closed by MatkovIvan** 2023-09-12 12:02 UTC
Labels: wait for reply, project templates
