### ISSUE TITLE
cann't find the function

### ISSUE THREAD

**Issue by False-Mask** [JetBrains/compose-multiplatform#2578] opened 2022-12-26 13:35 UTC
this is my composable function def
![image](https://user-images.githubusercontent.com/72421304/209554234-a4640937-97f4-44b6-a9de-ee84ab3c5415.png)

when it runs it throws 
![image](https://user-images.githubusercontent.com/72421304/209554343-f4288944-42f4-4076-9f60-00069aad70e6.png)

if i add the default args ,it works ..
![image](https://user-images.githubusercontent.com/72421304/209554478-31d3b80b-07ec-4945-8f37-42fd8900c2d6.png)

**Comment by dima-avdeev-jb** [comment] 2022-12-27 15:07
@False-Mask 
I can't reproduce your problem.
Can you please share a reproducible sample on GitHub?

**Comment by okushnikov** [comment] 2024-07-14 16:21
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2578">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:36 UTC
Labels: wait for reply
