### ISSUE TITLE
Compose-Desktop: When a TextField exceeds 300 lines, there is a noticeable lag when editing

### ISSUE THREAD

**Issue by SanchezABCs** [JetBrains/compose-multiplatform#3334] opened 2023-07-10 05:07 UTC

**Comment by igordmn** [comment] 2023-07-10 11:42
The current TextField isn't designed for big texts. If you need to show a lot of lines, you should write/find another implementation, use LazyList + TextField, or wait for [TextField2](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text2/package-summary) (it may solve the issue, we are not sure yet)

One of the reasons - it stores the state in immutable String. For large texts, the state should be represented by something like a gap buffer.

Only reproduced lags with 3000 lines:
```
import androidx.compose.material.TextField
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        var state by remember { mutableStateOf(
                (1..3000).map { "aaaaaaa aaaaaaaaaa a aasdgfsd gdsg dsfg dfagfd gsdfg sfd gdsfg dsfg sdgdfs gdsfg sdfg sdg dzfg df gdfg" }
                        .joinToString("\n")
            )
        }
        TextField(
            state,
            { state = it }
        )
    }
}
```
3000 lines:
https://github.com/JetBrains/compose-multiplatform/assets/5963351/001d880f-0662-43f5-8aba-d39f76545e1c

100 lines:
https://github.com/JetBrains/compose-multiplatform/assets/5963351/e9488c61-3f7a-4b1f-bc34-ab561e16464c

(Windows 11, OpenJDK 20, Intel i9 13900K)

Leave the issue open, until Compose has a widget capable to work with a large amount of text

**Comment by okushnikov** [comment] 2024-08-26 14:41
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3334">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:21 UTC
Labels: enhancement, performance, text
