### ISSUE TITLE
java.lang.ClassCastException: class androidx.compose.runtime.internal.ComposableLambdaImpl cannot be cast to class kotlin.jvm.functions.Function

### ISSUE THREAD

**Issue by vovahost** [JetBrains/compose-multiplatform#1620] opened 2021-12-20 06:10 UTC
I'm getting this error occasionally:

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class androidx.compose.runtime.internal.ComposableLambdaImpl cannot be cast to class kotlin.jvm.functions.Function0 (androidx.compose.runtime.internal.ComposableLambdaImpl and kotlin.jvm.functions.Function0 are in unnamed module of loader 'app')
```
The code which would cause this error:

```
ComposePanel().setContent {
  Box(
    modifier = Modifier
      .fillMaxSize()
      .background(color = Color.Blue)
  ) {
    Text(
      text = "Test",
      modifier = Modifier.align(Alignment.Center)
    )
  }
}
```

The error is thrown when `setContent()` is called. Once the error happens every Run will throw the error again. Rebuilding the project and running it again fixes the error until it happens sometime again.

**Comment by akurasov** [comment] 2021-12-20 09:28
Could you share the whole reproducer, please?

**Comment by bojankoma** [comment] 2022-08-12 10:08
Resurrecting this issue since this is happening on 1.2.0 with Kotlin 1.7.10 (and 1.7.0) when building an Idea plugin with Compose UI.

**Comment by bojankoma** [comment] 2022-08-12 10:11
Here is the complete project reproducer to test out, if needed.
https://github.com/bojankoma/intellij-gradle-warden

**Comment by bojankoma** [comment] 2022-08-12 10:14
Sorry to spam a little, but this can be reproduced now on each run, not just occasionally. 
Idea UI Run tab shows errors, in order:
`Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/TypesJVMKt`
`Caused by: java.lang.ClassNotFoundException: kotlin.reflect.TypesJVMKt PluginClassLoader[PluginDescriptor(name=Gradle Warden, id=com.infinum.intellij.plugins.warden, path=/Users/bojan/Workspace/IntelliJ/Plugins/Warden/build/idea-sandbox/plugins/Warden, version=1.0.1)] com.intellij.ide.plugins.cl.PluginClassLoader@112d4d55`
`Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/TypesJVMKt`

@akurasov let me know if there is something I can try or do to mitigate this, but at the moment building Idea plugins with Compose is not possible and we are blocked.

**Comment by HGyllensvard** [comment] 2023-02-09 01:59
I experienced this just now while running an Android UI test using `AndroidComposeTestRule`.

We have had a shared base class for running these tests before.

So:
```
open TestBase {
..
}

fun FeatureTest: TestBase {
   @Test
   fun testA() {
   }
}
```

This has worked fine for months, but I recently tried to create another layer to share logic between the tests:
```
open TestBase {
..
}

open FeatureTestBase: TestBase {
..
}

fun FeatureTest: FeatureTestBase {
   @Test
   fun testA() {
   }
}
```

And now the tests consistently fail. There are no constructor parameters in the `FeatureTestBase` nor `TestBase`.

Stack:
```
02-09 12:55:53.809  7058  7091 E TestRunner: java.lang.ClassCastException: androidx.compose.runtime.internal.ComposableLambdaImpl cannot be cast to kotlin.jvm.functions.Function0
02-09 12:55:53.809  7058  7091 E TestRunner: 	at remove_test_name
02-09 12:55:53.809  7058  7091 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:148)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:147)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:476)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:294)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTextInputService(ComposeUiTest.android.kt:360)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTextInputService(ComposeUiTest.android.kt:217)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:293)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:347)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:217)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:292)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:321)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:217)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:291)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:334)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:217)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:290)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.junit4.EspressoLink.withStrategy(EspressoLink.android.kt:66)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:289)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.junit4.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:157)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:288)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.junit4.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:287)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:147)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
02-09 12:55:53.809  7058  7091 E TestRunner: 	at removed_class_name
02-09 12:55:53.809  7058  7091 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2361)
02-09 12:55:53.810  7058  7091 E TestRunner: ----- end exception -----
```


We are using:
- Compose: 1.3.1
- Kotlin: 1.7.10
- Android Gradle Plugin: 7.2.2

**Comment by eymar** [comment] 2023-11-08 11:20
**Current status:**

I tried to use kotlin 1.9.20 and CM 1.5.10 and it seems to work good without ClassCastException issue. Please give it a try!

**Comment by okushnikov** [comment] 2024-07-14 16:09
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5111">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:08 UTC
Labels: crash, desktop
