### ISSUE TITLE
iOS:  LazyColumn scroll bug

### ISSUE THREAD

**Issue by Caij** [JetBrains/compose-multiplatform#3572] opened 2023-08-26 09:11 UTC
**Describe the bug**
During scrolling, LazyColumn suddenly scrolls to the top, only on the iOS platform; there are no issues on the Android platform.

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*:  1.4.3
- OS version(s)* (required for Desktop and iOS issues): iPhone 8 16.4

```
 val model by homeComponent.model.subscribeAsState()
    val rememberLazyListState = rememberLazyListState()
    LaunchedEffect(homeComponent) {
        homeComponent.init(object : Callback<Pair<Int, Int>> {
            override suspend fun onResult(t: Pair<Int, Int>) {

            }

            override fun onError(throwable: Throwable) {

            }
        })
    }
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(top = paddingTop),
        state = rememberLazyListState) {
        itemsIndexed(model.tweets) { index, item ->
            AllTypeCardItemContent(item)
        }
    }
```

https://github.com/JetBrains/compose-multiplatform/assets/8597839/51dd71a5-0f2b-41ff-82fb-39e07a2be28b

https://github.com/JetBrains/compose-multiplatform/assets/8597839/e055267c-70d1-4d95-bc4f-cf93d1e71bef

**Comment by elijah-semyonov** [comment] 2023-08-28 07:18
Hi, it's known and worked on currently..
Duplicate of https://github.com/JetBrains/compose-multiplatform/issues/3335

**Closed by elijah-semyonov** 2023-08-28 07:18 UTC
Labels: bug, submitted

**Comment by Caij** [comment] 2023-08-29 08:01
@elijah-semyonov Is this fixed in version 1.5.0 release?

**Comment by elijah-semyonov** [comment] 2023-08-29 08:10
No, it will be fixed in later patch after [this PR](https://github.com/JetBrains/compose-multiplatform-core/pull/776) is merged.

**Comment by Caij** [comment] 2023-09-05 05:06
@elijah-semyonov I'm very sorry to bother you, but I would like to inquire about the timeline for addressing this issue. Many of my app users have reported this problem.

**Comment by elijah-semyonov** [comment] 2023-09-05 07:07
@Caij you don't bother me at all, right now the solution for this issue in PR I've linked is partly a workaround for some bugs introduced by us in a mechanism called `synthetic events`. Doing it properly without workarounds and creating regressions could get some time, because it requires some internal discussion and all targets are using this mechanism.

Compose Multiplatform for Compose is in Alpha now, so issues like that are expected and we really value your feedback and reports which helps us to solve them.

I can't give you an accurate timeline, because there are quite some moving parts, but if it's a dire issue affecting you in long term, you could build compose locally from [this repo](https://github.com/JetBrains/compose-multiplatform-core), cherry pick PR above and ship your app with locally built compose. It will be probably accompanied with other bugs introduced by us between the release and jb-main HEAD, but it's the best we can do for now.

Watch the status of this PR (and related PRs if any) and follow us on social platforms to see if it's included in the update to come or not.

**Comment by okushnikov** [comment] 2024-07-14 16:12
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3572">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
