### ISSUE TITLE
[Windows] Setting custom icon doesn't work and causes startup crashes

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3873] opened 2023-10-28 11:52 UTC
**Describe the bug**
After specifying `iconFile` in build.gradle.kts, the default icon was still being used. What is more serious, it crashes with the following message when the application launches.
> instream parameter is null

**Affected platforms**
- Desktop (Windows)

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Specify a custom .ico file at `compose.desktop.application.nativeDistributions.windows.iconFile` in build.gradle.kts, as instructed by the [official documentation](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Native_distributions_and_local_execution/README.md#app-icon).
2. Run `createDistributable` gradle task.
3. Examine the directory `build\compose\binaries\main\app\<application-name>`
4. Icons of the .exe and .ico files are the default one
5. Launch the .exe file
6. It crashes with an alert

**Expected behavior**
Custom icon file should be used. The application should not crash.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by sunny-chung** [comment] 2023-10-29 06:25
This issue is also reproducible in macOS.

1. Regarding the crash, it is reproducible whenever the project is cleaned before building binaries. The issue disappears on the second build without cleaning.
2. Regarding the icon, it also happens to macOS 10.15.7. Copying the artifact to a macOS 14.0, the icon would appear correctly in the newer OS.
3. Now it looks like the icon has no relationship with the crash.

**Comment by eymar** [comment] 2023-10-30 13:50
I tried to reproduce but it works for me.
Could you please check that the icon file exists at the given path?

If you set `windows.iconFile.set(project.file("icon.ico"))` then it expects the `icon.ico` in the same folder that `build.gradle.kts` of desktop app module. 
If you checked and the file is at correct path, then could you please provide a sample project where this issue can be reprdouced?

**Comment by sunny-chung** [comment] 2023-11-05 04:27
About macOS app icon issue,
1. Please checkout this project and build on a Mac with any macOS version
https://github.com/sunny-chung/compose-desktop-app-icon-issue
2. Transfer to a Mac with macOS 10.15 (if the build is compiled at newer macOS version)
3. It can be seen that custom app icon is not used in the `.app` and `.dmg` artifacts in macOS 10.15
<img width="882" alt="Screenshot 2023-11-05 at 11 55 04 AM" src="https://github.com/JetBrains/compose-multiplatform/assets/14835950/352fc1ff-3eae-48d5-a05f-63cc54e67acd">

4. If these artifacts are transferred to a newer macOS, the app icon shows.

About Windows app icon issue, I could not reproduce with compose 1.5.10.

**Comment by mmmatey** [comment] 2024-01-01 19:50
I tried reproduce it on my side as-well and for me works fine. What you can do is to try print out the path of the appicon file in the build.gradle.kts. That way you will be able to find out where the actual icon file should be. Most probably the file is not in the right path...

```
            macOS {
                println("ICON path ${project.file("appicon/appicon.icns")}")
                iconFile.set(project.file("appicon/appicon.icns"))
            }
```

**Comment by okushnikov** [comment] 2024-07-14 16:08
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3873">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:03 UTC
Labels: bug, wait for reply, native distribution
