### ISSUE TITLE
Compose WASM Text or Font missing symbol

### ISSUE THREAD

**Issue by DXueShengKa** [JetBrains/compose-multiplatform#3067] opened 2023-04-17 10:27 UTC
![IMG_20230417_181033.png](https://user-images.githubusercontent.com/32562627/232457931-3b59cfb0-942c-4b2b-96a6-850a594a58f8.png)

https://zal.im/wasm/iv/

https://github.com/Kotlin/kotlin-wasm-examples/tree/main/compose-imageviewer#compose-multiplatform-for-web

**Comment by eymar** [comment] 2023-04-19 08:05
It's a duplicate of https://github.com/JetBrains/compose-multiplatform/issues/3051

**Closed by eymar** 2023-04-19 08:05 UTC
Labels: bug, duplicate, web, reproduced

**Comment by okushnikov** [comment] 2024-07-14 16:18
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3067">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
