### ISSUE TITLE
AnnotatedString using extra Span with fontSize is inconconsistenly scaled

### ISSUE THREAD

**Issue by jbruchanov** [JetBrains/compose-multiplatform#3769] opened 2023-10-04 08:25 UTC
**Describe the bug**
Using AnnotatedString with extra fontSize is inconsistent android vs ios/jvmDesktop.
See following screenshot having `Text(text, fontSize = 14.sp)`
- Specially noticeable for case of `0.5em`, where the text on ios/desktop screens are unexpectedly smaller comparing to `7.sp` or `1.em` or `14.sp`
- I think it's expected for the testcase to have `0.5em = 7sp` and `2em = 28sp` (didn't try to pixel perfect measure it, though optically it seems to be correct assumption on Android)

**Affected platforms**
Select one of the platforms below:
- Desktop
- iOS
(probably all non Android)

**Versions**
- Kotlin version*: "1.9.10"
- Compose Multiplatform version*: "1.5.2"
- OS version(s)* (required for Desktop and iOS issues):
```
windows 11 (3840x1600 38" ~ 109dpi based on https://dpi.lv/) 100% font size in win settings
iosSimulator 14 
android 12
```
- JDK (for desktop issues): 17.0.8+7-b1000.22 amd64

**To Reproduce**
Create a screen with following code
```
@Composable
fun AnnotatedText() {
    val sampleText = "SAMPLE text 12345"
    val text = buildAnnotatedString {
        appendLine(sampleText)
        withStyle(SpanStyle(fontSize = 0.5f.em)) {
            appendLine("$sampleText 0.5em")
        }
        withStyle(SpanStyle(fontSize = 1f.em)) {
            appendLine("$sampleText 1em")
        }
        withStyle(SpanStyle(fontSize = 2.em)) {
            appendLine("$sampleText 2em")
        }

        withStyle(SpanStyle(fontSize = 7.sp)) {
            appendLine("$sampleText 7sp")
        }
        withStyle(SpanStyle(fontSize = 14.sp)) {
            appendLine("$sampleText 14sp")
        }
        withStyle(SpanStyle(fontSize = 28.sp)) {
            appendLine("$sampleText 28sp")
        }
    }
    Text(text, fontSize = 14.sp)
}
```

**Expected behavior**
Scaling should be consistent across all platforms

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/1651939/54862cb3-5580-4988-b1c9-7cb053d4f1d7)

**Comment by dima-avdeev-jb** [comment] 2023-10-09 13:09
It may be a duplicate of this Issue: https://github.com/JetBrains/compose-multiplatform/issues/2770

**Comment by okushnikov** [comment] 2024-08-26 14:36
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3769">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:11 UTC
Labels: bug, duplicate, reproduced
