### ISSUE TITLE
Performance issues(missing frames) on LazyColum

### ISSUE THREAD

**Issue by xinzhengzhang** [JetBrains/compose-multiplatform#4438] opened 2024-03-06 13:52 UTC
**Describe the problem**

Bad performance on LazyColum( There is no problem with using Colum ) and the content of the screen does not move with the hand (latency)

- Have you noticed any patterns or specific circumstances under which the problem occurs?
In both implementations, I used the Instruments tool Allocation and Animation Hitches and Time Profiler. 
I also tried grab the metal profile. It's all subtle levels. It doesn't seem to be a gpu performance problem. I feel like it's still a cpu problem.
The data performance of the two methods is basically the same, but the actual touch is obviously felt with LazyColum jank.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version: 1.9.20
- Compose Multiplatform version: 1.6.0
- OS version(s) (required for Desktop and iOS issues): iOS 17.3.1
- OS architecture (x86 or arm64):  arm64
- Device: iPhone 13

**Sample code**
```
// kotlin
fun getDemoViewController(isIdle: (Boolean) -> Unit): UIViewController {
    return ComposeUIViewController(
        content = {
            LazyColumn(userScrollEnabled = true, modifier = Modifier.fillMaxSize()) {
                items((0..100).toList(), { it }) { index ->
                    Text("Item $index", style = TextStyle(fontSize = 30.sp), modifier = Modifier.height(150.dp))
                }
            }

            // no problem using Column
//            Column(modifier = Modifier.fillMaxSize().verticalScroll(rememberScrollState())) {
//                (0..100).forEach { index ->
//                    Text(
//                        "Item $index",
//                        style = TextStyle(fontSize = 30.sp),
//                        modifier = Modifier.height(150.dp)
//                    )
//                }
//            }

        }
    )
}

//swift
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    window = UIWindow(frame: UIScreen.main.bounds)
    window?.makeKeyAndVisible()
    window?.rootViewController = UINavigationController(rootViewController: Compose_view_iosKt.getDemoViewController { _ in})
    window?.backgroundColor = .white
    return true
  }
}
```

**Video**
https://drive.google.com/file/d/1pekBo5D5OI-rkMHCb7byMYbAnsdXcz_c/view?usp=share_link

**Profiling data**
https://drive.google.com/drive/folders/1yndeXWYojDAoYxiZoraq-HVajq0HbbcX?usp=share_link

**Comment by igordmn** [comment] 2024-03-07 22:22
> Bad performance on LazyColum( There is no problem with using Colum)

@elijah-semyonov, could you check it on your device, when you have time? If we have a visible input lag with `LazyColumn` comparing to `Column`, it is worth to investigate/fix soon. I suspect a few things.

**Comment by kasem-sm** [comment] 2024-04-01 18:20
Facing the same issue. The CPU consumption goes ~80% just with LazyColumn.

**Comment by elijah-semyonov** [comment] 2024-04-02 07:26
I'll have a look

**Comment by elijah-semyonov** [comment] 2024-04-02 08:21
Not related to performance, seems like a state update error, investigating further.

https://github.com/JetBrains/compose-multiplatform/assets/4167681/dfd5056a-1fd9-4432-ae3c-4e8bf902aadd

**Comment by kasem-sm** [comment] 2024-04-02 14:11
> Facing the same issue. The CPU consumption goes ~80% just with LazyColumn.

Not related to this issue, sorry! But the scroll lag is visible.

**Comment by dangdo1** [comment] 2024-04-09 10:49
Facing the same issue...

**Comment by kiethayqua** [comment] 2024-04-09 13:52
Facing the same issue, and when start screen recording the scroll behavior so smooth

**Comment by kiethayqua** [comment] 2024-04-11 04:01
@m-sasha before your PR will be reviewed and merged, how can I patch the dependency for my project ?

**Comment by m-sasha** [comment] 2024-04-11 07:19
That would be difficult. Just wait for the first dev build after my PR is merged.

**Comment by kiethayqua** [comment] 2024-04-11 07:30
@m-sasha thanks for your response

**Comment by tipsypotato** [comment] 2024-04-18 13:20
Runs perfectly with the test at [JetBrains/compose-multiplatform-core/pull/1260](https://github.com/JetBrains/compose-multiplatform-core/pull/1260) but unfortunately the "visible jump" comes back when commenting out the `LaunchedEffect(Unit) { ... }`, it seems the while-loop in `LaunchedEffect(Unit) { ... }` results in something similar to [screen recording](https://github.com/JetBrains/compose-multiplatform/issues/4438#issuecomment-2045231465 on iOS, @m-sasha please have a furthur look.

**Comment by m-sasha** [comment] 2024-04-18 14:27
@tipsypotato Not sure I understand. In my reproducer, the `LaunchedEffect(Unit){...}` is what is driving the scrolling. Without that it would not scroll.

Can you post a reproducer where the jump is still visible? Is it only visible on iOS? Can you post a video?

**Comment by tipsypotato** [comment] 2024-04-19 04:20
@m-sasha Thanks for reply

> the `LaunchedEffect(Unit){...}` is what is driving the scrolling.

Yeah but we can also scroll it mannually. I did some further tests, the scrolling experience with LazyColumn is still far from Column when scrolling on a real iOS device, it happened both on iPhoneSE3 and iPhone13 while run perfectly on Android. 
You can check the iOS screen recording below:

https://github.com/JetBrains/compose-multiplatform/assets/40794760/9129160b-c190-4231-ba92-56b180a4c21e

reproducer code:
```kotlin
@Composable
fun TestLazyColumn() {
    Box(modifier = Modifier.fillMaxSize()) {
        Row {
            Column(
                modifier = Modifier
                    .fillMaxHeight()
                    .weight(1f)
                    .verticalScroll(rememberScrollState())
            ) {
                (0..100).forEach { index ->
                    Text(
                        "Column item $index",
                        style = TextStyle(fontSize = 30.sp),
                        modifier = Modifier.height(150.dp).fillMaxWidth().border(
                            width = 1.dp,
                            color = Color.Black
                        )
                    )
                }
            }


            LazyColumn(
                state = rememberLazyListState(),
                modifier = Modifier.fillMaxHeight().weight(1f)
            ) {
                items(100) { index ->
                    Text(
                        "LazyColumn item $index",
                        style = TextStyle(fontSize = 30.sp),
                        modifier = Modifier.height(150.dp).fillMaxWidth().border(
                            width = 1.dp,
                            color = Color.Black
                        )
                    )
                }
            }
        }
    }
}
```

**Comment by m-sasha** [comment] 2024-04-19 06:10
@elijah-semyonov I guess more investigation is needed.

**Comment by elijah-semyonov** [comment] 2024-04-19 06:18
@m-sasha I'll have another look.

**Comment by elijah-semyonov** [comment] 2024-04-19 07:10
I struggle to reproduce it on both devices after the fix.
Can you use slomo camera from the other device to verify?


https://github.com/JetBrains/compose-multiplatform/assets/4167681/91867b71-5679-41e3-8c73-36bd5b1f2a0c
https://github.com/JetBrains/compose-multiplatform/assets/4167681/6b6ad933-68b7-494d-9dd0-9cfcae7fe83d

**Comment by jnelle** [comment] 2024-04-22 18:26
I'm experiencing the same issue, along with an additional one. It will become apparent when you scroll up.
https://github.com/JetBrains/compose-multiplatform/assets/36324542/79224172-abda-4e08-b95d-8ce4f75a6487

**Comment by elijah-semyonov** [comment] 2024-04-23 06:53
@jnelle 
Can you describe what you think you see? I'm not sure what to focus on exactly.

**Comment by m-sasha** [comment] 2024-04-23 07:01
I think he means the list seems to scroll to a random far position sometimes.
But this is a different issue, possibly a bug in the user code. Please post a reproducer in a new issue.

**Comment by tipsypotato** [comment] 2024-04-23 08:33
@elijah-semyonov In your second slomo video `14_pro.mov`, the stutter happens at 0:09, 0:13, 0:23 and 0:26, and after several attempts with [my reproducer](https://github.com/JetBrains/compose-multiplatform/issues/4438#issuecomment-2065729826), I noticed the stutter unexpectedly happens on Column when scrolling both at the sametime, while when scrolling the Column or the LazyColumn only, it seems the stutter only happens with LazyColumn.

**Comment by elijah-semyonov** [comment] 2024-04-23 09:52
@tipsypotato 
Yeah, it's a debug build. Release build is much better (though can also have occasional stutters due to GC).
Can you check if you have this behavior on release builds?

**Comment by jnelle** [comment] 2024-04-23 09:52
@elijah-semyonov I'm facing the performance issues when I scroll down and also when I scroll up the list skips random positions. 

Here is the reproducible code:

```kotlin
         is UiState.Success -> {
                    LazyColumn(modifier = Modifier.padding(innerPadding)) {
                        items(count = (uiState as UiState.Success<MainFeedResponse>).data.clips.size) {
                            Card(
                                Modifier.fillMaxWidth(),
                                shape = RoundedCornerShape(16.dp),
                                ) {
                                Image(
                                    painter = rememberImagePainter(
                                        (uiState as UiState.Success<MainFeedResponse>).data.clips[it].image
                                    ),
                                    contentDescription = "image",
                                )
                                Text((uiState as UiState.Success<MainFeedResponse>).data.clips[it].title)

                            }

                        }
                    }

                }
  ```
  
  You'll find the repository here:
  
  https://github.com/Nelle-Bendlage-IT/MassengeschmackTV

**Comment by elijah-semyonov** [comment] 2024-04-23 09:53
@jnelle 
Thanks, I'll have a look!

**Comment by jnelle** [comment] 2024-04-23 10:17
@elijah-semyonov I'm also facing the performance (stutters) issues on my Pixel 6 Pro, but it could be possible that this is caused from debug build. But the scroll behavior is also wrong but not the same as one iOS. 

https://github.com/JetBrains/compose-multiplatform/assets/36324542/8501b99b-f5d9-4f8d-9b63-7a70fc5ae71f

**Comment by elijah-semyonov** [comment] 2024-04-23 10:24
@jnelle 
We don't have an ownership over Android implementation. Could you please file an issue to Google Compose Issue tracker and paste a link here?

**Comment by tipsypotato** [comment] 2024-04-23 10:38
> @tipsypotato Yeah, it's a debug build. Release build is much better (though can also have occasional stutters due to GC). Can you check if you have this behavior on release builds?

@elijah-semyonov It still happens with release build on iOS, the stutters are frequent and subtle, but still very noticeable compared to Column. Our project uses lots of LazyColumn, so it would be very appreciated if you could give it a further look!

**Comment by elijah-semyonov** [comment] 2024-04-29 08:46
@tipsypotato Apart from the issues you've noticed on my slowmo video, do you see something else? I'm trying to figure out if it's a lazy-column bug that we are not aware of (like the initially reported one), or general performance issues, which we are already working on.

**Comment by tipsypotato** [comment] 2024-05-11 04:51
@elijah-semyonov add the code below to `TestLazyColumn` in the [reproduce code above](https://github.com/JetBrains/compose-multiplatform/issues/4438#issuecomment-2065729826), the lazy-column performance issue will be gone.
```kotlin
LaunchedEffect(Unit) {
    while (true) {
        withFrameMillis {}
    }
}
```

**Comment by MatkovIvan** [comment] 2024-05-13 16:21
@tipsypotato this code snippet makes me think that it's probably related to https://github.com/JetBrains/compose-multiplatform-core/pull/1356

**Comment by xiaozhikang0916** [comment] 2024-05-15 03:28
@MatkovIvan As https://github.com/JetBrains/compose-multiplatform-core/pull/1356 is merged, any chance to have a try with a dev-release?

**Comment by MatkovIvan** [comment] 2024-05-15 07:38
@xinzhengzhang 
I've triggered CI for test build with this change - `0.0.0-jb-main-dev1635` should be ready in ~1h

**Comment by xinzhengzhang** [comment] 2024-05-15 12:05
@MatkovIvan  Looks like 0.0.0-jb-main-dev1635 doesn't work and still performs well under workaround https://github.com/JetBrains/compose-multiplatform/issues/4438#issuecomment-2105548354

**Comment by MatkovIvan** [comment] 2024-05-15 12:09
OK, so my guess was wrong.
@elijah-semyonov @m-sasha it looks like it requires a future inversion

**Comment by jnelle** [comment] 2024-07-14 14:39
> @elijah-semyonov I'm also facing the performance (stutters) issues on my Pixel 6 Pro, but it could be possible that this is caused from debug build. But the scroll behavior is also wrong but not the same as one iOS.
> 
>  video_2024-04-23_12-15-43.mp4

This issue was my bad, I forgot to set the height for the Image which was inside the Box.

**Comment by okushnikov** [comment] 2024-07-14 14:57
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4438">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:26 UTC
Labels: performance, ios
