### ISSUE TITLE
 Custom Vertical Padding for Dropdown Menu

### ISSUE THREAD

**Issue by HTGAzureX1212** [JetBrains/compose-multiplatform#1831] opened 2022-02-12 08:38 UTC
Currently the default vertical padding for a dropdown menu is `8dp` and it is not possible to override such padding (I dug into the source code).

Is there a way to override the default padding, as I have tried using `Modifier.padding(vertical = <custom padding>)` and it doesn't work (probably the subsequent calls to the same method in the library overrode that)?

**Comment by akurasov** [comment] 2022-02-15 12:45
And what is the use-case when it is needed?

**Comment by HTG-YT** [comment] 2022-02-15 13:38
This could enable the customisation for UI layout (from a user respective) without writing another composable component at least, for one.

**Comment by dvu3** [comment] 2022-07-06 21:49
Definitely +1 to this. Our product would love to have scrollable dropdowns with no vertical padding.

**Comment by mahozad** [comment] 2022-09-17 09:47
I think https://github.com/JetBrains/compose-jb/issues/1878 is related.

**Comment by borichellow** [comment] 2022-11-10 13:14
Is there any way it will be fixed?

**Comment by nguoitriki1** [comment] 2022-11-15 06:54
@Composable
fun SortDropdown(
    modifier: Modifier = Modifier,
    expanded: Boolean = false,
    sortMode: SortMode,
    onItemClick: (SortMode) -> Unit,
    onExpanded: (Boolean) -> Unit
) {

    Box(
        modifier = modifier
            .padding(vertical = 4.dp)
            .size(48.dp)
            .clip(CircleShape)
            .clickable {
                onExpanded(true)
            },
        contentAlignment = Alignment.Center
    ) {
        Image(
            modifier = Modifier,
            painter = painterResource(id = R.drawable.choice_audio_sort_icon),
            contentDescription = null,
            contentScale = ContentScale.Inside
        )
        DropdownMenuNoPaddingVeitical(
            expanded = expanded,
            onDismissRequest = { onExpanded(false) },
            modifier = Modifier.width(226.dp),
        ) {
            sortRes.forEachIndexed { index, value ->
                DropdownMenuItem(
                    contentPadding = PaddingValues(0.dp),
                    modifier = Modifier
                        .widthIn(200.dp)
                        .height(56.dp)
                        .background(if (sortMode.sortIndex == index) AppTheme.colors.choiceAudio.itemDropDownSelectedColor else Color.Transparent),
                    onClick = {
                        onExpanded(false)
                        onItemClick(SortMode(index, sortMode.isAsc))
                    }) {
                    Column(modifier = Modifier.fillMaxSize()) {
                        Text(
                            modifier = Modifier.fillMaxSize().wrapContentHeight(),
                            text = stringResource(id = value),
                            style = Typography.button.copy(
                                fontSize = 16.sp,
                                color = AppTheme.colors.choiceAudio.titleTextColor,
                                fontWeight = FontWeight.Normal
                            )
                        )
                        Divider(color = AppTheme.colors.choiceAudio.dividerColor)
                    }
                }
            }
            Row(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(horizontal = 8.dp)
                    .padding(top = 10.dp, bottom = 2.dp)
            ) {
                ButtonDropDown(
                    modifier = Modifier
                        .fillMaxSize()
                        .weight(1f),
                    text = stringResource(R.string.asc),
                    onClick = {
                        onExpanded(false)
                        onItemClick(SortMode(sortMode.sortIndex, true))
                    },
                    isSelected = sortMode.isAsc
                )
                Spacer(modifier = Modifier.width(6.dp))
                ButtonDropDown(
                    modifier = Modifier
                        .fillMaxSize()
                        .weight(1f),
                    text = stringResource(R.string.desc),
                    onClick = {
                        onExpanded(false)
                        onItemClick(SortMode(sortMode.sortIndex, false))
                    },
                    isSelected = !sortMode.isAsc
                )
            }
        }
    }
}

@Composable
fun ButtonDropDown(
    modifier: Modifier = Modifier,
    text: String,
    isSelected: Boolean,
    onClick: () -> Unit
) {
    Surface(
        shape = RoundedCornerShape(8.dp),
        modifier = modifier
            .height(46.dp)
            .fillMaxWidth()
    ) {
        Text(
            modifier = Modifier
                .fillMaxSize()
                .background(brush = if (isSelected) AppTheme.colors.splash.bushButton else AppTheme.colors.choiceAudio.brushGray)
                .clickable {
                    onClick()
                }
                .wrapContentHeight(),
            text = text,
            style = Typography.button.copy(color = if (isSelected) AppTheme.colors.choiceAudio.selectColorTextButton else AppTheme.colors.choiceAudio.unselectColorTextButton),
            textAlign = TextAlign.Center
        )
    }
}

@Composable
fun SettingItemDropDown(modifier: Modifier = Modifier, onItemClick: (Int) -> Unit) {
    var expanded by remember { mutableStateOf(false) }

    Box(modifier = modifier) {
        Image(
            modifier = Modifier
                .size(56.dp)
                .padding(end = 6.dp)
                .clickable {
                    expanded = true
                },
            alignment = Alignment.Center,
            painter = painterResource(id = R.drawable.choice_audio_setting_more),
            contentDescription = null,
            contentScale = ContentScale.Inside
        )
        DropdownMenuNoPaddingVeitical(
            expanded = expanded,
            offset = DpOffset(39.dp,0.dp),
            onDismissRequest = { expanded = false },
            modifier = Modifier.width(190.dp),
        ) {

            itemRes.forEachIndexed { index, value ->
                DropdownMenuItem(
                    modifier = Modifier
                        .widthIn(120.dp)
                        .height(56.dp),
                    onClick = {
                        expanded = false
                        onItemClick(itemRes[index])
                    }) {
                    Text(
                        text = stringResource(id = value),
                        style = Typography.button.copy(
                            fontSize = 16.sp,
                            color = AppTheme.colors.choiceAudio.titleTextColor,
                            fontWeight = FontWeight.Normal
                        )
                    )
                }

            }
        }
    }
}

**Comment by rylexr** [comment] 2023-08-31 01:32
Any news on this?

**Comment by AleSpero** [comment] 2023-09-22 11:02
+1. Right now the best solution is to have a custom BasicTextField with your preferred size and paddings.

**Comment by m-sasha** [comment] 2023-09-22 11:11
I'll close this as duplicate of https://github.com/JetBrains/compose-multiplatform/issues/1878. Even though this bug is earlier, the other one is more general as not only vertical paddings are hardcoded.

**Closed** 2023-09-22 11:11 UTC
Labels: duplicate, enhancement, desktop

**Comment by okushnikov** [comment] 2024-07-14 16:12
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1831">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
