### ISSUE TITLE
iOS Add Compose to existing iOS project

### ISSUE THREAD

**Issue by onseok** [JetBrains/compose-multiplatform#3505] opened 2023-08-16 09:20 UTC
**Describe the bug**
After adding `pod("FirebaseAnalytics", "~> 10.13")` to the `shared build.gradle.kts` cocoapods block, the iOS app fails to run. 
The iOS application can no longer recognize the shared module. Just like this.

```
error: cannot find 'AppModuleKt' in scope
        AppModuleKt.doInitKoin()
        ^~~~~~~~~~~
        
error: cannot find 'NapierProxyKt' in scope
        NapierProxyKt.debugBuild()
        ^~~~~~~~~~~~~
```

Interestingly, when the `pod("FirebaseAnalytics") { version = "~> 10.13" }` block is commented out and run iosApp is executed, the application runs without any issues. The exact cause of this behavior remains unclear.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta02

**Screenshots**
<img width="664" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/76798309/134a410d-ff80-4c8f-a019-1df74f394334">
<img width="822" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/76798309/91e24e5d-a9b2-478e-a32a-ca8bd4ebdb5f">

And this is `gradle.properties`

<img width="814" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/76798309/0aec10d6-d4c4-48a6-a624-90888fedc57c">

**Comment by EBfVince** [comment] 2023-08-16 13:37
I had a problem similar to yours some time ago. 

This is not a problem due to Compose Multiplatform. This is probably due to the version of Xcode you are using. 

FirebaseAnalytics uses an old API that is not supported anymore in the new Xcode versions. 

Try downgrading Xcode version to something like 14.0 and retry to build your project.

Read more here: https://kotlinlang.slack.com/archives/C9JM6Q2UX/p1686842942651169

**Comment by mazunin-v-jb** [comment] 2023-08-16 23:36
Hello! Thanks for submitting the issue.
[My reproducer](https://github.com/mazunin-v-jb/compose-mp-issue-3505) works fine. (Similar project versions to yours, Xcode version is Version 14.3.1 (14E300c))
Could you please create a minimal reproducer? It will be helpful for understanding the problem.

Also, try to check with a lower version of Xcode. This also could be a cause of this behavior.

**Comment by onseok** [comment] 2023-08-17 01:56
Thank you for your response.
My Xcode version was also `14.3.1 (14E300c)`, and the reproducer project from @mazunin-v-jb worked well for me too.

Upon further inspection, I realized that the issue arose after adding the run script to Xcode's Build Phases, as suggested in this tutorial: [connect-the-framework-to-your-ios-project](https://kotlinlang.org/docs/multiplatform-mobile-integrate-in-existing-app.html#connect-the-framework-to-your-ios-project)

Here's the script I added:

```
# Type a script or drag a script file from your workspace to insert its path.
cd "$SRCROOT/.."
./gradlew :shared:embedAndSignAppleFrameworkForXcode
```

After removing this run script, everything started working fine again.

**Comment by okushnikov** [comment] 2024-08-26 14:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3505">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:17 UTC
Labels: question, ios
