### ISSUE TITLE
When will proguard be upgraded to 7.4? It seems that it cannot support jdk 21 now.

### ISSUE THREAD

**Issue by sunny-zhang-98** [JetBrains/compose-multiplatform#4817] opened 2024-05-16 09:21 UTC
https://github.com/JetBrains/compose-multiplatform/blob/abfd6c92e5441863ab07b5e235f1f8ac541ea22c/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/dsl/ProguardSettings.kt#L15

**Comment by eymar** [comment] 2024-05-16 09:42
You can change the version in your build.gradle.kts using `ProguardSettings.version` property:
https://github.com/JetBrains/compose-multiplatform/blob/abfd6c92e5441863ab07b5e235f1f8ac541ea22c/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/dsl/ProguardSettings.kt#L20

**Comment by MatkovIvan** [comment] 2024-05-16 09:46
Duplicate of #3818

**Closed by MatkovIvan** 2024-05-16 09:46 UTC
Labels: enhancement, gradle

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4817">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
