### ISSUE TITLE
rememberSaveable not being restored on iOS

### ISSUE THREAD

**Issue by DevSrSouza** [JetBrains/compose-multiplatform#4112] opened 2024-01-09 23:18 UTC
**Describe the bug**
`rememberSaveable` is not being restored after presenting a new viewController (in the sample, the `UIImagePickerController`).

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Simulator in Xcode 14.3
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
```kotlin
fun MainViewController() = ComposeUIViewController {
    val randomNumber = rememberSaveable {
        Random.nextInt()
    }
    Column {
        val rootViewController = LocalUIViewController.current
        val imagePicker = remember {
            ImagePicker(
                rootController = rootViewController
            )
        }
        Text(text = "$randomNumber")
        Button(onClick = {
            imagePicker.openCamera()
        }) {
            Text("Open camera")
        }
    }
}

internal class ImagePicker(
    private val rootController: UIViewController
) {
    private val pickerController = UIImagePickerController().apply {
        sourceType = UIImagePickerControllerSourceType.UIImagePickerControllerSourceTypeCamera
    }

    fun openCamera() {
        rootController.presentViewController(pickerController, true, null)
    }
}
```

Steps:
- Look at the Random number text
- open camera
- Cancel the operation
- The random number text has change

**Expected behavior**
The text with the random number should be the same/restored

**Screenshots**
https://github.com/JetBrains/compose-multiplatform/assets/29736164/3d249104-071c-42e3-8769-04eb6e659250

**Comment by MatkovIvan** [comment] 2024-01-09 23:46
It's duplicate of #1932

Despite that mentioned issue is quite old, it's not actually forgotten - we're planning to support this as part of (partially) porting lifecycle packages, which is required for proper navigation support.

**Closed by MatkovIvan** 2024-01-09 23:46 UTC
Labels: bug, submitted

**Comment by DevSrSouza** [comment] 2024-01-09 23:50
@MatkovIvan I tough that issue was not related to iOS it self.

It seems that a previous version for Compose iOS was working because was not disposing the Composition, based on the comments of this PR:
https://github.com/JetBrains/compose-multiplatform-core/pull/747

**Comment by MatkovIvan** [comment] 2024-01-10 00:26
> It seems that a previous version for Compose iOS was working

Thanks for this note. There are a few corner cases here, previously it was a source of memory leaks. So, it's about two things:
1. Correct lifecycle of the Compose
2. Restoring `rememberSaveable` during Compose re-creation

(1) is not trivial problem of combinng GC and ARC, @elijah-semyonov and @ASalavei are working on it.
(2) is duplicate, as I mentioned above

**Comment by elijah-semyonov** [comment] 2024-01-11 11:54
Actually, the memory leak with determined but not too eager scene destruction is already implemented:
https://github.com/JetBrains/compose-multiplatform-core/commit/e001c0834bf2104c769055ea6db56d1b22eadccd#diff-ecbf335e72ff3f67cd7b87edb287efad88f3088f4c6a71b450d98b14c867d132

**Comment by okushnikov** [comment] 2024-07-14 16:05
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4112">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
