### ISSUE TITLE
[1.6.10-Beta02] Breaks cocoapod import iOS library

### ISSUE THREAD

**Issue by cmpeguerog** [JetBrains/compose-multiplatform#4709] opened 2024-04-26 15:11 UTC
**Describe the bug**
After updating to **Compose multiplatform** 1.16.10-beta02 gradle sync fails importing pods dependencies. Currently im trying to import **libPhoneNumber-iOS** but i did test with other libraries and the issue still there. The last working version was 1.6.10-dev1557

Gradle Task output: **Task with name 'podBuildLibPhoneNumber-iOSIphonesimulator' not found in project ':composeApp'.**

**Affected platforms**
- iOS
- Android
**Versions**
- Kotlin version* : 2.0.0-RC1 
- Compose Multiplatform version*: 1.6.10-beta02
- OS version(s)* (required for Desktop and iOS issues): Ventura 13.6.6
- OS architecture (x86 or arm64): x86

**Additional context**
```
 cocoapods {
        version = libs.versions.android.version.name.get()
        summary = "iOS libraries"
        ios.deploymentTarget = "16.0"

        pod("libPhoneNumber-iOS", version = "~> 0.8", moduleName = "libPhoneNumber_iOS")
    }

**Comment by MatkovIvan** [comment] 2024-04-26 15:40
Duplicate of #4632

**Closed by MatkovIvan** 2024-04-26 15:40 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-08-26 13:41
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4709">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
