### ISSUE TITLE
Resource usage from multiple modules - org.jetbrains.compose.resources.MissingResourceException

### ISSUE THREAD

**Issue by IlyaPavlovskii** [JetBrains/compose-multiplatform#4418] opened 2024-03-03 21:48 UTC
**Describe the bug**

I've tried to use a new stable version of [compose multiplatform resources](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html) and found one problem with iOS build.
When my application module includes internal submodules with resource usage - I always receive runtime crash on iOS app version. 
To solve this problem, I have to copy-paste resources from ALL submodules into the APP module. Looks like an iOS bug.

![image](https://github.com/JetBrains/compose-multiplatform/assets/1473820/d25ab045-b1d8-4f18-b5ae-9a29851c0d81)

here is the commit with solution: https://github.com/IlyaPavlovskii/YouTubePlayer/commit/9e26611f2c36c69bfd9128c22b34a7da097602d2#diff-1b4fc3f655cfb0189c13c5849ed6e536963e18bd502fb3ff8af5a0975180e939

**Affected platforms**

- [ ] Desktop (Windows, Linux, macOS)
- [x] iOS
- [ ] Web (K/Wasm) - Canvas based API
- [ ] Web (K/JS) - Canvas based API
- [ ] Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): N/A
- OS architecture (x86 or arm64): all
- Device (model or simulator for iOS issues):  simulator - iOS 17.2
- JDK (for desktop issues): -

**Expected behavior**
Build without copy-paste resources from submodules for iOS build.

**Comment by MatkovIvan** [comment] 2024-03-04 08:19
Currently using resources from multiple modules is not supported. Documented here: https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

Duplicate of #4229

**Closed by MatkovIvan** 2024-03-04 08:19 UTC
Labels: bug, submitted

**Comment by kingsword09** [comment] 2024-03-15 09:10
@MatkovIvan In the `compose-multiplatform 1.6.1` version, the multiple modules `composeResources` is still not supported on the `iOS` platform. Is there a plan on which version this feature will be added?

**Comment by MatkovIvan** [comment] 2024-03-15 09:19
@terrakok is already [working](https://github.com/JetBrains/compose-multiplatform/pull/4454) on it (please note that it will require KGP >= `2.0.0-Beta05`)

**Comment by dmitry-stakhov** [comment] 2024-03-15 09:34
@MatkovIvan thank you for the update. Can I know when it's planned to be released? Any plans to have `1.6.2`?

**Comment by okushnikov** [comment] 2024-07-14 15:07
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4418">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
