### ISSUE TITLE
Could not package to dmg file

### ISSUE THREAD

**Issue by GaoXing0608** [JetBrains/compose-multiplatform#4118] opened 2024-01-11 11:08 UTC
Could not package on MacOS

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.22
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): MacOS11
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17
-

codesign error log
/Library/Developer/CommandLineTools/usr/bin/codesign_allocate: fatal error: file not in an order that can be processed (code signature data out of place): /Users/gaoxing/Documents/idea/PerfCatDesktop/build/compose/tmp/sign/libsqlitejdbc.jnilib
/Users/gaoxing/Documents/idea/PerfCatDesktop/build/compose/tmp/sign/libsqlitejdbc.jnilib: the codesign_allocate helper tool cannot be found or used

![image](https://github.com/JetBrains/compose-multiplatform/assets/47878271/e13f037d-30a6-49dd-b81b-f430baf857ae)

**Comment by MatkovIvan** [comment] 2024-01-11 11:16
Duplicate of #3914

**Closed** 2024-01-11 11:16 UTC
Labels: bug, duplicate, native distribution, macos

**Comment by okushnikov** [comment] 2024-07-14 16:05
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4118">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
