### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getParameter')

### ISSUE THREAD

**Issue by Sagar-upadhayay** [JetBrains/compose-multiplatform#4130] opened 2024-01-16 07:20 UTC
when i run web module at first time after localhost run see this error on webpage

Cannot read properties of undefined (reading 'getParameter')
TypeError: Cannot read properties of undefined (reading 'getParameter')
    at _glGetString (webpack-internal:///./kotlin/skiko.mjs:942:99458)
    at http://localhost:8080/skiko.wasm:wasm-function[7771]:0x2a23ec
    at http://localhost:8080/skiko.wasm:wasm-function[610]:0x1f01d
    at <SecondApp:composeApp>.org.jetbrains.skia.Companion.makeGL (http://localhost:8080/composeApp.wasm:wasm-function[21441]:0x2c5080)
    at <SecondApp:composeApp>.org.jetbrains.skiko.CanvasRenderer.<init> (http://localhost:8080/composeApp.wasm:wasm-function[23916]:0x2f6841)
    at <SecondApp:composeApp>.org.jetbrains.skiko.<no name provided>.<init> (http://localhost:8080/composeApp.wasm:wasm-function[23963]:0x2f7604)
    at <SecondApp:composeApp>.org.jetbrains.skiko.SkiaLayer.attachTo (http://localhost:8080/composeApp.wasm:wasm-function[24013]:0x2f7ebc)
    at <SecondApp:composeApp>.org.jetbrains.skiko.SkiaLayer.attachTo$default (http://localhost:8080/composeApp.wasm:wasm-function[24014]:0x2f7fd7)
    at <SecondApp:composeApp>.androidx.compose.ui.window.ComposeWindow.<init> (http://localhost:8080/composeApp.wasm:wasm-function[33584]:0x3bb44f)
    at <SecondApp:composeApp>.androidx.compose.ui.window.CanvasBasedWindow (http://localhost:8080/composeApp.wasm:wasm-function[33546]:0x3baa29)

**Comment by pjBooms** [comment] 2024-01-16 12:12
Can you describe in details the steps to reproduce the problem?

**Comment by Sagar-upadhayay** [comment] 2024-01-17 07:25
After download projects template from jetbrain website target android,
destop, web with  and after open project in android studio Run compose
multiplatform web app in windows pc not in mac ios.
Localhost run webpage show this error

**Comment by pjBooms** [comment] 2024-01-18 17:54
Unfortunately I cannot reproduce this error. What browser of what version do you use?

**Comment by Sagar-upadhayay** [comment] 2024-01-21 16:30
Chrome browser version 120
 Its latest version of chrome in windows 10

**Comment by pjBooms** [comment] 2024-01-22 12:17
Same for me (Version 120.0.6099.225 (Official Build) (64-bit)). Then what JDK (version, vendor, build) do you use?

**Comment by Sagar-upadhayay** [comment] 2024-01-23 10:25
Please connect with my pc on Google Meet or any desk.
I have used Jdk

GRADLE LOCAL JAVA HOME
jetbrain Runtime version 17.0.7

**Comment by Intex32** [comment] 2024-01-25 23:21
Hey, I have the same error in my project based on [this](https://github.com/Kotlin/kotlin-wasm-examples/tree/main/compose-imageviewer) repo. This was compiled using Oracle OpenJDK 17. The main html file of the output of gradle task `wasmJsBrowserDistribution` was opened in Chromium (Version 119) on Linux: Nothing renders, above error in the console. Strangely, opening the same html file in Chrome on Windows works.

**Comment by Intex32** [comment] 2024-01-26 21:06
@pjBooms I just tested if the behavior is alike for the above referenced repo (kotlin-wasm-examples/image-viewer). And indeed, same error is shown when exported and opened. With that I assume it should be reproduceable somehow.
Let me know if you need any other information.

**Comment by dosier** [comment] 2024-03-02 20:07
Same issue here on `Chrome Version 121.0.6167.85 (Official Build) (arm64)`

**Comment by Sagar-upadhayay** [comment] 2024-03-23 20:13
please give solution

**Comment by okushnikov** [comment] 2024-07-14 15:06
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4130">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:52 UTC
Labels: bug, windows, web
