### ISSUE TITLE
Compose Multiplatform and Jetpack Compose method signatures are inconsistent.

### ISSUE THREAD

**Issue by Junzz0** [JetBrains/compose-multiplatform#5004] opened 2024-06-21 06:48 UTC
**Describe the bug**
Compose Multiplatform and Jetpack Compose method signatures are inconsistent.

**Affected platforms**

- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library 

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.7.0-dev1686
  - Navigation Multiplatform version (for related issues): 2.8.0-alpha02
  - ...
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): x86
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 17

**To Reproduce**
https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/NavigationBar.kt
https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/NavigationDrawer.kt
https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/NavigationRail.kt

https://github.com/androidx/androidx/blob/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/NavigationBar.kt
https://github.com/androidx/androidx/blob/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/NavigationDrawer.kt
https://github.com/androidx/androidx/blob/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/NavigationRail.kt

Compose Multiplatform is `interactionSource: MutableInteractionSource = remember { MutableInteractionSource() }`
Jetpack Compose is `interactionSource: MutableInteractionSource? = null,`

#4952 

**Expected behavior**
Expectations are consistent with upstream.

**Comment by MatkovIvan** [comment] 2024-06-21 06:58
Last released multiplatform version of material3 is based on 1.2.1

Adopting 1.3 betas is in progress. Closing as duplicate of #4849

**Closed by MatkovIvan** 2024-06-21 06:58 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-08-26 13:36
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5004">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
