### ISSUE TITLE
iOS Crash: LocalUriHandler not handling phone URIs

### ISSUE THREAD

**Issue by yuroyami** [JetBrains/compose-multiplatform#3971] opened 2023-11-24 17:24 UTC
(@mazunin-v-jb : moved versions here)
Kotlin version: 1.9.21
Compose-jb: 1.5.11
OS: iOS 16.3.1 arm64

Consider the following code:

```kotlin
val websiteUri = "https://www.example.com"
val phoneUri = "tel:+29429402"

val uriHandler = LocalUriHandler.current
uriHandler.openUri(websiteUri) //Works fine on Android and iOS
uriHandler.openUri(phoneUri) <--- Crashes
```

The syntax `tel: + phone number` is used for Android only (afaik), however, it is not working on iOS. I haven't tested yet whether the iOS syntax (`tel:// + phone number`) is handled on iOS (probably cannot be handled on Android if it works on iOS). The LocalUriHandler needs to route both syntaxes to their proper handlers on each platform, replacing `tel:` with `tel://` for iOS, and removing the two slashes if it is being routed to Android from `tel://` syntax.

In order to launch a telephony URI for iOS, I use this code for now:

```swift
        if let phoneURL = URL(string: "tel://\(phoneNumber)") {
            UIApplication.shared.open(phoneURL, options: [:], completionHandler: nil)
        }
```

**Comment by mazunin-v-jb** [comment] 2023-11-27 13:54
Hello, thank you for submitting the issue.
Could you please also provide the log crash?

**Comment by yuroyami** [comment] 2023-12-25 09:40
@mazunin-v-jb I am away from my work station for quite some while but as far as I remember, the issue occurred while I was using a phone number that contains white spaces and parentheses. I did not try using a phone number without white spaces or the parentheses.

Kotlin version: 1.9.21
Compose-jb: 1.5.11
OS: iOS 16.3.1 arm64

**Comment by mazunin-v-jb** [comment] 2024-01-16 14:53
Thank you for your answer. As far as I remember, I've tried just a number without any special symbols like you described.
I'll take a look.

**Comment by mazunin-v-jb** [comment] 2024-02-21 21:11
Hello, @yuroyami!
Sorry for long responding.
I've tried to dig dipper into this problem, so I've created [a reproducer with many cases of phone numbers.](https://github.com/mazunin-v-jb/cmp-issue-3971/tree/main)
Could you please check it? For me, it works as expected on both iOS and Android.

Also, for iOS testing, please use a physical device (iPhone or iPad). iOS Simulator can't forward `tel:/` uri to phone app cause it doesn't have it.
Maybe that was the reason for different behavior in our cases.

**Comment by okushnikov** [comment] 2024-07-14 15:54
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3971">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:57 UTC
Labels: bug, wait for reply, crash, ios
