### ISSUE TITLE
Enhancement: Improve codeviewer example:  No protrude splittable both side .

### ISSUE THREAD

**Issue by MulticolorWorld** [JetBrains/compose-multiplatform#148] opened 2020-11-28 07:22 UTC
In the "vertical splitter" example currently used in codeviewer, the left side does not protrude due to the minimum size specification, but the right side has no limit and will protrude outside the window.
I'd like to improve this, but I'm wondering if you have any good examples.

Sorry Im poor English end use machine translation sorry.

**Comment by MulticolorWorld** [comment] 2020-11-28 07:23
If this is not appropriate here, I would be grateful if you could guide me to the right place.

**Comment by MulticolorWorld** [comment] 2020-11-29 13:10
How to get parent size in composable function? If exist, coerceAtMost() is work it.

**Comment by igordmn** [comment] 2020-11-29 13:15
You can look at this:
https://github.com/JetBrains/compose-jb/commit/9e67cfc916f696220d630ceb6e5b67e9570777a3

But it is not finished. If we resize main window then we will see a small lag (size of panel will not be immediately changed)

**Comment by MulticolorWorld** [comment] 2020-11-29 15:16
Getting size composable itself to use onSizeChanged() and size-state is workaround? Allow it normally?

**Comment by igordmn** [comment] 2020-11-29 15:26
>Getting size of composable itself to use onSizeChanged() and size-state is workaround? Allow to use it normally?

Probably the lag when we resize the main window caused by onSizeChanged (because the panel will be resized only on the second frame).

Probably we need to constrain sizes of panels not inside onSizeChanged, but inside VerticalSplittable function

**Comment by MulticolorWorld** [comment] 2020-11-29 15:36
Oh, sorry. Apart from this issue, I wanted to ask if this usage is normal. Probably because there are going to be many situations where you want to know the size of itself.

**Comment by igordmn** [comment] 2020-11-29 15:43
>I wanted to ask if this usage is normal

Probably in most cases we should use [Layout](https://developer.android.com/reference/kotlin/androidx/compose/ui/layout/package-summary#layout) or [WithConstraints](https://developer.android.com/reference/kotlin/androidx/compose/ui/layout/package-summary#withconstraints)

Because we will know the size of the container immediatly (in the current frame).

But in the case it is not importand to know the size in the current frame, we can use onSizeChanged and size-state.

**Comment by okushnikov** [comment] 2024-07-14 17:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5586">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 11:11 UTC
Labels: enhancement, examples, desktop
