### ISSUE TITLE
Revert the throwing toString() of the self CSS selector

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/compose-multiplatform#1940] opened 2022-03-08 21:54 UTC
Hello,

After the issue #1440 was addressed, it broke some code, without providing any alternative.

The following code snippets used to produce the desired effect of targeting this element it it had the `kotlin-colors-conic-gradient` CSS class, but it now fails **at runtime**:

```kotlin
"$self.kotlin-colors-conic-gradient" {
    background("conic-gradient(from 225deg, #7F52FF, #C711E1, #E44857, #C711E1, #7F52FF)")
}
```
```kotlin
combine(self, className("kotlin-colors-conic-gradient")).style {
    background("conic-gradient(from 225deg, #7F52FF, #C711E1, #E44857, #C711E1, #7F52FF)")
}
```

I have to downgrade Kotlin to `1.5.21` and Compose to `1.0.0-alpha1-rc4` until this is reverted, and I say reverted because I believe no object should have its `toString()` function throw by design, unless there's actually something wrong in the runtime, which isn't the case here. This goes against all expectations for Kotlin and Java developers, and beyond as you can't even log the string representation in any way.

I don't understand how #1440 was an issue and why it's been "solved" like that. Can you tell?

Thank you and all the best,

Louis CAD

**Comment by akurasov** [comment] 2022-03-09 13:24
Could you please share a whole small reproducer?

**Comment by eymar** [comment] 2022-03-14 11:08
As I remember there was a bug related to `self`. The most feasible solution at that point made it not possible to use `self` in strings. The idea was that using `self` in strings is not necessary at all, since corresponding selector functions can be used: `combine(...)` for example. 

As for alternatives:

```kotlin
combine(self, className("kotlin-colors-conic-gradient")).style {
    background("conic-gradient(from 225deg, #7F52FF, #C711E1, #E44857, #C711E1, #7F52FF)")
}
```

Does it fail in your case? 
It works in my case, so maybe there's something else I need to consider.

**Comment by LouisCAD** [comment] 2022-03-14 17:04
Yes it was failing in my case.

This revision of my repo should reproduce this issue: https://github.com/LouisCAD/ResumeComposition/tree/0a361613c0ecb68cc789e085c6dd7abdda357cda

**Comment by eymar** [comment] 2022-03-15 11:17
```
Index: resume/src/jsMain/kotlin/com/louiscad/resume/LouisCadResumeStyleSheet.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/resume/src/jsMain/kotlin/com/louiscad/resume/LouisCadResumeStyleSheet.kt b/resume/src/jsMain/kotlin/com/louiscad/resume/LouisCadResumeStyleSheet.kt
--- a/resume/src/jsMain/kotlin/com/louiscad/resume/LouisCadResumeStyleSheet.kt	(revision 0a361613c0ecb68cc789e085c6dd7abdda357cda)
+++ b/resume/src/jsMain/kotlin/com/louiscad/resume/LouisCadResumeStyleSheet.kt	(date 1647342848919)
@@ -31,7 +31,7 @@
 
     override val borderedSectionWrapper: String by style {
         background("conic-gradient(from 150deg, magenta, cyan, magenta)")
-        "$self.kotlin-colors-conic-gradient" {
+        combine(self, className("kotlin-colors-conic-gradient")) style {
             background("conic-gradient(from 225deg, #7F52FF, #C711E1, #E44857, #C711E1, #7F52FF)")
         }
         padding(borderSize)
Index: resume/src/jsMain/kotlin/com/louiscad/resume/ResumeStyleSheet.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/resume/src/jsMain/kotlin/com/louiscad/resume/ResumeStyleSheet.kt b/resume/src/jsMain/kotlin/com/louiscad/resume/ResumeStyleSheet.kt
--- a/resume/src/jsMain/kotlin/com/louiscad/resume/ResumeStyleSheet.kt	(revision 0a361613c0ecb68cc789e085c6dd7abdda357cda)
+++ b/resume/src/jsMain/kotlin/com/louiscad/resume/ResumeStyleSheet.kt	(date 1647342718880)
@@ -38,6 +38,11 @@
         "h3" { fontSize(16.px) }
         "h4" { fontSize(14.px) }
         "h5" { fontSize(13.px) }
+
+        "@page" {
+            property("size", "auto")
+            margin(0.mm)
+        }
     }
 
     open val container by style {
@@ -52,10 +57,6 @@
         media("print") {
             margin((-10).px)
         }
-        "@page" {
-            property("size", "auto")
-            margin(0.mm)
-        }
         "html" {
             margin(0.mm)
         }
@@ -67,7 +68,7 @@
     open val sectionsColumn by style {
         "h1, h2, h3, h4, h5, h6".split(", ").map {
             desc(self, selector(it))
-        }.joinToString() style {
+        }.let { group(*it.toTypedArray()) } style {
             textAlign("center")
             property("margin-block-start", 8.px)
             property("margin-block-end", 8.px)
```

With the patch above [this commit](https://github.com/LouisCAD/ResumeComposition/tree/0a361613c0ecb68cc789e085c6dd7abdda357cda) works.

**Comment by eymar** [comment] 2022-03-17 09:07
@LouisCAD did the patch above help?

**Comment by okushnikov** [comment] 2024-07-14 17:17
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1940">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:50 UTC
Labels: question, web
