### ISSUE TITLE
ComposeUIViewController cannot dealloc on iOS platform

### ISSUE THREAD

**Issue by hxxyyangyong** [JetBrains/compose-multiplatform#3361] opened 2023-07-18 06:54 UTC
After I experimented with compose to write ios pages, I found that the memory usage was particularly large and continued to grow，
so I am doing a case of using Compose to display pictures on the ios platform to analyze the memory usage problem. The address is as follows:

https://github.com/hxxyyangyong/TestDemo

Use the analysis tool that comes with XCode to do memory analysis, and encounter several problems; as follows:
1. There is a problem with CGColor leaking
2. After the Compose UI Controller page exits, dealloc cannot be executed 

_（Regarding this point, I used the runtime method in iOS to replace the method. The native UIViewController can execute dealloc, but the ViewController created by ComposeUIViewController cannot execute dealloc）_

Stack logs of internal unreleased and memory leaks：

![image](https://github.com/JetBrains/compose-multiplatform/assets/1219331/1ee77b50-8012-4d3c-b2e0-a18d6ba46a56)

![image](https://github.com/JetBrains/compose-multiplatform/assets/1219331/b9e9d4a4-d255-4414-9fe5-cb66e030fc80)

![image](https://github.com/JetBrains/compose-multiplatform/assets/1219331/00b40135-659c-486c-a0f5-dab1f01e947b)

![image](https://github.com/JetBrains/compose-multiplatform/assets/1219331/562ffdf1-0503-4341-8f97-6cb7752f36f4)

![image](https://github.com/JetBrains/compose-multiplatform/assets/1219331/c9e793e9-dea8-42d3-a82b-14c5cbaef209)
。。。

At the same time, after I tried to upgrade kotlin to 1.9.0 locally, the problem still exists. I guess it should be caused by Compose-Multiplatform's unreasonable handling of OC objects.

profile ：

[testdemo.trace.zip](https://github.com/JetBrains/compose-multiplatform/files/12077067/testdemo.trace.zip)

**Comment by alexzhirkevich** [comment] 2023-07-18 07:42
Duplicate of https://github.com/JetBrains/compose-multiplatform/issues/3201

**Comment by hxxyyangyong** [comment] 2023-07-18 08:30
Is there a solution currently? Or rely on subsequent upgrades? @alexzhirkevich

**Comment by alexzhirkevich** [comment] 2023-07-18 14:32
No current solution. Hope it will be fixed with kotlin 1.9 in the next release

**Comment by sunildhiman90** [comment] 2023-07-18 14:34
Hi, Sorry to ask but can anyone tell me, how we can track if dealloc is called or not for ios. How are you getting these traces which are in screenshots?

**Comment by elijah-semyonov** [comment] 2023-07-21 08:20
@sunildhiman90 you can launch the app in Xcode and use Xcode Instruments to do all kinds of profiling just like for native iOS apps.

**Comment by sunildhiman90** [comment] 2023-07-21 13:35
Thanx @elijah-semyonov , Actually i have very little knowledge about ios native  development , thats why i asked

**Comment by elijah-semyonov** [comment] 2023-07-26 08:26
Closing as duplicate of
https://github.com/JetBrains/compose-multiplatform/issues/3201

**Closed by elijah-semyonov** 2023-07-26 08:26 UTC
Labels: bug, duplicate, skiko, native

**Comment by okushnikov** [comment] 2024-08-26 14:40
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3361">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
