### ISSUE TITLE
Support for Layout Inspector for Android

### ISSUE THREAD

**Issue by CRamsan** [JetBrains/compose-multiplatform#2914] opened 2023-03-23 21:23 UTC
Android Studio is not able to open the hierarchy tree or recomposition count when running using the Android libraries from Jetbrains Compose/Compose Multiplatform. Having access to this tools would be a great benefit to be able to efficiently debug issues on layouts on Android.  
The [Compose Multiplatform template](https://github.com/JetBrains/compose-multiplatform/tree/master/templates/multiplatform-template) is the minimum required to repro this issue.

Currently testing:
- Android Studio: Electric Eel 2022.1.1 Patch 2
- Kotlin: 1.8.0
- AGP: 7.4.2
- Compose: 1.4.0-alpha01-dev977

**Comment by Shabinder** [comment] 2023-04-25 21:31
been more than a month, any etas on this / workarounds ?

**Comment by hereisderek** [comment] 2023-06-19 23:33
really hope this would get more attraction.

**Comment by senk0n** [comment] 2023-08-29 09:26
It's possible, just a matter of configuration, see https://github.com/JetBrains/compose-multiplatform-template/pull/18#issuecomment-1696974824

**Comment by Omico** [comment] 2024-01-14 01:11
Any updates for this? It only shows the top composable of it. This bug makes Compose Multiplatform difficult to debug.

IntelliJ IDEA 2023.3.2

IDEA plugins: 
Android 233.13135.106
Jetpack Compose 233.13135.106
Compose Multiplatform IDE Support 1.5.11

Compose Multiplatform 1.5.11
Kotlin 1.9.21

![image](https://github.com/JetBrains/compose-multiplatform/assets/14316223/7e2655a0-cf5b-46a1-9445-71645a2eefae)

**Comment by Omico** [comment] 2024-02-23 18:35
Just notice it works now!

IntelliJ IDEA 2023.3.4

IDEA plugins:
Android 233.14475.28
Jetpack Compose 233.13135.106
Compose Multiplatform IDE Support 1.5.12

Compose Multiplatform 1.6.0-rc02
Kotlin 1.9.22

![image](https://github.com/JetBrains/compose-multiplatform/assets/14316223/95374af0-105f-4968-8e36-a235208dae54)

**Comment by robxyy** [comment] 2024-03-12 07:17
@Omico Can you provide a demo? I have tried using the same environment, but it still doesn't work.

**Comment by jccr** [comment] 2024-03-19 08:27
> @Omico Can you provide a demo? I have tried using the same environment, but it still doesn't work.

It wasn't working (just showing MaterialTheme, and no child nodes) until I added these to my `android` target.

As suggested by https://github.com/JetBrains/compose-multiplatform/issues/2914#issuecomment-1697083407

```kotlin
android {
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = libs.versions.compose.compiler.get()
    }

```

**Comment by robxyy** [comment] 2024-03-19 12:57
> As suggested by [#2914 (comment)](https://github.com/JetBrains/compose-multiplatform/issues/2914#issuecomment-1697083407)
> 
> ```kotlin
> android {
>     buildFeatures {
>         compose = true
>     }
>     composeOptions {
>         kotlinCompilerExtensionVersion = libs.versions.compose.compiler.get()
>     }
> ```
Thanks. I've found the cause of the problem, `library module` should also be set up like this :)

**Comment by Omico** [comment] 2024-05-28 18:05
Here is a full demo with Kotlin 2.0.0 & Compose Multiplatform 1.6.10. The layout inspector is working.
https://github.com/Omico/picsum/tree/cmp

**Comment by okushnikov** [comment] 2024-08-26 13:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2914">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:40 UTC
Labels: enhancement, android studio, submitted
