### ISSUE TITLE
Recomposition does not occur when iterating a list of window states, if a state is dynamically added after initial composition

### ISSUE THREAD

**Issue by hakanai** [JetBrains/compose-multiplatform#4099] opened 2024-01-04 10:16 UTC
**Describe the bug**
Following the example from ["Open and close multiple windows"][1], if the application instead begins with no windows visible, and the first window state is added from a `LaunchedEffect`, then the window which should appear never appears, and the application terminates instead.

[1]: https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new#open-and-close-multiple-windows

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): Corretto-17.0.9.8.1

**To Reproduce**
1. Copy the [sample code][2] into a new Kotlin file:
2. Run its `main()` function
3. Wait until the process exits - observe that no window appears

Useful breakpoints:
- A breakpoint on the code which adds the window state to the list shows that it does get called and does add it to the list
- A breakpoint on the loop over the states shows that it only gets called once at the start, when the list of window states is empty - and does not get called after adding the state

[2]: https://gist.github.com/hakanai/a9ec53c015c54b7de10729e75fa05069

**Expected behavior**
As far as I can tell, adding the window state to the list of windows _should_ result in recomposition.

**Comment by m-sasha** [comment] 2024-01-04 11:29
This appears to be the same as https://github.com/JetBrains/compose-multiplatform/issues/3987

**Comment by eymar** [comment] 2024-01-08 09:30
Let's close it as a duplicate of #3987 if you don't mind

**Closed by eymar** 2024-01-08 09:30 UTC
Labels: bug, submitted

**Comment by okushnikov** [comment] 2024-07-14 16:08
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4099">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
