### ISSUE TITLE
kotlin/native - items in UIKitView compose are not remembered and are recomposing on scroll.

### ISSUE THREAD

**Issue by pradeep-magzter** [JetBrains/compose-multiplatform#3458] opened 2023-08-04 12:34 UTC
compose multiplatform 1.5.0-beta01 - kotlin/native - items in UIKitView compose are not remembered and are recomposing on scroll.
learning to use koltin-native api for ios image, video, audio, webview, pdf, map etc. Loaded those in a lazycolumn.
issue: items in UIKitView compose are not remembered and are recomposing on scroll.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta01
- OS version(s)* (required for Desktop and iOS issues): Mac OS 12.6.7
- OS architecture (x86 or arm64): x86

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. clone https://github.com/lspradeep/compose-multiplatform-media.git
2. run in iOS simulator
3. Scroll down to see recomposition in UIKitView

**Expected behavior**
Smooth scroll without recomposition

https://github.com/JetBrains/compose-multiplatform/assets/107530424/85078ef8-4976-45c4-b1b4-a21cf67c9613

**Comment by lspradeep** [comment] 2023-08-04 16:13
The same issue is reproducible in the M1 Macbook too.

https://github.com/JetBrains/compose-multiplatform/assets/25198507/63fda85b-c49f-4b88-80be-6b27e4edde2e


Kotlin version*: 1.9.0
Compose Multiplatform version*: 1.5.0-beta01
OS version(s)* (required for Desktop and iOS issues): macOS 13.4.1 (c) 
OS architecture (x86 or arm64): arm64

**Comment by elijah-semyonov** [comment] 2023-08-09 09:48
This is currently by design and we don't pool `UIView`s to be reused like `UI[Table/Collection]View`s internally do. Currently you can try to work around it by supplying remembered UIView from outside to the `factory`.

**Comment by lspradeep** [comment] 2023-08-09 16:51
I get your point. but I think that's how the code is written. please correct me if I'm wrong. 
refer: https://github.com/lspradeep/compose-multiplatform-media/blob/master/shared/src/iosMain/kotlin/commonapis.ios.kt

consider the below code from `commonapis.ios.kt` file, and let me know what can be improved to avoid that issue.
```
@OptIn(ExperimentalForeignApi::class)
@Composable
actual fun MediaPlayerUI(modifier: Modifier, url: String) {
    var avPlayer by remember { mutableStateOf<AVPlayer?>(null) }
    var avPlayerViewController by remember { mutableStateOf<AVPlayerViewController?>(null) }
    var uiView by remember { mutableStateOf<UIView?>(null) }

    LaunchedEffect(Unit) {
        avPlayer = withContext(Dispatchers.Main) {
            AVPlayer(uRL = NSURL(string = url))
        }
        avPlayerViewController = withContext(Dispatchers.Main) {
            AVPlayerViewController().apply {
                player = avPlayer
                showsPlaybackControls = true
                entersFullScreenWhenPlaybackBegins = true
                exitsFullScreenWhenPlaybackEnds = true
                videoGravity = AVLayerVideoGravityResize
                contentOverlayView?.autoresizesSubviews = true
            }
        }
        uiView = withContext(Dispatchers.Main) {
            avPlayerViewController?.view
        }
    }

    if (avPlayer != null && uiView != null) {
        UIKitView(
            modifier = modifier,
            factory = {
                uiView!!
            },
            interactive = true,
            background = Color.Gray
        )
    }
}
```

**Comment by Lowae** [comment] 2023-09-25 03:40
> I get your point. but I think that's how the code is written. please correct me if I'm wrong. refer: https://github.com/lspradeep/compose-multiplatform-media/blob/master/shared/src/iosMain/kotlin/commonapis.ios.kt我明白你的意思。但我认为这就是代码的编写方式。如果我错了，请纠正我。 参考： https://github.com/lspradeep/compose-multiplatform-media/blob/master/shared/src/iosMain/kotlin/commonapis.ios.kt
> 
> consider the below code from `commonapis.ios.kt` file, and let me know what can be improved to avoid that issue.考虑以下来自commonapis.ios.kt文件的代码，并让我知道可以改进哪些内容以避免该问题。
> 
> ```
> @OptIn(ExperimentalForeignApi::class)
> @Composable
> actual fun MediaPlayerUI(modifier: Modifier, url: String) {
>     var avPlayer by remember { mutableStateOf<AVPlayer?>(null) }
>     var avPlayerViewController by remember { mutableStateOf<AVPlayerViewController?>(null) }
>     var uiView by remember { mutableStateOf<UIView?>(null) }
> 
>     LaunchedEffect(Unit) {
>         avPlayer = withContext(Dispatchers.Main) {
>             AVPlayer(uRL = NSURL(string = url))
>         }
>         avPlayerViewController = withContext(Dispatchers.Main) {
>             AVPlayerViewController().apply {
>                 player = avPlayer
>                 showsPlaybackControls = true
>                 entersFullScreenWhenPlaybackBegins = true
>                 exitsFullScreenWhenPlaybackEnds = true
>                 videoGravity = AVLayerVideoGravityResize
>                 contentOverlayView?.autoresizesSubviews = true
>             }
>         }
>         uiView = withContext(Dispatchers.Main) {
>             avPlayerViewController?.view
>         }
>     }
> 
>     if (avPlayer != null && uiView != null) {
>         UIKitView(
>             modifier = modifier,
>             factory = {
>                 uiView!!
>             },
>             interactive = true,
>             background = Color.Gray
>         )
>     }
> }
> ```

I think you can move you uiView to a ViewModel or others to control it lifecycle by manual.

**Comment by Lowae** [comment] 2023-09-25 03:41
> I get your point. but I think that's how the code is written. please correct me if I'm wrong. refer: https://github.com/lspradeep/compose-multiplatform-media/blob/master/shared/src/iosMain/kotlin/commonapis.ios.kt
> 
> consider the below code from `commonapis.ios.kt` file, and let me know what can be improved to avoid that issue.
> 
> ```
> @OptIn(ExperimentalForeignApi::class)
> @Composable
> actual fun MediaPlayerUI(modifier: Modifier, url: String) {
>     var avPlayer by remember { mutableStateOf<AVPlayer?>(null) }
>     var avPlayerViewController by remember { mutableStateOf<AVPlayerViewController?>(null) }
>     var uiView by remember { mutableStateOf<UIView?>(null) }
> 
>     LaunchedEffect(Unit) {
>         avPlayer = withContext(Dispatchers.Main) {
>             AVPlayer(uRL = NSURL(string = url))
>         }
>         avPlayerViewController = withContext(Dispatchers.Main) {
>             AVPlayerViewController().apply {
>                 player = avPlayer
>                 showsPlaybackControls = true
>                 entersFullScreenWhenPlaybackBegins = true
>                 exitsFullScreenWhenPlaybackEnds = true
>                 videoGravity = AVLayerVideoGravityResize
>                 contentOverlayView?.autoresizesSubviews = true
>             }
>         }
>         uiView = withContext(Dispatchers.Main) {
>             avPlayerViewController?.view
>         }
>     }
> 
>     if (avPlayer != null && uiView != null) {
>         UIKitView(
>             modifier = modifier,
>             factory = {
>                 uiView!!
>             },
>             interactive = true,
>             background = Color.Gray
>         )
>     }
> }
> ```

I think you can move you uiView to a ViewModel or others to control it lifecycle by manual.

**Comment by pradeep-magzter** [comment] 2023-10-22 20:41
[sorry, my bad.. should have replied from the same account I guess..]

I get your point. but I think that's how the code is written. please correct me if I'm wrong. 
refer: https://github.com/lspradeep/compose-multiplatform-media/blob/master/shared/src/iosMain/kotlin/commonapis.ios.kt

consider the below code from `commonapis.ios.kt` file, and let me know what can be improved to avoid that issue.
```
@OptIn(ExperimentalForeignApi::class)
@Composable
actual fun MediaPlayerUI(modifier: Modifier, url: String) {
    var avPlayer by remember { mutableStateOf<AVPlayer?>(null) }
    var avPlayerViewController by remember { mutableStateOf<AVPlayerViewController?>(null) }
    var uiView by remember { mutableStateOf<UIView?>(null) }

    LaunchedEffect(Unit) {
        avPlayer = withContext(Dispatchers.Main) {
            AVPlayer(uRL = NSURL(string = url))
        }
        avPlayerViewController = withContext(Dispatchers.Main) {
            AVPlayerViewController().apply {
                player = avPlayer
                showsPlaybackControls = true
                entersFullScreenWhenPlaybackBegins = true
                exitsFullScreenWhenPlaybackEnds = true
                videoGravity = AVLayerVideoGravityResize
                contentOverlayView?.autoresizesSubviews = true
            }
        }
        uiView = withContext(Dispatchers.Main) {
            avPlayerViewController?.view
        }
    }

    if (avPlayer != null && uiView != null) {
        UIKitView(
            modifier = modifier,
            factory = {
                uiView!!
            },
            interactive = true,
            background = Color.Gray
        )
    }
}
```

**Comment by elijah-semyonov** [comment] 2023-10-24 07:33
Yes, this case is a bit different story and unexpected side effect of interop views being able to fire `viewDidDisappear` on Compose UIViewController and trigger scene disposal. We are currently approach that will allow a user to avoid this. 

See https://github.com/JetBrains/compose-multiplatform/issues/3698.

**Comment by okushnikov** [comment] 2024-08-26 14:33
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3458">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:23 UTC
Labels: bug, wait for reply, discussion
