### ISSUE TITLE
Horizontal scroll doesn't work on Linux

### ISSUE THREAD

**Issue by fourlastor** [JetBrains/compose-multiplatform#2528] opened 2022-12-02 21:37 UTC
The following code snippet (100 boxes that should scroll horizontally) doesn't respond to mouse/touchpad scrolling:
```kotlin
Window(onCloseRequest = ::exitApplication) {
    Row(modifier = Modifier.fillMaxSize().horizontalScroll(rememberScrollState())) {
        repeat(100) {
            Box(modifier = Modifier.height(40.dp).width(40.dp).padding(4.dp).background(Color.LightGray))
        }
    }
}
```

Vertical scrolling (a `Column` with `.verticalScroll(rememberScrollState())`) works correctly (it scrolls when using a scrollwheel/touchpad)

JVM: Temurin 17.0.4
Compose version: 1.2.0
Kotlin version: 1.7.10
OS info:
![image](https://user-images.githubusercontent.com/1263058/205392457-8c81067c-2c98-4317-b949-607f453f620d.png)

**Comment by rock3r** [comment] 2022-12-02 22:13
And this works on Jetpack Compose, right?

**Comment by fourlastor** [comment] 2022-12-02 22:27
Yep, works fine on Jetpack Compose 1.2.0 on Android

**Comment by fourlastor** [comment] 2022-12-03 09:08
Just noticed that the [scrollbars example](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Desktop_Components#scrollbars) works. The issue is only capturing mouse/touchpad events to scroll horizontally

**Comment by Qdafengzi** [comment] 2022-12-20 10:05
The same  on macOS desktop app

**Comment by GazimSoliev** [comment] 2023-02-01 12:25
I have the same problem :(

**Comment by GazimSoliev** [comment] 2023-02-01 12:28
LazyRow also doesn't work correctly

**Comment by igordmn** [comment] 2023-02-06 13:36
In https://github.com/JetBrains/compose-jb/issues/2690 there was a small workaround described - use Shift with vertical scroll of wheel.

But we still need to support wheel left/right, if the rest of the system supports that.

**Comment by igordmn** [comment] 2023-02-14 08:51
_Investigation._

Scroll isn't received by Swing (underlying framework):
```
import java.awt.Dimension
import javax.swing.JFrame
import javax.swing.SwingUtilities

fun main() {
    SwingUtilities.invokeLater {
        val j = JFrame()
        j.addMouseWheelListener {
            println("wheel")
        }
        j.size = Dimension(200, 200)
        j.isVisible = true
    }
}
```
Doesn't work on JBR 17, JDK 17. But it works in IDEA somehow. We should look at its sources.

**Comment by m-sasha** [comment] 2023-02-14 11:02
If vertical scrolling works, surely the events are received, no?

**Comment by igordmn** [comment] 2023-02-14 12:12
When we scroll vertically - we receive events. When horizontally - we don't receive.

**Comment by m-sasha** [comment] 2023-02-14 13:52
@igordmn I think we're talking about different things.

I think you're talking about physical horizontal scrolling, like a horizontal scroll-wheel?

I'm talking about vertical scroll events causing horizontal scrolling in the UI.

Not sure what the original bug reporter meant.

**Comment by mbunderline76** [comment] 2023-07-31 18:28
i'm wondering when this issue is going to fix

**Comment by dima-avdeev-jb** [comment] 2023-08-01 06:54
> i'm wondering when this issue is going to fix

Based on other issues and priorities, we want to postpone fix of current issue.

**Comment by tealsnow** [comment] 2024-01-06 11:58
@mbunderline76

> i'm wondering when this issue is going to fix

This is a problem for me when using a trackpad, i.e. scrolling with two fingers left and right. I should not have to hold down shift for compose to receive horizontal scroll events.

**Comment by NuruNabiyev** [comment] 2024-04-03 14:03
I did an investigation and still can't receive horizontal scroll events (without pressing shift). I checked out intellij community source code, I even tried jetbrains runtime (21) but the scroll events are still not received! Also tried the `--add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED` but nothing works... 

This is a huge problem for my app as well because it is 2d canvas based.
Do you have any updates on this @igordmn? 
Thanks in advance

**Comment by PMARZV** [comment] 2024-05-27 20:49
@igordmn same problem here, users (i include myself here) would expect scrolling without having to shift to work. Is there any workaround so that it works? The expected behaviour should be like the tabs row in intellj idea. Thanks to all the team btw!

**Comment by okushnikov** [comment] 2024-07-14 14:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2528">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:41 UTC
Labels: bug, input, linux, desktop
