### ISSUE TITLE
`isSystemInDarkTheme()` not causing recomposition when using `UINavigationController` as wrapper on compose `UIViewController`

### ISSUE THREAD

**Issue by begali** [JetBrains/compose-multiplatform#4987] opened 2024-06-17 10:00 UTC
**Describe the bug**
`androidx.compose.foundation.isSystemInDarkTheme()` not causing recomposition when using `UINavigationController` as wrapper on compose `UIViewController`. 

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0

**To Reproduce**
```ContentView.swift
struct ContentView: View {
    var body: some View {
        RootNavControllerWrapper()
            .ignoresSafeArea(.keyboard)
            .ignoresSafeArea(.all)
    }
} 

struct RootNavControllerWrapper: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UINavigationController {
        let rootController = MainViewControllerKt.MainViewController()
        let navController = UINavigationController(rootViewController: rootController)
        navController.setNavigationBarHidden(true, animated: false)
        return navController
    }
    
    func updateUIViewController(_ uiViewController: UINavigationController, context: Context) {}
}

```

1. Run this code snippet:
   ```MainViewController.kt
   @Composable
   fun MainViewController() {
       println("APP theme mode: "+ isSystemInDarkTheme())
   }
   ```
2. Click on Simulator-> Features-> Toggle Appearance

**Comment by elijah-semyonov** [comment] 2024-06-18 10:18
Reproducible on desktop as well.

https://github.com/JetBrains/compose-multiplatform/assets/4167681/f1449ad1-33de-40b3-a681-ac2e782f21e1

**Comment by elijah-semyonov** [comment] 2024-06-18 12:16
Can't reproduce

https://github.com/JetBrains/compose-multiplatform/assets/4167681/aa553c9c-82b5-46b9-919f-5e962a1c99fd

**Comment by elijah-semyonov** [comment] 2024-06-18 12:20
Can you please send a repro project?

**Comment by alexzhirkevich** [comment] 2024-06-18 17:35
It [overrides](https://github.com/alexzhirkevich/compose-cupertino/blob/54bfbb58f6b36248c5947de343567903298ee308/cupertino-core/src/iosMain/kotlin/io/github/alexzhirkevich/cupertino/SystemBarAppearance.ios.kt#L57) user interface style to let you have light keyboard for light app when the system is dark. Interesting side effect

**Comment by begali** [comment] 2024-06-20 01:17
@elijah-semyonov Can please check? `viewController.overrideUserInterfaceStyle = if (dark)
            UIUserInterfaceStyle.UIUserInterfaceStyleDark
        else UIUserInterfaceStyle.UIUserInterfaceStyleLight` as mentioned by @alexzhirkevich causing the theme not to change in compose.

**Comment by okushnikov** [comment] 2024-08-26 13:37
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4987">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:21 UTC
Labels: wait for reply, ios
