### ISSUE TITLE
Compose Compiler 1.5.12+ causes Only @HiddenFromObjC declaration can be a subtype of @HiddenFromObjC declaration

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#4777] opened 2024-05-07 22:17 UTC
**Describe the bug**
Using the compose compiler v1.5.12+ results in the following error when compiling for ios targets:

```
Only @HiddenFromObjC declaration can be a subtype of @HiddenFromObjC declaration
```

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10-rc1 and 1.6.2
- Kotlin version: 1.9.23
- OS version(s) (required for Desktop and iOS issues): macOS 14.4.1
- OS architecture (x86 or arm64): arm64

**To Reproduce**
1. Run `./gradlew assemble` on https://github.com/eygraber/vice/tree/renovate/kotlin-monorepo
2. See error

**Expected behavior**
No error

**Additional context**
The error is reported on this line:

```kotlin
public abstract class FlowSource<T> : ViceSource<T>
```
where `ViceSource` is:

```kotlin
public interface ViceSource<T> {
  @Composable
  public fun currentState(): T
}
```

Originally reported [here](https://youtrack.jetbrains.com/issue/KT-68048/Kotlin-1.9.24-Only-HiddenFromObjC-declaration-can-be-a-subtype-of-HiddenFromObjC-declaration) because I thought it was an issue with Kotlin 1.9.24, but then I tested on Kotlin 1.9.23 with all compiler versions starting from 1.5.12 and was able to repro the issue.

**Comment by shishkin-pavel** [comment] 2024-05-10 15:49
the problem was in name clash (`ViceSource` class inherited hide annotation due to `ViceSource` composable function)
should be fixed in `1.5.13.2` for kotlin 1.9.23 & `1.5.13.3` for kotlin 1.9.24

**Comment by eygraber** [comment] 2024-05-10 15:50
Awesome thank you

**Comment by Kashif-E** [comment] 2024-05-14 20:18
hey @shishkin-pavel  i am using kotlin rc3 and compose rc02 and facing this issue, what should i do to get rid of it?

**Comment by shishkin-pavel** [comment] 2024-05-14 20:40
Hi, @Kashif-E , make sure you updated compose compiler to version `1.5.13.2` (for kotlin 1.9.23) / `1.5.13.3` (kotlin 1.9.24) or updated Compose Multiplatform to version `1.6.10-rc02`

**Comment by Kashif-E** [comment] 2024-05-14 20:47
@shishkin-pavel  i am using kotlin 2.0.0-rc3 and compose 1.6.10-rc02

**Comment by shishkin-pavel** [comment] 2024-05-14 20:53
could you share some reproducer? probably this is another similar problem

**Comment by eygraber** [comment] 2024-05-21 22:36
@shishkin-pavel I'm seeing this again in 1.6.10 with Kotlin 2.0.0 stable and the Compose compiler from the Kotlin plugin.

[Here's the error](https://github.com/eygraber/immich-kmp/actions/runs/9182294014/job/25250872460?pr=48#step:5:883) on this [PR updating to Kotlin 2.0](https://github.com/eygraber/immich-kmp/pull/48) (I'm going to disable building ios now so it doesn't block me).

It's being reported on the first line here:

```kotlin
abstract class ImmichSessionPortal<K, V, I, C, E, S> : VirtuePortal<K, V, I, C, E, S, ImmichSessionComponent>()
  where V : ViceView<I, S>, C : ViceCompositor<I, S>, E : ViceEffects {
  abstract override val parentComponent: ImmichSessionComponent
  abstract override val component: ImmichSessionPortalComponent<K, V, I, C, E, S>
}

interface ImmichSessionPortalComponent<K, V, I, C, E, S> :
  VirtuePortalComponent<V, I, C, E, S, ImmichSessionComponent>
  where V : ViceView<I, S>, C : ViceCompositor<I, S>, E : ViceEffects {
  @get:Provides val route: K
}
```

**Comment by eygraber** [comment] 2024-05-24 06:19
@shishkin-pavel Can this get reopened? I'm now starting to see this in multiple libraries, and it's getting harder to keep disabling ios :grimacing: 

In this case it was working fine with Kotlin 2.0.0 and CMP 1.6.10, but starting throwing the error on the first line here on [this PR](https://github.com/eygraber/vice/pull/99):

```kotlin
abstract class SampleDestination<V, I, C, S> : ViceDestination<V, I, C, DummyEffects, S>()
  where V : ViceView<I, S>, C : ViceCompositor<I, S> {
  override val effects = DummyEffects
  @Composable final override fun OnBackPressedHandler(enabled: Boolean, onBackPressed: () -> Unit) {}
}
```

It seems to work if I add

```kotlin
@OptIn(ExperimentalObjCRefinement::class)
@HiddenFromObjC
```

to `SampleDestination` but I feel like that's just punting the problem down the road. I also don't have any of my code annotated with `HiddenFromObjC` so I'm not sure where this is coming from.

**Comment by shishkin-pavel** [comment] 2024-05-24 09:10
@eygraber sure, ill take a look at it today

**Comment by shishkin-pavel** [comment] 2024-05-27 15:35
@eygraber sorry for the delay. for Kotlin version 2, the publication of compose compiler artifact occurs simultaneously with the release of Kotlin compiler and the necessary changes have not yet made it into the release, but I hope that they will make it into the next one. probably it would make sense to close current issue only when they would be merged and new version of kotlin compiler and compose compiler woudl be published

**Comment by eygraber** [comment] 2024-05-28 04:29
@shishkin-pavel thanks, looking forward to the fix!

**Closed** 2024-06-17 12:33 UTC
Labels: bug, compiler, p:critical

**Comment by eygraber** [comment] 2024-07-11 20:41
Should this be fixed in 2.0.10?

**Comment by eygraber** [comment] 2024-07-11 21:38
This is still failing with 2.0.10-RC

**Comment by okushnikov** [comment] 2024-07-14 14:52
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4777">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
