### ISSUE TITLE
Unexpected IndexOutOfBounds from LazyLayout / IntervalList

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#2300] opened 2022-09-08 21:38 UTC
An unexpected `IndexOutOfBounds` exception was thrown while we were using our application, and the entire stack trace did not contain our code from start to end. So we were not able to reproduce it on our side, but it's definitely concerning that it could happen again.

Looking at the stack trace, it seems to have originated from a LazyLayout component, specifically the IntervalList.

Is there something you can make out of the stack trace below? It's the full dump of the trace.

```
java.lang.IndexOutOfBoundsException: Index 7, size 7
	at androidx.compose.foundation.lazy.list.IntervalListKt.intervalIndexForItemIndex(IntervalList.kt:56)
	at androidx.compose.foundation.lazy.list.IntervalListKt.intervalForIndex(IntervalList.kt:52)
	at androidx.compose.foundation.lazy.list.LazyListItemsProviderImpl.getKey(LazyListItemsProviderImpl.kt:73)
	at androidx.compose.foundation.lazy.layout.LazyLayoutPlaceablesProvider.getAndMeasure-0kLqBqw(LazyMeasurePolicy.kt:56)
	at androidx.compose.foundation.lazy.list.LazyMeasuredItemProvider.getAndMeasure-oA9-DU0(LazyMeasuredItemProvider.kt:45)
	at androidx.compose.foundation.lazy.list.LazyListMeasureKt.measureLazyList-wroFCeY(LazyListMeasure.kt:145)
	at androidx.compose.foundation.lazy.list.LazyListKt$rememberLazyListMeasurePolicy$1$1.measure-3p2s80s(LazyList.kt:259)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2.invoke-0kLqBqw(LazyLayout.kt:55)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2.invoke(LazyLayout.kt:44)
	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:355)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:55)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:306)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:39)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.foundation.ScrollingLayoutModifier.measure-3p2s80s(Scroll.kt:342)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:39)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:306)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:39)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
	at androidx.compose.foundation.layout.SizeModifier.measure-3p2s80s(Size.kt:781)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:39)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:99)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:98)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1798)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:88)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:76)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:98)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui(LayoutNode.kt:1317)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui$default(LayoutNode.kt:1313)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure(MeasureAndLayoutDelegate.kt:170)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:228)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:38)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:201)
	at androidx.compose.ui.platform.SkiaBasedOwner.measureAndLayout(SkiaBasedOwner.skiko.kt:266)
	at androidx.compose.ui.node.Owner$DefaultImpls.measureAndLayout$default(Owner.kt:182)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:342)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:341)
	at androidx.compose.ui.ComposeScene.onMouseMove(ComposeScene.skiko.kt:468)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM(ComposeScene.skiko.kt:428)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM$default(ComposeScene.skiko.kt:397)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.onMouseEvent(ComposeLayer.desktop.kt:420)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.access$onMouseEvent(ComposeLayer.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:278)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:274)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:89)
	at androidx.compose.ui.awt.ComposeLayer.onMouseEvent(ComposeLayer.desktop.kt:274)
	at androidx.compose.ui.awt.ComposeLayer.access$onMouseEvent(ComposeLayer.desktop.kt:70)
	at androidx.compose.ui.awt.ComposeLayer$4.mouseMoved(ComposeLayer.desktop.kt:261)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6680)
	at java.desktop/java.awt.Component.processEvent(Component.java:6404)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by TostF** [comment] 2022-10-06 10:17
I have the same issue. Android project with new features added in compose. Fragment with ComposeView. This error is one of the issues that we have after transition. Not a single part of the exception has redirection to our code.

**Comment by haikalpribadi** [comment] 2022-11-19 15:47
The more our application is used, the more frequent we see this error. I'd say it happens regularly in one over 100 times the module is launched. It's getting quite concerning now.

Any insight into the issue, guys?

**Comment by jamesreprise** [comment] 2022-11-21 08:30
This has been encountered in other programs built using Jetpack Compose:
- https://github.com/google/accompanist/issues/1161
- https://github.com/mozilla-mobile/fenix/issues/24036

**Comment by TostF** [comment] 2022-11-21 08:41
Update on my part: In our app this was caused by Sentry library update. So its not connected to the case.

**Comment by developerw5** [comment] 2023-02-15 10:50
Hello. I'm using lazycolumn along with swiprefresh, I get this error too.
Did you manage to solve the problem?

**Comment by kistitan** [comment] 2023-02-16 09:34
Hey there,

We are also keep encountering this issue in crash reports. 
Couldn't reproduce locally, but as mentioned above the more the app used the more frequent this issue appear.

Possibly relevant library versions:

Compose: v1.2.1
Accompanist: v0.25.1
Compose Paging: v1.0.0-alpha17

Thank you in advance for looking into it

**Comment by Damercy** [comment] 2023-10-30 20:31
I have been facing a similar issue with `LazyColumn` in my application. A partial solution right now seems to be by using `LazyVerticalGrid with a span of 1 & number of columns set as 1`. Not sure why but this seems to be working.

My library versions:
- `androidx.compose.foundation:foundation:1.6.0-alpha08`
- `compose_compiler_version = 1.5.3`
- `compose_bom = 2023.10.01`

**Comment by Blackghost56** [comment] 2023-10-30 21:27
> I have been facing a similar issue with `LazyColumn` in my application. A partial solution right now seems to be by using `LazyVerticalGrid with a span of 1 & number of columns set as 1`. Not sure why but this seems to be working.
> 
> My library versions:
> 
> * `androidx.compose.foundation:foundation:1.6.0-alpha08`
> * `compose_compiler_version = 1.5.3`
> * `compose_bom = 2023.10.01`


I have a similar problem, in my case, rolling back to the previous version of the library helps:

- worked -> implementation 'androidx.compose.material3:material3-android:1.2.0-alpha09'
- crashed ->  implementation 'androidx.compose.material3:material3-android:1.2.0-alpha10'

**Comment by kochchy** [comment] 2023-11-03 13:25
@Damercy thanks, your workaround is working for me as well

**Comment by juhaodong** [comment] 2023-11-06 19:59
add keys for lazycolumn can help

**Comment by roshanrajaratnam** [comment] 2023-11-22 12:17
This issue seems to be still occurring in `androidx.compose.material3:material3-android:1.2.0-alpha11`

**Comment by Julius-Babies** [comment] 2023-12-15 15:51
Seems to be fixed in androidx.compose.material3:material3-android:1.2.0-beta01. But there are problems with the HorizontalPager

**Comment by roshanrajaratnam** [comment] 2023-12-15 22:12
Mine disappeared from alpha12 onwards that was happening on a LazyColumn

**Comment by okushnikov** [comment] 2024-08-26 14:33
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2300">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 10:04 UTC
