### ISSUE TITLE
App Store verification fails with "The app references non-public symbols"

### ISSUE THREAD

**Issue by sergei-mikhailovskii-idf** [JetBrains/compose-multiplatform#3840] opened 2023-10-20 07:53 UTC
**Describe the bug**
I implemented a library which uses Compose Multiplatform to display logs and added it to the iOS project. It builds fine, but when I upload the app to the App Store, lane fails with the following error:

`ERROR: [ContentDelivery.Uploader] Asset validation failed (11) The app references non-public symbols in Payload/AppName.app/AppName: _ubidi_close, _ubidi_getDirection, _ubidi_getLength, _ubidi_getLevelAt, _ubidi_openSized, _ubidi_reorderVisual, _ubidi_setPara, _ubrk_clone, _ubrk_current, _ubrk_first, _ubrk_getRuleStatus, _ubrk_next, _uloc_getDefault, _uloc_toLanguageTag, _uscript_getScript (ID: b685f704-5d49-42c6-b138-5d9237029ac2)
`

I googled this problem and it seems that there's some problem with SKIA library (https://groups.google.com/g/skia-discuss/c/eY229SYmHbA)

So there's a question - how can I fix this issue? Thanks in advance for the answer!

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.10 
- Compose Multiplatform version*:  1.5.3
- OS version(s)* (required for Desktop and iOS issues): any
- OS architecture (x86 or arm64): arm64

**To Reproduce**
1) Try to upload the app to the App Store
2) See result

**Expected behavior**
Successfull upload of the IPA to the App Store

**Additional context**
XCode version - 15.0
Here are libs I used

```
val commonMain by getting {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation("io.realm.kotlin:library-base:1.11.0")
                implementation("com.arkivanov.decompose:extensions-compose-jetbrains:2.1.2-compose-experimental")
                implementation("com.arkivanov.decompose:decompose:2.1.2")
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.4.1")
            }
        }
        val androidMain by getting {
            dependencies {
                implementation("androidx.activity:activity-compose:1.8.0")
            }
        }
        val iosSimulatorArm64Main by getting
        val iosMain by getting {
            dependsOn(commonMain)
            iosSimulatorArm64Main.dependsOn(this)
        }
```

**Comment by MatkovIvan** [comment] 2023-10-20 08:05
> it seems that there's some problem with SKIA library

Yes, Compose relies on skia library under the hood. SKIA uses ICU library for Unicode support, but it's [built with reference to a non-system library](https://github.com/JetBrains/skia-pack/blob/84c4bb055177bed57dd6e14d3247c034c0720dbf/script/build.py#L38C6-L38C25).

Is it reproducible on our [template](https://github.com/JetBrains/compose-multiplatform-template) project for you? Or is it just about your own project with this set of dependencies?

**Comment by sergei-mikhailovskii-idf** [comment] 2023-10-20 08:15
@MatkovIvan thanks for the support, unfortunately I cannot test with the template app, since I cannot upload it to the AppStore and check

**Comment by dima-avdeev-jb** [comment] 2023-10-26 17:14
I checked validation process with Xcode 15
All fine

<img width="750" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/ce0718f9-013b-4047-9b86-9709b7123131">

**Comment by dima-avdeev-jb** [comment] 2023-10-26 17:17
@sergei-mikhailovskii-idf Can you please check validation in Xcode when building archive?

To do so you need folow these steps:
 - Go to Product -> Archive
 
 
<img width="274" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/df854793-efd3-40bc-a820-4850175c4c11">


 - Don't use Xcode Cloud and start proccess of Archive again.
 
  - Wait some time while archiving
  
   - Choose Validate App
   
   
<img width="789" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/84fd63e1-f388-4ae2-a54a-862db3b414ed">

**Comment by sergei-mikhailovskii-idf** [comment] 2023-10-30 10:24
@dima-avdeev-jb hi! I did in the way u described and received the same error after the validation

<img width="748" alt="Screenshot 2023-10-30 at 13 17 37" src="https://github.com/JetBrains/compose-multiplatform/assets/64923802/ab500ca5-eca8-40c6-bced-d110d102c204">

Here's the failure in logs

```
Asset validation failed
The app references non-public symbols in Payload/appname.app/appname: _ubidi_close, _ubidi_getDirection, _ubidi_getLength, _ubidi_getLevelAt, _ubidi_openSized, _ubidi_reorderVisual, _ubidi_setPara, _ubrk_clone, _ubrk_current, _ubrk_first, _ubrk_getRuleStatus, _ubrk_next, _uloc_getDefault, _uloc_toLanguageTag, _uscript_getScript (ID: 0f90461d-3a4e-40a5-9b29-c92115d578d1)
2023-10-30 13:14:08.796  INFO: [ContentDelivery.Uploader] 
=============
VERIFY FAILED with 1 error.
=============
```

**Comment by dima-avdeev-jb** [comment] 2023-10-30 15:02
@sergei-mikhailovskii-idf Thanks!
It is good, because now we can check your problem without full AppStore publication process.

Can you please provide a minimal reproducible sample of this Issue?
You need to remove all sentence(secret) information from your project. Simplify code as much as possible. But bug still needs to appear! And share this project on GitHub.
It will help us for better understanding of this Issue.

**Comment by sergei-mikhailovskii-idf** [comment] 2023-11-07 15:50
@dima-avdeev-jb sorry for the delay, here's the sample
https://github.com/SergeiMikhailovskii/log-view-app

**Comment by sergei-mikhailovskii-idf** [comment] 2023-11-20 07:23
@dima-avdeev-jb hello! any updates here or not yet?

**Comment by dima-avdeev-jb** [comment] 2023-11-20 14:07
@sergei-mikhailovskii-idf Sorry, not yet. I will check your samples little bit later

**Comment by sergei-mikhailovskii-idf** [comment] 2023-11-20 14:08
@dima-avdeev-jb no problems, it's ok

**Comment by Kashif-E** [comment] 2023-11-24 08:01
having the same issue

**Comment by Kashif-E** [comment] 2023-11-24 08:06
@sergei-mikhailovskii-idf  have you found any solution?

**Comment by sergei-mikhailovskii-idf** [comment] 2023-11-24 08:21
@Kashif-E hi! not yet. seems that the issue is in compatibility with some other dependency

**Comment by Kashif-E** [comment] 2023-11-24 08:22
@sergei-mikhailovskii-idf  i am also testing this on my side ill update if i find something

**Comment by Kashif-E** [comment] 2023-11-24 10:02
found a similar issue about skia https://github.com/Shopify/react-native-skia/issues/1133

**Comment by Kashif-E** [comment] 2023-11-24 12:30
@sergei-mikhailovskii-idf by any chance are you using reachability ?

**Comment by xiangning17** [comment] 2023-11-27 07:34
having the same issue. @sergei-mikhailovskii-idf Do you mean to confirm that the problem is not with the Compose framework or skia library? It's because of some other dependency of your own.

**Comment by xiangning17** [comment] 2023-11-27 07:47
@Kashif-E Thanks for the reply, I also saw the Rect-Native related issue you associated with it, and over there the issue was resolved, but there seems to be no official movement on the Compose side, so is there anything else that can be done at the moment?

I think it's a bit strange, if this is the issue that's causing it to not pass the App Store, then the amount of feedback on the issue shouldn't be so low, or is there actually no one actually using Compose for iOS for development at all yet 😂

**Comment by sergei-mikhailovskii-idf** [comment] 2023-11-27 07:48
> having the same issue. @sergei-mikhailovskii-idf Do you mean to confirm that the problem is not with the Compose framework or skia library? It's because of some other dependency of your own.

Hi, I think that the problem is in compatability of the Compose and some other dependency

**Comment by Kashif-E** [comment] 2023-11-27 07:53
@sergei-mikhailovskii-idf  @xiangning17 We have been uploading our app on test flight for the past month and didnt  had any issue we didnt update any library or anything else and started having this issue on thursday. Its a very strange thing  to happen actually, this app is actually full compose but we have another app which uses compose with swift ui and there is no issue with that

**Comment by Kashif-E** [comment] 2023-11-27 07:55
@dima-avdeev-jb   if you can take some time out to check this it would be great we had planned a launch this week, our android app has close to 5m downloads on playstore and we are expecting a similar traffic on ios as well. It would be great if you can help with this asap

**Comment by Kashif-E** [comment] 2023-11-27 11:28
@dima-avdeev-jb @MatkovIvan  this is what we got from apple 
![Uploading Screenshot 2023-11-27 at 4.27.05 PM.png…]()

**Comment by dima-avdeev-jb** [comment] 2023-11-27 12:46
Sure, I will check sample https://github.com/SergeiMikhailovskii/log-view-app on this week. And try to locally verify it.
I hope it helps to find root of the problem

**Comment by xiangning17** [comment] 2023-11-28 12:55
> @sergei-mikhailovskii-idf Can you please check validation in Xcode when building archive?
> 
> To do so you need folow these steps:
> 
> * Go to Product -> Archive
> 
> <img alt="image" width="274" src="https://private-user-images.githubusercontent.com/99798741/278423137-df854793-efd3-40bc-a820-4850175c4c11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzI0ODksIm5iZiI6MTcwMTA3MjE4OSwicGF0aCI6Ii85OTc5ODc0MS8yNzg0MjMxMzctZGY4NTQ3OTMtZWZkMy00MGJjLWE4MjAtNDg1MDE3NWM0YzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA4MDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YzE4NmU5NmIxY2RlOTQxZWM5YWRkYmU3MTUyZWYyNTRjMzI4MGRhYmY4N2U5MTJlZDdkZWRiYzllNTA4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZsKVvQBleare4MZiXXcLbEGJrP0OXJVPC6p9ifI0dj4">
> * Don't use Xcode Cloud and start proccess of Archive again.
> * Wait some time while archiving
> * Choose Validate App
> 
> <img alt="image" width="789" src="https://private-user-images.githubusercontent.com/99798741/278423450-84fd63e1-f388-4ae2-a54a-862db3b414ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzI0ODksIm5iZiI6MTcwMTA3MjE4OSwicGF0aCI6Ii85OTc5ODc0MS8yNzg0MjM0NTAtODRmZDYzZTEtZjM4OC00YWUyLWE1NGEtODYyZGIzYjQxNGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA4MDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYTZjMTkyYzVjNWViYjc0ZmUyZjNjNjI4MWI4M2UwOGE1ZGZhNDU3NmFjNmU4YzU1Y2YzZTkwYTBjOWZlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Ue4Vq2DkIX-Wlsqhf36It5UDMtDTQMp3L2bLMZxjL4">

@dima-avdeev-jb I select "Validate App" in the third step and it also fine, but when I select "Distribute App" I get an email from Apple telling me the same error message! I hope this helps.

**Comment by xiangning17** [comment] 2023-11-29 08:47
> The issue was with Facebook SDK and another analytic sdk that we were using @xiangning17 @sergei-mikhailovskii-idf

@Kashif-E Are you saying that you have a Facebook SDK dependency on cocapods in Kotlin Multiplatform that is causing this issue? Or are you saying that you are relying on the Facebook SDK in the Podfile of iosApp? I am locally reducing the dependencies in Kotlin Multiplatform to only compose related ones still reporting the error.

**Comment by Kashif-E** [comment] 2023-11-30 05:11
I had the facebook sdk as cocoapod on the native side. After the removal of fb sdk and another analytics sdk the error went away.

**Comment by dima-avdeev-jb** [comment] 2023-12-02 16:37
@sergei-mikhailovskii-idf 
I tryed to check your project, but error occurs:

`Could not find com.idfinance.kmm:behaviour_tracker:1.1.9`

Project: https://github.com/SergeiMikhailovskii/log-view-app

**Comment by dima-avdeev-jb** [comment] 2023-12-02 16:52
@sergei-mikhailovskii-idf 
[UPDATE]:
I just removed `com.idfinance.kmm:behaviour_tracker:1.1.9` to sync project

**Comment by dima-avdeev-jb** [comment] 2023-12-02 17:12
@sergei-mikhailovskii-idf 
I reproduced the problem. But I have less problems in error description:

<img width="734" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/38b96d6b-8417-43ba-8d9f-f628a74790d2">

I will try to solve it

**Comment by dima-avdeev-jb** [comment] 2023-12-02 18:07
@sergei-mikhailovskii-idf 
One of possible solution is to use dynamic frameworks
To do apply `isStatic = false` (or simply remove this line) in 2 gradle files:
 - [data/build.gradle.kts](https://github.com/SergeiMikhailovskii/log-view-app/blob/4f5ff82d45a04a81c7c17b571ae66c84335c31d3/data/build.gradle.kts#L23)
 - [presentation/build.gradle.kts](https://github.com/SergeiMikhailovskii/log-view-app/blob/4f5ff82d45a04a81c7c17b571ae66c84335c31d3/presentation/build.gradle.kts#L24)
 
But in this case was problems with CocoaPods dependencies

**Comment by dima-avdeev-jb** [comment] 2023-12-02 20:48
@sergei-mikhailovskii-idf 
Also, I found that problem disappears after removing `pod 'FirebaseDatabase'` from iosApp/Podfile even with static=true

**Comment by xiangning17** [comment] 2023-12-14 06:23
Hi @dima-avdeev-jb Is there any progress on this issue?

**Comment by dima-avdeev-jb** [comment] 2023-12-15 05:22
@xiangning17 For now you can use dynamic framework (isStatic = false in build.gradle.kts, or simple remove this line because it is false by default)
Or do not use pod 'FirebaseDatabase'

**Comment by dima-avdeev-jb** [comment] 2023-12-15 05:23
@sergei-mikhailovskii-idf Can you please try some of solutions what I mentioned before?

**Comment by xiangning17** [comment] 2023-12-15 05:38
But I depend on other libraries that are static and are required for Firebase integration😂

**Comment by sergei-mikhailovskii-idf** [comment] 2023-12-18 09:20
> @sergei-mikhailovskii-idf Can you please try some of solutions what I mentioned before?

hello, sorry, didn't find a time yet( I'll try to do it approximately 23-24 December

**Comment by FoRRestDp** [comment] 2024-01-12 04:04
I my case this error was caused by `pod 'Mixpanel'`, resolved by replacing it with `pod 'Mixpanel-swift'`

**Comment by FoRRestDp** [comment] 2024-01-12 15:03
In my case this problem was caused by `pod 'Mixpanel’`, I resolved it by replacing this dependency with `pod 'Mixpanel-swift'`

**Comment by VertaZoom** [comment] 2024-02-13 08:06
Is there any workaround for this?

I have `isStatic = true` set for the framework and the following `pods` are connected:
`pod("FirebaseAnalytics")`
`pod("FirebaseCrashlytics")`
`pod("FirebaseRemoteConfig")`
`pod("Sentry")`

I get the exact same error after submitting the application for review, there is no way to set `isStatic = false` since all pods are static

**Comment by Kashif-E** [comment] 2024-02-13 08:11
@VertaZoom  we are using these 
pod("FirebaseAnalytics")
pod("FirebaseCrashlytics")
pod("FirebaseRemoteConfig")
and not getting the issue have you tried removing sentry and test?

**Comment by VertaZoom** [comment] 2024-02-13 08:27
@Kashif-E Do you build `xcFramework` and connect it to another existing project and everything works fine?

We release the same application with the same dependencies as a standalone application and build a library for use in other applications. 

As a standalone application, the `AppStore` accepts it and has already published it, but if we build `xcFramework` and connect it to another application, the AppStore no longer accepts it.

**Comment by VertaZoom** [comment] 2024-02-15 12:08
It turned out that in the project with the `Compose xcFramework` dependency, there was also a `Pod 'Intercom'` and for some reason they conflicted with each other.

It helped to connect `Intercom` via `SMP`, and the `Compose` library via `cocoapods`

**Comment by ahmedsalemelzeiny** [comment] 2024-02-23 12:29
I’m Currently trying to integrate sendbird in compose Multiplatform project and everything is working fine in debug mode and the functionality is working fine but when trying to upload the build to testflight I got an email from Apple:-

> ITMS-90338: Non-public API usage - The app references non-public symbols in AppName - DEV: _ubidi_close, _ubidi_getDirection, _ubidi_getLength, _ubidi_getLevelAt, _ubidi_openSized, _ubidi_reorderVisual, _ubidi_setPara, _ubrk_clone, _ubrk_current, _ubrk_first, _ubrk_getRuleStatus, _ubrk_getRuleStatusVec, _ubrk_isBoundary, _ubrk_last, _ubrk_next, _ubrk_previous, _uloc_getDefault, _uloc_toLanguageTag, _uscript_getScript. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/


And after removing sendbird pod it’s working fine, then I used the pod directly in another project without compose Multiplatform and I didn’t get such an issue

**Comment by dima-avdeev-jb** [comment] 2024-02-25 07:29
Possible related issue: 
 - https://github.com/JetBrains/compose-multiplatform/issues/4335

**Comment by RoniSapirstein** [comment] 2024-02-26 13:47
We are having the same issue, when uploading the build to testflight we are receiving an email from Apple with the following error:
Hello,
We noticed one or more issues with a recent delivery for the following app:
Please correct the following issues and upload a new binary to App Store Connect.
ITMS-90338: Non-public API usage - The app references non-public symbols in Nanit: _ubidi_close, _ubidi_getDirection, _ubidi_getLength, _ubidi_getLevelAt, _ubidi_openSized, _ubidi_reorderVisual, _ubidi_setPara, _ubrk_clone, _ubrk_current, _ubrk_first, _ubrk_getRuleStatus, _ubrk_getRuleStatusVec, _ubrk_isBoundary, _ubrk_last, _ubrk_next, _ubrk_previous, _uloc_getDefault, _uloc_toLanguageTag, _uscript_getScript. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. 

When I tried to validate the version through xcode as suggested, it was approved.

I've tried just to add Compose dependency one after the other.
implementation(compose.runtime)
implementation(compose.foundation)
implementation(compose.material3)
implementation(compose.ui)
@OptIn(ExperimentalComposeLibrary::class)
implementation(compose.components.resources)
Except of compose.runtime, each of them triggered this email.

I've also tried this:
One of possible solution is to use dynamic frameworks
To apply isStatic = false (or simply remove this line) and it didn't help.

**Comment by dima-avdeev-jb** [comment] 2024-02-26 14:01
@RoniSapirstein What Compose version are you using?

**Comment by lital-nanit** [comment] 2024-02-27 17:24
@dima-avdeev-jb following on @RoniSapirstein's comment, we've also just got rid of all our pods in KMM cocoapods block, but still, same exact error when uploading to the store.

**Comment by dima-avdeev-jb** [comment] 2024-02-28 06:25
@lital-nanit What Compose version are you using?

**Comment by dima-avdeev-jb** [comment] 2024-02-28 06:39
@ahmedsalemelzeiny @RoniSapirstein @lital-nanit 
Can you please provide a minimal reproducible sample project?

**Closed** 2024-03-14 11:16 UTC
Labels: bug, skia, ios

**Comment by okushnikov** [comment] 2024-07-14 15:07
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3840">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
