### ISSUE TITLE
Canvas does not repaint, but the frame rate of the program will also decrease.

### ISSUE THREAD

**Issue by ShirasawaSama** [JetBrains/compose-multiplatform#4042] opened 2023-12-15 15:22 UTC
**Describe the problem**

Canvas does not repaint, but the frame rate of the program will also decrease.

**Affected platforms**

- Desktop

**Versions**
- Kotlin version: 1.9.21
- Compose Multiplatform version: 1.5.11
- OS version(s) (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): bellsoft jdk 21

**Sample code**

```kotlin
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.drawText
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.rememberTextMeasurer
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
fun FPSMeasurer(modifier: Modifier) {
    var fps by remember { mutableStateOf(0) }
    LaunchedEffect(Unit) {
        var fpsCount = 0
        var lasUpdate = 0L
        while (true) {
            withFrameMillis {
                if (++fpsCount == 5) {
                    fps = (fpsCount * 1000 / (it - lasUpdate)).toInt()
                    fpsCount = 0
                    lasUpdate = it
                }
            }
        }
    }

    Text("FPS: $fps", modifier, color = Color.Red, fontWeight = FontWeight.Bold)
}

fun main() = application {
    Window({ exitApplication() }) {
        Box {
            val measurer = rememberTextMeasurer()
            Canvas(Modifier.fillMaxSize()) {
                val h = size.height / 10
                for (i in 0..10) {

                    var j = 0f
                    while (j < size.width) {
                        drawRect(Color.Black, Offset(j, i * h), Size(0.5f, h))
                        j += 0.5f
                    }
                }
                drawText(measurer, "Size: ${size.width}x${size.height}", Offset(32f, 80f))
            }
            FPSMeasurer(Modifier.align(Alignment.TopStart).padding(start = 24.dp, top = 24.dp))
        }
    }
}
```

**Screenshot**

![image](https://github.com/JetBrains/compose-multiplatform/assets/17093811/4630ede3-1ebc-453b-b2ec-834d423caf87)

Always maintained between 2-5fps, even without any repaint and recompose.

**Profiling data**

![image](https://github.com/JetBrains/compose-multiplatform/assets/17093811/d0b2f1c5-5f28-4270-9adb-754d3d05ac64)

![image](https://github.com/JetBrains/compose-multiplatform/assets/17093811/ab3f9e91-4724-47e1-a541-d157cedb4962)

**Additional information**

My screen is 4k.

Why did I encounter this problem? Because I am writing an audio processing program that requires real-time waveform drawing, and then I realize that even if I am not redrawn at all, the frame rate will decrease to a very low level:

![image](https://github.com/JetBrains/compose-multiplatform/assets/17093811/69510acb-4de7-4726-b0de-2783224d8765)

**Comment by m-sasha** [comment] 2023-12-19 11:50
Hi. Can you clarify what the issue is? Are you asking why `withFrameMillis` is called at all without any "repainting", or why the frame rate goes down to 5fps?

**Comment by m-sasha** [comment] 2023-12-19 14:09
You should use `Modifier.graphicsLayer` in order to cache the result of your drawing.

Unfortunately, it won't help much in this case - the FPS measurer itself is causing Compose to re-send all the drawing commands every frame, and since there are a lot of them (you're drawing each pixel individually), it takes a long time for the underlying rendering engine to execute them.

What you can do is draw what you need into an offscreen `ImageBitmap`, and when that's ready, draw it on screen. Here's a rough example:

```
@Composable
private fun MyComplexCanvas(modifier: Modifier) {
    var size: IntSize? by remember { mutableStateOf(null) }
    Box(
        modifier = modifier
            .onPlaced {
                size = it.size
            }
    ) {
        val bitmap by produceState<ImageBitmap?>(null, key1 = size) {
            value = withContext(Dispatchers.Default) {
                size?.let { size ->
                    ImageBitmap(
                        width = size.width,
                        height = size.height
                    ).also { bitmap ->
                        val blackPaint = Paint().also {
                            it.color = Color.Black
                        }
                        with(Canvas(bitmap)) {
                            val h = size.height / 10
                            for (i in 0..10) {
                                var j = 0f
                                while (j < size.width) {
                                    drawRect(Rect(Offset(j, (i * h).toFloat()), Size(0.5f, h.toFloat())), blackPaint)
                                    j += 0.5f
                                }
                            }
                        }
                    }
                }
            }
        }
        Box(modifier.drawBehind {
            bitmap?.let {
                drawImage(it)
            }
        })
    }
}
```

**Comment by ShirasawaSama** [comment] 2023-12-24 16:03
I found that if I directly use NativeCanvas to draw, it can reduce the drawing time from 12ms to 400us.

**Comment by ShirasawaSama** [comment] 2023-12-24 21:21
@m-sasha May I ask if there is a way to create a canvas instance for offscreen (GPU)?

`Surface.makeRasterN32Premul` is for CPU.

And I have tried `makeFromBackendRenderTarget` and `makeRenderTarget`.

But it seems that there are too many private and internal native methods that cannot be called, so I was not able to successfully create a GPU drawing instance.

Drawing using CPU is extremely slow, 15x slower than using GPU.

**Comment by m-sasha** [comment] 2023-12-25 10:16
@igordmn Can you assist here?

**Comment by ShirasawaSama** [comment] 2023-12-27 17:25
I use the following code to get a more than 5x improvement in rendering performance.

```kotlin
import androidx.compose.foundation.layout.Spacer
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.awt.ComposeWindow
import androidx.compose.ui.awt.*
import androidx.compose.ui.draw.drawWithCache
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.*
import org.jetbrains.skia.*
import org.jetbrains.skia.Canvas
import org.jetbrains.skiko.context.*
import java.awt.Window
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import java.lang.reflect.Field
import java.util.WeakHashMap

@Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
private object SurfaceUtil {
    private lateinit var ComposeWindow_delegate: Field
    private lateinit var ComposeWindowDelegate_bridge: Field
    private val ContextHandlerSurface: MethodHandle
    private var redrawerCache: MutableMap<Window, ContextHandler>? = null

    init {
        var contextHandlerSurface: MethodHandle? = null
        try {
            ComposeWindow_delegate = ComposeWindow::class.java.getDeclaredField("delegate").apply { isAccessible = true }
            ComposeWindowDelegate_bridge = ComposeWindowDelegate::class.java.getDeclaredField("_bridge").apply { isAccessible = true }
            contextHandlerSurface = MethodHandles.lookup().unreflectGetter(ContextHandler::class.java.getDeclaredField("surface").apply { isAccessible = true })
            redrawerCache = WeakHashMap()
        } catch (e: Exception) {
            e.printStackTrace()
        }
        ContextHandlerSurface = contextHandlerSurface ?: MethodHandles.empty(MethodType.methodType(Surface::class.java))
    }

    fun getSurface(window: Window): Surface? {
        val cache = redrawerCache ?: return null
        var ctx = cache[window]
        if (null == ctx) try {
            val redrawer = (ComposeWindowDelegate_bridge.get(ComposeWindow_delegate.get(window)) as WindowComposeBridge).component.redrawer!!
            ctx = redrawer::class.java.getDeclaredField("contextHandler").apply { isAccessible = true }.get(redrawer) as ContextHandler
            cache[window] = ctx
        } catch (e: Exception) {
            e.printStackTrace()
        }
        if (null == ctx) return null
        val surface = ContextHandlerSurface.invokeExact(ctx) as Surface
        return if (surface.isClosed) null else surface
    }
}

@Composable
fun NativePainter(modifier: Modifier, block: Canvas.(size: Size) -> Unit) {
    @Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
    val window = androidx.compose.ui.window.LocalWindow.current
    Spacer(modifier.drawWithCache {
        var image: Image? = null
        if (window != null && size.width != 0F && size.height != 0F) {
            SurfaceUtil.getSurface(window)?.makeSurface(size.width.toInt(), size.height.toInt())?.apply {
                canvas.block(size)
                image = makeImageSnapshot()
                close()
            }
        }
        onDrawBehind {
            image?.apply {
                drawContext.canvas.nativeCanvas.drawImage(this, 0F, 0F)
                if (!isClosed) close()
            }
        }
    })
}
```

**Comment by Hazer** [comment] 2024-04-26 20:09
@ShirasawaSama Instead of using the `Image` composable, you can use it in a single pass with `.drawWithCache`. Probably safer than your last code and maybe has good enough performance? I got 120fps with this code where the previous code was 30fps max.

```kotlin

@Composable
fun ImageBitmapCanvasRendering(measurer: TextMeasurer) {

    Spacer(
        Modifier.fillMaxSize()
            .drawWithCache {
                val imageBitmap = ImageBitmap(
                    width = size.width.roundToInt(),
                    height = size.height.roundToInt()
                )
                val graphicCanvas = androidx.compose.ui.graphics.Canvas(imageBitmap)
                val paint = Paint().also {
                    it.color = Color.Black
                }

                with(graphicCanvas) {
                    val h = size.height / 10
                    for (i in 0..10) {

                        var j = 0f
                        while (j < size.width) {
                            drawRect(
                                Size(0.5f, h).toRect(Offset(j, i * h)),
                                paint = paint
                            )
                            j += 0.5f
                        }
                    }
                }

                onDrawBehind {
                    drawImage(imageBitmap)
                    drawText(measurer, "Size: ${size.width}x${size.height}", Offset(32f, 80f))
                }
            })
}

 fun Size.toRect(offset: Offset) = Rect(offset, this)
```

But I think for your use-case, using shaders and RenderEffect are a better long term solution for this particular Composable, if you can figure out how to use shaders, cause I haven't found how to make it work yet. I've been trying to make a waveform work with skiko/compose for a while but I don't know how to properly send my audio channel data as input shader. 

I have a working [(sample)](https://shaders.skia.org/?id=1221aa2bb9d4249bb77bc0d283d306b30af1c51bb00f3cf2741bdf1d407348e4) here if you want to see it with fixed improper test input.

Here's the shader if you want to try out :
```shader
 uniform float2 iResolution;
 layout(color) uniform half4 iBackgroundColor;

 uniform shader iChannel0;

 vec4 main(float2 fragCoord) {
     // Normalized pixel coordinates (from 0 to 1)
     vec2 uv = fragCoord/iResolution.xy;
     float offsetedY = uv.y * 2.0 - 1.0;

     //float value = texture(iChannel0, vec2(uv.x, 0.25)).r;
     float value = iChannel0.eval(vec2(uv.x, 0.25) * iResolution.xy).r;

     vec3 backgroundColor = iBackgroundColor.rgb;

      // I named alpha, but it's more like painting white above,
     // real alpha channel not used
     float waveColorAlpha = 0.4;
     vec3 waveColor = backgroundColor + vec3(waveColorAlpha);

     // Create half wave up
     vec3 topWave = vec3(step(offsetedY, value));
     topWave *= waveColor;

     // Create mirror of the top-half wave
     vec3 bottomMirror = vec3(step(-offsetedY, value));
     bottomMirror *= waveColor;

     // merge top
     vec3 wave = mix(
       bottomMirror, topWave,
       smoothstep(-0.01,0.01, offsetedY)
     );

     // Output to screen
     vec3 colorBlack = vec3(0.0,0.0,0.0);
     if (wave.rgb != colorBlack) {
       // Paint wave
         return vec4(wave, 1.0);
     } else {
         // Paint un-rendered black with BackgroundColor
         return vec4(backgroundColor, 1.0);
     }
 }
```

I couldn't figure out how to set my `iChannel0` shader from code, Android seems to have more tools for it, but I have not tried them because I want Multiplatform.
```kotlin
fun Modifier.drawWaveShader(channelData: DoubleArray) = this.drawWithCache {
    val runtimeEffect = RuntimeEffect.makeForShader(WAVE_SHADER_SRC)

    val shader = RuntimeShaderBuilder(runtimeEffect).apply {
        uniform("iBackgroundColor", Color.Red.toArgb())
        uniform("iResolution", size.width, size.height)
        // TODO: child("iChannel0", channelData) // What should be sent here? We had more options in Android.
     }.makeShader()

    val brush = ShaderBrush(shader)
    onDrawBehind {
        drawRect(brush)
    }
}

// Calling it
Spacing(
            modifier = Modifier
                .fillMaxSize()
                .drawWaveShader(audioChannelData)
        )
```

**Comment by ShirasawaSama** [comment] 2024-04-28 15:38
@Hazer Thank you for your solution. When I have free time, I will test the performance of this solution.

In fact, currently I draw each bar approximately as a triangle and call the drawVertices function to draw it. Although this performance has indeed reached an acceptable level, it is still not perfect enough.

https://github.com/EchoInMirror/EchoInMirror/blob/master/components/src/commonMain/kotlin/com/eimsound/daw/components/Waveform.kt#L66

**Comment by okushnikov** [comment] 2024-08-26 13:41
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4042">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2024-09-23 09:47 UTC
Labels: performance, windows, desktop
