### ISSUE TITLE
Bug. Parent background feels same as childs even if they have other alpha channel, and draw background on top of any childs (layout/draw doesn't compare alpha channel between colors of childs)

### ISSUE THREAD

**Issue by b0r1ngx** [JetBrains/compose-multiplatform#3641] opened 2023-09-07 20:03 UTC
**Describe the bug**
When place two Box's inside one Column / Box (etc, not test other, but i think its global Layout/draw problem).

I found this in my special case:
If first box have same background color with parent (RRGGBB, but other AA), first box will go drawn behind parent background (try to reproduce with my code example and look screenshot, not bet on my best english:c)

for example: 
1. background parent is Color.Black,
2. first box Modifier.background(color = Color(0x4D000000)),
3. When we go check how it looks (in app), we see that background is going on top of first box.

**Affected platforms**
Select one of the platforms below:
- Android 
- things all (not tested)

I report it by the link for Android, but i think its also have same behaviour on Multiplatform Compose. 

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0

**To Reproduce**
```kotlin
Column(
modifier = Modifier.background(color = Color.Black, shape = CircleShape) // CircleShape is just for visibility of bug
) {
Box(
        modifier = Modifier
            .padding(
                start = 16f.dp,
                top = 10f.dp,
                end = 16f.dp
            )
            .height(10f.dp)
            .fillMaxSize()
            .background(
                color = Color(0x4D000000),
                shape = RoundedCornerShape(
      topStart = 10f.dp, topEnd = 10f.dp
  )
            )
    )

Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                color = Color.Blue,
                shape = RoundedCornerShape(
      topStart = 10f.dp, topEnd = 10f.dp
  )
            )
    ) {
 content() // place here any content, for example compose.Text(), etc...
}
}
```

**Expected behavior**
Boxes go one by one, how it must be because im using Column for place childs back-to-back.

**Screenshots**
![compose_bug](https://github.com/JetBrains/compose-multiplatform/assets/55315908/2f1cfe95-92e5-4d76-b39c-db9f3a4e719d)

**Additional context**
Try to reproduce with my code example and look screenshot, not bet on my best english:c

**Comment by igordmn** [comment] 2023-09-08 16:09
>  first box will go drawn behind parent background

When you draw a transparent Black color (0x4D000000) over the opaque Black color (0xFF000000), the result color is Black (0xFF000000). So, it isn't drawn behind the parent background, it is just the result color is also Black.

Try to change the Column color to Red, and you will see that Column's background is behind the Box:
<img width="588" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5963351/4319a3c5-cf87-4e65-a04c-a90794612abd">

If you need to draw a Gray color over the Black color, you should use a Gray color (0xFFB2B2B2), not a fully Transparent color (0x4D000000).

Closing, as it works as expected. Let me know, if the issue is about something else, and I misinterpreted it.

**Closed by igordmn** 2023-09-08 16:09 UTC
Labels: bug, submitted

**Comment by b0r1ngx** [comment] 2023-09-13 09:26
Oh, absolutely right, doesn't thing in this way:c

**Comment by okushnikov** [comment] 2024-08-26 14:37
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3641">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
